<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="이번 주에 상원 등급은 딱 한 칸 움직였고, 방향이 민주당 반대쪽이었다. Cook이 뉴햄프셔를 Lean D에서 Toss-up으로 내렸고, 그래서 이 사이트의 등급가중 산수는 3주 만에 처음으로 —그것도 아래로— 움직여 +2.25석에서 +2.125석이 됐다. 그런데 같은 주에 나머지 모든 지표가 반대 방향으로 갔다. 7주간 D+6.0~6.6에 갇혀 있던 제너릭 밸럿이 위로 뚫려 네 집계가 D+7.2~8.6에 안착했고, 알래스카에서 사이클 처음으로 순위선택투표 라운드를 실제로 돌린 초당적 조사가 나왔으며, 예측시장은 한 주에 10센트 올랐다. 그리고 이번 주 데이터에는 아무도 크게 다루지 않은 반대 방향의 실측이 하나 더 있다 — 세 개 주에서 고령층이 공화당 쪽으로 돌아섰다.">

<title>26주차 · 09/14~09/20 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4c961d36af2bde8817862cab509c7b87.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">26주차 · 09/14~09/20</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-cook은-멈췄고-나머지-둘이-이틀에-17건을-옮겼다" id="toc-하원-cook은-멈췄고-나머지-둘이-이틀에-17건을-옮겼다" class="nav-link" data-scroll-target="#하원-cook은-멈췄고-나머지-둘이-이틀에-17건을-옮겼다">하원 — Cook은 멈췄고, 나머지 둘이 이틀에 17건을 옮겼다</a></li>
  <li><a href="#주지사-알래스카가-일주일-만에-두-번-움직였다" id="toc-주지사-알래스카가-일주일-만에-두-번-움직였다" class="nav-link" data-scroll-target="#주지사-알래스카가-일주일-만에-두-번-움직였다">주지사 — 알래스카가 일주일 만에 두 번 움직였다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-3주-만에-움직였고-아래로-움직였다" id="toc-상원-산수-3주-만에-움직였고-아래로-움직였다" class="nav-link" data-scroll-target="#상원-산수-3주-만에-움직였고-아래로-움직였다">상원 산수 — 3주 만에 움직였고, 아래로 움직였다</a></li>
  <li><a href="#연령-역전-이번-주-가장-저평가된-실측" id="toc-연령-역전-이번-주-가장-저평가된-실측" class="nav-link" data-scroll-target="#연령-역전-이번-주-가장-저평가된-실측">연령 역전 — 이번 주 가장 저평가된 실측</a></li>
  <li><a href="#공화당의-현시선호-세-번째-주-연속" id="toc-공화당의-현시선호-세-번째-주-연속" class="nav-link" data-scroll-target="#공화당의-현시선호-세-번째-주-연속">공화당의 현시선호 — 세 번째 주 연속</a></li>
  <li><a href="#두-개의-숫자가-어긋난-곳-기록해-둘-불일치" id="toc-두-개의-숫자가-어긋난-곳-기록해-둘-불일치" class="nav-link" data-scroll-target="#두-개의-숫자가-어긋난-곳-기록해-둘-불일치">두 개의 숫자가 어긋난 곳 — 기록해 둘 불일치</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">26주차 · 09/14~09/20</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    이번 주에 상원 등급은 딱 한 칸 움직였고, 방향이 민주당 반대쪽이었다. Cook이 뉴햄프셔를 Lean D에서 Toss-up으로 내렸고, 그래서 이 사이트의 등급가중 산수는 3주 만에 처음으로 —그것도 아래로— 움직여 +2.25석에서 +2.125석이 됐다. 그런데 같은 주에 나머지 모든 지표가 반대 방향으로 갔다. 7주간 D+6.0~6.6에 갇혀 있던 제너릭 밸럿이 위로 뚫려 네 집계가 D+7.2~8.6에 안착했고, 알래스카에서 사이클 처음으로 순위선택투표 라운드를 실제로 돌린 초당적 조사가 나왔으며, 예측시장은 한 주에 10센트 올랐다. 그리고 이번 주 데이터에는 아무도 크게 다루지 않은 반대 방향의 실측이 하나 더 있다 — 세 개 주에서 고령층이 공화당 쪽으로 돌아섰다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 9월 20일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 9/14~9/20 일간 브리핑 35건(전국·상원·하원·주정부·Korea Watch 각 7/7 — <strong>5개 트랙 전부 결손 없음</strong>). 뉴스 기준: 미 동부시간 9/19(토) 저녁까지. 선거일(11/3)까지 44일. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>상원 등급이 한 칸 움직였고, 그 한 칸이 민주당 반대쪽이었다.</strong> Cook이 <strong>9/15 뉴햄프셔를 Lean D → Toss-up</strong>으로 내렸다. 2주 사이 네 번째 기관의 공화 방향 이동이지만(IE 9/3 · 사바토 9/3 · CNN 순위 9/14 · Cook 9/15), <strong>3대 기관 등급을 실제로 움직여 의석 산술을 바꾼 것은 이번이 처음</strong>이다. 그래서 이 사이트의 등급가중 순 기대의석은 3주 연속 +2.25석에서 <strong>+2.125석</strong>으로 내려갔다 — 이동분은 전액 뉴햄프셔다.</li>
<li><strong>그런데 Cook이 든 근거가 조사가 아니라 자금이다.</strong> 파파스는 65%로 이긴 형식적 경선에까지 수입의 <strong>79%</strong>를 썼고, 그래서 보유 현금이 사실상 대등해졌다(수누누 302만 대 파파스 384만 달러). 반면 공개 조사는 정반대다 — RCP 평균 <strong>파파스 +2</strong>, 예측시장 <strong>민주 사수 83%</strong>. <strong>전망기관 4표 대 공개 데이터 1표</strong>가 이 지도의 최대 미해결 문제이고, 이 사이트가 지난주 판별 시험으로 지목했던 Kalshi 뉴햄프셔 가격은 이번 주 <strong>85¢ → 83¢</strong>로 2센트 내렸다. 방향은 전망기관 쪽인데, 폭은 등급 이동을 정당화하기엔 작다.</li>
<li><strong>나머지는 전부 반대 방향으로 갔고, 시장이 가장 크게 움직였다.</strong> 7주간 D+6.0~6.6에 고착돼 있던 제너릭 밸럿이 9/17 하루에 위로 뚫려 <strong>네 집계가 D+7.2~8.6</strong>에 이틀 연속 안착했다(Silver 자체 표기 “이번 사이클 민주당 최고점”). 그리고 <strong>Kalshi 상원 다수 계약이 49¢ → 59¢로 한 주에 10센트 올랐다</strong> — 이 사이트가 이 계약을 추적한 이래 최대 주간 이동이고, 다섯 주 동안 48~49¢에서 꿈쩍 않던 값이다. 같은 주에 Race to the WH는 63.9% → <strong>68.7%</strong>, Decision Desk HQ는 50.0% → <strong>52.0%</strong>였다.</li>
<li><strong>알래스카에서 이번 사이클 최고 가치의 조사 한 건이 나왔다.</strong> AARP 의뢰 초당적 조사(Fabrizio Ward[R] + Impact Research[D])가 1순위 펠톨라 46–41에 <strong>순위선택 라운드를 실제로 돌려 펠톨라 53–47</strong>을 냈다. 알래스카의 기존 수치는 전부 <strong>승자를 결정하지 않는 1순위 토플라인</strong>이었으므로, 이것이 핵심 탈환주가 승자 결정 규칙 하에서 전환된다는 첫 증거다. 시장은 즉시 반응했다 — <strong>64¢ → 72¢</strong>, 감시 9주 중 최대 상승.</li>
<li><strong>그리고 아무도 크게 다루지 않은 반대 방향의 실측이 하나 있다.</strong> 같은 AARP 조사에서 <strong>50세 이상은 설리번 49–42</strong>다. 이게 알래스카만의 일이 아니다 — 같은 주 <strong>조지아 65세 이상 콜린스 +14 · 텍사스 50세 이상 팩스턴 +11</strong>이 나왔다. <strong>세 개 주에서 반복 실측된 연령 역전이고, 전국 단위에서 이번 주 확정된 “투표가능층이 등록유권자보다 민주 쪽”이라는 역전과 정반대 방향이다.</strong> 둘 다 참일 수 있지만, 둘 다 51석 전망에 온전히 반영될 수는 없다.</li>
<li><strong>메인이 한 달 만에 처음으로 두 방향을 가리켰다.</strong> Quantus(공화계)가 <strong>콜린스 47.1–46.4</strong>를 냈다 — 8월 중순 의혹 이후 이 시계열의 <strong>첫 콜린스 우위</strong>이고, 이 사이트가 8월부터 적어 둔 Bear 체크리스트 항목이 발화한 것이다. 다만 0.7p는 동률이고, RCP 평균은 여전히 잭슨 +2.3이며, <strong>이번 주 메인과 조지아의 공화 방향 이동은 둘 다 Quantus 단일 하우스다</strong> — 독립 확인 2건이 아니라 한 기관의 판독이 두 주에 걸쳐 가중된 것이다.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>일반투표(제너릭) — <strong>이번 주 최대 사건</strong></td>
<td><strong>D+7.5</strong>(Silver Bulletin) · <strong>LV 보정 D+8.2</strong> · RCP <strong>D+8.6</strong>(50.5/41.9) · USPD D+7.4(49.3/41.9) · FPO D+7.2(50.5/43.2)</td>
<td>9/17~9/19</td>
<td><strong>7주간 D+6.0~6.6이던 회랑이 9/17 하루에 위로 뚫렸고, 이틀 연속 유지됐다.</strong> 하루 급등이 유지됐다는 것이 창(window) 인공물이 아니라 수준 변화라는 판정 기준이고, 통과했다. 정직한 요약은 Silver 기준 <strong>9/1 D+6.4 → 9/17 D+7.5로 3주에 걸쳐 약 1p 이동, 현재가 사이클 최고점</strong>이다. 동력은 평균 내부 감쇠가 아니라 <strong>고품질 신규 조사의 연쇄 착지</strong>다 — Reuters/Ipsos D+7(임기 최대) · NYT/시에나 LV <strong>D+8</strong> · CBS/YouGov LV D+8 · Economist/YouGov LV D+12 · Marquette LV D+13. <strong>RCP의 D+8.6은 9/17 하루 +2.1p인데 롤링 윈도 교체 효과가 섞여 있어 밴드 천장으로 할인해 읽는다</strong></td>
</tr>
<tr class="even">
<td><strong>LV 역전 — 이번 주에 정립된 구조</strong></td>
<td>Silver LV 보정 <strong>+0.7</strong>(D+7.5→<strong>D+8.2</strong>) · Marquette 자체 스크린 <strong>+5p</strong>(RV D+8→<strong>LV D+13</strong>) · Economist/YouGov LV <strong>D+12</strong></td>
<td>9/2~9/18</td>
<td><strong>서로 독립적인 세 방법이 같은 말을 했다 — 투표가능층이 등록유권자보다 더 민주당 쪽이다.</strong> 중간선거에서 LV 스크린은 통상 공화당 쪽으로 기울었으므로 <strong>역사 패턴의 역전</strong>이고, 기제는 실측된 투표 확실성 격차다(“반드시 투표” 민주 <strong>77</strong> / 공화 <strong>69</strong>, “매우 열의” 47 / 32). 결정적 보강은 방법론이다 — <strong>역사적으로 공화당에 가장 유리했던 유선 실사(NYT/시에나)가 D+8로 착지했다.</strong> 의석을 실제로 예측하는 지표 기준으로 환경은 D+7.5가 아니라 <strong>D+8.2 이상</strong>에 가깝다</td>
</tr>
<tr class="odd">
<td>트럼프 순지지도</td>
<td><strong>−19.5</strong>(Silver Bulletin, 9/18) ~ <strong>−24.6</strong>(FiftyPlusOne, 9/18) · USPD <strong>−21.1</strong>(37.7/58.8, 9/19) · 개별 최저 <strong>−26</strong>(Marquette·Quinnipiac)</td>
<td>9/18~9/19</td>
<td><strong>Silver Bulletin이 두 주 연속 −19.5에 고착됐다</strong>(9/16 하루 −20.1 판독 후 복귀). 이번 주 못 움직인 사건 목록이 지난주보다 무겁다 — <strong>연준 만장일치 인상, 연방대법원 우편투표 패소, 7주 조기 산회, 리야드 첫 민방위 경보.</strong> 지지율이 −20 부근에 이미 가격형성돼 있다는 뜻이다. 1기 동기 −13.0·바이든 동기 −11.3 대비 구조적 열위 <strong>약 6.5~8%p</strong>(원천이 주중 바이든 동기 수치를 −11.6에서 −11.3으로 조정)</td>
</tr>
<tr class="even">
<td>지지의 ‘강도’ — 강도가 산술로 계측됐다</td>
<td>강한 지지 <strong>15%</strong> / 약한 지지 22 / 약한 부정 16 / 강한 부정 <strong>47</strong> — 강도 순계 <strong>−32</strong></td>
<td>Marquette 9/2~9</td>
<td>지난주 이 자리에 “총계에도 밸럿에도 잡히지 않고 투표율·소액 후원에 잡히는 유형”이라고 썼다. <strong>이번 주에 그것이 숫자가 됐다.</strong> 2025년 2월 강한 지지 29%에서 19개월 만에 거의 절반이고, 공화당원·공화 성향 중 강한 지지는 <strong>36%</strong>뿐이다. 그리고 “반드시 투표”가 <strong>강한 지지층 81% / 약한 지지층 61% / 공화당원이면서 부정평가 56%</strong>로 계단식으로 감쇠한다 — <strong>강도 감쇠가 투표 확실성 격차로 번역되는 경로가 실측됐다.</strong> USPD 기준 무당층 지지 <strong>34%</strong>는 2018년 웨이브(−41석) 직전의 36%를 하회한다</td>
</tr>
<tr class="odd">
<td>이슈 지지율 — 시계열 최저 경신</td>
<td><strong>인플레이션·생활비 19</strong>(7월 24) · 유가 20 · 이란 전쟁 26 · 경제 28 · 관세 30 · 이민 43 · 국경안보 49</td>
<td>Marquette 9/2~9</td>
<td><strong>19%는 이 시계열에서 전 이슈 통틀어 사상 최저다.</strong> 더 무거운 것은 그 아래다 — 공화당원 중 “정책이 물가를 낮춘다”가 <strong>76%(2024-12) → 37%</strong>로 붕괴했고 무당층은 28% → 9%다. 64%가 “그의 정책이 인플레이션을 높인다”고 답한다(낮춘다 18%). 유권자 우선순위는 물가·생활비 37% + 경제 16% = <strong>경제 이슈 53%</strong>. Reuters/Ipsos에서는 <strong>경제 운용 정당 우위가 민주 38–37로 약 10년 만에 역전</strong>됐다</td>
</tr>
<tr class="even">
<td>금리·가격 — 연준이 “안 잡혔다”를 공식화했다</td>
<td><strong>FOMC 9/16 만장일치(12–0) 25bp 인상 → 3.75~4.00%</strong>, 점도표 <strong>18명 중 16명</strong> 추가 인상 · 10년물 장중 <strong>5.045%</strong>(2007년 이래 최고) · 모기지 ~7%</td>
<td>9/15~9/18</td>
<td><strong>만장일치라 지목할 반대파가 없다</strong> — 트럼프는 다음 날 이사회를 “매우 적대적, 매우 정치적”으로 공격했지만, 대법원 공격과 같은 구조적 약점을 갖는다(한 주에 대법원·연준·EU/캐나다 셋이 “적대적”으로 규정됐다). 5% 하회는 한 세션도 못 버텼다. <strong>선거 7주 전의 인상은 “인플레이션이 해결되지 않았다”는 공식 선언</strong>이다</td>
</tr>
<tr class="odd">
<td>연료 — 약속과 가격의 괴리가 매주 갱신된다</td>
<td>휘발유 <strong>$4.4759 사이클 최고</strong>(9/19) · 경유 <strong>$6.2694 신기록</strong>(9/15) · 브렌트 $109.44(9/14) → <strong>$103.87</strong>(9/18 마감)</td>
<td>AAA·주간</td>
<td><strong>유가는 내렸는데 주유소 가격은 올랐다.</strong> 브렌트가 주간 −1.2%인데 휘발유는 나흘간 +15센트다 — 하락이 복구 ’계획’에 기반한 반면 <strong>얀부 실측은 반대</strong>이기 때문이다(9/11 이후 선적 제로, 펌프장 3곳 손상, 10월 유럽 고객 차단). 경합주 값: <strong>MI $4.93 · PA $4.57 · OH $4.54.</strong> 브라운대 트래커 기준 2/28 개전 이후 추가 연료 지출 <strong>약 1,070억 달러(가구당 약 770달러)</strong> — 번역을 견디는 숫자다. <strong>어떤 유가 하락도 선거 전 마지막 물가 지표인 10/14 CPI에는 늦는다</strong></td>
</tr>
<tr class="even">
<td>반증 증거 — 이번 주가 가장 무거웠다</td>
<td>8월 소매판매 <strong>+1.2%</strong>(컨트롤그룹 +1.4%) · 신규 실업수당 <strong>19.6만</strong>(2개월 최저) · 브렌트 $109 → $104</td>
<td>9/16~9/18</td>
<td><strong>한 달간 가장 강한 친여당 데이터</strong>다. 다만 두 가지 단서가 붙는다 — 소매판매는 <strong>명목치이고 9월 연료 급등 이전</strong>이며(검증은 10/15), 실물 견조는 <strong>연준 매파성을 고착시키는 양날</strong>이다(강한 고용 + 높은 물가 = 준스태그플레이션 조합). 컨퍼런스보드 LEI는 3월 이후 <strong>첫 하락</strong>(−0.1%)이고 주요 하방 요인이 소비자 기대다 — “지금은 안 줄지만 선행 계열은 전부 아래”</td>
</tr>
<tr class="odd">
<td>제도전 — 사흘 새 세 번 정리됐고 전부 여당에 불리</td>
<td>연방대법원 <strong>USPS 우편투표 규칙 정지 신청 기각</strong>(9/14) · 하원 이란 전쟁권한 <strong>220–204 가결</strong>(공화 7명 이탈, 4명이 최전선) · 헤그세스 탄핵 표결 회피 <strong>7주 조기 산회</strong>(9/17)</td>
<td>9/14~9/17</td>
<td><strong>2026년 유권자에게 새 우편투표 장벽은 없고, 투표율 모델링의 최대 행정 불확실성이 제거됐다.</strong> 트럼프는 자신이 임명한 3인을 공격하고 판결을 <strong>“공화당에 큰 손실”</strong>로 규정했다 — 규칙의 목적에 대한 가장 솔직한 시인이다. 여론은 해당 명령 <strong>위헌 60–39</strong>(무당층 64–36). 전쟁권한 이탈 7명 중 <strong>4명이 최전선</strong>이라는 것은 후보들 자신의 환경 판독이고, 조기 산회는 “다수당이 장관 한 명을 지키려 산회했다”는 프레임을 공짜로 줬다. <strong>남은 45일간 본회의 표결이 환경 변수에서 제거됐다</strong> — 선거 전 의회 일정은 상원 H.Con.Res.89(10/2) 하나뿐이다</td>
</tr>
</tbody>
</table>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p><strong>이번 주 상원 등급 이동은 1건이고, 그 1건이 민주당 반대쪽이다</strong> — Cook이 9/15 뉴햄프셔를 Lean D → Toss-up으로 내렸다. 그러니 이 표를 읽을 때 순서를 뒤집어야 한다. 첫째, <strong>등급 열에서 움직인 것은 뉴햄프셔 하나뿐</strong>이고 그것이 이 사이트의 산수를 3주 만에 처음으로, 아래로 움직였다. 둘째, <strong>시장 열은 거의 전부 위로 갔다</strong> — AK +8¢ · TX +8¢ · MI +4¢ · OH +5¢ · IA +3¢ · GA +1.1¢ · NC +0.7¢, 보합 ME, <strong>유일한 하락이 NH −2¢</strong>다. 상원 다수 계약은 49¢ → <strong>59¢</strong>로 한 주에 10센트 올랐다. 셋째, 핵심 열에서 <strong>알래스카와 텍사스가 조사의 종류를 바꿨다</strong> — 둘 다 양당 공동 실사이고, 하나는 승자 결정 규칙을, 하나는 인구집단 구조를 쟀다. 그리고 그 두 조사 안에 <strong>연령 역전</strong>이라는 반대 방향 신호가 같이 들어 있다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 9/15 / Sabato 8/26 / IE 9/17)</th>
<th>시장 (Kalshi 9/20)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Lean D / Likely D / Tilt D</td>
<td>93.6¢ (▲1.1)</td>
<td><strong>결집과 이탈이 같은 주에 진행됐다.</strong> 켐프 주지사가 9/14 콜린스를 공식 지지했다 — 경선에서 둘리를 밀었던 주지사의 선거 7주 전 전향이므로 설득 자산이 아니라 <strong>결집 신호</strong>다(9/24 켐프+튠 합동 모금). 반대편에서는 공화 인사 3인(플레이크 전 상원의원·밸도스타/티프턴 시장)이 오소프를 지지했다. <strong>Quantus 오소프 +3.8은 완전 배분 조사의 첫 5%p 이내 측정</strong>이고 켐프 지지 당일 실사가 시작됐다 — 대조는 같은 공화계 Trafalgar +6.6. 정직한 범위는 <strong>오소프 +4~+7</strong>(9월 초 +8~9에서 하락). <strong>양 후보 과반 미달 시 12/1 결선</strong>이고, 상원 다수당이 확정된 뒤의 결선은 투표율 동학이 급변한다. 65세 이상 <strong>콜린스 +14</strong> (<strong>축소·시장 무반응</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td>66¢ (▲4)</td>
<td><strong>‘회복’이 확정됐다.** Emerson 엘사예드 48–46(9/12~14)·EPIC-MRA +4로 비당파 3연속이고 Silver 평균은 <strong>+2.9로 사이클 최대</strong>다. 과소평가된 수치는 호감도다 — <strong>엘사예드 순 +5 대 로저스 순 −4.</strong> 자금이 더 결정적이다: <strong>SMP가 1,000만을 증액해 미시간 누적 3,000만 달러</strong>가 됐다. 경선 후 유포된 ’엘사예드 방기’ 프레임은 자금 흐름과 양립하지 않는다 — </strong>이 사이트가 8월에 그 프레임을 수록했으므로 여기서 정정한다.** 공화 쪽은 머스크 America PAC이 새로 들어와 <strong>머스크·트럼프 계열·상원 지도부 자금이 동시에 투입된 유일한 사수 주</strong>가 됐다. 잔존 리스크는 학력 분열(비대졸 로저스 +3). 10/8·10/21 토론 양측 합의 확인 (<strong>개선 확정</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td><strong>Toss-up (9/15 ↓)</strong> / Lean D / Toss-up</td>
<td><strong>83¢ (▼2)</strong></td>
<td><strong>이번 주 지도의 구조적 이상점이자 유일한 산술 변경.</strong> Cook이 <strong>조사가 아니라 자금을 근거로</strong> 강등했다 — 파파스가 65%로 이긴 형식적 경선에까지 수입의 <strong>79%</strong>를 소진해 보유 현금이 사실상 대등해졌고(수누누 302만 대 파파스 384만), SLF 계열 One Nation이 세금 공격 광고를 집행 중이다(제시카 테일러: “전국 공화당의 투입 규모는 민주당에 적색 경고등”). <strong>반면 공개 데이터는 정반대다</strong> — RCP 평균 파파스 +2, InsiderAdvantage +8(기간 미기재로 DB 미등재), co/efficient 46–46, 예측시장 83%. 3주 내 조사가 <strong>13%p 범위</strong>에 흩어져 지도 최대 분산이다. <strong>지난주 판별 시험으로 지목한 Kalshi 가격이 2센트 내렸다</strong> — 전망기관 쪽으로 기운 첫 신호이되 폭은 작다 (<strong>악화(등급)·시장 −2¢</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D / Tilt D</td>
<td>92.7¢ (▲0.7)</td>
<td><strong>주중 집계 사이트의 “+8.2 → +4.2 접전화”를 이 사이트는 근거 없음으로 기각한다</strong> — 그 압축을 뒷받침하는 공개 조사가 특정되지 않았고, 최신 공개 조사는 정반대다. 그리고 그것을 낸 곳이 <strong>공화계 하우스</strong>다: <strong>Harper Polling/Carolina Journal 쿠퍼 49–34(+15)</strong>, 시리즈 궤적 3월 +8 → 9월 +15. 내용은 쿠퍼의 상승이 아니다(52→49%로 오히려 하락) — <strong>왯틀리 연합의 누수</strong>다: 공화 결집률 83→74%, 트럼프 2024 투표자 확보 85→72%, 공화당원 18%·트럼프 투표자 19%가 미결정. <strong>설득이 아니라 투표율의 이야기이고 미결정 공화층은 돌아올 수 있다.</strong> 트럼프 9/16 개스토니아 유세가 그 재결집을 만드는지가 최대 미해결 질문이다(Harper는 유세 이전 실사) (<strong>개선·닻 재확인</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss-up / Toss-up / <strong>Toss-up (9/17 ↑)</strong></td>
<td>67¢ (—)</td>
<td><strong>의혹 후 첫 콜린스 우위가 나왔다</strong> — Quantus(공화계, 9/14~15) <strong>콜린스 47.1–46.4</strong>. 이 사이트가 8월부터 적어 둔 Bear 체크리스트 항목이 발화한 것이다. 규율 셋: ① <strong>0.7p는 어떤 기준으로도 동률</strong>(배분 시 0.2p), ② 대조군은 여전히 잭슨 쪽(최근 5건 중 4건·RCP 평균 +2.3), ③ <strong>메인과 조지아의 공화 방향 이동은 둘 다 Quantus 단일 하우스</strong>다. 그럼에도 질적 변화는 실재한다 — <strong>한 달 만에 처음으로 메인 조사가 두 방향을 가리켰고</strong>, 메인을 잃으면 ‘핵심 4곳 석권=+4’ 경로가 깨져 Bull이 확장주를 요구하게 된다. 토론 4회가 10/6~15에 압축돼 있다. <strong>부수 성과: 13개월 넘게 낡은 값이던 IE 메인 등급이 Tilt R → Toss-up으로 갱신됐다</strong> (<strong>악화·시장 무반응</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss-up / Toss-up / Tilt R</td>
<td><strong>72¢ (▲8)</strong></td>
<td><strong>3주 공백이 사이클 최고 가치의 조사 한 건으로 해소됐고, 핵심은 마진이 아니라 방법이다.</strong> AARP 의뢰 <strong>초당적</strong> 조사(Fabrizio Ward[R]+Impact Research[D], 9/8~11, LV 800)가 1순위 펠톨라 46–41에 <strong>순위선택 라운드를 실제로 돌려 펠톨라 53–47</strong>을 냈다. 알래스카의 기존 수치는 전부 <strong>승자를 결정하지 않는 1순위 토플라인</strong>이었다 — <strong>핵심 탈환주가 승자 결정 규칙 하에서 전환된다는 첫 증거</strong>다. 같은 조사가 자기 반증을 담았다: <strong>50세 이상 설리번 49–42</strong>이고 이 층의 투표 의향이 더 높다. 대조로 라스무센(9/13~14) 39–39 동률. 동명이인 수사는 <strong>연방 대배심 소환장 단계로 격상</strong> — 부호는 진정으로 양방향이다(도플갱어 4%가 정리되면 <strong>펠톨라의 시뮬레이션 마진에는 불리</strong>하다) (<strong>개선·시장 최대 상승</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td>57¢ (▲5)</td>
<td><strong>조사와 자금이 정반대를 가리켰다.</strong> BGSU/YouGov(학술, 9/1~10, LV 1,000) <strong>브라운 48–45</strong>로 <strong>4연속 민주 우위</strong> 완성 — <strong>무당층 격차가 전체의 약 두 배</strong>라 정당 가중의 산물이 아니다. 반대편에서 Pollsmax 평균만 허스티드 46.3–46.1이고, 이 사이트는 설명 책임이 평균 쪽에 있다는 판정을 유지한다. 자금 쪽은 반대다: 트럼프·머스크·코크·상원 지도부 계열 <strong>‘팝업’ 슈퍼PAC들이 한 주에 1,400만 달러</strong>를 집행해 누적 광고비가 <strong>2억 9,800만 달러로 사이클 상원 최대</strong>가 됐다. 로이터는 촉발 요인을 명시했다 — <strong>“허스티드가 3~5%p 열세.”</strong> 팝업 구조는 <strong>기부자 공개가 투표 후로 지연되는 법적 설계</strong>다. <strong>브라운의 우위는 이 밀도에서 검증된 적이 없다</strong> (<strong>유지·확인</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Toss-up / Toss-up / Lean R</td>
<td><strong>59¢ (▲8)</strong></td>
<td><strong>우위·동률이 5연속</strong>이 됐다(Emerson 47–46 포함, 동일 도구 기준 8월 팩스턴 +1에서 순 2p 이동). 실질은 토플라인이 아니라 구조 실측이다: <strong>Cook/TelevisaUnivision 히스패닉 전용 조사 탈라리코 63–30</strong>(OnMessage[R]+Hart[D] 공동, n=1,000) — 2024년 텍사스를 만든 히스패닉 쏠림의 역전을 양당 공동으로 측정한 것이라 <strong>하우스 이펙트로 할인할 수 없는 이 주 최강 근거</strong>다. 단 같은 주 Emerson 하위표본은 +15로 <strong>18%p 불일치가 텍사스 최대 미해결 측정 문제</strong>다. 자금: SLF 텍사스 계열 PAC 출범, 보도 금액이 <strong>3,200만 대 5,400만 달러로 갈린다</strong>(FEC 원본 대조 전까지 범위로 적는다) — 어느 쪽이든 <strong>7월에는 방어하지 않던 주를 방어 중</strong>이다. 팩스턴은 9/22 토론을 수락하지 않은 채 D-2에 접근했다 — <strong>9주 주요정당 후보 중 유일한 전무 수락자.</strong> 50세 이상 <strong>팩스턴 +11</strong> (<strong>개선·시장 +8¢</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Toss-up / Lean R / Tilt R</td>
<td>41¢ (▲3)</td>
<td><strong>9주 중 최대인 10%p 측정 격차가 이번 주에도 미해소다</strong> — Rasmussen(공화계) 투렉 +5 대 Emerson 힌슨 +5, 사이에 Suffolk 힌슨 +4(8/20~23, 이번 주 신규 수록). 최소 한 기관이 크게 틀렸다는 뜻인데, <strong>아이오와는 그 판정을 간단히 내릴 수 없는 유일한 주다</strong> — 공화계가 D+5를 내고 무성향이 R+5를 내서 <strong>방향이 하우스 성향과 어긋나</strong> 조지아·오하이오식 ‘자백’ 논리가 안 먹힌다. 그래서 이번 주 실질은 조사가 아니라 <strong>현시선호</strong>다: 밴스 부통령(9/18)과 배라소 원내총무(9/19)가 <strong>트럼프가 13%p로 이긴 주에 연이틀</strong> 들어왔고, <strong>내부 판세가 힌슨 +5와 같다면 하지 않을 배분</strong>이다. 두 행사 모두 투렉 공격이 아니라 <strong>자기 이슈 방어</strong>였다. 승부 집단은 무당층이고 그 규모가 등록 민주를 넘는다. 10/7 단일 토론 (<strong>혼조·미해소</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 이 사이트 조사 DB에 새로 들어간 본선 조사는 <strong>여덟 건</strong>이다 — 조지아 1건(Quantus 9/14~16), 미시간 1건(Emerson/Nexstar), 노스캐롤라이나 1건(Harper/Carolina Journal), 메인 1건(Quantus), 알래스카 2건(AARP 초당적 · Rasmussen), 텍사스 1건(Emerson/Nexstar), 뉴햄프셔 1건(co/efficient). <strong>실사기간이 확인되지 않은 것은 넣지 않았다</strong> — 뉴햄프셔 InsiderAdvantage 파파스 +8(기간 미기재)과 텍사스 Telemundo/Mason-Dixon(세부 미공표)이 그렇고, 조지아 Quantus 9/9~12(미배분 24%로 해석 불가)는 원천 자체가 후속 조사로 대체했다. 텍사스 Cook/TelevisaUnivision은 히스패닉 전용 조사라 <strong>전주(全州) 조사표에 넣지 않고 서술로만 반영</strong>했다.</p>
</section>
<section id="하원-cook은-멈췄고-나머지-둘이-이틀에-17건을-옮겼다" class="level2">
<h2 class="anchored" data-anchor-id="하원-cook은-멈췄고-나머지-둘이-이틀에-17건을-옮겼다">하원 — Cook은 멈췄고, 나머지 둘이 이틀에 17건을 옮겼다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cook 토플라인 — <strong>9일 연속 동결</strong></td>
<td>Solid D <strong>185</strong> / Likely D 12 / Lean D 9 / <strong>Toss Up 21 (D 5 · R 16)</strong> / Lean R 7 / Likely R 21 / Solid R <strong>180</strong> (9/11 보드, 자동 취득 — 합계 435 검증). <strong>전주와 완전히 동일하고, 9일 연속은 이번 사이클 Cook 최장이다.</strong> 토스업 21석 명단도 원문 대조에서 정확히 일치했다</td>
</tr>
<tr class="even">
<td>등급 이동 — <strong>이틀에 17건, 전원 민주 방향</strong></td>
<td><strong>사바토 9/16 8건</strong>: AR-02·NV-02·NY-21·OH-10 Safe→Likely R / CO-05 Likely→Lean R / <strong>IA-02·MI-04 Lean R→Toss-up</strong> / <strong>NJ-07 Toss-up→Lean D</strong>. <strong>Inside Elections 9/17 9건</strong>: CO-05·IA-02·NC-01 Lean→Tilt R / <strong>FL-14 Tilt R→Toss-up</strong> / FL-16·TX-09·WI-01 Safe→Likely R / FL-27 Likely→Lean R / NY-19 Lean→Likely D. 사바토 토스업 <strong>22석(D4/R18)</strong>, IE 협의 토스업 <strong>17석</strong></td>
</tr>
<tr class="odd">
<td><strong>NJ-07 — 두 번째 민주 방향 토스업 이탈</strong></td>
<td>사바토가 킨(R)의 지역구를 Toss-up → <strong>Lean D</strong>로 뺐다. 토스업 층의 이동은 오랫동안 <strong>전부 공화 의석이 악화되며 들어오는 방향</strong>이었고, 나가는 방향은 TX-34(9/10)에 이어 두 번째다. 근거였던 StimSight 조사(베넷 47–42)는 <strong>스폰서 연계</strong>라 이 사이트는 깨끗한 수치로 취급하지 않는다(소유주가 DNC 전국위원이자 베넷 기부자) — <strong>비스폰서 교차검증이 1순위 감시 항목</strong></td>
</tr>
<tr class="even">
<td><strong>FL-14 — 8월 편입구 최초의 3사 합의</strong></td>
<td>IE가 Tilt R → Toss-up으로 올리면서 8월 신규 편입 지역구 중 처음으로 <strong>세 기관이 토스업에 합의</strong>했다. 플로리다 게리맨더가 FL-14에서 <strong>설계 성능에 미달한다는 가장 강한 확인</strong>이다</td>
</tr>
<tr class="odd">
<td>Cook 홀드아웃 — 이제 적체가 아니라 판단</td>
<td><strong>TX-15</strong>(사바토 Toss-up·IE Tilt R인데 Cook만 Lean R — 편입 1순위, 이동 시 22석) · <strong>NC-11</strong>(사바토 Toss-up·<strong>IE도 9/17 Tilt R로 이동</strong>, Cook만 Lean R) · 역방향으로 <strong>NJ-07·TX-34</strong>(Cook이 사바토를 따라가면 <strong>20석으로 첫 감소</strong>). <strong>Cook Lean R 7석 중 5석이 이제 타기관 기준으로 한 단계 이상 민주 쪽</strong>이다</td>
</tr>
<tr class="even">
<td><strong>모리스의 등급기관 보정 연구 — 이번 주 최대 해석 갱신</strong></td>
<td>2010~2022 중간선거에서 <strong>3사 토스업의 67%를 야당이 획득</strong>했다는 경험적 구간 승률(야당 Lean 95~97%·여당 Lean 22%·여당 Likely 12%)을 같은 Cook 분포에 대입하면 문자적 <strong>D 218석·51%</strong>가 <strong>D 228석·83%</strong>로 이동한다. <strong>“Cook 토스업 = 동전던지기”라는 독법이 공식 폐기됐다는 뜻</strong>이고, 이 사이트는 이번 주부터 <strong>216석(문자적) / 224석(경험 보정) 병기 체제</strong>로 전환한다</td>
</tr>
<tr class="odd">
<td><strong>Cook 자체 경합구 직접 계측 — 바닥과 천장이 동시에</strong></td>
<td><strong>Cook Battleground District Project</strong>(New River[D]+GS Strategy[R] 양당 공동, 경합 37개구 LV 1,052, ±3.02): 지역구 제너릭 <strong>D+2(49–47)</strong> — 트럼프 평균 <strong>+5 지형에서 7p 스윙</strong>. 이슈 신뢰 경제 +7·인플레 +8·<strong>휘발유 +12</strong>·데이터센터 +10, 이민만 R+5. <strong>그런데 CPR 자신의 해석이 천장 논거다</strong> — 민주 증가분이 “대체로 트럼프 +10 이하 지역구에 국한”되고 <strong>공화 보유 의석의 86%가 그 선 위</strong>다</td>
</tr>
<tr class="even">
<td>시장·모델 — 사이클 최고치</td>
<td><strong>실시간 5개 거래소 합산 민주 하원 통제 87.9%</strong>(9/18, $46.3M — <strong>8회 연속 상승</strong>) · 이 사이트 Kalshi 직접 취득분 <strong>91.2¢</strong>(9/20, 전주 86¢) · <strong>CBS/YouGov 모델 D 228석</strong>(95% 구간 215~230대 후반) · DDHQ <strong>70%·D 231석</strong>(모델 갱신 9/18) · FiftyPlusOne 모델 중앙값 <strong>D 238·98%</strong> · Smarter.Vote 228(8/27 이후 <strong>24일 정체 — 가중 하향</strong>)</td>
</tr>
<tr class="odd">
<td>지역구 실측 — 전면 공백</td>
<td><strong>Tier-1 21석에 대한 신규 단일 지역구 공개 조사 0건.</strong> NY-17(전국 최대 표적)은 노동절 후 <strong>11일 넘게 공백</strong>이고 IA-01·MI-07·OH-07도 마찬가지다. <strong>광고 문서화가 사실상 선행지표 역할을 하는 국면</strong></td>
</tr>
<tr class="even">
<td>트럼프계 슈퍼PAC — 방어 지도가 공개 등급보다 넓다</td>
<td>9/1 동시 등록된 유령성 PAC 2개(No Going Back · Safety and Affordability — 인프라 전부 공유)가 2주 만에 <strong>3개 PAC 합산 1억 3,650만 달러 이상 예약</strong>(NPR/AdImpact 9/18). 확인된 하원 표적은 NY-17·FL-25·MI-04·NV-03·TX-15·KY-06·AL-02인데 <strong>MI-04·NV-03·KY-06은 어느 공표 경합 층에도 없거나 Likely R</strong>다. 구조적 논점 셋: ① <strong>9/1 등록 = 기부자 공개 10월 말 지연</strong>(사전·우편투표 기간 내내 익명성 구매) ② <strong>최저단가 창을 사흘 놓친 시장가 매입</strong>(10월 1달러는 8월 1달러보다 적은 노출을 산다) ③ <strong>작명에서 MAGA 제거</strong> — 방어 지역구에서 대통령 브랜드가 순부담이라는 시인</td>
</tr>
</tbody>
</table>
<p><strong>이번 주 하원의 사건은 등급이 움직인 게 아니라 등급을 읽는 법이 바뀐 것이다.</strong> 이 사이트는 오랫동안 Cook 토스업 21석을 반씩 나눠 216석을 산출하고 “218 미달”이라고 적어 왔다. 이번 주에 모리스가 그 산식의 가중치 자체에 <strong>계측된 대안</strong>을 제시했다 — 지난 네 번의 중간선거에서 토스업의 67%는 야당이 가져갔다. 같은 분포에 그 계수를 넣으면 <strong>224석</strong>이다. 문자적 해석 51%가 경험 보정 83%가 되고, <strong>83%는 처음으로 시장 밴드(87.9%) 안으로 들어온다.</strong> 일주일 전 35%p였던 ’등급 문자해석 대 시장’의 괴리가 <strong>5%p로 압축됐다.</strong></p>
<p><strong>그런데 같은 주에 천장도 계측됐고, 이쪽이 덜 알려졌다.</strong> Cook 자신의 경합구 직접 조사는 D+2를 냈다 — 트럼프 +5 지형이므로 <strong>7p 스윙</strong>이고, 다수를 확보하기에 충분한 수치다. 하지만 CPR은 그 증가분이 <strong>트럼프 +10 이하 지역구에 국한</strong>되고 공화 보유 의석의 86%가 그 위에 있다고 썼다. <strong>경합 집합 자체가 공화 우세 지형으로 이동해 있어서, D+8 환경도 의석 전환율이 2018년(D+8, −40석)에 못 미칠 수 있다는 것이 이번 사이클 고유의 제도적 상한이다.</strong> 두 계측을 같이 놓으면 결론은 하나다 — <strong>양립하는 답은 ’완만한 폭의 민주 다수’이지 2018년급 석권이 아니다.</strong> 이 사이트는 중심 시나리오를 <strong>D 224~230</strong>으로, 다수 확률을 <strong>85~88%</strong>로 적는다. (<a href="https://centerforpolitics.org/crystalball/seven-weeks-to-go-polling-not-getting-better-for-republicans-8-house-rating-changes/">사바토 8건</a> · <a href="https://insideelections.com/house-report-shorts-sept-17-2026/">IE 9건</a> · <a href="https://www.gelliottmorris.com/p/2026-09-18-race-raters-lagging-midterms">모리스</a> · <a href="https://www.cookpolitical.com/analysis/survey-research/battleground-district-project/new-battleground-district-poll-shows">Cook Battleground</a> · <a href="https://www.npr.org/2026/09/18/nx-s1-5971202/trump-super-pac-midterm-spending-republicans-democrats">NPR/AdImpact</a> · <a href="https://electionbettingodds.com/House-Control-2026.html">ElectionBettingOdds</a>)</p>
</section>
<section id="주지사-알래스카가-일주일-만에-두-번-움직였다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-알래스카가-일주일-만에-두-번-움직였다">주지사 — 알래스카가 일주일 만에 두 번 움직였다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (9/20)</th>
<th>전주(9/13)</th>
<th>등급 (Cook 9/18 / Sabato 9/3 / IE 9/17)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td><strong>94.2¢</strong></td>
<td>92.7¢</td>
<td>Solid D / Likely D / <strong>Safe D (9/17↑)</strong></td>
</tr>
<tr class="even">
<td>미시간</td>
<td>90.8¢</td>
<td>91¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="odd">
<td>애리조나</td>
<td>88¢</td>
<td>87¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="even">
<td>위스콘신</td>
<td><strong>84¢</strong></td>
<td>81¢</td>
<td>Toss-up / Lean D / Toss-up</td>
</tr>
<tr class="odd">
<td><strong>알래스카</strong></td>
<td><strong>82¢</strong></td>
<td>64¢</td>
<td><strong>Toss-up (Cook 9/17↑)</strong> / Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>아이오와</td>
<td>80¢</td>
<td>78¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>57¢</td>
<td>56¢</td>
<td>Toss-up / Lean R / Tilt R</td>
</tr>
<tr class="even">
<td>조지아</td>
<td>56¢</td>
<td>56¢</td>
<td>Toss-up / Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td>47¢</td>
<td>45¢</td>
<td>Toss-up / Lean R / Tilt R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>30¢</td>
<td>33¢</td>
<td>Lean R / Lean R / Tilt R</td>
</tr>
</tbody>
</table>
<p><strong>지난주 이 표에서 “취약한 상향”이라고 적은 항목이 일주일 만에 한 칸 더 갔다.</strong> Cook은 9/10에 알래스카를 Likely R → Lean R로 옮겼고, <strong>9/17에 다시 Lean R → Toss-up</strong>으로 옮겼다. 사바토가 9/1에 이미 Toss-up이었으므로 <strong>양사 등급이 이번 사이클 처음으로 완전히 일치</strong>했다. 그리고 지난주에 이 사이트가 적었던 취약성 — “근거가 실측이 아니라 구도 해석 한 건이고 본선 실측은 0건” — 이 같은 주에 해소됐다. <strong>AARP 초당적 조사가 본선 첫 실측을 냈다: JKT 40 – 윌슨 20 – 브론슨 14 – 테일러 7.</strong> 시장은 <strong>64¢에서 82¢로 18센트</strong> 올랐다 — 이 사이트가 추적하는 주지사 10곳 중 압도적 최대 이동이다.</p>
<p><strong>그런데 이 조사의 진짜 내용은 1순위 합계다.</strong> 민주 40 대 공화 3인 합계 41이다. <strong>승부는 공화 3인의 순위선택 이양 완결률에 전적으로 달려 있고, 그 이양률 실측은 0건이다.</strong> 윌슨은 9/18 두 경쟁자에게 사퇴를 요구했고 브론슨·테일러는 거부했다 — <strong>10/4 후보 등록 마감이 이 요구가 실제 구도 변경(3R→2R)으로 이어지는지의 유일한 기한</strong>이다. 알래스카는 여전히 이 표에서 신뢰구간이 가장 넓은 칸이고, 가격이 18센트 오른 것과 구조가 해소된 것은 다른 이야기다.</p>
<p><strong>캔자스에서는 반대 일이 벌어졌다 — 실측 한 건이 시나리오 하나를 죽였다.</strong> 사이클 첫 비당파 조사인 Emerson/Nexstar(9/15~16)가 <strong>매스터슨 51–44(R+7)</strong>를 냈다. 이 사이트와 원천 트랙은 전주에 “다음 비당파 조사가 나오면 상방 시나리오를 판정한다”는 조건을 명문화했는데, <strong>조건이 충족되는 동시에 기각됐다</strong> — 캔자스 상방은 공식 폐기다. 더 읽을 것은 조사 안의 구성이다: <strong>같은 표본에서 트럼프 −13이고 켈리 주지사 +7인데 매스터슨이 +7이다.</strong> 환경과 레이스가 분리된 이번 사이클 최선명 사례이고, 캔자스의 정당 교대 관성에 대한 첫 실측 뒷받침이다. 남은 변수는 인지도다 — <strong>홀셔를 모른다는 응답이 12%</strong>인데 양측 광고 집행 규모가 확보되지 않았다.</p>
<p><strong>그리고 같은 표본 안에서 상원과 주지사가 갈리는 현상이 이번 주에 세 주에서 확인됐는데, 방향이 주마다 반대다.</strong> 캔자스에서는 주지사가 R+7인데 같은 조사의 상원은 무당파 후보가 무당층에서 +15다. 조지아에서는 라스무센이 주지사 <strong>잭슨 +3</strong>(사이클 첫 공화 우위)과 상원 <strong>오소프 +9</strong>를 같은 날 냈다. 미시간에서는 Emerson이 주지사 <strong>벤슨 +7</strong>(오차범위 밖)과 상원 <strong>접전</strong>을 같은 표본에서 냈다. <strong>분화의 방향이 주마다 반대이므로 체계적 편향이 아니라 후보 함수다.</strong> 이 사이트가 써 온 “무당파에서 민주가 두 자릿수로 앞선다”는 규칙은 이제 <strong>상원 트랙 한정</strong>으로 정정한다 — 주지사 트랙에는 조지아·캔자스라는 반례가 있다.</p>
<p><strong>한편 조사가 없어야 할 곳에 조사가 없다는 것이 이번 주 주지사 트랙의 두 번째 사실이다.</strong> 9/16 연준 인상은 실현됐는데, 이 사이트가 ’환경 의존 우위’로 분류한 세 주(<strong>위스콘신·미시간·네바다</strong>)의 인상 후 조사는 주말 기준 <strong>나흘째 0건</strong>이다. 미시간의 Emerson 조사조차 실사 종료가 9/14로 <strong>인상 이전</strong>이다. 감도 시험은 개시만 된 상태이고, 다음 주 최대 관측점이다. 대신 비여론 신호는 쌓였다 — <strong>네바다 소매업협회가 2022년 롬바르도 지지를 뒤집고 포드를 지지했고</strong>(사유: 비용·관세), <strong>오하이오 의사협회 PAC은 의사 출신 후보 액턴이 아니라 라마스와미를 지지했다.</strong> 방향이 반대인 두 사례의 공통 구조는 정당이 아니라 <strong>회원의 직접 이익</strong>이다. 메인에서는 DGA 계열 PAC이 TV 55만 달러를 철회해 <strong>실측·시장·집계·자원배분·IE Safe D 다섯 계통이 정렬</strong>했다 — 이 사이트는 이번 주부터 <strong>’자원배분’을 제4 관측 채널로 신설</strong>한다. (<a href="https://thehill.com/homenews/campaign/6096933-alaska-gov-race-cook-tossup/">Cook/AK</a> · <a href="https://www.aarp.org/press/releases/2026-09-17-new-aarp-alaska-poll-older-voters-will-be-influential-in-u-s-senate-gubernatorial-and-congressional-races.html">AARP/AK</a> · <a href="https://emersoncollegepolling.com/kansas-2026/">Emerson/KS</a> · <a href="https://politicalwire.com/2026/09/16/amy-acton-leads-in-ohio-governors-race/">BGSU/OH</a> · <a href="https://www.wlns.com/your-local-election-hq/benson-leads-james-michigan-poll/">Emerson/MI</a> · <a href="https://www.ajc.com/politics/2026/09/polls-paint-starkly-different-pictures-of-georgias-top-races/">AJC(GA 트랙 분화)</a> · <a href="https://lasvegassun.com/news/2026/sep/15/nevada-retailers-group-citing-high-costs-and-tarif/">NV 소매업협회</a> · <a href="https://signalcincinnati.org/2026/09/17/why-a-doctors-pac-chose-vivek-ramaswamy-over-dr-amy-acton/">OH 의사협회 PAC</a> · <a href="https://www.sunjournal.com/2026/09/17/national-democrats-ease-up-on-maine-governor-spending-due-to-confidence-in-hannah-pingree/">ME 자원배분</a>)</p>
<hr>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>26주차(9/14~9/20) 거시 환경은 ’회랑이 깨진 주간’이었다 — 7주간 D+6.0~6.6에 고착돼 있던 제너릭 밸럿이 처음으로 위로 뚫려 네 집계가 D+7.2~8.6(중심값 Silver D+7.5, 투표가능층 보정 D+8.2, “이번 사이클 민주당 최고점”)에 이틀 연속 안착했고, 방향은 전주에 이어 여당에 불리한 쪽으로 한 단계 더 기울었다.</strong> 연준은 9/16 만장일치 25bp 인상(3.75~4.00%)과 함께 18명 중 16명의 추가 인상 점도표를 내놨고, Marquette 조사는 인플레이션 지지율 19%(시계열 전 이슈 최저)·공화당 내 “정책이 물가를 낮춘다” 76→37% 붕괴·투표가능층 스크린의 민주 +5p 역전(3중 확인)을 실측했으며, 연방대법원의 우편투표 기각(9/14)·전쟁권한 220–204 가결(공화 7명 이탈)·하원의 7주 도피 산회로 제도·의회 변수도 일방향으로 정리됐다. 반증 증거도 이번 주가 가장 무거웠다 — 소매판매 +1.2%와 신규청구 19.6만의 실물 견조, 브렌트 $109→$104의 완화, 그리고 트럼프가 9/22 유엔총회 걸프 정상회담을 입력값으로 지목한 “전면 격파냐 종전이냐” 결정의 종전 갈래 — 그러나 AAA 휘발유는 사이클 최고 $4.4759로 오르며 약속과 가격의 괴리를 매주 갱신했고, 얀부 선적 제로·리야드 첫 피격이 완화 시나리오를 잠식했으며, 어떤 유가 하락도 선거 전 마지막 물가 지표인 10/14 CPI에는 늦는다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(강) — 전주 판정 유지, 확신도 추가 상승(확신의 대상이 ’방향’에서 ’수준 D+7 중반~8’까지 확장). 직전 주 대비 변화 방향: 밸럿 수준 약 1p 민주 쪽 이동으로 사이클 최고점 경신이며, 남은 최대 반전 경로는 9/22 걸프 회담發 조기 종전이나 그 실현 확률은 9/19 리야드 피격으로 좁아졌다.</strong> (인용: <code>national_weekly/2026-09-20</code> §6-4)</p>
</blockquote>
<p>여기에 세 가지를 덧붙인다.</p>
<p>첫째, <strong>확신의 대상이 바뀌었다는 위 문장이 이번 주의 핵심이고, 이 사이트는 그것을 다르게 표현하고 싶다.</strong> 지난 일곱 주 동안 이 사이트가 반복해서 적은 문장은 “지지율이 빠지고 유가가 사상 최고인데 밸럿이 멈췄다”였다. 그 정지는 <strong>가격 충격이 선거 지표로 번역되지 않는다</strong>는 뜻일 수도 있었고, <strong>번역에 시차가 있다</strong>는 뜻일 수도 있었다. 두 해석은 예측이 정반대로 갈린다. <strong>이번 주에 두 번째 쪽이 이겼다.</strong> 경유 $6와 소비자심리 47.8이 있던 주에 밸럿은 D+6.4~6.6이었는데, 그 다음 주에 나온 고품질 조사들이 연달아 D+7~8에 착지했다. <strong>정지는 천장이 아니라 지연이었다.</strong> 이 판정이 중요한 이유는 아직 번역되지 않은 재고가 남아 있기 때문이다 — 9/16 인상, 사이클 최고 휘발유값, 10/14 CPI는 <strong>아직 어느 조사에도 들어가 있지 않다.</strong></p>
<p>둘째, <strong>그런데 이번 주 조사에는 그 각주가 여전히 붙는다.</strong> 이 표에 실린 상원 조사의 실사 창은 대부분 <strong>9/8~9/16</strong>이다. FOMC 인상은 9/16이고 휘발유 사이클 최고는 9/19다. <strong>이번 주 조사 대부분은 인상 전후의 경계에 걸쳐 있고, 인상과 유가 최고가가 완전히 반영된 첫 조사는 다음 주부터 나온다.</strong> 지난주에도 같은 각주를 달았는데, 그때는 “충격 이전의 세계를 재는 마지막 측정”이라고 썼다. 이번 주는 조금 다르다 — <strong>충격의 절반이 들어간 측정</strong>이고, 그래서 다음 주 조사가 이번 주보다 더 좋게 나오면 그것은 새 정보이지 잡음이 아니다.</p>
<p>셋째, <strong>반증 증거가 이번 주 가장 무거웠다는 원천의 판단에 한 줄을 보탠다.</strong> 소매판매 +1.2%와 신규청구 19.6만은 실물 경제가 멀쩡하다는 뜻이고, 보통은 여당에 좋은 소식이다. <strong>그런데 이번 사이클에서는 그것이 양날이다</strong> — 강한 고용과 높은 물가가 같이 있으면 연준은 계속 올린다. 실제로 점도표는 18명 중 16명이 추가 인상이다. <strong>“경제가 튼튼한데 유권자가 화가 나 있다”는 서술은 이 사이클에서 모순이 아니라 인과다</strong> — 소비가 멈추지 않으니 금리가 내려가지 않고, 금리가 내려가지 않으니 모기지가 7%다. 물가 지지율 19%는 그 인과의 끝단이다.</p>
</section>
<section id="상원-산수-3주-만에-움직였고-아래로-움직였다" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-3주-만에-움직였고-아래로-움직였다">상원 산수 — 3주 만에 움직였고, 아래로 움직였다</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 50–50은 밴스 부통령의 캐스팅보트로 공화 다수이므로 부족하다. 무소속 3인 중 민주 코커스를 약속한 사람은 없다 — <strong>+4 산술에 우회로는 없다.</strong></p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 9/15·사바토 8/26 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .50 + IA .375</td>
<td><strong>+3.125석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td>GA .125 + MI .50 + <strong>NH .375</strong></td>
<td><strong>−1.000석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.125석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>GA .125 + MI .50 + NH <strong>.25</strong></td>
<td>+2.25석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td><strong>Cook의 뉴햄프셔 Lean D→Toss-up 1건</strong></td>
<td><strong>−0.125석</strong></td>
</tr>
</tbody>
</table>
<p><strong>3주 연속 소수점까지 같던 숫자가 이번 주에 움직였고, 방향이 아래다.</strong> 이동분은 전액 뉴햄프셔다 — Cook이 NH를 Lean D에서 Toss-up으로 내리면서 이 주의 상실 위험 가중치가 .25(Cook·Sabato 둘 다 Lean D)에서 .375(Cook Toss-up .50과 Sabato Lean D .25의 평균)로 올라갔다. <strong>감시 9주 중 이번 주에 등급이 움직인 곳은 뉴햄프셔 하나뿐이고, 그것이 민주당 쪽이 아니었다는 것이 이 표의 전부다.</strong></p>
<p><strong>여기서 두 가지를 기록해 둔다.</strong> 첫째, <strong>원천 상원 브리핑은 같은 주의 기대 순증을 +2.0석으로 적는다.</strong> 차이는 사바토의 뉴햄프셔 등급에서 온다 — 원천은 사바토가 9/3에 NH를 Toss-up으로 내렸다고 보는데, <strong>이 사이트가 받는 270towin 재게시 피드의 사바토 스탬프는 여전히 8/26자이고 값은 Lean D 그대로다.</strong> 이 사이트는 직접 받는 피드를 정본으로 삼으므로 +2.125를 쓰되, 차이가 있다는 사실을 여기 남긴다. 어느 쪽이든 결론(+4 미달)은 바뀌지 않는다. 둘째, <strong>Inside Elections의 메인 등급이 이번 주에 갱신됐다</strong> — 이 사이트가 지난 몇 주 동안 “2025-07-24자라 잭슨 지명·스캔들 국면 전체보다 앞선 낡은 값”이라고 적어 온 Tilt R이 <strong>9/17 Toss-up으로 바뀌었다.</strong> 원천 상원 브리핑은 IE의 이번 주 상원 이동을 0건으로 기록하고 있어 이 항목은 이 사이트 피드에만 잡혔다. 산수에는 들어가지 않지만(두 기관 평균이므로), <strong>13개월 넘게 열려 있던 낡은 값 플래그 하나가 닫혔다.</strong></p>
<p>네 종류의 숫자는 이번 주에 <strong>셋이 같이 올랐다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>59¢</strong></td>
<td>49¢</td>
<td>거래액 $413만·미결제 $212만. <strong>한 주에 10센트 — 이 사이트가 이 계약을 추적한 이래 최대 주간 이동이고, 다섯 주 동안 48~49¢에서 움직이지 않던 값이다.</strong> 개별 주도 한 곳만 빼고 전부 올랐다(AK +8¢·TX +8¢·MI +4¢·OH +5¢·IA +3¢, <strong>유일한 하락 NH −2¢</strong>)</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (Decision Desk HQ)</td>
<td><strong>52.0%</strong> (평균 의석 D 51 – R 49)</td>
<td>49.0%→50.0%</td>
<td>모델 갱신 9/18. 전주 50.0%에서 52.0%로 올라 처음 다수 쪽에 섰다. <strong>그런데 평균 의석은 D 51로 전주와 같다</strong> — 확률만 올랐고 의석은 그대로다. 51석은 <strong>여유가 0인 다수</strong>이므로 52%는 “넉넉한 우세”가 아니라 “동전던지기보다 아주 조금 나은, 오차 여유 없는 과반”에 대한 값이다. 네 수치 중 가장 보수적</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>68.7%</strong> (예상 의석 D 52.3 – R 47.7)</td>
<td>63.9%</td>
<td>Infogram 라이브 시계열 직접 취득(마지막 관측 9/20, 137점). <strong>2주 연속 상승이고 네 수치 중 최고다.</strong> 예상 의석도 51.6 → 52.3으로 다수선 위로 더 올라갔다</td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.125석</strong></td>
<td>+2.25석</td>
<td>서수적 등급을 확률로 환산 — 전국 환경이 들어갈 자리가 구조적으로 없다. <strong>3주 만에 움직였고 방향이 아래다</strong></td>
</tr>
</tbody>
</table>
<p><strong>지난주에 이 자리에서 “Race to the WH 혼자 63.9%로 떠났다”고 썼다. 이번 주에는 혼자가 아니었다.</strong> 세 지표가 같이 올랐고, 그래서 두 모델의 격차는 13.9%p에서 <strong>16.7%p로 오히려 더 벌어졌다.</strong> 그런데 지난주와 결정적으로 다른 점이 하나 있다 — <strong>시장이 그 사이로 들어와 앉았다.</strong> 전주에는 DDHQ 50.0과 Kalshi 49가 아래쪽에 붙어 있고 RtWH만 위에 있었다. 이번 주에는 <strong>52 &lt; 59 &lt; 68.7</strong>이다. 시장이 두 모델의 중간값 근처로 이동했다는 것은 <strong>거래자들이 보수적인 모델보다는 낙관적인 모델 쪽으로 가중치를 옮겼다</strong>는 뜻이고, 이건 지난 다섯 주의 가격 정체가 깨진 첫 신호다.</p>
<p><strong>그래도 평균 내지 말 것이라는 규칙은 그대로다.</strong> 52%와 68.7%는 같은 데이터를 먹고 나온 값인데 16.7%p 차이다. 차이를 만드는 것은 데이터가 아니라 가정이고, 이 폭 자체가 가정 차이의 크기다. 그리고 <strong>어느 쪽을 믿든 예측 의석은 51~52석</strong>이다 — Silver Bulletin의 FLIPR Deluxe가 이번 주 <strong>사이클 최고 59%</strong>를 찍었는데, 그 모델의 예측 의석이 <strong>정확히 51 D – 49 R</strong>이다. <strong>59%는 “여유 있는 우세”가 아니라 여유 0의 최소 과반에 대한 확률이다.</strong> 이것이 이번 주의 규정적 사실이다.</p>
<p><strong>마지막으로 이 사이트의 등급가중 +2.125석이 여전히 +4에 크게 미달한다는 점을 어떻게 읽어야 하는지 반복해 둔다.</strong> 이 산수는 토스업 여섯 곳을 독립 시행으로 취급해 반씩 나눠 갖게 한다. 실제 선거에서 토스업들은 <strong>같은 바람에 함께 흔들린다.</strong> 전국 환경이 LV 기준 D+8.2라면 그 상관은 한 방향으로 작동한다. <strong>그래서 이 산수는 환경이 좋을 때 과소, 나쁠 때 과대 추정하고, 지금은 과소 쪽이다.</strong> 그것을 알고 쓰는 것이 이 표의 용법이며, 다른 세 수치와 나란히 놓되 같은 잣대로 비교하지 않는다.</p>
</section>
<section id="연령-역전-이번-주-가장-저평가된-실측" class="level2">
<h2 class="anchored" data-anchor-id="연령-역전-이번-주-가장-저평가된-실측">연령 역전 — 이번 주 가장 저평가된 실측</h2>
<p><strong>이번 주에 두 개의 반대 방향 실측이 같이 나왔는데, 하나만 널리 인용됐다.</strong></p>
<p>널리 인용된 쪽은 전국 단위다. <strong>투표가능층이 등록유권자보다 더 민주당 쪽이라는 것</strong>이 세 가지 독립적인 방법으로 확인됐다 — Silver의 LV 보정 +0.7, Marquette의 자체 스크린 +5p, Economist/YouGov의 LV 웨이브 D+12. 중간선거에서 LV 스크린은 통상 공화당 쪽으로 기울었으므로 <strong>역사 패턴의 역전</strong>이고, 기제도 실측됐다(“반드시 투표” 민주 77 / 공화 69).</p>
<p><strong>인용되지 않은 쪽은 주 단위다. 그리고 방향이 정반대다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>조사</th>
<th>연령 교차표</th>
<th>전체 토플라인</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>알래스카</td>
<td>AARP (양당 공동, 9/8~11)</td>
<td><strong>50세 이상 설리번 49–42</strong></td>
<td>펠톨라 46–41 (RCV 후 53–47)</td>
</tr>
<tr class="even">
<td>조지아</td>
<td>Quantus (공화계, 9/14~16)</td>
<td><strong>65세 이상 콜린스 +14</strong></td>
<td>오소프 48.2–44.4</td>
</tr>
<tr class="odd">
<td>텍사스</td>
<td>Emerson/Nexstar (비당파, 9/12~14)</td>
<td><strong>50세 이상 팩스턴 +11</strong></td>
<td>탈라리코 47–46</td>
</tr>
</tbody>
</table>
<p><strong>세 주, 세 조사기관, 서로 다른 성향, 같은 방향이다.</strong> 그리고 이 셋은 전부 이 사이트의 <strong>핵심 탈환 경로에 있는 주</strong>다 — 알래스카는 핵심 4곳 중 하나, 텍사스는 확장 보험, 조지아는 사수 라인이다.</p>
<p><strong>왜 이것이 중요한가.</strong> 전국 LV 역전은 “투표할 사람들이 민주 쪽”이라고 말한다. 주 단위 연령 역전은 “<strong>가장 확실하게 투표하는 연령층</strong>이 공화 쪽”이라고 말한다. <strong>두 문장이 동시에 참일 수 있다</strong> — 전국 LV 스크린은 열의(enthusiasm)를 잡고, 연령 교차표는 습관(habit)을 잡는다. 젊은 층의 열의가 올라가고 고령층이 공화 쪽으로 더 기울면 전국 LV는 민주 쪽으로, 고령층 비중이 높은 주의 교차표는 공화 쪽으로 동시에 갈 수 있다.</p>
<p><strong>문제는 그 둘이 51석 전망에 온전히 반영될 수 없다는 것이다.</strong> 알래스카의 AARP 조사는 그 긴장을 한 조사 안에 담고 있다 — <strong>전체 표본에서는 RCV 후 펠톨라 53–47이고, 50세 이상에서는 설리번 49–42</strong>다. 그리고 현지 보도는 알래스카 고령층의 투표 의향이 전체보다 높다고 강조한다. <strong>“측정된 유권자층에서는 이기고, 투표 확실성이 가장 높은 층에서는 진다” — 이것이 토스업의 정의다.</strong></p>
<p><strong>이 사이트는 어느 쪽이 맞는지 판정하지 않는다. 대신 기록해 둔다</strong> — 이번 주에 민주 방향 증거를 세는 사람은 전국 LV 역전을 셋으로 세고 주 단위 연령 역전을 세지 않았고, 그 반대도 마찬가지였다. <strong>둘을 같이 세는 것이 정직한 계산이다.</strong> 그리고 판별 데이터가 언제 오는지도 분명하다 — <strong>사전투표가 시작되면 연령별 실제 투표자 구성이 매일 공개된다.</strong> 텍사스 10/19, 애리조나 10/7이 가장 이르다.</p>
</section>
<section id="공화당의-현시선호-세-번째-주-연속" class="level2">
<h2 class="anchored" data-anchor-id="공화당의-현시선호-세-번째-주-연속">공화당의 현시선호 — 세 번째 주 연속</h2>
<p><strong>이 사이트가 3주 연속 같은 항목을 적는 이유는 이번 주에 그 규모가 또 커졌기 때문이다.</strong></p>
<p><strong>첫째, 오하이오다.</strong> 트럼프·머스크·코크·상원 지도부 계열 팝업 슈퍼PAC들이 <strong>한 주에 1,400만 달러</strong>를 집행해 누적 광고비가 <strong>2억 9,800만 달러 — 사이클 상원 최대</strong>가 됐다. 로이터는 촉발 요인을 보도에 명시했다: <strong>“허스티드가 3~5%p 열세.”</strong> 공화 보유 의석(특별선거)에 사이클 최대 물량이 들어간다는 것 자체가 판세 진술이다.</p>
<p><strong>둘째, 텍사스다.</strong> SLF가 텍사스 계열 PAC을 출범시켰고 보도 금액이 3,200만에서 5,400만 달러 사이다. <strong>트럼프가 14%p로 이긴 주이고, 7월에는 전국 공화당이 방어하지 않던 주다.</strong></p>
<p><strong>셋째, 아이오와다.</strong> 밴스 부통령과 배라소 원내총무가 <strong>트럼프가 13%p로 이긴 주에 연이틀</strong> 들어왔다. 그리고 두 행사의 내용이 더 말한다 — <strong>둘 다 투렉을 공격하지 않고 자기 이슈를 방어했다</strong>(관세·농민, 팁·초과근무 감세). <strong>내부 판세가 Emerson의 힌슨 +5와 같다면 부통령과 원내총무의 시간을 여기에 쓰지 않는다.</strong></p>
<p><strong>넷째, 미시간이다.</strong> 머스크의 America PAC이 새로 진입해 기존 600만 달러 반(反)엘사예드 집행에 얹혔다 — <strong>머스크·트럼프 계열·상원 지도부 자금이 동시에 들어온 유일한 민주 사수 주</strong>다.</p>
<p><strong>다섯째, 하원이다.</strong> 트럼프계 PAC 3개의 2주 합산 예약이 <strong>1억 3,650만 달러 이상</strong>인데, 확인된 표적 중 <strong>MI-04·NV-03·KY-06은 어느 공표 경합 층에도 없거나 Likely R</strong>이다. <strong>공화 내부의 방어 지도가 공개 등급보다 넓다는 독립 증거 3건</strong>이고, 이 사이트가 매주 추적하는 “등급이 못 따라잡은 현실”의 가장 직접적인 자료다.</p>
<p><strong>반대 방향도 적는다.</strong> 이 물량에는 세 가지 할인 요인이 있다. ① <strong>9/1 등록은 기부자 공개를 10월 말로 미룬다</strong> — 사전·우편투표 기간 내내 자금 출처가 익명이다. ② <strong>최저단가 창(9/4 개장)을 사흘 놓친 시장가 매입</strong>이라 헤드라인 금액이 실제 노출량을 과대표시한다(AP). ③ 그리고 <strong>1억 3,650만 달러는 실재하는 종반 물량</strong>이다 — 이 사이트가 “방어의 자백”으로 읽는 것과 별개로, 그 돈은 실제로 광고가 되어 나간다. 오하이오가 그 시험대다: <strong>누적 2억 9,800만 달러의 포화 환경에서 브라운의 4연속 우위가 유지되는지가, 이 사이트가 추적할 수 있는 유일한 판별 지표다.</strong></p>
</section>
<section id="두-개의-숫자가-어긋난-곳-기록해-둘-불일치" class="level2">
<h2 class="anchored" data-anchor-id="두-개의-숫자가-어긋난-곳-기록해-둘-불일치">두 개의 숫자가 어긋난 곳 — 기록해 둘 불일치</h2>
<p><strong>첫째, 예측시장 수치다.</strong> 원천 상원 브리핑은 이번 주 Kalshi 상원 다수를 <strong>53%</strong>, Polymarket을 약 54%로 기록했다. 그런데 <strong>이 사이트가 9/20 Kalshi 공개 API에서 직접 받은 값은 59.0¢</strong>다. 5~6%p 차이이고, 이 사이트는 <strong>직접 취득한 원가격만 싣는다</strong>는 규칙에 따라 59¢를 쓴다. 차이의 원인은 시점일 가능성이 높다 — 원천의 기록 시점이 9/18~19이고 이 사이트의 취득은 9/20이다. <strong>한 주에 10센트가 움직인 계약에서는 이틀이 5%p를 만들 수 있다.</strong> 지난주에도 같은 종류의 불일치를 기록했는데(원천 51% 대 직접 취득 48¢), 그때와 달리 이번에는 방향이 반대다 — <strong>원천이 더 낮게 적었다.</strong></p>
<p><strong>둘째, 사바토의 상원 등급이다.</strong> 원천은 사바토가 <strong>9/3에 상원 3건(AK Lean R→Tilt R · OH Tilt R→Toss-up · NH Tilt D→Toss-up)</strong>을 옮겼다고 기록한다. 그런데 <strong>이 사이트가 받는 270towin 재게시 피드의 사바토 스탬프는 9/20 실행에서도 여전히 8/26자이고, 세 주의 값도 각각 Toss-up · Toss-up · Lean D로 그대로</strong>다. 둘 중 하나는 틀렸다. 한 가지 방증을 적어 둔다 — <strong>원천이 서술한 “Tilt D”·“Tilt R”은 사바토가 쓰지 않는 등급이다</strong>(Tilt는 Inside Elections·RaceToTheWH·Kalshi 계열이 쓰고, Cook·Sabato는 Lean까지만 쓴다). 그래서 이 사이트는 원천의 해당 서술이 IE 이동과 혼동됐을 가능성을 두고, <strong>피드 값을 따라 사바토 NH를 Lean D로 계산한다.</strong> 산수는 +2.125 대 +2.0으로 갈리고, 결론은 바뀌지 않는다.</p>
<p><strong>셋째, 반대 방향의 불일치도 있다.</strong> 원천은 <strong>IE의 이번 주 상원 이동을 0건</strong>으로 기록하고 IE의 메인 등급을 “13개월 미갱신 Tilt R”로 계속 저가중 처리한다. 그런데 <strong>이 사이트의 피드는 IE 스탬프가 9/3에서 9/17로 바뀌면서 메인이 Tilt R → Toss-up으로 올라간 것을 보여준다.</strong> 같은 날 IE가 하원 9건·주지사 2건을 공표한 것은 원천도 기록하고 있으므로, <strong>상원도 같이 갱신됐는데 원천이 놓쳤을 가능성이 높다.</strong> 이 사이트는 피드를 따른다.</p>
<p><strong>넷째, 주지사 등급 미러 지연이 해소됐다.</strong> 원천 주정부 브리핑은 “270toWin의 Cook 미러가 9/17 알래스카 이동을 미반영(주말 확인 시점에도 9/10 표기)”이라고 기록하며 미러를 교차검증용으로 강등했다. 그런데 <strong>이 사이트가 9/21 실행에서 받은 피드는 Cook 9/18자로 알래스카 Toss-up을 반영하고 있다.</strong> 미러가 하루 이틀 늦었을 뿐이고, 지금은 정합한다.</p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (9/14~9/20).</strong> 주간 DB는 <strong>21건 추가</strong>(전주 17건)로 4주 연속 증가해 사이클 최고다(8→15→17→21). <strong>그런데 이번 주의 특징은 집중이 아니라 종결이다</strong> — 2주간 이월돼 온 두 개의 열린 질문이 각각 닫혔고, 닫힌 방식이 둘 다 “아니오”였다.</p>
<p><strong>첫째, 호르무즈 파병 질문이 ’아니오’로 닫혔다.</strong> 9/17 예정이던 NSC 상임위가 서면회의로 전환됐고, <strong>이재명 대통령이 9/18 기자회견에서 전투 관여 형태의 파병을 공식 배제</strong>했다 — “전쟁에 관여하거나 개입하는 파병은 없을 것.” 대안으로 제시된 것은 <strong>소말리아 해역에 이미 나가 있는 청해부대의 작전 범위 확대</strong>(한국 유조선·상선 보호)인데, 이 설계의 핵심은 법률이다 — <strong>신규 파병에 요구되는 헌법 60조의 국회 동의 요건이 발생하지 않는다.</strong> 같은 날 워싱턴에서 조현–루비오 회담(2월 이후 첫 양자)이 열려 ’전투 기여 제외 + 자유 항행 회복 기여 + 투자 이행’의 교환이 미측에 전달됐다. <strong>트럼프의 8월 직접 요청에 대한 공개 거절이고, 이 사이트가 지난 3주간 “절차가 전진하고 제동이 여섯 겹으로 붙었다”고 적어 온 국면의 결말이다.</strong></p>
<p><strong>둘째, 3,500억 달러 패키지가 ’재협상’으로 재정의됐다.</strong> 1호 사업 발표가 9/18 MOU 무산을 포함해 2주 연속 연기된 끝에 <strong>대통령이 재협상 개시를 공식 확인</strong>했다 — 미해결 조항은 ’상업적 합리성’과 I-SPV 금융 구조이고 시한은 제시되지 않았다. 같은 날 루비오 국무장관은 “조속한 이행”을 공개 압박했다. 그리고 DB에 처음 등재된 서술이 하나 있다 — <strong>“트럼프가 중간선거 전 합의를 공개할 수 있게 하는 일정”</strong>이라는 표현이다. <strong>미국 행정부 최대 단일 외국인 투자 약속의 인용 가능성이 종반전에 흔들리고 있다는 뜻이고, 이 사이트가 이 사안을 상원 트래커와 나란히 놓는 이유가 여기 있다.</strong> 사용후핵연료 4,000톤 재처리 제안도 처음 등재됐다.</p>
<p><strong>셋째, 미 의회의 한국 발화는 이번 주도 0건이다.</strong> 상원 [K] 항목 7일 연속 부재이고, <strong>경합 레이스 후보의 한국 관련 발언도 0건</strong>이다 — 토스업 텍사스의 1호 사업(엔시날 LNG)에 대한 후보 언급은 3주째 없다. 미국 측 발화는 복귀했지만(루비오 “조속한 이행” · 브런슨 “조건에 기초” · MSMT 국무부 성명) <strong>전부 행정부·군 채널</strong>이다. 신규 관측 지점이 하나 생겼다 — <strong>SK하이닉스의 인텔 오하이오 공장 임차 검토</strong>로, 대형 한국 반도체 투자가 상원 경합주에 착지할 수 있는 첫 후보다(현재 후보 언급 0건). 사상 첫 비수도 개최인 부산 KIDD(9/16~18)는 전작권 전환 “가속” 협력을 명기한 공동발표문을 냈다(목표 연도는 미설정이고, FY26 NDAA 1268조의 법적 트립와이어가 병존한다).</p>
<p><strong>넷째, 한국계 하원 진용의 축소가 확정 기록됐다.</strong> CA-40이 Prop 50 병합으로 <strong>공화 대 공화 본선</strong>이 됐고, 미셸 스틸의 대사 부임과 김 바렛의 탈락이 겹쳐 <strong>2027년 한국계 하원 의원단은 전국 결과와 무관하게 120대에서 줄어든다.</strong> 이 사이트가 하원 트래커에서 따로 쫓는 몇 안 되는 [K] 항목이다.</p>
<p><strong>다음 주 검증 구간</strong>: 9/22 국회 비공개 보고 실제 개최 여부 · 9/23 한미 전략투자 MOU 서명식 성사 여부와 서명 사업 구성 · 유엔총회(9/22 개막) 계기 한미 정상 접촉 · 청해부대 확대의 법적 형식(국방부 고시 대 국회 보고) · SK하이닉스–인텔 오하이오 공식 확인/부인. (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>9/22(화) — 이번 사이클 최대 분산의 날.</strong> 네 개가 같은 날이다. ① <strong>트럼프–걸프 6개국 정상 회담</strong>(유엔총회 개막) — 트럼프 본인이 이란 “전면 격파냐 종전이냐” 결정의 입력값으로 지목했다. <strong>조기 종전은 선거 전 유일한 유가 반전 경로인데 10/14 CPI에는 늦고, 9/19 리야드 피격으로 확률이 좁아졌다.</strong> ② <strong>텍사스 Hearst/NBC–텔레문도 토론 D-데이</strong> — 팩스턴의 3주 무대응이 수락·거부·무대응 중 어떤 형태로 끝나는지. ③ <strong>한국의 3,500억 달러 패키지 국회 비공개 보고</strong> 실제 개최 여부. ④ 조지아 11Alive 주지사 토론(바텀스만 수락 — 두 번째 단독 무대가 되는지).</li>
<li><strong>9월 하순 — 인상 이후 첫 경합주 조사.</strong> 이번 주 조사 대부분은 9/8~16 실사로 <strong>FOMC 전후 경계</strong>에 걸쳐 있다. 인상과 휘발유 사이클 최고가($4.4759)가 완전히 반영된 첫 조사가 다음 진짜 데이터다. 직결 대상이 명확하다 — <strong>‘환경 의존 우위’ 주지사 3곳(WI·MI·NV)은 인상 후 조사가 나흘째 0건</strong>이다.</li>
<li><strong>뉴햄프셔 — 두 번째 독립 조사와 Kalshi 가격.</strong> 이 지도 최대의 미해결 문제(전망기관 4표 대 조사 1표)를 가를 데이터다. <strong>가격이 계속 내려가면 전망기관이 빨랐던 것이고, 83¢ 부근에서 버티면 등급 이동이 군집행동이었다는 뜻이다.</strong> InsiderAdvantage +8의 원자료(기간·표본)도 같이 확인 대상이다.</li>
<li><strong>메인 — 후속 조사 두 건.</strong> Quantus 콜린스 +0.7이 단일 하우스 이탈값인지 추세 전환의 시작인지. <strong>10/6 첫 토론까지 남은 조사 창이 판 위에서 가장 값비싼 데이터다.</strong></li>
<li><strong>9/24(목) — 켐프+튠 콜린스 모금 행사.</strong> 결집 효과의 지속 검증인데, <strong>판별 데이터가 될 9/16 이후 실사 비공화계 조지아 조사는 현재 예정된 것이 없다.</strong> 12/1 결선 시나리오의 확률 추적을 이번 주부터 시작한다.</li>
<li><strong>오하이오 — 다음 공개 조사.</strong> 누적 2억 9,800만 달러·주당 1,400만 달러의 포화 환경에서 브라운의 4연속 우위가 압축되는지. <strong>이 사이트가 추적할 수 있는 유일한 판별 지표다.</strong></li>
<li><strong>10/2(금) — 상원 H.Con.Res.89 이란 전쟁권한 상정 시한.</strong> 하원 부재로 <strong>선거 전 유일한 의회 일정</strong>이고, <strong>콜린스(ME)·설리번(AK)·허스티드(OH) 전원이 기록투표</strong>를 한다. 각 주 토론 직전 소재로 전환되는 경로다.</li>
<li><strong>10/4(일) — 알래스카 후보 등록 마감.</strong> 윌슨의 사퇴 요구가 실제 구도 변경(3R→2R)으로 이어지는지의 <strong>유일한 기한</strong>이다. 같은 주에 APOC 존슨 건 본안(10/8)과 연방 대배심 기소 판단이 놓여 있다.</li>
<li><strong>10/6~15 — 토론 밀집 블록.</strong> ME 상원 4회 · MI 주지사 10/6 · IA 상원 10/7(단일) · GA 상원/MI 상원 10/8 충돌 · GA APC 10/12(잭슨 불참 확정) · IA 주지사 10/14. <strong>아이오와의 10%p 격차와 메인의 방향 전환 여부가 여기서 갈린다.</strong></li>
<li><strong>10/14(수) — 9월 CPI, 선거 20일 전.</strong> 유권자 결정 전 <strong>마지막 물가 지표</strong>이고, 경유 신기록·휘발유 사이클 최고의 전가를 담을 첫 숫자다. 이어 10/15 9월 소매판매(8월 +1.2% 서프라이즈 검증)와 <strong>3분기 FEC 보고</strong>(신설 트럼프계 PAC의 첫 포괄 — 단 기부자 공개는 10월 말 지연), 10/19 텍사스 사전투표 개시가 온다.</li>
<li><strong>등급 감시 3건</strong> — <strong>Cook이 MI(3연속 D 우위)·NC(Harper +15)로 민주 방향 이동을 하는지</strong>(이번 주 유일한 이동이 반대 방향이었으므로 이것이 대칭성 시험이다) · <strong>Cook의 하원 첫 재가동 방향</strong>(TX-15·NC-11 편입이면 22석, NJ-07·TX-34 추종이면 20석) · <strong>사바토 상원 스탬프가 실제로 갱신되는지</strong>(위 불일치 ②의 해소).</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 09/14~09/20 — 일간 35/35건, <strong>5개 트랙 전부 결손 없음</strong>). 환경 지표 — Silver Bulletin·FiftyPlusOne·RealClearPolling·USPollingData·Morning Consult·Reuters/Ipsos·NYT/시에나·CBS News/YouGov·Economist/YouGov·Marquette Law School·Quinnipiac·하버드 CAPS/해리스. 경제 — FOMC(9/16 성명·점도표)·인구조사국(소매판매)·노동부(신규청구)·연준(산업생산)·컨퍼런스보드(LEI)·AAA·EIA·브라운대 연료 트래커. 상원 실측 — Quantus Insights(공화계)·Trafalgar Group(공화계)·Emerson College/Nexstar·EPIC-MRA·Harper Polling/Carolina Journal(공화계)·AARP/Fabrizio Ward–Impact Research(양당 공동)·Rasmussen Reports(공화계)·BGSU/YouGov(학술)·co/efficient·Cook/TelevisaUnivision(OnMessage–Hart 양당 공동)·Suffolk University. 주지사 실측 — BGSU/YouGov·Emerson College/Nexstar·Rasmussen Reports(공화계)·Suffolk·St.&nbsp;Pete Polls. 하원 — Cook Battleground District Project(New River–GS Strategy 양당 공동)·CBS/YouGov 모델·Hart Research/TelevisaUnivision·StimSight(스폰서 연계)·GQR(민주계). 상원·주지사 등급 — Cook(상원 <strong>9/15</strong>·주지사 <strong>9/18</strong>)·Sabato(상원 8/26·주지사 9/3)·Inside Elections(상원·주지사 <strong>9/17</strong>) 270towin 재게시분 자동 취득(9/21 실행 — 상원 35/35·주지사 35/36, 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). 하원 등급 — Cook <strong>9/11 보드</strong> 자동 취득(435개구 해독, 합계 435 검증 — 9일 연속 동결). 예측시장 — Kalshi 공개 API 원가격(9/20). 외부 모델 — Decision Desk HQ(모델 갱신 9/18)·Race to the WH(라이브 시계열 마지막 관측 9/20, 137점). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. <strong>다음 조사는 이 사이트 DB에 넣지 않고 서술로만 반영했다</strong> — 뉴햄프셔 InsiderAdvantage 파파스 +8(조사기간 미기재) · 텍사스 Telemundo/Mason-Dixon 탈라리코 +3(세부 미공표) · 텍사스 Cook/TelevisaUnivision 히스패닉 63–30(히스패닉 전용 조사라 전주 조사표에 부적합) · 조지아 Quantus 9/9~12(미배분 약 24%로 원천이 해석 불가 판정) · 애리조나 AARP 주지사(D+5와 D+8 이중 노출, 대조 전) · 텍사스 SoCal Strategies 주지사 R+8(공화계 단독·비당파 재현 대기). <strong>기록해 둘 불일치 4건</strong>: ① 원천 상원 브리핑은 이번 주 Kalshi 상원 다수를 53%로 적으나 이 사이트가 9/20 공개 API에서 직접 받은 값은 <strong>59.0¢</strong>다 — <strong>직접 취득한 원가격만 싣는다.</strong> ② 원천은 사바토의 9/3 상원 3건 이동(AK·OH·NH)을 기록하나 이 사이트의 270towin 재게시 피드는 9/20 실행에서도 사바토 스탬프가 <strong>8/26자</strong>이고 값도 불변이다 — 등급가중 산수가 <strong>+2.125 대 +2.0</strong>으로 갈리며, 이 사이트는 피드를 따른다(결론 불변). 참고로 원천이 쓴 “Tilt D/Tilt R”은 사바토가 사용하지 않는 등급이다. ③ 원천은 IE의 이번 주 상원 이동을 0건으로 적으나 이 사이트 피드는 IE 스탬프가 9/3→<strong>9/17</strong>로 바뀌며 <strong>메인이 Tilt R→Toss-up</strong>으로 올라간 것을 보여준다 — 13개월 넘게 낡은 값이던 플래그가 닫혔다. ④ 원천 주정부 브리핑은 270toWin의 Cook 미러가 9/17 알래스카 이동을 미반영했다고 기록했으나, 9/21 실행 피드는 <strong>Cook 9/18자로 AK Toss-up을 반영</strong>하고 있다 — 미러 지연은 해소됐다. <strong>주의회 확인(월 1회 항목) — 변동 없음</strong>: Sabato의 새 주의회 등급 라운드가 확인되지 않아 <code>state_legislatures.json</code>은 손대지 않았다(원천 주간의 주의회 서술은 제이콥슨 1/22 등급 계통이라 이 파일의 Sabato 계통과 원천이 다르다). 이번 주 자동 취득 로그에 조회 실패·정렬 불일치로 건너뛴 항목은 뉴햄프셔 주지사 시장(2026 만기 계약 부재) 1건뿐이다. <strong>이번 주 상원 조사는 대부분 9/8~9/16 실사로 9/16 FOMC 인상과 9/19 휘발유 사이클 최고가($4.4759)의 경계에 걸쳐 있다.</strong> 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>