<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="이번 주에 등급은 한 칸도 움직이지 않았다. Cook·사바토·Inside Elections 세 기관이 모두 상원 등급표를 동결했고, 그래서 이 사이트의 등급가중 산수는 3주 연속 +2.25석으로 소수점까지 같다. 움직인 것은 그 아래층이다. 공화당 성향 조사기관 두 곳이 네 개 주에서 민주 우위를 냈고, 4주째 비어 있던 메인의 구멍이 조사 네 건으로 한꺼번에 메워졌으며, 아이오와가 최약 고리에서 10%p 범위의 진짜 미결로 재개방됐다. 그리고 외부 모델 하나가 54.2%에서 63.9%로 뛰었다 — 2주 연속 좁혀졌다고 썼던 모델 간 격차가 한 주 만에 두 배 넘게 다시 벌어졌다. 한 가지를 반드시 붙여 적어야 한다. 이번 주 상원 조사는 전부 경유 $6·소비자심리 47.8·연준 인상 이전에 실사된 것이다.">

<title>25주차 · 09/07~09/13 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-68e6e372e1b701cc28bb74d6e3c58b49.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">25주차 · 09/07~09/13</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-지도-하나가-실제로-사라졌다" id="toc-하원-지도-하나가-실제로-사라졌다" class="nav-link" data-scroll-target="#하원-지도-하나가-실제로-사라졌다">하원 — 지도 하나가 실제로 사라졌다</a></li>
  <li><a href="#주지사-알래스카의-두-칸이-한-칸으로-좁혀졌다" id="toc-주지사-알래스카의-두-칸이-한-칸으로-좁혀졌다" class="nav-link" data-scroll-target="#주지사-알래스카의-두-칸이-한-칸으로-좁혀졌다">주지사 — 알래스카의 두 칸이 한 칸으로 좁혀졌다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-이번-주에는-들어갈-것-자체가-없었다" id="toc-상원-산수-이번-주에는-들어갈-것-자체가-없었다" class="nav-link" data-scroll-target="#상원-산수-이번-주에는-들어갈-것-자체가-없었다">상원 산수 — 이번 주에는 들어갈 것 자체가 없었다</a></li>
  <li><a href="#공화당의-현시선호-이번-주-가장-저평가된-증거" id="toc-공화당의-현시선호-이번-주-가장-저평가된-증거" class="nav-link" data-scroll-target="#공화당의-현시선호-이번-주-가장-저평가된-증거">공화당의 현시선호 — 이번 주 가장 저평가된 증거</a></li>
  <li><a href="#두-개의-숫자가-어긋난-곳-기록해-둘-불일치" id="toc-두-개의-숫자가-어긋난-곳-기록해-둘-불일치" class="nav-link" data-scroll-target="#두-개의-숫자가-어긋난-곳-기록해-둘-불일치">두 개의 숫자가 어긋난 곳 — 기록해 둘 불일치</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">25주차 · 09/07~09/13</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    이번 주에 등급은 한 칸도 움직이지 않았다. Cook·사바토·Inside Elections 세 기관이 모두 상원 등급표를 동결했고, 그래서 이 사이트의 등급가중 산수는 3주 연속 +2.25석으로 소수점까지 같다. 움직인 것은 그 아래층이다. 공화당 성향 조사기관 두 곳이 네 개 주에서 민주 우위를 냈고, 4주째 비어 있던 메인의 구멍이 조사 네 건으로 한꺼번에 메워졌으며, 아이오와가 최약 고리에서 10%p 범위의 진짜 미결로 재개방됐다. 그리고 외부 모델 하나가 54.2%에서 63.9%로 뛰었다 — 2주 연속 좁혀졌다고 썼던 모델 간 격차가 한 주 만에 두 배 넘게 다시 벌어졌다. 한 가지를 반드시 붙여 적어야 한다. 이번 주 상원 조사는 전부 경유 $6·소비자심리 47.8·연준 인상 이전에 실사된 것이다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 9월 13일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 9/7~9/13 일간 브리핑 35건(전국·상원·하원·주정부·Korea Watch 각 7/7 — <strong>5개 트랙 전부 결손 없음</strong>). 뉴스 기준: 미 동부시간 9/12(토) 저녁까지. 선거일(11/3)까지 51일. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>세 기관이 전부 멈췄다 — 상원 등급 이동 0건.</strong> Cook은 8/20, 사바토는 8/26, Inside Elections는 9/3 이후 상원 등급표를 한 칸도 바꾸지 않았다. 그래서 이 사이트의 등급가중 순 기대의석은 <strong>3주 연속 +2.25석</strong>이다. 지난주에는 “IE가 움직였는데 이 산수에 들어갈 자리가 없다”고 썼는데, 이번 주에는 <strong>들어갈 것 자체가 없다.</strong></li>
<li><strong>대신 공화당 성향 조사기관들이 움직였고, 방향이 자기 성향과 반대였다.</strong> 금요일 Rasmussen이 단일 기간(9/8~10) 세 개 주를 동시 공표해 <strong>아이오와 투렉 +5 · 메인 잭슨 +1 · 뉴햄프셔 파파스 +11</strong>을 냈고, 이틀 전 Trafalgar가 <strong>미시간 엘사예드 +1.5</strong>를 냈다. Rasmussen 3건은 같은 하우스·같은 기간이라 <strong>독립 관측 3건이 아니다</strong>(가중치는 1건보다 크고 3건보다 작다). 그럼에도 무게가 실리는 이유는 방향이다 — 하우스 이펙트는 보통 자기 성향에 <strong>반하는</strong> 쪽으로 틀리지 않는다.</li>
<li><strong>4주째 비어 있던 메인이 한 주에 네 건으로 메워졌고, 전부 잭슨 우위였다.</strong> CNN/SSRS +3 · YouGov +4 · Abacus LV +9 · Rasmussen +1 — 7/25 지명 이후 <strong>5연속</strong>, 8월 중순 경찰 기록 보도 이후로도 <strong>4연속</strong>이다. 지난주 “이번 가을 최대의 단일 정보 갱신”이라고 적었던 그 공백이 메워졌고, ‘플랫너 2.0’ 침몰 기제는 <strong>발화하지 않았다.</strong> 단 같은 Abacus 조사의 <strong>등록유권자 필터는 콜린스 +1</strong>이다 — 한 조사 안에 D+9와 R+1이 같이 있다.</li>
<li><strong>모델 하나가 크게 뛰었는데 시장은 1센트만 올랐다.</strong> Race to the WH가 <strong>54.2% → 63.9%</strong>로 9.7%p 올랐고(예상 의석 D 50.8 → 51.6), Decision Desk HQ는 49.0% → <strong>50.0%</strong>, Kalshi 상원 다수는 48¢ → <strong>49¢</strong>다. 2주 연속 좁혀졌다고 썼던 두 모델의 격차는 5.2%p에서 <strong>13.9%p로 한 주 만에 두 배 넘게 다시 벌어졌다.</strong> 평균 내지 말 것 — 좁혀졌다 벌어지는 이 폭 자체가 가정 차이의 크기다.</li>
<li><strong>이번 주 조사는 전부 ’그 전’에 실사됐다.</strong> 표에 실린 상원 조사의 최신 종료일은 <strong>9/10</strong>이고, 경유 사상 첫 $6(9/11)·미시간대 소비자심리 <strong>47.8</strong>(9/11)·9/16 연준 인상 확률 <strong>86~90%</strong>는 그 뒤에 왔다. <strong>인상 이후 첫 경합주 조사가 다음 진짜 데이터다.</strong></li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>트럼프 순지지도</td>
<td><strong>−19.5</strong>(Silver Bulletin) ~ <strong>−24.7</strong>(FiftyPlusOne 35.7/60.4)</td>
<td>9/11</td>
<td><strong>Silver Bulletin은 한 주 내내 −19.5로 완전히 고착됐다</strong>(9/7·9/8·9/9·9/11 네 차례 갱신에서 수치 불변). FiftyPlusOne만 −23.2(9/5) → −24.7(9/11)로 −1.5p 악화했고 USPollingData는 −20.0 → −20.6(9/11) → −20(9/12)이다. 밴드는 RCP −17.3에서 FPO −24.7까지 <strong>7.7%p</strong>. <strong>사우디 생산 붕괴·$6 경유·7% 모기지를 담은 한 주가 톱라인을 거의 못 움직였다</strong> — 지지율이 이미 −20 부근에 가격형성돼 있다는 뜻이다. 1기 동기(−11.6) 대비 <strong>약 8%p 열위</strong>는 그대로</td>
</tr>
<tr class="even">
<td>지지율의 ‘강도’ — 이번 주 최대 발견</td>
<td>공화 지지층 <strong>“강한 지지” 52% → 41%</strong>(NBC/Decision Desk) · 공화 내 지지 <strong>72%</strong>(FT/Focaldata, 시리즈 최저)</td>
<td>8/20~9/1 · 8/28~9/2</td>
<td>설계가 다른 두 기관이 같은 방향을 가리켰다. <strong>이탈이 아니라 열의 감소</strong>다. 총계 지지율에도 제너릭 밸럿에도 잡히지 않고 <strong>투표율·소액 후원·자원봉사에 잡히는</strong> 유형이라, 이번 주 환경 재료 중 유일하게 “아직 측정되지 않은 채 축적되는” 항목이다</td>
</tr>
<tr class="odd">
<td>일반투표(제너릭)</td>
<td><strong>D+6.4~6.6</strong> (RCP 48.3/41.9 · USPD 48.1/41.5 · FPO 49.9/43.4 · Silver) · Silver <strong>LV 보정 D+7.6</strong></td>
<td>9/11~9/12</td>
<td><strong>독립적인 네 평균이 0.2%p 폭 안에 모였다 — 이번 사이클 최대의 일치.</strong> 주말 이동분(+0.1~+0.7)은 신규 조사가 아니라 평균 내부 가중치 감쇠에서 나온 것이라 금요일 뉴스 반응으로 읽으면 안 된다. 더 중요한 것은 <strong>모집단 균열이 해소 방향으로 정리됐다</strong>는 점이다 — LV 계열 4건(Focaldata D+7 · UMass D+8 · Emerson D+7.7 · Quantus D+6.9)이 연속으로 평균 위에 착지했고 Silver 자체 LV 보정이 D+7.6으로 확인됐다. <strong>의석을 예측하는 지표 기준으로 환경은 D+6보다 D+7.6에 가깝다</strong></td>
</tr>
<tr class="even">
<td>LV 모형 스프레드 — 미해소</td>
<td>Quinnipiac <strong>D+11</strong>(RV) vs 하버드 CAPS/해리스 <strong>R+2</strong>(LV, 미갱신 이월)</td>
<td>9/3~9/6</td>
<td><strong>13%p 폭</strong>이다. 지난주 이 자리에 “이번 사이클 최대 미해결 쟁점”이라고 적었는데 이번 주에 폭이 더 벌어졌다. 같은 균열이 주 단위에서도 재현됐다 — 메인 Abacus가 <strong>같은 조사에서 LV 잭슨 +9 / RV 콜린스 +1</strong>을 냈고, 텍사스 AARP는 50세 이상(올해 텍사스 공화 예비 투표자의 78%)에서 <strong>팩스턴 +13</strong>을 냈다</td>
</tr>
<tr class="odd">
<td>가격 — 이번 주 최대 악재</td>
<td>브렌트 <strong>$100 최초 돌파</strong>(9/9) → 장중 $107 → <strong>$104.42</strong>(9/11) · 경유 <strong>$6.05~6.06 사상 첫 $6</strong>(9/11, +63% y/y) · 휘발유 <strong>$4.29~4.30</strong> · 모기지 <strong>7.07%</strong></td>
<td>9/9~9/12</td>
<td>공급 충격의 주체가 이란의 봉쇄에서 <strong>미국의 유조선 격침 · 사우디 생산 붕괴</strong>(8월 일 623.8만 배럴, 1990년 이후 최저) <strong>· 동–서 송유관 폐쇄</strong>(9/12, 호르무즈를 우회하는 유일 경로)로 이동했다. 10년물은 <strong>4.979%</strong>로 5%에 2bp까지 갔다. <strong>전쟁 프리미엄이 소비자 고시금리로 나타난 사이클 첫 사례</strong> — $105 유가는 세입자에게 추상이지만 7% 모기지는 아니다</td>
</tr>
<tr class="even">
<td>물가 — 반증이 여기 있다</td>
<td>8월 CPI <strong>헤드라인 3.4% / 근원 2.4%</strong>(7월 2.5%에서 둔화) · 8월 PPI <strong>전년 +5.4%</strong>(경유 전월비 <strong>+24.1%</strong>)</td>
<td>9/10~9/11</td>
<td>근원이 내려간 것은 <strong>인플레가 배럴로 수입되는 에너지 충격</strong>이라는 최명확 증거이고, 그래서 되돌릴 수 있는 종류다. 이것이 이번 주 유일한 반전 경로다. 반대편에는 PPI가 있다 — <strong>연료 소매마진 −11.3%</strong>는 8월에 주유소가 흡수한 몫이 있었다는 뜻이고, <strong>9월 전가는 더 완전할 것</strong>이다. 그 첫 지표가 <strong>10/14 9월 CPI, 선거 19일 전</strong>이다</td>
</tr>
<tr class="odd">
<td>심리</td>
<td>미시간대 9월 예비 <strong>47.8</strong> (예상 ~51.0, 전월 51.7)</td>
<td>9/11</td>
<td><strong>48년 시계열 2위 최저이자 1퍼센타일 미만</strong>이고, 과거 여섯 차례 침체 시작점을 <strong>전부 밑돈다</strong>. 기대인플레 1년치는 4.0% → 4.6%. 결정적인 것은 <strong>양당 동반 하락</strong>이다 — 당파적 착시가 아니라는 뜻이다. 확정치는 9/25</td>
</tr>
<tr class="even">
<td>금리</td>
<td>9/16 FOMC 25bp 인상 확률 <strong>50.6%(9/6) → 69%(9/10) → 85.6~90%(9/11 CPI 후)</strong></td>
<td>9/11 (CME)</td>
<td>블랙아웃(9/5~17) 중에 확률만 35%p 올랐다. <strong>CPI가 마지막 입력이었고, 인상이 기본 시나리오가 됐다.</strong> 선거 7주 전에 트럼프가 임명한 워시 의장의 연준이 소비자심리 1퍼센타일 국면에서 금리를 올리는 구도다</td>
</tr>
<tr class="odd">
<td>제도전 — 두 건 다 민주 방향</td>
<td><strong>미주리 재획정 종결</strong>(9/10, 2022년 지도 확정) · <strong>우편투표 금지명령 항소심 유지</strong>(9/10)</td>
<td>9/10</td>
<td>지난주 “양건 모두 연방대법원 재상륙 대기”라고 적은 두 건이 이번 주에 정리됐다. 미주리는 <strong>연방대법원이 클라크 판사의 TRO를 정지</strong>시키면서 주 대법원 7-0 판결이 단독 유효 명령으로 남았고, USPS 규칙은 <strong>제1순회항소법원이 정지 신청을 기각</strong>해 11/3까지 차단이 유지된다. 다만 26A305는 <strong>잭슨 대법관 앞에서 여전히 미결</strong>이고, 그 사이 9/13 기준 최소 5개 주가 발송을 시작했다</td>
</tr>
<tr class="even">
<td>정당의 현시선호</td>
<td>댈러스 전당대회(9/9~10) — 상원 연사 4인의 <strong>이란·관세 언급 0회</strong> · 접전 3인(S.콜린스·설리번·서누누) <strong>불참</strong> · 경합 후보 <strong>절반 미만 참석</strong></td>
<td>9/9~9/10</td>
<td>사상 첫 중간선거 전당대회의 산출물은 자해에 가까웠다 — 1인당 <strong>$5,000 ‘트럼프 배당’</strong>(비용 약 1.25조 달러)을 밴스가 몇 시간 만에 수정했고, <strong>“cheat like hell” 투표 선서</strong>가 금요일 보도를 지배했으며, 트럼프 본인이 <strong>휘발유 값은 선거 전에 안 내려간다</strong>고, 밴스는 <strong>이란 전쟁이 유권자를 이탈시켰다</strong>고 말했다. <strong>어떤 여론조사보다 나은 현시선호다</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p><strong>이번 주 상원 등급 이동은 0건이다</strong> — Cook(8/20)·사바토(8/26)·Inside Elections(9/3) 셋 다 멈췄다. 그래서 이 표에서 읽을 것은 등급 열이 아니라 나머지 두 열이다. 첫째, <strong>공화당 성향 하우스 두 곳이 네 개 주에서 민주 우위를 냈다</strong>(Rasmussen IA·ME·NH, Trafalgar MI) — 단 Rasmussen 3건은 같은 기간·같은 하우스라 독립 관측 3건이 아니다. 둘째, <strong>시장이 이번 주 조사를 따라갔다</strong> — 새 조사가 민주 쪽으로 나온 세 주에서 값이 올랐고(TX +3¢ · IA +2¢ · NH +2¢), 신규 데이터가 없거나 반증이 섞인 주에서 빠졌다(MI·ME·OH 각 −2¢ · AK −1¢ · GA −0.8¢). 상원 다수 계약은 48¢ → <strong>49¢</strong>로 1센트 올랐다. <strong>메인은 예외로 기록해 둔다</strong> — 새 조사 네 건이 전부 잭슨 우위였는데 가격은 2센트 빠졌다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 8/20 / Sabato 8/26 / IE 9/3)</th>
<th>시장 (Kalshi 9/13)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Lean D / Likely D / Tilt D</td>
<td>92.5¢ (▼0.8)</td>
<td><strong>창 내 신규 조사 없음 — 그리고 그 부재가 이번 주 조지아의 스토리다.</strong> AJC(9/8)가 “오소프가 이기고 있어서 조지아가 전국적 주목을 잃는다”는 역설을 제기했고, <strong>오소프가 자금을 타 주로 돌려야 하는 것 아니냐</strong>는 질문까지 나왔다 — 조지아가 격전지가 아니라 <strong>자금 공급처</strong>로 논의된 첫 사례. 콜린스는 전당대회 상원 연사 4인 중 유일하게 <strong>트럼프를 0회 호명</strong>했다. 현금 20:1(4,200만 대 210만) (<strong>안정</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td>62¢ (▼2)</td>
<td><strong>‘로저스 우위’ 서사가 사망했다.</strong> 공화계 Trafalgar +1.5(9/7~9) · CNN/SSRS +3 · MSU +5로 <strong>3연속 민주 우위</strong>, 최근 6건 평균 약 엘사예드 +3. 반대편에 Glengariff/WDIV 로저스 +1.4가 있고, <strong>무당층 부호가 정면 충돌한다</strong> — CNN 엘사예드 +16 대 Glengariff 로저스 +14. 30%p 폭의 이 불일치가 현 지도 최대의 측정 쟁점이다. 9·11 25주기 공방은 양방향으로 오갔다 (<strong>개선·시장 −2¢</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Lean D / Lean D / <strong>Toss-up (9/3)</strong></td>
<td><strong>85¢ (▲2)</strong></td>
<td><strong>9/8 예비선거가 무상처로 끝났다</strong> — 파파스 62.5–35.4, 서누누 69.1–25.6. 예비 후 첫 조사 Rasmussen <strong>파파스 +11</strong>의 핵심은 표면이 아니라 내부다: 트럼프 지지로 69%를 얻은 나흘 뒤 <strong>서누누의 공화 지지층 결집률이 64%</strong>로 찍혔다. 이탈값 취급이 맞다 — 직전 UNH(8/26)는 <strong>서누누 +2</strong>였다. <strong>지난주 강등에도 안 움직이던 시장이 이번 주 2센트 올랐다.</strong> 여전히 모든 Bull 경로의 구속 조건 (<strong>대진 확정·주의 신호</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D / Tilt D</td>
<td>92¢ (▲0.5)</td>
<td><strong>같은 날 두 학술 조사가 같은 구조를 확인했다</strong> — Elon 쿠퍼 49–38(<strong>+11</strong>) · East Carolina 46–39(<strong>+7</strong>, 강제선택 52–44). 공통 기제는 <strong>왯틀리가 51일 남기고 약 3분의 1에게 미정의 상태</strong>라는 것이고, 인지도는 광고 증가에도 53%→47%로 <strong>오히려 내려갔다</strong>. Elon의 NC 트럼프 지지율 <strong>31/54는 자사 취임 후 최저</strong>. 9/4부터 이미 투표 중이고 토론은 아직 미합의다 (<strong>최강 탈환지 재확인</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss Up / Toss Up / Tilt R(낡음)</td>
<td>67¢ (▼2)</td>
<td><strong>지도 최대의 구멍이 네 건으로 메워졌고 전부 같은 방향이었다</strong> — CNN/SSRS +3 · YouGov +4 · Abacus LV +9 · Rasmussen +1. 지명 후 5연속, 스캔들 후 4연속. 반증도 정밀하다: <strong>Abacus의 RV 필터는 콜린스 +1</strong>이고, CNN 기준 잭슨 지지자의 <strong>71%가 “콜린스 반대” 동기</strong>다(콜린스 지지자는 74%가 “찬성”) — 스캔들에 강하되 확장이 어려운 연합. 지출은 콜린스 약 8,000만 대 잭슨 약 4,500만. 토론 4회는 <strong>전부 사전투표 개시 이후</strong> (<strong>개선·시장 −2¢</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss Up / Toss Up / Tilt R</td>
<td>64¢ (▼1)</td>
<td><strong>2주 연속 신규 조사·캠페인 뉴스 0건 — 핵심 4곳 중 데이터가 가장 적다.</strong> 뉴스의 부재는 위험의 부재가 아니다. 구조는 그대로다: 펠톨라(민주 단독) 대 공화 3인, RCV에서 민주 1순위는 자동 결집·공화 1순위는 분산. 로이터가 예비 득표를 재조명했다 — <strong>펠톨라 8.2만 대 현직 설리번 6.9만</strong>. 동명이인 출마의 유권자 혼란 공모 여부에 대한 <strong>연방 대배심 수사가 계속 중</strong>이고, 기소 판단은 <strong>방향을 예측할 수 없는 양방향 꼬리</strong>다 (<strong>무데이터</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss Up / Toss Up / Toss-up</td>
<td>52¢ (▼2)</td>
<td><strong>InsiderAdvantage 브라운 47–42(+5)</strong> — Fox +8(2회)·Abacus +6에 이어 독립기관의 중간 한 자릿수 민주 우위 세 번째다. 그런데 <strong>Pollsmax 평균은 여전히 허스티드 +1.1</strong>(모델 추정치)이라 <strong>개별 조사와 평균의 괴리가 감시 9주 중 최대</strong>다. 이건 경선에 대한 진술이 아니라 <strong>평균 구성에 대한 진술</strong>이다. 허스티드는 전당대회에서 브라운을 “과거의 유물”로 — 기록이 아니라 연식을 — 공격했다. 자금은 SLF 7,900만(공화 단일 주 최대) 대 SMP 2,400만(민주 단일 주 최대) (<strong>개선·시장 −2¢</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Toss Up / Toss Up / Lean R</td>
<td><strong>51¢ (▲3)</strong></td>
<td><strong>이번 주 지도에서 정보량이 가장 큰 것은 조사가 아니라 자금이다</strong> — MAGA Inc.의 중간선거 본선 첫 대규모 투입 <strong>1,000만 달러가 트럼프가 14%p로 이긴 주의 ’방어’로 갔다</strong>(주간 발표 합계 약 2,740만). 툰 원내대표는 전당대회 기간 댈러스에서 <strong>팩스턴 모금 행사를 주재</strong>했다 — 예비에서 코닌을 밀었던 지도부의 항복이다. 조사는 누적 우위(AARP +4 · InsiderAdvantage +1 · Univision +5, 최근 13건 중 11건 탈라리코 우위·동률)인데 <strong>AARP 연령 교차표가 그것을 할인할 최선의 이유</strong>다(50세 이상 팩스턴 +13). 팩스턴의 토론 회피는 9/9 시한 도과로 이어졌다 (<strong>시장 +3¢</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Toss Up / Lean R / Tilt R</td>
<td>38¢ (▲2)</td>
<td><strong>지난주의 “최약 고리” 판정이 금요일에 뒤집혔다</strong> — Rasmussen <strong>투렉 +5</strong>(“트럼프가 13포인트로 이긴 주에서 놀라운 일” — 기관 자체 해설)와 방법론적으로 독립인 YouGov <strong>투렉 +1(RV)~+4(엄격 LV)</strong>가 Emerson 힌슨 +5(8/31~9/1)와 정면으로 맞선다. <strong>9일 사이 양질 조사 3건이 10%p 범위에 흩어져 있다</strong> — 정직한 해석은 ’민주 우위’가 아니라 <strong>기관 간 실질 불일치가 있는 경합</strong>이다. 설명 변수는 YouGov의 <strong>IA 트럼프 41/57(순 −16)</strong> — 2024년 +13에서 29%p 이동. 분할투표는 계속 잡힌다(상원 동률 대 주지사 샌드 +11) (<strong>재개방</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 이 사이트 조사 DB에 새로 들어간 본선 조사는 <strong>열두 건</strong>이다 — 메인 3건(CNN/SSRS · Abacus · Rasmussen), 미시간 3건(CNN/SSRS · Glengariff/WDIV · Trafalgar), 아이오와 2건(YouGov · Rasmussen), 노스캐롤라이나 2건(Elon · East Carolina), 뉴햄프셔 1건(Rasmussen), 텍사스 1건(AARP/Fabrizio Ward–Impact). 표본·실사기간이 확인되지 않은 것들은 넣지 않았다(아래 as-of 참조).</p>
<p><strong>이 주의 사건은 “누가 무슨 결과를 냈는가”가 아니라 “누가 그걸 냈는가”다.</strong> 금요일에 Rasmussen이 단일 조사기간(9/8~10) 세 개 주를 동시 공표했고, 결과는 아이오와 투렉 +5 · 메인 잭슨 +1 · 뉴햄프셔 파파스 +11이었다. 이틀 전에는 Trafalgar가 미시간에서 엘사예드 +1.5를 냈다. 둘 다 공화당 성향으로 분류되는 하우스다. <strong>이 표에서 가장 하중이 큰 사실은 방향이지 크기가 아니다</strong> — 하우스 이펙트는 보통 자기 성향에 반하는 쪽으로 틀리지 않기 때문이다.</p>
<p><strong>그런데 세 건을 세 건으로 세면 안 된다.</strong> Rasmussen의 세 조사는 같은 기간·같은 방법·같은 하우스다. 하나의 기관이 하나의 스크린으로 세 주를 잰 것이므로 <strong>독립 관측 3건이 아니고</strong>, 적정 가중치는 “1건보다는 크고 3건보다는 작다”. 이번 주 민주 방향 이동의 외견상 폭에는 <strong>“누가 공표했는가”의 산물이 섞여 있다.</strong> 이 주에서 진정으로 독립적인 증거선은 두 개뿐이다 — <strong>YouGov 아이오와</strong>(9/3~8, RV 2,169)와 <strong>경합주별 트럼프 지지율의 시계열 신저점</strong>(아이오와 −16 · 노스캐롤라이나 31/54 · 메인 31/67).</p>
<p><strong>메인은 이번 가을 최대의 정보 갱신이었고, 결과는 민주 쪽이었다.</strong> 지난주 이 자리에서 “어느 Bull 경로도 메인을 필요로 하는데 그 주의 참값을 이 사이트는 모른다”고 썼다. 이번 주에 네 건이 한꺼번에 나왔고 전부 잭슨 우위였다. 7/25 지명 이후 <strong>5연속</strong>, 8월 경찰 기록 보도 이후로도 <strong>4연속</strong>이다 — <strong>‘플랫너 2.0’ 침몰 기제는 발화하지 않았다.</strong> 그런데 정밀하게 읽으면 승부는 아직 열려 있다. Abacus는 같은 조사에서 <strong>적극투표층 잭슨 +9 / 등록유권자 콜린스 +1</strong>을 냈다. 어느 투표율 모형이 맞는지가 곧 이 선거다. 그리고 잭슨 연합의 <strong>71%는 “콜린스 반대”</strong> 동기다(콜린스 지지자는 74%가 “콜린스 찬성”). <strong>스캔들에는 강하고 확장에는 약한 연합</strong>이라는 뜻이다. 한 가지 역사적 반증도 적어 둔다 — 콜린스는 2020년에 여론조사에서 전패하고 이겼다.</p>
<p><strong>아이오와는 지난주 판정을 뒤집었지만 ’민주 우위’로 뒤집힌 것은 아니다.</strong> 9일 사이에 나온 양질 조사 셋이 10%p 범위에 흩어져 있다 — Emerson 힌슨 +5(8/31~9/1) · YouGov 투렉 +1<sub>+4(9/3</sub>8) · Rasmussen 투렉 +5(9/8~10). 지난주 이 자리에 “8/20 Cook 이동이 추세의 시작이 아니라 정점이었을 가능성”이라고 적었는데, <strong>금요일 두 건이 그 가능성을 낮췄다.</strong> 특히 공화 성향 하우스가 낸 +5가 그렇다. 그렇다고 최신 두 건만 세는 것도 잘못이다 — Emerson은 여전히 이 주에서 신뢰도가 가장 높은 공개 조사다. <strong>정직한 서술은 “최약 고리에서 진짜 미결로 재개방”이지 “민주가 앞선다”가 아니다.</strong> 구조 신호 하나는 일관된다: 무당층이 투렉 쪽이고(Rasmussen 49–28), 분할투표가 계속 잡히며(상원 동률 대 주지사 샌드 +11), 트럼프 주내 순지지가 −16이다. <strong>아이오와 민주당의 문제는 환경이 아니라 상원 한정 후보 인지도</strong>이고, 그건 10/7 단일 토론에서 좁혀질 수 있는 종류다. (<a href="https://www.rasmussenreports.com/public_content/politics/elections/election_2026/election_2026_iowa_senate">Rasmussen IA</a> · <a href="https://d3nkl3psvxxpe9.cloudfront.net/documents/iowa_election_20260903.pdf">YouGov IA</a> · <a href="https://www.thetrafalgargroup.org/wp-content/uploads/2026/09/MI-Gen-Sen-Full-Report-0910.pdf">Trafalgar MI</a> · <a href="https://edition.cnn.com/2026/09/09/politics/cnn-polls-maine-senate-michigan-senate-abdul-el-sayed-susan-collins">CNN(ME·MI)</a> · <a href="https://www.rasmussenreports.com/public_content/politics/elections/election_2026/election_2026_maine_senate">Rasmussen ME</a> · <a href="https://www.rasmussenreports.com/public_content/politics/elections/election_2026/election_2026_new_hampshire_senate">Rasmussen NH</a> · <a href="https://www.wral.com/news/nccapitol/cooper-maintains-lead-over-whatley-elon-university-poll-sept-2026/">Elon(NC)</a> · <a href="https://surveyresearch-ecu.reportablenews.com/pr/ecu-poll-cooper-leads-whatley-by-7-points">ECU(NC)</a> · <a href="https://thehill.com/homenews/campaign/6083122-james-talarico-ken-paxton-texas-senate-aarp-poll/">AARP(TX)</a> · <a href="https://www.nhpr.org/politics/2026-09-08/pappas-sununu-win-senate-primaries-nh-newhampshire-elections-2026">NHPR(예비선거)</a> · <a href="https://www.axios.com/2026/09/05/trump-magainc-paxton-talarico-texas-senate">Axios(MAGA Inc.)</a>)</p>
</section>
<section id="하원-지도-하나가-실제로-사라졌다" class="level2">
<h2 class="anchored" data-anchor-id="하원-지도-하나가-실제로-사라졌다">하원 — 지도 하나가 실제로 사라졌다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>미주리 — 종결</strong></td>
<td>나흘간 세 법원을 오간 끝에 끝났다. <strong>9/8 캐버노 대법관이 주의 정지 신청을 기각</strong> → 수 분 뒤 연방지법 클라크 수석판사가 <strong>정반대의 14일 TRO</strong>(2025년 지도 강제) → 9/9 법정모독 신청·제8순회 기각으로 확전, 세인트루이스 카운티는 “법적 무인지대”라며 선거 준비를 중단 → <strong>9/10 연방대법원이 클라크 TRO를 정지</strong>. 주 대법원 7-0 판결이 단독 유효 명령으로 남아 <strong>11월은 2022년 지도(6R–2D)로 치른다.</strong> 결정적 제약은 지도 법리가 아니라 <strong>선거 행정</strong>(9/18~19 재외·군인 용지 발송 기한)이었고, 그 벽 나흘 전에 풀렸다</td>
</tr>
<tr class="even">
<td>필요 순증 — <strong>조건부 쌍 소멸</strong></td>
<td>명목 <strong>+3</strong> 불변. 실질은 지난주의 조건부 쌍(<sub>+7/</sub>+8)이 소멸하고 <strong>~+7 단일값으로 확정</strong>됐다. 두 경로가 독립적으로 교차 확인한다 — ① 미주리 2022년 지도 확정으로 ~+8 분기가 제거됐고, ② 같은 날(9/10) <strong>Cook 재획정 트래커가 공화 지도 순증을 “약 4석”으로 재발행</strong>했다(이 사이트가 이월해 온 +8~9는 폐기). 3 + 4 = ~+7</td>
</tr>
<tr class="odd">
<td>Cook 토플라인</td>
<td>Solid D <strong>185</strong> / Likely D 12 / Lean D 9 / <strong>Toss Up 21 (D 5 · R 16)</strong> / Lean R 7 / Likely R <strong>21</strong> / Solid R <strong>180</strong> (9/11 보드, 자동 취득 — 합계 435 검증). 전주(184/12/9/21/7/20/182) 대비 <strong>2건 이동: MO-05 Solid R→Solid D · MO-02 Solid R→Likely R</strong>. <strong>둘 다 토스업 층 밖 이동이라 토스업 멤버십은 21석 그대로다</strong></td>
</tr>
<tr class="even">
<td>등급 이동 — 17일 정체 종료</td>
<td><strong>3개 기관 재가동분 17건 중 16건이 민주 방향이다.</strong> Cook 9/11 위 2건 · 사바토 9/10 4건 전부 민주 방향(AL-02 · MO-02 · MO-05 · <strong>TX-34 Toss-up→Lean D</strong>) · Inside Elections 9/10 하원 3건(FL-14 Lean R→<strong>Tilt R</strong> · MN-01 Solid→Likely R · TX-35 Likely→Lean R)</td>
</tr>
<tr class="odd">
<td><strong>TX-34 — 사이클 첫 민주 방향 토스업 이탈</strong></td>
<td>사바토가 곤잘레스(D)의 사우스텍사스 지역구(트럼프 +10 신지도)를 <strong>Toss-up → Lean D</strong>로 뺐다. 그동안 토스업 층의 이동은 <strong>전부 공화 의석이 악화되며 들어오는 방향</strong>이었다 — 나가는 방향은 처음이다. Cook은 미추종(Toss Up 유지). 배경 증거로 <strong>Cook/TelevisaUnivision 양당 공동 조사</strong>(하트 리서치+온메시지)가 TX-15·28·34 히스패닉 오버샘플(n=414)에서 하원 투표의향 <strong>D+14</strong>(53–39)를 냈다</td>
</tr>
<tr class="even">
<td>Cook 홀드아웃 3건 — 이제 적체가 아니라 판단</td>
<td>법원발 등급 변경에 대한 반응 지연이 <strong>IE 0일 · Cook 1일</strong>로 측정됐다. 그러므로 남은 홀드아웃은 늦은 게 아니라 <strong>능동적 신호</strong>로 읽어야 한다 — ① <strong>TX-15</strong>(사바토 Toss-up·IE Tilt R·독립 조사 D+5까지 쌓였는데 Cook만 Lean R), ② <strong>NC-11</strong>(사바토·IE Toss-up, Cook Lean R), ③ 역방향으로 <strong>TX-34</strong>(사바토 Lean D, Cook Toss Up 유지). ①②가 움직이면 토스업 22석, ③을 따라가면 <strong>20석으로 첫 감소</strong></td>
</tr>
<tr class="odd">
<td>OH-07 — 제도적 출구 전폐</td>
<td>윤리위 60일 시한이 9/4 경과했고(판단은 선거 후로), 존슨 하원의장은 견책을 배제했으며, 후보 교체 시한도 지났다. 그 위에서 <strong>NRCC가 밀러 캠프와 공동 45만 달러 광고를 9/7 개시</strong>했고 밀러는 <strong>자기 캠페인에 100만 달러를 대여</strong>했다. 조사는 당파 의뢰 4건 평균 D+8.7인데 <strong>독립 조사 부재 28일째 — 보드 최장기 결측치</strong>다</td>
</tr>
<tr class="even">
<td>실측</td>
<td>지역구 전체 유권자 기준 신규 독립 조사 <strong>0건</strong>. 최신 독립치는 여전히 TSU(8/18~22: TX-15 D+5 · TX-34 D+3 · TX-28 D+11)다</td>
</tr>
<tr class="odd">
<td>모델·시장 — 간극이 계측됐다</td>
<td><strong>실시간 시장 5개 거래소 합산 민주 하원 통제 84.0%</strong>(9/12, 합산 $43.2M — 칼시 85~86·폴리마켓 86~87·베트페어 83~84·프리딕트잇 80~81·스마켓츠 81~86) · 이 사이트 Kalshi 취득분 <strong>86¢</strong>(9/13) · <strong>DDHQ 68%</strong>(모델 갱신 9/11, 평균 의석 D 229 – R 206) · Smarter.Vote 97%(8/27 이후 <strong>17일 정체</strong> — 상단을 지지하는 유일한 수치라 가중 하향) · <strong>등급가중 기대의석 약 216석</strong>(전주 215 → +1, 증분은 전액 MO-05 환원분). 218에는 여전히 미달</td>
</tr>
<tr class="even">
<td>기준선이 둘로 갈렸다</td>
<td>Inside Elections가 새 기준선을 공표했다 — <strong>공화 우세 212 / 민주 우세 207 / 순수 토스업 16, 민주는 16 중 11 필요.</strong> Smarter.Vote의 비토스업 민주 220과 <strong>13석 간극</strong>이다. 같은 주장이 아니므로 평균 내지 말고 병기한다. 공표된 모든 방법론에서 민주 우세이고, “얼마나”는 <strong>D 218~230</strong>이다</td>
</tr>
</tbody>
</table>
<p><strong>하원에서 이번 주에 실제로 벌어진 일은 지도 한 장이 사라진 것이다.</strong> 이 사이트는 그동안 하원을 “명목 필요 순증 +3 / 실질 약 +8”의 이중 구조로 써 왔고, 지난주에는 미주리 판결 때문에 그것이 <strong>조건부 쌍</strong>(~+7 또는 ~+8)이 됐다고 적었다. 이번 주에 그 쌍이 소멸했다. 그리고 같은 날 <strong>Cook이 공화 지도 순증 총량 자체를 “약 4석”으로 재추정</strong>했다 — 이 사이트가 이월해 온 +8~9의 절반이다. 두 사실이 3 + 4 = ~+7에서 만난다. <strong>미주리 하나가 아니라 재획정 이득의 총량 추정이 같이 내려왔다는 점이 더 중요하다.</strong></p>
<p><strong>그래서 확률을 올렸는가. 올리지 않았다.</strong> 민주 다수 확률의 중심값을 <strong>85% 안팎에서 유지</strong>하는데, 다만 지난주와 이유가 다르다. 지난주에는 “재료가 조건부·제도적”이라 유보했다. 이번 주에는 그 조건이 둘 다 해소됐고 상향 트리거로 지목했던 “기관 재등급 개시”도 실제로 발동됐다(3개 기관 17건 중 16건). <strong>그런데도 중심값을 안 올리는 이유는 하나로 압축된다 — 제너릭 밸럿이 정지했다.</strong> 경유가 사상 첫 $6를 찍고 소비자심리가 1퍼센타일로 내려간 주에 밸럿은 D+6.4~6.6이었다. <strong>이번 주 이동의 대부분은 환경 개선이 아니라 제도·측정의 재가격화</strong>다. 대신 확신도는 올랐다 — 중심값 85%의 근거가 이월된 시장가에서 <strong>실시간 5개 거래소 합산 84.0%</strong>로 교체됐기 때문이다. 다음 상향 트리거는 둘이다: <strong>Cook이 TX-34를 따라가거나 TX-15·NC-11을 토스업에 넣는 것</strong>, 그리고 <strong>밸럿의 D+7 회랑 안착.</strong> (<a href="https://www.scotusblog.com/2026/09/justice-kavanaugh-turns-down-request-from-missouri-to-use-congressional-map-expected-to-aid-repu/">SCOTUSblog</a> · <a href="https://www.nbcnews.com/politics/supreme-court/supreme-court-blocks-missouris-attempt-use-newly-drawn-republican-cong-rcna596857">NBC(연방대법원)</a> · <a href="https://www.stlpr.org/government-politics-issues/2026-09-10/supreme-court-missouri-hoskins-congressional-map">STLPR</a> · <a href="https://www.cookpolitical.com/analysis/house/redistricting-analysis/2025-2026-redistricting-tracker-how-many-seats-could-flip-0">Cook 재획정 트래커</a> · <a href="https://www.cookpolitical.com/analysis/house/missouri-house/two-missouri-house-race-ratings-change-after-redistricting-roller">Cook(MO 2건)</a> · <a href="https://rollcall.com/2026/09/10/rating-changes-10-races-move-toward-democrats-one-toward-republicans/">Roll Call(IE 이동)</a> · <a href="https://www.cookpolitical.com/analysis/house/texas-house/exclusive-new-poll-hispanic-texas-voters-shows-collapse-gops-2024">Cook/TelevisaUnivision</a> · <a href="https://electionbettingodds.com/House-Control-2026.html">ElectionBettingOdds</a>)</p>
</section>
<section id="주지사-알래스카의-두-칸이-한-칸으로-좁혀졌다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-알래스카의-두-칸이-한-칸으로-좁혀졌다">주지사 — 알래스카의 두 칸이 한 칸으로 좁혀졌다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (9/13)</th>
<th>전주(9/6)</th>
<th>등급 (Cook 9/10 / Sabato 9/3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td>92.7¢</td>
<td>95.8¢</td>
<td>Solid D / Likely D</td>
</tr>
<tr class="even">
<td>미시간</td>
<td><strong>91¢</strong></td>
<td>88¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="odd">
<td>애리조나</td>
<td>87¢</td>
<td>87¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="even">
<td>위스콘신</td>
<td>81¢</td>
<td>80¢</td>
<td>Toss-up / Lean D</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>78¢</td>
<td>76¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>64¢</td>
<td>63¢</td>
<td><strong>Lean R (9/10↑)</strong> / Toss-up</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>56¢</td>
<td>57¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>조지아</td>
<td>56¢</td>
<td>56¢</td>
<td>Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td><strong>45¢</strong></td>
<td>42¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>33¢</td>
<td>32¢</td>
<td>Lean R / Lean R</td>
</tr>
</tbody>
</table>
<p><strong>지난주 이 표에서 “단독 최우선 감시 대상”으로 지목한 항목이 해소됐다.</strong> Cook이 15일 침묵을 깨고 <strong>9/10 알래스카를 Likely R → Lean R</strong>로 옮겼다. 사바토가 9/1에 Toss-up으로 내린 뒤 벌어져 있던 <strong>두 칸 격차가 한 칸으로 좁혀졌고</strong>, 이 사이트가 쓰는 양사 평균 가중치는 .25에서 <strong>.375</strong>로 올라간다. 그래서 주지사 기대 순증은 <strong>+0.75석 → +0.875석</strong>이다.</p>
<p><strong>그런데 이 상향은 취약하다는 것을 같이 적어야 한다.</strong> 근거가 실측이 아니라 <strong>구도 해석 한 건</strong>(1D 대 3R)이고, 알래스카 본선 실측은 여전히 <strong>0건</strong>이다. 실측 한 건이면 되돌아갈 수 있는 종류의 상향이다. 그리고 같은 발표에서 <strong>Cook은 오리건을 공화 방향으로 옮겼다</strong>(이동 후 범주 미확인). <strong>전국 환경이 주지사 트랙에서 균질하게 작동하지 않는다는 실증</strong>이고, Cook 자신이 서두에서 그렇게 썼다.</p>
<p><strong>알래스카에서 이번 주 내내 움직인 것은 정책도 여론도 아니라 규칙이었고, 리스크의 부호는 단선적이지 않다.</strong> 트렉 테일러(R) 복권의 유일한 근거였던 법무부 보고서가 부실로 검증됐다 — <strong>파라리걸이 하루 반 만에 작성</strong>했고, 121명 중 91명을 지목했으며(주지사·부지사 후보 8인 전원 포함), 확인된 오류가 다수이고, 국장 본인이 “동명이인 오인 가능”을 인정했다. 주 공직윤리위(APOC)는 신속처리를 거부해 본안이 10/8까지 밀렸고, 소송 두 건이 제기됐다. 여기서 <strong>직관을 뒤집어 읽어야 한다</strong> — 민주당은 같은 하자로 복권된 주하원 후보만 걸고 <strong>테일러는 제소하지 않았다.</strong> <strong>테일러가 낙마하면 3R이 2R이 되어 공화 조정이 쉬워지기 때문이다.</strong> “보고서가 부실하다”는 뉴스는 JKT에게 유리한 뉴스가 <strong>아니다.</strong> 알래스카 .375는 10곳 중 신뢰구간이 가장 넓다.</p>
<p><strong>네바다에서 사이클 첫 비당파 조사가 나왔고, 그 값어치는 중심값이 아니라 분산에 있다.</strong> Emerson/KLAS(9/5~8)가 <strong>포드 44–롬바르도 42(D+2)</strong>를 내면서 8주 공백이 해소됐다. 중요한 것은 이 수치가 <strong>여름 공화 의뢰 3건(롬바르도 +7~+12)의 약 11%p 친공화 편향을 정량화</strong>했다는 점이다 — 8주 동안 “실제로는 R+8일 수도 있다”고 열어 두어야 했던 하방 꼬리가 제거됐다. 이 사이트는 이 계수를 <strong>하우스 이펙트 규칙으로 일반화</strong>해 캔자스의 양당 의뢰 수치와 오하이오 RCP 평균에도 같은 할인을 적용한다. 미시간에서는 Glengariff가 <strong>벤슨 46.8–42.7(D+4.1)</strong>로 4주 만의 비당파 실측을 냈는데, RCP 평균 D+6.7보다 작아 작업 구간의 하단이다.</p>
<p><strong>그런데 미시간·네바다·위스콘신 세 곳에서 같은 구조가 확인됐고, 이게 이번 주 주지사 트랙의 진짜 발견이다.</strong> 벤슨은 <strong>순호감도에서 뒤지면서 득표에서 앞서고</strong>(순호감 −4.2 대 제임스 +2.4), 롬바르도는 <strong>순호감도 +10인데 득표에서 −2</strong>다. 정확히 거울상이다. 위스콘신에서는 데이터센터가 “비용이 편익보다 크다” 76%인데 <strong>최중요 이슈로는 5%(7위)</strong>이고 생활비가 42%(1위)다. 세 주 모두 <strong>우위가 자생적이지 않고 환경이 대여한 것</strong>이라는 뜻이고, 그렇다면 <strong>9/16 연준 인상이 가장 먼저 흔들 값들이다.</strong> 반대로 <strong>아이오와는 여기서 빠진다</strong> — 샌드가 자기 당 호감도보다 약 20%p 초과 성과를 내고 있어 “후보 요인 주도” 유형으로 분류되며, 그래서 10곳 중 등급이 가장 견고하다. 다만 아이오와 YouGov의 D+10~11은 <strong>의뢰자가 확인되지 않아 등급 근거로 쓰지 않는다</strong>(나흘 전 Emerson D+3과 오차범위가 겹치지 않는다).</p>
<p><strong>레이스 밖에서 구조 신호 두 건이 나왔다.</strong> 로드아일랜드 민주 예비에서 <strong>파울크스가 현직 맥키를 62–38로 축출</strong>했다 — 선출직 주지사 기준 2014년 이후 전국 최초다. 이건 특별선거 초과성과를 전부 ’반공화 정서’로 읽는 해석에 대한 <strong>반증</strong>이다. 반현직 정서라면 현직이 출마 중인 두 곳(네바다 롬바르도 R · 애리조나 홉스 D)에 <strong>양방향</strong>으로 작동한다. 두 번째는 더 무겁다 — 9/6 오하이오 캔필드 페어에서 <strong>무장 남성이 액턴 후보에게 돌진해 체포됐다</strong>(권총 2정 소지). 1순위 주지사 트랙에서 후보를 겨냥한 첫 물리적 위협이고, <strong>사건 후 7일간 오하이오 신규 조사는 0건</strong>이라 표심 영향은 전적으로 미측정이다. 오하이오는 RCP 평균 구성이 전부 당파 의뢰로 확인돼 <strong>1순위 10곳 중 실측 기반이 가장 약한 주</strong>다.</p>
<p>주의회는 이번 주 등급 변동이 없다. 대신 <strong>감시 인프라의 결함이 확인됐다</strong> — 체임버 등급의 1차 권위로 써 온 CNalysis가 2024년 선거 후 <strong>운영을 종료</strong>했다(후속은 State Navigate). 그동안 기록된 “체임버 등급 변동 없음” 중 일부는 판단이 아니라 <strong>관측 실패</strong>였을 수 있다. 이 사이트는 이를 소급 신뢰도 문제로 명시해 두고, 다수당 교체 가능 체임버는 사바토/제이콥슨 기준 <strong>토스업 9곳</strong>(민주 상방 6 · 공화 상방 3)으로 유지한다. (<a href="https://www.cookpolitical.com/analysis/governors/governors-overview/oregon-governor-shifts-toward-gop-while-alaska-moves">Cook 9/10</a> · <a href="https://emersoncollegepolling.com/nevada-2026-poll-ford-and-lombardo/">Emerson(NV)</a> · <a href="https://www.detroitnews.com/story/news/politics/2026/09/08/michigan-governor-poll-jocelyn-benson-john-james/91653234007/">Detroit News(MI)</a> · <a href="https://alaskabeacon.com/2026/09/11/report-used-to-justify-reinstatement-of-alaska-republican-governor-candidate-appears-flawed/">Alaska Beacon(보고서 부실)</a> · <a href="https://www.nbcnews.com/politics/2026-election/helena-foulkes-winner-rhode-island-democratic-governor-primary-mckee-rcna596559">NBC(RI)</a> · <a href="https://www.nbcnews.com/politics/2026-election/armed-person-confronts-ohio-gubernatorial-candidate-amy-acton-event-ca-rcna596395">NBC(OH)</a>)</p>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>25주차(9/7~9/13) 거시 환경은 ’가격의 주간’이었고, 여당에 불리한 방향으로 또 한 단계 기울었다.</strong> 브렌트유 사상 첫 $100 돌파(9/9)·경유 사상 첫 $6 돌파($6.05, 9/11)·모기지 7% 재진입에 9월 미시간대 소비자심리 47.8(48년 시계열 2위 최저, 양당 동반 하락)이 겹쳤고, 9/16 FOMC 25bp 인상이 확률 86~90%의 기정사실이 됐으며, 트럼프 본인이 휘발유 가격은 선거 전에 안 내려간다고, 밴스는 이란 전쟁이 유권자를 이탈시켰다고 인정했다. 지지율 평균은 −19.5~−24.7의 바닥에 고착된 채(1기 동기 대비 약 8%p 열위) 이슈별 지지율만 사상 최저를 갱신했고(경제 32/65, 이란 29/65), 제너릭 밸럿은 네 집계가 D+6.4~6.6으로 수렴하며 투표가능층 보정 기준 D+7.6이 확인됐다 — 공화당 연합은 이탈 대신 강도 감쇠(강한 지지 52→41%)로 물러지는 중이다. 제도전에서는 미주리 재획정이 2022년 지도로 종결(1석 민주 이동)되고 우편투표 금지명령이 항소심에서 유지돼 구조 변수 두 개가 민주 쪽으로 정리됐다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(강) — 전주 판정 유지, 확신도 추가 상승.</strong> 유일한 반전 경로는 근원 CPI 2.4%가 시사하는 에너지 충격의 가역성 — 9/14 살랄라 회담發 걸프 해운 완화가 실현될 경우 헤드라인 물가의 빠른 하락 여지 — 이나, 사우디 생산 36년 저점과 동–서 송유관 폐쇄라는 물리적 제약, 그리고 9/16 인상·9/29 캐나다산 수입금지·10/14 CPI(선거 19일 전)라는 예정된 악재 일정이 그 여지를 좁히고 있다. (인용: <code>national_weekly/2026-09-13</code> §6-4)</p>
</blockquote>
<p>여기에 세 가지를 덧붙인다.</p>
<p>첫째, <strong>이번 주에 확정된 것은 수준이 아니라 강도다.</strong> 지난주에는 트럼프 지지율의 <strong>바닥이 32~33%로 확정</strong>됐다고 썼다. 이번 주에 나온 것은 그 아래층이다 — NBC/Decision Desk에서 공화 지지층의 <strong>“강한 지지”가 52%에서 41%로</strong> 내려갔고(MAGA 층은 71% → 62%), FT/Focaldata에서 공화당 내 지지가 <strong>72%로 시리즈 최저</strong>를 찍었다. 설계가 전혀 다른 두 조사가 같은 방향을 가리켰다. <strong>이건 이탈이 아니라 열의의 감소이고, 총계 지지율에도 제너릭 밸럿에도 잡히지 않는다.</strong> 잡히는 곳은 투표율·소액 후원·자원봉사다. 그래서 이번 주 환경 재료 중 <strong>유일하게 “아직 측정되지 않은 채 축적되는” 항목</strong>이고, 이 사이트가 이것을 따로 적어 두는 이유다.</p>
<p>둘째, <strong>밸럿은 또 멈췄다 — 그리고 이번에는 멈춘 자리가 다르다.</strong> 지난주에도 “지지율이 빠지고 유가가 사상 최고인데 밸럿이 멈췄다”고 썼다. 이번 주에도 경유 $6, 심리 47.8, 인상 확률 90%가 겹쳤는데 밸럿은 D+6.4~6.6이었다. 다만 <strong>정지의 성격이 지난주와 다르다.</strong> 네 개의 독립 평균이 <strong>0.2%p 폭 안으로 수렴</strong>했고, 투표가능층 계열 네 건이 연달아 평균 위에 착지했으며, Silver 자체 LV 보정이 <strong>D+7.6</strong>으로 확인됐다. 즉 헤드라인 평균과 LV 조사들의 간극은 <strong>이견이 아니라 모집단 차이</strong>로 정리됐다. <strong>의석을 실제로 예측하는 지표 기준으로 환경은 D+6이 아니라 D+7.6에 가깝다.</strong> 이건 총량이 정지한 주에 나온 가장 중요한 한 줄이다.</p>
<p>셋째, <strong>그래도 이번 주 데이터에는 전부 같은 각주가 붙는다.</strong> 표에 실린 상원 조사의 최신 종료일은 <strong>9/10</strong>이다. 경유 $6는 9/11, 소비자심리 47.8도 9/11, 인상 확률 86~90%도 9/11이며, 송유관 폐쇄는 금요일 장 마감 후였다. <strong>최근 72시간의 충격은 어떤 조사에도 아직 들어가 있지 않다.</strong> 그래서 이 사이트가 이번 주 어떤 수치를 옮기든, 그것은 <strong>충격 이전의 세계를 재는 마지막 측정</strong>이다.</p>
</section>
<section id="상원-산수-이번-주에는-들어갈-것-자체가-없었다" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-이번-주에는-들어갈-것-자체가-없었다">상원 산수 — 이번 주에는 들어갈 것 자체가 없었다</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 50–50은 밴스 부통령의 캐스팅보트로 공화 다수이므로 부족하다. 무소속 3인 중 민주 코커스를 약속한 사람은 없다 — <strong>+4 산술에 우회로는 없다.</strong></p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 8/20·사바토 8/26 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .50 + IA .375</td>
<td><strong>+3.125석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td>GA .125 + MI .50 + NH .25</td>
<td><strong>−0.875석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.25석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>동일</td>
<td>+2.25석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td>Cook·사바토·Inside Elections <strong>세 기관 전부 이동 0건</strong></td>
<td><strong>0.00석</strong></td>
</tr>
</tbody>
</table>
<p><strong>이 표가 3주 연속 소수점까지 같고, 이번 주 이유가 가장 단순하다.</strong> 지난주에는 “Cook·사바토가 멈춘 사이 IE가 세 건을 옮겼는데 이 산수는 두 기관 평균이라 들어갈 자리가 없다”고 썼다. 이번 주에는 <strong>IE도 멈췄다.</strong> 세 기관 전부 이동 0건이다. 그러므로 이 숫자가 안 변한 것은 판단이 아니라 <strong>입력의 부재</strong>다.</p>
<p>그런데 <strong>입력이 없는 동안 아래층에서는 많은 일이 있었다.</strong> 메인의 4주 공백이 민주 방향으로 메워졌고, 미시간의 ‘로저스 우위’ 서사가 공화계 조사를 포함해 3연속으로 무너졌으며, 아이오와가 재개방됐고, 공화당 자금이 텍사스 <strong>방어</strong>로 갔다. <strong>등급 기반 점추정은 유지하되, 증거 분포는 민주 쪽으로 이동했고 리스크 구성이 재편됐다</strong>고 쓰는 것이 정확하다.</p>
<p>리스크 구성의 재편을 구체적으로 적으면 이렇다. 2주 전 이 자리의 하방 무게중심은 <strong>‘NH 상실 + IA·TX 확장 실패’</strong>였다. 이번 주에 <strong>아이오와와 메인이 리스크 목록에서 후퇴</strong>했고, 미시간은 사실상 빠졌다. 남은 것은 <strong>’NH 상실’이라는 단일 축</strong>이다. 그리고 그 축이 왜 결정적인지는 산수로 나온다 — <strong>필수 사수 1석을 잃으면 핵심 4곳을 전부 이겨도 50–50이고, 50–50은 밴스가 공화로 깬다.</strong> 모든 Bull 경로의 구속 조건은 획득이 아니라 뉴햄프셔다.</p>
<p><strong>뉴햄프셔에 대해 이번 주 데이터는 양쪽을 다 준다.</strong> 예비선거는 무상처로 끝났고(파파스 62.5%·서누누 69.1%), 예비 후 첫 조사는 파파스 +11이며, 시장은 83¢에서 85¢로 올랐다. 반대편에는 <strong>직전 UNH의 서누누 +2</strong>가 있고 <strong>IE의 Toss-up 강등</strong>이 그대로 살아 있다. 그리고 파파스 +11 자체가 <strong>서누누의 공화 결집률 64%</strong>라는 이례값 위에 서 있다 — 나흘 전 트럼프 지지로 예비를 69% 얻은 후보의 결집률로는 설명이 안 된다. <strong>추적해야 할 숫자는 +11이 아니라 64%이고, 두 번째 예비 후 조사가 그 판정 데이터다.</strong></p>
<p>네 종류의 숫자는 이번 주에 <strong>하나만 크게 움직였다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>49¢</strong></td>
<td>48¢</td>
<td>거래액 $359만·미결제 $178만. 다수 계약이 1센트 오르는 사이 개별 주는 조사를 따라갔다 — TX +3¢·IA +2¢·NH +2¢ 대 MI·ME·OH 각 −2¢·AK −1¢</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (DDHQ)</td>
<td><strong>50.0%</strong> (평균 의석 D 51 – R 49)</td>
<td>49.0%</td>
<td>모델 갱신 9/11. 평균 의석이 50에서 <strong>51로</strong> 올라 처음으로 다수선을 넘었다. 확률은 정확히 50.0%인데 의석 평균은 51이다 — <strong>둘은 다른 값이고, 이 간격이 상원 다수 경합의 비대칭을 보여준다</strong></td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>63.9%</strong> (예상 의석 D 51.6 – R 48.4)</td>
<td>54.2%</td>
<td>Infogram 라이브 시계열 직접 취득(마지막 관측 9/13, 136점). <strong>이번 주 최대 수치 변동 — 9.7%p 상승</strong></td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.25석</strong></td>
<td>+2.25석</td>
<td>서수적 등급을 확률로 환산 — 전국 환경이 들어갈 자리가 구조적으로 없다. <strong>3주 연속 동일</strong></td>
</tr>
</tbody>
</table>
<p><strong>2주 연속 좁혀졌다고 썼던 그 격차가 한 주 만에 두 배 넘게 다시 벌어졌다.</strong> 두 모델의 차이는 8월 하순 6.3%p → 지난주 5.2%p → 이번 주 <strong>13.9%p</strong>다. 그리고 벌어진 방식이 특이하다 — DDHQ와 Kalshi는 각각 1%p·1센트씩 올라 <strong>49~50 구간에 나란히 붙어 있는데</strong>, Race to the WH 혼자 63.9%로 떠났다. 지난주 이 자리에 “격차의 원인은 데이터가 아니라 가정이고, 5.2%p가 남아 있다는 건 그 가정 차이가 사라지지 않았다는 뜻”이라고 썼다. <strong>이번 주가 그 문장의 증명이다</strong> — 같은 한 주의 데이터를 먹고 한 모델은 10%p 가까이 오르고 다른 모델은 1%p 올랐다면, 차이를 만드는 것은 데이터가 아니다. <strong>평균 내지 말 것.</strong></p>
<p><strong>정직하게 덧붙일 것이 하나 더 있다.</strong> 이 사이트의 등급가중 +2.25석은 <strong>다수 문턱(+4)에 크게 미달</strong>하는데, 같은 주에 RtWH는 민주 다수 확률 63.9%를 말한다. 모순처럼 보이지만 아니다. 등급가중 산수는 <strong>토스업 여섯 곳을 독립 시행으로 취급해 반씩 나눠 갖게</strong> 하는데, 실제 선거에서 토스업들은 <strong>같은 바람에 함께 흔들린다.</strong> 전국 환경이 LV 기준 D+7.6이라면 그 상관은 한 방향으로 작동한다. <strong>그래서 이 산수는 환경이 좋을 때 과소, 나쁠 때 과대 추정한다</strong> — 그것을 알고 쓰는 것이 이 표의 용법이고, 그래서 다른 세 수치와 나란히 놓되 같은 잣대로 비교하지 않는다.</p>
</section>
<section id="공화당의-현시선호-이번-주-가장-저평가된-증거" class="level2">
<h2 class="anchored" data-anchor-id="공화당의-현시선호-이번-주-가장-저평가된-증거">공화당의 현시선호 — 이번 주 가장 저평가된 증거</h2>
<p>여론조사보다 읽기 쉬운 자료가 이번 주에 넉 장 나왔고, 넷 다 같은 방향을 가리켰다.</p>
<p><strong>첫째, 돈이 어디로 갔는가.</strong> 트럼프 MAGA Inc.의 중간선거 본선 <strong>첫 대규모 투입 1,000만 달러</strong>가 공격이 아니라 <strong>텍사스 방어</strong>로 갔다. 트럼프가 2024년에 <strong>14%p로 이긴 주</strong>다. 여기에 Lone Star Liberty PAC 1,500만(18개 시장 2주)과 머스크 America PAC 240만이 얹혀 주간 발표 합계가 약 <strong>2,740만 달러</strong>다. 슈퍼팩 실탄 4억 달러의 2.5%가 한 주에, 안전해야 할 주에 들어갔다.</p>
<p><strong>둘째, 누가 무대에 올랐고 무엇을 말하지 않았는가.</strong> 댈러스 전당대회 개막일 경합주 상원 연사 4명(팩스턴·허스티드·왯틀리·M.콜린스)은 <strong>이란 전쟁과 관세를 단 한 번도 언급하지 않았다.</strong> 이란은 공식 화두 목록에 아예 없었다. 이 사이트가 이걸 증거로 취급하는 이유는 단순하다 — <strong>공격받는 쪽이 어떤 주제를 피하는지는 그 주제의 유효성에 대한 자백</strong>이다. 같은 주에 브라운·탈라리코·투렉이 전부 생활비를 밀고 있었다.</p>
<p><strong>셋째, 누가 안 왔는가.</strong> 가장 접전인 세 주의 공화 후보 — <strong>S.콜린스(메인) · 설리번(알래스카) · 서누누(뉴햄프셔)</strong> — 가 전부 불참했다. 하원 쪽에서도 경합 후보 <strong>절반 미만</strong>이 참석했고, 잭 넌(IA-03)은 “지역구로 돌아가 뛰겠다”고 했다. <strong>어떤 여론조사보다 나은 현시선호다.</strong></p>
<p><strong>넷째, 지도부가 무엇을 인정했는가.</strong> 툰 원내대표는 <strong>“나는 현실주의자다… 지금은 경쟁적인 환경”</strong>이라고 공개로 말했고, 같은 기간 댈러스에서 <strong>팩스턴 모금 행사를 주재</strong>했다 — 예비선거에서 코닌을 밀었던 그 지도부다.</p>
<p><strong>반대 방향도 적는다.</strong> 전당대회에서 나온 <strong>$5,000 ‘트럼프 배당’</strong>은 비용이 약 1.25조 달러로 현행 관세 수입의 10배이고 공화당 의원 발의도 없어 정책이라기보다 메시지인데, <strong>밴스가 몇 시간 만에 “관세 재원·노동자 배당·부유층 제외”로 수정</strong>했다 — 12시간 안에 당 투톱이 서로 다른 정책을 설명했다는 뜻이다. 그리고 <strong>“cheat like hell” 투표 선서</strong>가 금요일 보도를 지배했다. 이 두 건은 상대 진영의 공격 소재이기 이전에, <strong>이 사이트가 앞으로 있을 우편투표·명부·개표확정 소송의 배경 기록으로 남겨 두는 증거</strong>다.</p>
</section>
<section id="두-개의-숫자가-어긋난-곳-기록해-둘-불일치" class="level2">
<h2 class="anchored" data-anchor-id="두-개의-숫자가-어긋난-곳-기록해-둘-불일치">두 개의 숫자가 어긋난 곳 — 기록해 둘 불일치</h2>
<p>이 사이트는 자동 취득 피드를 등급의 정본으로 삼는다. 이번 주에 그 피드와 원천 브리핑이 <strong>두 곳에서 어긋났고, 둘 다 그대로 적어 둔다.</strong></p>
<p><strong>첫째, 오하이오의 Cook 등급이다.</strong> 이 사이트의 270towin 재게시 피드는 Cook 오하이오를 <strong>Toss-up</strong>(8/20 기준)으로 읽는데, 원천 상원 브리핑은 <strong>Lean R</strong>로 적고 있다. 산수에 미치는 영향은 작지 않다 — Toss-up이면 .50, Lean R이면 .375이고, 순 기대의석이 <strong>+2.25 대 +2.125</strong>로 갈린다. <strong>이 사이트는 피드를 따라 +2.25를 쓰되, 차이가 있다는 사실을 여기 남긴다.</strong> 어느 쪽이든 결론(+4 미달)은 바뀌지 않는다.</p>
<p><strong>둘째, 상원 다수 계약의 가격이다.</strong> 원천 브리핑은 <strong>9/6에 Kalshi·Polymarket이 계약 사상 처음으로 민주 상원 장악 약 51%를 찍었다</strong>고 기록했다(2차 보도 인용). 그런데 이 사이트가 <strong>같은 날 Kalshi 공개 API에서 직접 받은 값은 48¢</strong>였고, 이번 주(9/13) 직접 취득값은 <strong>49¢</strong>다. 이 사이트는 <strong>자기가 직접 받은 원가격만 싣는다</strong> — 그래서 표에는 49¢가 들어가 있고, “사상 첫 51% 역전”은 이 사이트가 확인하지 못한 수치다. 다만 방향은 일치한다(전주 대비 +1). 참고로 하원 쪽에서도 같은 종류의 오류가 원천에서 적발됐다 — 한 매체가 폴리마켓의 <strong>민주 86~87%를 “공화 62%”로 부호를 뒤집어 보도</strong>했고 다른 매체가 재전재했다. <strong>예측시장 수치의 2차 인용은 거래소 직접 조회 전까지 미검증으로 취급한다.</strong></p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (9/7~9/13).</strong> 주간 DB는 <strong>17건 추가</strong>(전주 15건)인데, 총량보다 집중도가 다르다 — <strong>17건 중 12건이 안보이고, 그 12건 전부가 호르무즈 단일 파일</strong>이다(4주 추이 8→3→5→12). 그리고 <strong>두 개의 시계가 9/17~18로 수렴한 주</strong>다.</p>
<p><strong>통상 — 사흘간의 확정·공방·부인.</strong> 9/7 산업부가 3,500억 달러 패키지의 <strong>1호 프로젝트로 텍사스 라살 카운티 엔시널 LNG 복합화력(6.3GW)</strong>을 보고했고 한미 전략투자운영위가 승인한 것으로 전해졌다. 사업비는 168억 → 198억에서 미측의 막판 증액 요구를 거쳐 <strong>약 223억 달러</strong>로 절충됐고, 협정문에는 <strong>미국 내 대형 원전 최대 8기</strong> 후속 조항이 담길 전망이다. 이튿날 산업부는 국회 보고에서 <strong>미측이 합의 총액을 넘는 투자를 요구</strong>하고 있다고 밝혔다가, 같은 날 밤 성명으로 <strong>“총액 초과 요구는 사실이 아니다 — 대미 총투자는 어떤 경우에도 2,000억 달러, 연간 송금은 200억 달러를 넘지 않는다”</strong>고 공식 부인했다. <strong>쟁점이 ’1호 사업의 가격’에서 ’합의 총액이 상한인가’로 갔다가 ’연간 송금 한도’라는 새 방어선으로 정리된 한 주</strong>다. 일정은 <strong>9/17 국회 비공개 보고 · 이르면 9/18 MOU 서명</strong>이고, 9/18은 금액이 아니라 프레임워크 서명이 될 공산이 크다.</p>
<p><strong>안보 — 절차가 전진하고 제동이 여섯 겹으로 붙었다.</strong> 국방부가 파병 검토의 <strong>첫 물리적 조치</strong>로 현장실사단을 UAE에 보냈고(9/8 확인, 9/10 귀국), NSC 상임위는 <strong>이르면 9/17</strong> — 투자 패키지 국회 보고와 <strong>같은 날</strong>이다. 검토 패키지는 비전투(군수지원함·P-8 해상초계기·약 150명)이고, 절차는 NSC 결정 → 국무회의 의결 → <strong>국회 동의</strong>다. 제동도 같은 속도로 쌓였다 — 국방부 브리핑의 방향성 표현 후퇴, 대통령실의 ‘군사적 기여’ 범위 축소, 총리의 “결정된 것 없다”, 외교부 1차관의 <strong>“사회적 합의”</strong> 요건(시한 없는 비법률적 조건이 처음 요건 목록에 올랐다), 국방위원장의 국방부 설명 <strong>공개 부인</strong>, 그리고 <strong>9/12 약 540개 종교·시민사회단체의 전국 동시 집회.</strong> <strong>제약이 행정부에서 입법부로, 다시 국가 바깥으로 확장된 주</strong>다.</p>
<p><strong>이란이 이 사안을 한-이란 양자 현안으로 격상시켰다.</strong> 이란 외무부는 9/7 <strong>한국어로 작성한 게시물</strong>로 제3국의 군사적 관여는 “침략자에 대한 직접 지원으로 간주될 것”이라고 경고하면서 64년 우호 관계를 병기했고, 9/11에는 <strong>테헤란 요청으로</strong> 개전 후 6번째 외교장관 통화(조현–아라그치)가 성사돼 ‘미결정’ 입장이 직접 전달됐다. 경고와 채널 유지의 병행이다.</p>
<p><strong>그리고 주말에 논리의 지형이 바뀌었다.</strong> 9/10~11 사우디 <strong>동–서 원유 송유관(일 500만 배럴)이 폐쇄</strong>됐다 — <strong>걸프 원유가 호르무즈를 우회하는 주된 경로</strong>다. 한국의 호르무즈 원유 의존도 <strong>61%</strong>를 부분적으로 헤지하던 길이 사라졌으므로, <strong>공급안보 논거(기여 찬성)와 교전당사국화 논거(기여 반대)가 동시에 강해지는 첫 사실</strong>이다. 이 사이트가 이 건을 상원 트래커와 나란히 놓는 이유도 거기 있다 — <strong>서울의 호르무즈 검토를 촉발한 압박의 원천이 바로 이 브리핑의 환경 지표 그 자체</strong>다.</p>
<p><strong>미국 쪽에서는 조용했고, 그 조용함이 데이터다.</strong> 미 의회의 한국 발화는 이번 주 <strong>0건</strong>(상원 [K] 7일 연속 부재), 경합 레이스 후보의 한국 관련 발언·표결도 <strong>0건</strong>이다. 미국 측 발 항목은 <strong>흥 카오 해군장관 대행의 9/9 한화 필리 조선소 방문</strong>(조선 1,500억 몫의 첫 고위급 현장 확인) 하나뿐이다. <strong>지리적 불일치도 그대로다</strong> — 1호 프로젝트 엔시널은 <strong>토스업 상원 레이스가 걸린 텍사스</strong>에서 주 단위 경제 뉴스 규모인데 <strong>어느 후보도 쟁점화하지 않았고</strong>, 사이클 최대 신규 투자(현대제철–POSCO 루이지애나 58억 달러)는 선거주 밖이다. 알래스카 주지사 후보 4인은 9/9 수산업 포럼에서 <strong>최대 수출시장인 한국을 포함해 어떤 수출시장도 거명하지 않았다</strong> — 이후 이 레이스에 통상이 등장하면 이번 주 기록이 그 부재의 기준선이다. <strong>다음 주는 9/17 NSC·국회 보고 동일자 겹침과 9/18 MOU·유엔총회 개시가 한국 파일 전체의 검증 구간이다.</strong> (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>9/14(월) — 두 개가 같은 날 열린다.</strong> <strong>오만 살랄라 회담</strong>(이란·걸프 외교장관·이라크의 호르무즈 임시 항로 논의)은 <strong>11월 전에 미국 유가를 낮출 수 있는 유일한 변수</strong>다. 그리고 같은 날 <strong>뉴욕 개장</strong>이 금요일 장 마감 후 터진 동–서 송유관 폐쇄를 처음 가격에 반영한다. 이번 주 유일한 반전 경로(근원 CPI 2.4%의 가역성)가 실현될지가 여기서 갈린다.</li>
<li><strong>9/15<sub>16(화</sub>수) — FOMC.</strong> 25bp 인상이 확률 86~90%로 반영돼 있다. 인상은 <strong>선거 7주 전에 “인플레이션이 안 잡혔다”는 공식 선언</strong>이 된다. 직결 대상이 명확하다 — 생계비 노출 하원 토스업(IA-01/03·OH-07/09·MI-07/10·PA-07/08/10·WI-03)과 <strong>“환경 의존 우위” 주지사 3곳(WI·MI·NV)</strong>이다. <strong>인상 이후 첫 경합주 조사가 다음 진짜 데이터다.</strong></li>
<li><strong>아이오와 — Rasmussen 외 기관의 조사.</strong> 현 지도에서 가치가 가장 높은 미결 질문이다. Emerson +5(R) 대 YouGov·Rasmussen +1~+5(D)의 <strong>10%p 불일치</strong>가 어느 쪽으로 해소되느냐가 ‘핵심 3 + 확장 1’ 경로의 실현 확률을 좌우한다.</li>
<li><strong>뉴햄프셔 — 두 번째 예비 후 조사.</strong> 추적할 숫자는 파파스 +11이 아니라 <strong>서누누의 공화 결집률 64%</strong>다. UNH가 다음 진입 가능성이 가장 높다. 뉴햄프셔는 모든 Bull 경로의 전제 조건이므로 이 한 건의 정보가치가 이 지도에서 가장 크다.</li>
<li><strong>등급 감시 4건</strong> — <strong>Cook·사바토가 금요일 아이오와 데이터에 반응하는지</strong>(8/20 Cook 이동을 처음으로 입증하는 증거가 나왔다) · <strong>Cook의 TX-34 추종 여부</strong>(따라가면 토스업 21→20석 첫 감소) · <strong>Cook의 TX-15·NC-11 편입 여부</strong>(넣으면 22석) · IE가 <strong>13개월 미갱신인 미시간·메인 등급</strong>을 재검토하는지.</li>
<li><strong>9/17(목) — 조지아 첫 주지사 토론</strong>(메이컨, 잭슨 미수락 12일째) · 한국 <strong>NSC 상임위(이르면)와 투자 패키지 국회 비공개 보고가 같은 날</strong>이다.</li>
<li><strong>9/18~19(금) — UOCAVA 재외·군인 투표용지 발송 기한.</strong> 이후 지역구 단위 절차 변경은 물리적으로 종료된다. <strong>26A305는 여전히 잭슨 대법관 앞에서 미결</strong>이고, 그 사이 발송 주가 늘수록 정지의 실효가 줄어든다. 같은 날 <strong>한미 전략투자 MOU 서명 가능일</strong>과 <strong>이재명 대통령 유엔총회 방문 개시</strong>(9/18~28)가 겹친다.</li>
<li><strong>9/22(화) — 텍사스 Hearst/NBC–Telemundo 토론 시한.</strong> 팩스턴이 미수락 상태로 D-데이에 접근한다. “일정 조율”이 “거부”로 서사 전환을 완성하는지, 그리고 MAGA Inc.&nbsp;후속 투입이 텍사스 재투입인지 알래스카·오하이오 보강인지가 <strong>공화 자금의 다음 현시선호</strong>다.</li>
<li><strong>알래스카 — 대배심 기소 판단과 3주째 공백인 신규 조사.</strong> 기소는 11/3 전에 발화하면 <strong>방향을 예측할 수 없는 양방향 꼬리</strong>다. 주지사 쪽에서는 APOC 절차(9/21~28 사무국 보고서→답변→재반박, 본안 10/8까지)와 테일러 관련 소송이 <strong>공화 3분열 유지 여부</strong>를 가른다.</li>
<li><strong>10/14 — 9월 CPI, 선거 19일 전.</strong> 8월 PPI의 연료 소매마진 −11.3%가 말하는 <strong>미전가분</strong>이 여기서 나온다. 그 사이 9/25 미시간대 확정치, 9/29 캐나다산 수입 금지 발효가 놓여 있다.</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 09/07~09/13 — 일간 35/35건, <strong>5개 트랙 전부 결손 없음</strong>). 환경 지표 — Silver Bulletin·FiftyPlusOne·RealClearPolling·USPollingData·Morning Consult·NBC News/Decision Desk·FT/Focaldata·Quinnipiac·Reuters/Ipsos·하버드 CAPS/해리스·UMass·Emerson·Quantus. 경제 — BLS(CPI·PPI)·미시간대 소비자심리·AAA·CME FedWatch·프레디맥(모기지). 상원 실측 — CNN/SSRS·Trafalgar Group(공화계)·Glengariff/WDIV·Abacus Data·YouGov·Rasmussen Reports(공화계)·AARP/Fabrizio Ward–Impact Research·InsiderAdvantage·Univision·Elon University·East Carolina University. 주지사 실측 — Emerson College/KLAS·Glengariff. 상원·주지사 등급 — Cook(상원 8/20·주지사 <strong>9/10</strong>)·Sabato(상원 8/26·주지사 9/3)·Inside Elections(9/3) 270towin 재게시분 자동 취득(9/13 실행 — 상원 35/35·주지사 35/36, 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). 하원 등급 — Cook <strong>9/11 보드</strong> 자동 취득(435개구 해독, 합계 435 검증). 예측시장 — Kalshi 공개 API 원가격(9/13). 외부 모델 — Decision Desk HQ(모델 갱신 9/11)·Race to the WH(라이브 시계열 마지막 관측 9/13, 136점). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. <strong>다음 조사는 이 사이트 DB에 넣지 않고 서술로만 반영했다</strong> — 메인 YouGov 잭슨 +4(실사기간·표본 원출처 미확인) · 텍사스 Univision 탈라리코 +5(표본 미확인) · 텍사스 InsiderAdvantage·오하이오 InsiderAdvantage·사우스캐롤라이나 InsiderAdvantage(9/10 동시 공개분, 실사기간 미공표) · 아이오와 투렉 캠프 내부 조사(내부 조사) · 아이오와 주지사 YouGov D+10~11(의뢰자 미확인) · 캔자스 co/efficient(수치 미확보). <strong>기록해 둘 불일치 3건</strong>: ① 이 사이트의 등급 피드는 Cook 오하이오를 Toss-up으로, 원천 상원 브리핑은 Lean R로 적는다 — 산수가 +2.25 대 +2.125로 갈리며, 이 사이트는 피드를 따른다(결론 불변). ② 원천은 9/6 Kalshi·Polymarket의 “사상 첫 민주 51% 역전”을 2차 보도로 기록했으나, 이 사이트가 같은 날 Kalshi 공개 API에서 직접 받은 값은 48¢였고 9/13 직접 취득값은 49¢다 — <strong>직접 취득한 원가격만 싣는다.</strong> ③ Inside Elections의 미시간·메인 등급은 <code>date</code>가 2025-07-24로 13개월 이상 재검토되지 않았다 — 특히 메인 Tilt R은 잭슨 지명·스캔들 국면 전체보다 앞선 값이라 증거가 아니라 낡은 값으로 취급한다. 이번 주 자동 취득 로그에 조회 실패·정렬 불일치로 건너뛴 항목은 뉴햄프셔 주지사 시장(2026 만기 계약 부재) 1건뿐이다. <strong>이번 주 상원 조사는 전부 경유 $6·소비자심리 47.8·9/16 FOMC 이전 실사분이며 최신 종료일은 9/10이다.</strong> 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>