<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="이번 주에는 큰 수치가 하나도 움직이지 않았다. 지지율도 제너릭 밸럿도 5주째 같은 회랑이고, 상원 등급 이동은 사바토의 텍사스 한 건뿐이라 이 사이트의 등급가중 산수는 지난주와 소수점까지 같다. 움직인 것은 지도의 모양이다 — 텍사스가 컨센서스 토스업이 되면서 시장가가 처음 반반 위로 올라왔고(51¢), 같은 주에 뉴햄프셔가 세 번째 필수 사수 리스크로 들어오며 8¢가 빠졌다. 리스크의 무게중심이 ’탈환 미달’에서 ’수성 실패와 탈환 미달의 결합’으로 이동한 주다. 하원에서는 13일 동결이 풀리며 3대 기관이 48시간 안에 모두 민주 쪽으로 움직였는데, 그 최강의 근거가 19포인트 우향 재획정된 트럼프+11 지역구를 Cook이 동전 던지기로 판정한 것이다.">

<title>23주차 · 08/24~08/30 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0430ea7d5b71464ed03367c086f69d1e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">23주차 · 08/24~08/30</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-13일-동결이-풀리자-세-기관이-한꺼번에-움직였다" id="toc-하원-13일-동결이-풀리자-세-기관이-한꺼번에-움직였다" class="nav-link" data-scroll-target="#하원-13일-동결이-풀리자-세-기관이-한꺼번에-움직였다">하원 — 13일 동결이 풀리자 세 기관이 한꺼번에 움직였다</a></li>
  <li><a href="#주지사-등급은-0건인데-실측구조는-넷이-민주-쪽으로-갔다" id="toc-주지사-등급은-0건인데-실측구조는-넷이-민주-쪽으로-갔다" class="nav-link" data-scroll-target="#주지사-등급은-0건인데-실측구조는-넷이-민주-쪽으로-갔다">주지사 — 등급은 0건인데 실측·구조는 넷이 민주 쪽으로 갔다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-등급이-안-움직이면-산수도-안-움직인다" id="toc-상원-산수-등급이-안-움직이면-산수도-안-움직인다" class="nav-link" data-scroll-target="#상원-산수-등급이-안-움직이면-산수도-안-움직인다">상원 산수 — 등급이 안 움직이면 산수도 안 움직인다</a></li>
  <li><a href="#텍사스와-뉴햄프셔-같은-주에-열린-두-개의-문" id="toc-텍사스와-뉴햄프셔-같은-주에-열린-두-개의-문" class="nav-link" data-scroll-target="#텍사스와-뉴햄프셔-같은-주에-열린-두-개의-문">텍사스와 뉴햄프셔 — 같은 주에 열린 두 개의 문</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">23주차 · 08/24~08/30</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    이번 주에는 큰 수치가 하나도 움직이지 않았다. 지지율도 제너릭 밸럿도 5주째 같은 회랑이고, 상원 등급 이동은 사바토의 텍사스 한 건뿐이라 이 사이트의 등급가중 산수는 지난주와 소수점까지 같다. 움직인 것은 지도의 모양이다 — 텍사스가 컨센서스 토스업이 되면서 시장가가 처음 반반 위로 올라왔고(51¢), 같은 주에 뉴햄프셔가 세 번째 필수 사수 리스크로 들어오며 8¢가 빠졌다. 리스크의 무게중심이 ’탈환 미달’에서 ’수성 실패와 탈환 미달의 결합’으로 이동한 주다. 하원에서는 13일 동결이 풀리며 3대 기관이 48시간 안에 모두 민주 쪽으로 움직였는데, 그 최강의 근거가 19포인트 우향 재획정된 트럼프+11 지역구를 Cook이 동전 던지기로 판정한 것이다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 8월 24일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 8/24~8/30 일간 브리핑 35건(전국·상원·하원·주정부·Korea Watch 각 7/7 — <strong>5개 트랙 전부 결손 없음</strong>). 뉴스 기준: 미 동부시간 8/29(토) 저녁까지. 선거일(11/3)까지 65일. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>한 주 동안 큰 수치가 하나도 안 움직였다</strong> — 트럼프 순지지는 <strong>−23.6 → −23.1</strong>(FiftyPlusOne, 엿새 전 구간이 노이즈 밴드 내), 제너릭 밸럿은 독립 평균 4~5개가 <strong>D+6.0~6.7</strong>에서 <strong>5주째</strong> 고착이다. 대법원 우편투표 결정, 이란 제재 개시, 매파 잭슨홀, PCE 발표가 연달아 왔는데 어느 것도 회랑을 깨지 못했다. 상원 등급 이동도 <strong>사바토의 텍사스 한 건</strong>뿐이라, 이 사이트의 등급가중 순 기대의석은 <strong>+2.25석으로 지난주와 소수점까지 같다.</strong></li>
<li><strong>그런데 지도의 모양은 바뀌었다</strong> — <strong>텍사스가 컨센서스 토스업이 됐다.</strong> 8/26 사바토가 Leans R → Toss-up으로 옮겨 Cook(8/20)에 합류했고, 조사 두 건(TPOR D+7 · UT/Texas Politics Project D+3)이 동반했으며, 트럼프가 8/27 휴스턴 모금행사를 직접 주재했다. 시장은 탈라리코를 <strong>처음으로 반반 위(51¢)</strong>로 올렸다. 리치(reach) 의석 방어에 전국 자원이 들어가고 있다는 공개 인정이다.</li>
<li><strong>같은 주에 반대쪽 문이 열렸다 — 뉴햄프셔</strong> — UNH 그래닛스테이트 폴(8/20–24)이 시리즈 사상 처음으로 <strong>수누누 45 – 파파스 43</strong>을 냈다. 작년 9월 같은 시리즈가 파파스 +6이었으니 <strong>1년 새 8포인트</strong>다. 세인트앤셀름 D+7이 정면 반박이지만, 시장은 민주 <strong>91¢ → 83¢</strong>로 반응했다 — 감시 9주 중 이번 주 유일한 두 자릿수 하락이다. 등급은 양 기관 모두 Lean D 그대로다.</li>
<li><strong>모델과 시장이 3주 만에 처음 서로에게 다가왔다</strong> — Kalshi 상원 다수 <strong>46¢ → 48¢</strong>, Decision Desk HQ <strong>46.0% → 48.0%</strong>, Race to the WH <strong>55.5% → 54.3%</strong>. 지난주 9.5%p였던 두 모델의 격차가 <strong>6.3%p</strong>로 좁혀졌고, 좁혀진 방식이 한쪽의 항복이 아니라 양쪽의 접근이다.</li>
<li><strong>하원 — 13일 동결이 풀리자 3대 기관이 48시간 안에 모두 민주 쪽으로 갔다</strong> — Cook 3건 + Inside Elections 8건 + 사바토 3건, 역방향 <strong>0건</strong>. 토스업은 19 → <strong>21석(D5/R16)</strong>. 가장 무거운 한 건은 <strong>FL-14</strong>다 — 캐스터 낙선을 겨냥해 약 19포인트 우향 재획정된 <strong>트럼프+11</strong> 지역구인데 Cook이 동전 던지기로 판정했다. 공화당의 지도상 이득이 D+6 환경에서 액면대로 실현되지 않는다는 증거다.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>트럼프 순지지도</td>
<td><strong>−23.1</strong> (36.3/59.4)</td>
<td>8/28 (FiftyPlusOne)</td>
<td>주간 추이 −23.6(8/23) → −23.7 → −23.8 → −23.6 → −23.5 → <strong>−23.1</strong> — 방향은 +0.5p 개선이나 엿새 전 구간이 노이즈 밴드 안이다. Silver Bulletin은 <strong>−20.4가 3주째 같은 게시값</strong>(페이지 8/21). 모집단 이중 판독: <strong>전 성인 −20~−24 / 투표가능층 −14~−16</strong>(라스무센 5일 추적 −14가 이번 주 신규로 LV 상단을 확장)</td>
</tr>
<tr class="even">
<td>일반투표(제너릭)</td>
<td><strong>D+6.1</strong> (FiftyPlusOne 49.5/43.4)</td>
<td>8/28</td>
<td>독립 평균이 <strong>D+6.0~6.7에 5주째</strong> 고착 — FiftyPlusOne 6.1 · RCP 6.4 · USPollingData 6.6 · Silver Bulletin 6.7(LV 보정 <strong>8.1</strong>) · DDHQ 6.0. 하단은 등록유권자 기준(Morning Consult D+4 · WaPo–Ipsos D+3). <strong>DDHQ의 상원 순수 접전 임계선 D+7.5를 사이에 둔 위치가 그대로다</strong></td>
</tr>
<tr class="odd">
<td>금리 — 이번 주 최대 신규 악재</td>
<td>9월 인상 확률 <strong>35.4% → 약 57.5%</strong> · 2년물 <strong>+11bp(4.34%)</strong></td>
<td>8/28 (워시 잭슨홀 기조연설)</td>
<td>신임 연준 의장의 데뷔가 매파로 확정되면서 <strong>‘11월 전 완화’가 ’선거 전 인상’ 리스크로 역전</strong>됐다. 채권시장이 선거 전 인상을 절반 이상 확률로 가격화한 채 9월로 들어간다. 검증대는 <strong>9/16 FOMC</strong></td>
</tr>
<tr class="even">
<td>물가·소비</td>
<td>7월 PCE <strong>3.7%</strong>(근원 3.3%) · 실질 소비 <strong>0.0%</strong></td>
<td>8/26</td>
<td>헤드라인이 컨센서스(3.6%)를 상회하며 3%대 후반 고착. 실질 소비 급제동은 직전 주 월마트 신호의 거시 확인이다</td>
</tr>
<tr class="odd">
<td>심리·기대인플레</td>
<td>컨퍼런스보드 <strong>89.4</strong>(1월 이후 최저) · 1년 기대인플레 <strong>5.8%</strong> · 미시간대 <strong>51.7</strong></td>
<td>8/25~8/28</td>
<td>집권당 심판과 상관하는 ‘기대’ 성분이 하락을 주도(−5.8p). 심리 침체 + 고물가는 역사적으로 집권당을 벌하는 전형적 조합</td>
</tr>
<tr class="even">
<td>유가·휘발유</td>
<td>브렌트 <strong>$94.39 → $89.18</strong> (주간 <strong>−5.5%</strong>) · AAA 약 <strong>$4.09</strong></td>
<td>8/21~8/28</td>
<td><strong>이번 주 유일한 반증 재료.</strong> 시장이 이란 제재를 전쟁 리스크 완화로 읽었고, 이란–오만 임시 항행 회랑 제안이 부상했다 — 파이프라인에 실재하는 유일한 디스인플레 경로다. 다만 수준 자체는 <strong>사상 첫 ‘매일 $4 위’ 8월</strong></td>
</tr>
<tr class="odd">
<td>총량 vs 가계</td>
<td>Q2 GDP <strong>1.5%</strong> · 내구재 <strong>+1.1%</strong> · 엔비디아 매출 <strong>+106%</strong> vs 실질 소비 0.0%</td>
<td>8/26~8/27</td>
<td>“총량·기업은 버티고 가계는 쪼들리는” 괴리 구조가 한 층 더 굳었다. <strong>BLS 고용 벤치마크 예비 수정이 −7.9만에 그쳐</strong>(작년 ~−90만의 재판 없음) ‘견조한 노동시장’ 서사가 최대 시험을 통과한 것도 반증 재료</td>
</tr>
<tr class="even">
<td>투표 접근 — 신규 구조 변수</td>
<td>우편투표 행정명령 <strong>한 주에 4회 반전</strong> · 현재 TRO로 차단</td>
<td>8/24~8/28</td>
<td>8/24 대법원 6–3 부분 집행정지 → 8/26 USPS 최종 규칙 관보 공포 + 23개 주·DC 재소송 → 8/27 밤 14일 TRO 재차단 → 8/28 법무부 항소. <strong>9/3 예비금지명령 심리가 분수령</strong>이며, 시행 시 민주 투표 메커니즘에 불리한 방향이다</td>
</tr>
</tbody>
</table>
<p>지난주 이 자리에서 “불리함의 질이 조사에서 행동으로 이동했다”고 썼다. 이번 주는 그 다음 축이 움직였다 — <strong>변동성이 총량 지표에서 제도·정책 변수로 옮겨갔다.</strong> 지지율도 밸럿도 회랑 안에 정지해 있는 동안, 우편투표 규칙이 한 주에 네 번 뒤집혔고 이란 제재가 개시됐고 연준 의장이 매파로 데뷔했다. 큰 사건이 연달아 왔는데 총량이 안 움직였다는 사실 자체가 이번 주의 발견이다. <strong>이미 공화당에 나쁜 수준에서의 고착</strong>이기 때문이다.</p>
<p>새 악재는 금리 쪽에서 왔다. 워시 의장이 잭슨홀에서 “기저 인플레이션 추세가 의미 있게 개선되지 않았다”며 향후 수개월 내 인상 가능성을 시사했고, 9월 인상 확률이 35.4%에서 약 57.5%로 가격화됐다. 여름 내내 이 사이트가 추적해 온 생활비 채널에 <strong>’11월 전에 금리가 내려올 수 있다’는 유일한 완화 시나리오가 닫히고, 대신 선거 직전 인상 리스크가 열린 것</strong>이다. PCE 3.7% 고착, 기대인플레 5.8%, 사상 첫 ‘매일 4달러 위’ 8월 휘발유가 그 위에 얹혀 있다.</p>
<p>반대 방향으로도 처음으로 실재하는 재료가 나왔다. 브렌트가 주간 5.5% 떨어졌다 — 시장이 이란 제재를 전쟁의 대체재로 읽었기 때문이다. 유가에서 주유소 가격까지는 약 2주 시차이므로, 이 흐름이 유지되면 9월 중순 가격표에 반영된다. BLS 고용 벤치마크 수정이 −7.9만에 그친 것도 반증 재료다 — 작년의 ~−90만 같은 통계 충격은 없었다. 다만 이 둘은 금리 인상 가격화라는 신규 악재와 대체로 상쇄된다. (<a href="https://www.cnbc.com/2026/08/28/kevin-warsh-jackson-hole-federal-reserve-inflation.html">CNBC(워시)</a> · <a href="https://www.votebeat.org/national/2026/08/24/supreme-court-lifts-stay-trump-executive-order-on-elections-mail-ballot-restrictions/">Votebeat(우편투표)</a> · <a href="https://www.democracydocket.com/news-alerts/doj-appeals-court-order-temporarily-blocking-trumps-attack-on-mail-voting/">Democracy Docket(항소)</a> · <a href="https://home.treasury.gov/news/press-releases/sb0613">재무부(제재)</a> · 상세 <code>national_weekly/2026-08-30</code>)</p>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p>이번 주 상원 지도에서 나온 공식 등급 이동은 <strong>사바토의 텍사스 한 건</strong>(8/26, Leans R → Toss-up)뿐이다. 그런데 이 사이트가 자동 취득하는 등급 피드는 그 이동을 이미 8/28에 반영했기 때문에, <strong>등급가중 순 기대의석은 지난주와 정확히 같은 +2.25석이다.</strong> 대신 읽어야 할 것은 시장가의 방향이 갈렸다는 사실이다 — 오하이오 +4¢ · 미시간 +3¢ · 알래스카 +3¢ · 텍사스 +3¢가 오르는 동안 <strong>뉴햄프셔는 −8¢</strong>가 빠졌다. 등급은 정지해 있고 시장만 재배치된 주다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 8/20 / Sabato 8/26)</th>
<th>시장 (Kalshi 8/30)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Lean D / Likely D</td>
<td>93¢ (▲1)</td>
<td>이번 주 나온 건 조사가 아니라 <strong>지지 선언</strong>이다 — 사흘 새 공화 인사 3인(플레이크 전 상원의원 + 밸도스타·티프턴 시장)이 오소프 지지. 콜린스 쪽은 Overhaul PAC 전 인턴의 KKK 복장 사진 보도. 신규 +13 조사는 <strong>기관 미공개</strong>라 DB 미등재 (<strong>안정</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / Toss-up</td>
<td>64¢ (▲3)</td>
<td><strong>‘민주 최대 위험 의석’ 프레임 폐기.</strong> 8월 조사 5건 전부 엘사예드(서스쿼해나 +7·GBAO +6·TIPP +3·AARP +1), 로저스 우위는 RV 기준 폭스 +4 1건뿐. 로저스가 데이터센터 모라토리엄으로 당론과 결별 (<strong>강화</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Lean D / Lean D</td>
<td><strong>83¢ (▼8)</strong></td>
<td><strong>UNH 그래닛스테이트 첫 R 우위 — 수누누 45–43</strong>(8/20–24). 1년 새 8p 이동. 세인트앤셀름 파파스 48–41이 정면 반박. 민주 예비도 파파스 47–만주르 34로 좁혀짐(1년 전 65–14). 9/8 예비 (<strong>약화</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D</td>
<td>91¢ (=)</td>
<td>창 내 신규 조사 없음. 범위 HPU D+5 ~ Elon D+11. 좁혀짐의 원인은 쿠퍼 이탈이 아니라 <strong>왓틀리 인지도 상승</strong>(자연적 상한 존재). <strong>9/4 부재자 신청 개시 — 감시주 중 설득 기간이 가장 먼저 닫힌다</strong> (<strong>변동 없음</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss Up / Toss Up</td>
<td>70¢ (▲1)</td>
<td><strong>조사는 3주째 없지만 구조 변수 2건이 해소됐다</strong> — 플래트너 write-in 미등록(민주 표 분산 시나리오 소멸) + 군소 write-in 6인 등록으로 <strong>11월 RCV 확정</strong>. 콜린스 4회 토론 수락(첫 9/6 주간), 잭슨은 타운홀 요구로 보류 (<strong>미확인</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss Up / Toss Up</td>
<td>64¢ (▲3)</td>
<td><strong>개표 확정 — 펠톨라 48.1 – 설리번 42.7</strong>(약 98%). 동명이인(약 2.5%) 3위로 <strong>11월 RCV 본선 등재 확정</strong>. Almanac 산수: 두 설리번을 합쳐도 45.1%로 3p 열세 — 스포일러는 이제 공화 쪽 문제. 인증 8/31 (<strong>강화</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss Up / Toss Up</td>
<td>56¢ (▲4)</td>
<td><strong>NRSC 광고 역풍.</strong> I-71 사고 유족이 반브라운 이민 광고 철회를 공개 요구, NRSC는 사과 거부. 직전에 PolitiFact가 허스티드의 유사 주장에 ‘부정확’ 판정. 조사 편차는 여전히 감시 9주 중 최대 (<strong>강화</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Toss Up / <strong>Toss-up (8/26↑)</strong></td>
<td><strong>51¢ (▲3)</strong></td>
<td><strong>사바토 합류로 컨센서스 토스업 성립.</strong> TPOR 47–40(8/21–26, LV 1,000)·UT/TPP 42–39(6월 팩스턴 +1에서 반전). 트럼프 8/27 휴스턴 모금행사 직접 주재. 시장이 처음 반반 위로 (<strong>등급↑·시장↑</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Toss Up / Lean R</td>
<td>43¢ (▼1)</td>
<td><strong>Cook 이동 후 첫 공개 조사 — Suffolk 힌슨 45–41</strong>(8/20–23, ±4.4로 통계적 동률). 폭스 투렉 +4와 상쇄돼 RCP 평균 힌슨 +0.7. <strong>9/8 캐나다 보복관세 발효로 ‘관세→투표’ 채널 실전 개시</strong> (<strong>약화</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 신규 조사는 <strong>뉴햄프셔·텍사스 각 2건, 아이오와 1건</strong>이다(이 사이트 조사 DB에 등재한 기준).</p>
<p><strong>뉴햄프셔가 이 주의 사건이다.</strong> UNH 그래닛스테이트 폴(8/20–24)에서 수누누 45 – 파파스 43이 나왔는데, 이건 이 시리즈에서 수누누가 앞선 <strong>첫 관측</strong>이다. 작년 9월 같은 조사는 파파스 49–43이었다. 문제는 같은 창에 반대 신호가 있다는 것이다 — 세인트앤셀름(8/17–18 필드, 8/20 등재)은 파파스 48–41로 D+7이다. 두 조사가 10포인트 갈린 채 9/8 예비선거를 9일 앞두고 마지막 구간에 들어갔다. 정직한 서술은 “뉴햄프셔가 뒤집혔다”가 아니라 <strong>“이 주의 참값에 대해 두 지역 기관이 서로 다르고, 그 사실 자체가 여름 내내 없던 상태”</strong>다. 시장은 −8¢로 반응했고 등급 기관 둘은 아무것도 하지 않았다 — 등급이 조사에 후행하는 전형적 구간이다.</p>
<p><strong>텍사스는 반대 방향이다.</strong> TPOR(8/21–26, LV 1,000, ±3.3)이 탈라리코 47–40을 냈고 — RCP는 8/27자로 전체 톱라인 48–42를 등재했다 — UT/Texas Politics Project(8/5–13, RV 1,200, ±2.83)는 42–39로 같은 기관 6월 조사(팩스턴 43–42)를 뒤집었다. 여기에 사바토의 등급 이동과 트럼프의 직접 참전이 겹쳤다. 다만 <strong>RCP 평균은 아직 탈라리코 +1.7</strong>이고, 펀더멘털 가중 모델(Pollsmax)은 여전히 약 79% 공화다. 조사 두 건이 앞서간 것인지 평균이 뒤따라올 것인지는 아직 모른다.</p>
<p><strong>아이오와는 유일하게 반대로 나왔다.</strong> Cook이 8/20 토스업으로 올린 뒤 처음 나온 공개 조사(Suffolk, 8/20–23)가 힌슨 45 – 투렉 41이다. ±4.4에서 4포인트 차이는 통계적 동률이지만, 방향은 리치 티어 좌향 표류의 일반화를 반박한다. 같은 조사의 주지사 문항은 샌드 48 – 란 44로 정반대다 — <strong>아이오와는 티켓 상·하단이 갈리는 주로 봐야 한다.</strong></p>
<p>정정을 하나 적어 둔다. 이 사이트가 종합하는 상원 트랙 원문은 노스캐롤라이나를 <strong>Cook Toss-up / Sabato Leans D</strong>로 적었는데, 이 사이트가 자동 취득하는 270towin 재게시 피드는 <strong>Cook 8/20 Lean D · Sabato 8/26 Lean D</strong>로 두 기관이 일치한다. 이 사이트는 피드값을 싣는다. (<a href="https://www.newsweek.com/poll-shows-shifts-in-new-hampshire-senate-race-as-gop-aims-to-flip-seat-12373093">Newsweek(UNH)</a> · <a href="https://centerforpolitics.org/crystalball/2026-rating-changes/">Crystal Ball(등급 변동)</a> · <a href="https://thehill.com/homenews/campaign/6055357-texas-senate-poll-talarico-leading/">The Hill(TPOR)</a> · <a href="https://www.kxan.com/news/texas-politics/james-talarico-leads-ken-paxton-poll/">KXAN(UT/TPP)</a> · <a href="https://thehill.com/homenews/campaign/6051379-iowa-senate-governor-polls/">The Hill(Suffolk)</a> · <a href="https://rollcall.com/2026/08/26/senate-ballot-in-alaska-will-feature-two-dan-sullivans/">Roll Call(AK 동명이인)</a> · <a href="https://mainemorningstar.com/2026/08/26/six-write-in-candidates-file-for-maine-u-s-senate-race-prompting-ranked-choice-voting/">Maine Morning Star(RCV)</a>)</p>
</section>
<section id="하원-13일-동결이-풀리자-세-기관이-한꺼번에-움직였다" class="level2">
<h2 class="anchored" data-anchor-id="하원-13일-동결이-풀리자-세-기관이-한꺼번에-움직였다">하원 — 13일 동결이 풀리자 세 기관이 한꺼번에 움직였다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>등급 이동</td>
<td><strong>48시간 안에 3대 기관 전부 민주 방향 — Cook 3건 + Inside Elections 8건 + 사바토 3건, 역방향 0건.</strong> Cook 8/25: FL-14(캐스터·D)·MI-10(공석) Lean R → Toss Up, MI-08 Lean D → Likely D. 사바토 8/26: TX-15·TX-34 Toss-up, TX-28 Leans D</td>
</tr>
<tr class="even">
<td>Cook 토플라인</td>
<td>Solid D 184 / Likely D 12 / Lean D 9 / <strong>Toss Up 21 (D 5 · R 16)</strong> / Lean R 7 / Likely R 20 / Solid R 182 (8/25 보드, 자동 취득 — 합계 435 검증). 전주 대비 순변동 3건, 전부 민주 방향</td>
</tr>
<tr class="odd">
<td>전장 확장</td>
<td>Inside Elections가 공화 <strong>공석 3곳(KY-06·NV-02·SC-01)을 Solid R → Likely R</strong>로, CO-05를 Lean R로 이동. 반대편 민주 보유는 굳어짐(CA-21 Solid D, Cook MI-08 Likely D) — <strong>민주 노출 축소·공화 노출 확대의 비대칭</strong></td>
</tr>
<tr class="even">
<td>이번 주 최중요 전망치</td>
<td><strong>Inside Elections: 민주 순증 +2~+10석. 중간주기 재획정이 없었다면 +5~15석(최대 +10~20석)</strong>이었을 것 — 이 사이트가 써 온 ’명목/실질 이중 구조’를 예측기관이 처음 정량화했다</td>
</tr>
<tr class="odd">
<td>실측</td>
<td><strong>TX-15 첫 독립 조사 — 풀리도(D) 50–45</strong>(텍사스서던대, 8/18–22, LV 700, ±3.7). 당파 조사(HMP 50–45·51–45)와 사실상 동일. 같은 조사 TX-34 D+3 · TX-28 D+11</td>
</tr>
<tr class="even">
<td>보궐</td>
<td><strong>GA-13 결선(8/25) 블레어(D) 54–46</strong>으로 1차 8p 열세 역전 — 민주 단독 결선·초저투표율이라 <strong>스윙 시계열에는 사실상 0 가중</strong>, 기계적 효과는 공석 1석 해소</td>
</tr>
<tr class="odd">
<td>잔여 결측</td>
<td><strong>OH-07 독립 조사가 3주째 없다</strong> — 공개 4건이 전부 당파 의뢰(D2·R2). 존슨 의장의 휴회 유세 동선에서 유일하게 빠진 토스업 현역이기도 하다</td>
</tr>
<tr class="even">
<td>모델·시장</td>
<td>Kalshi 하원 다수 <strong>84¢</strong>(8/30, 전주 85¢) · <strong>DDHQ 66%</strong>(모델 갱신 8/28 — 평균 의석 D 228 – R 207) · Smarter.Vote 97%(AI 생성 명시 — 동급 취급 금지) · Polymarket ~89% · 등급가중 기대의석 약 <strong>215석</strong>(218 미달)</td>
</tr>
</tbody>
</table>
<p>이번 주 하원에서 가장 무거운 한 건은 <strong>FL-14</strong>다. 이 지역구는 캐스터를 떨어뜨리려고 약 19포인트 우향으로 다시 그은 곳이고, 새 지도에서 <strong>트럼프 +11</strong>이다. 그런데 Cook이 여기를 동전 던지기로 판정했다. 재획정이라는 도구가 D+6 환경에서 설계된 만큼 작동하지 않는다는 것을, 등급 기관이 자기 판단으로 인정한 사례다. 같은 방향의 실측이 <strong>TX-15</strong>에서 나왔다 — 트럼프 +18 지역구에서 텍사스서던대의 첫 독립 조사가 풀리도(D) 50–45를 냈고, 당파 조사와 수치가 거의 같았다.</p>
<p>Inside Elections가 톱라인으로 제시한 숫자는 이 사이트가 그동안 서술로만 다뤄 온 것을 처음 계량화한 것이다. <strong>민주 순증 전망 +2~+10석, 재획정이 없었다면 +5~15석(최대 +10~20석).</strong> 즉 재획정이 흡수한 민주 이득이 약 3~10석이라는 뜻이다. 이 사이트가 써 온 “명목 필요 순증 +3 / 실질 약 +8”에서 실질 쪽 수치는 이제 <strong>상한의 성격</strong>으로 읽어야 한다 — FL-14와 TX-15의 실측이 그 상한이 온전히 실현되지 않고 있음을 보여주기 때문이다.</p>
<p>한 가지 규율 항목. <strong>이번 주 제너릭 밸럿은 순변동이 사실상 0이었다</strong>(D+6.1, 8/28). 등급이 대거 움직인 주에 환경 지표가 정지해 있었다는 것은, 이 이동의 동인이 환경 악화가 아니라 <strong>대진 확정과 신규 조사에 대한 기관들의 후행 반영</strong>이라는 뜻이다. 민주 다수 확률의 중심값이 80% 안팎에서 85% 안팎으로 올라간 것은 ’새 정보’가 아니라 <strong>‘측정의 정밀화’</strong>로 읽는 것이 맞다. (<a href="https://www.cookpolitical.com/analysis/house/house-overview/three-house-race-ratings-michigan-and-florida-shift-democrats">Cook(3건 이동)</a> · <a href="https://rollcall.com/2026/08/26/rating-changes-seven-more-house-races-shift-toward-democrats/">Roll Call(IE 8건)</a> · <a href="https://centerforpolitics.org/crystalball/three-rating-changes-in-texas-all-towards-democrats/">Crystal Ball(텍사스 3건)</a> · <a href="https://thetexan.news/elections/2026/democrats-lead-in-poll-of-closely-contested-south-texas-congressional-districts/article_b4fe43ce-b2f0-4382-9fbf-36d10872df8c.html">The Texan(TX-15)</a> · <a href="https://www.nbcnews.com/politics/2026-election/everton-blair-wins-georgia-house-democrat-special-election-rcna593580">NBC(GA-13)</a>)</p>
</section>
<section id="주지사-등급은-0건인데-실측구조는-넷이-민주-쪽으로-갔다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-등급은-0건인데-실측구조는-넷이-민주-쪽으로-갔다">주지사 — 등급은 0건인데 실측·구조는 넷이 민주 쪽으로 갔다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (8/30)</th>
<th>전주(8/23)</th>
<th>등급 (Cook 8/27 / Sabato 8/26)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td>94¢</td>
<td>96¢</td>
<td>Solid D / Likely D</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>87¢</td>
<td>87¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="odd">
<td>애리조나</td>
<td>86¢</td>
<td>89¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="even">
<td>위스콘신</td>
<td><strong>80¢</strong></td>
<td>78¢</td>
<td>Toss-up / Lean D</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>76¢</td>
<td>78¢</td>
<td>Lean D / Toss-up</td>
</tr>
<tr class="even">
<td>조지아</td>
<td>60¢</td>
<td>59¢</td>
<td>Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td><strong>57¢</strong></td>
<td>52¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td><strong>55¢</strong></td>
<td>46¢</td>
<td>Likely R / Likely R</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td>42¢</td>
<td>42¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>36¢</td>
<td>32¢</td>
<td>Lean R / Lean R</td>
</tr>
</tbody>
</table>
<p><strong>1순위 경합 10곳의 등급 이동은 이번 주 0건이다.</strong> 그런데 실측과 구조는 넷이 움직였고, 그 결과 <strong>등급과 실측이 어긋난 주가 네 곳으로 늘었다.</strong></p>
<p>가장 큰 것은 <strong>알래스카</strong>다. 브론슨 전 앵커리지 시장이 8/26 “사퇴하지 않는다”고 공식 선언하면서 공화 단일화가 사실상 무산됐다. 8/26 갱신 집계 기준 순위는 JKT(D) 22.2 – 베기치(D) 20.5 – 윌슨(R) 10.2 – 브론슨(R) 8.2다. <strong>8/31 인증·사퇴 시한을 지나면 민주 2 대 공화 2의 RCV 본선이 확정</strong>되고, 공화 합산 약 19% 대 민주 상위 2인 약 42%의 표 분산이 구조로 굳는다. 그런데 등급은 Cook Likely R · 사바토 Likely R 그대로다. 시장은 46¢ → <strong>55¢</strong>로 9¢ 뛰었다 — 이 표에서 이번 주 최대 상승폭이고, <strong>등급과 시장의 괴리가 감시 10주 중 가장 큰 주</strong>가 됐다.</p>
<p><strong>위스콘신은 검증을 통과했다.</strong> Marquette 로스쿨(8/12–20, RV 891, ±4.0)이 예선 후 첫 비당파 본선 조사를 냈고, 적극투표층 기준 크롤리 49 – 티파니 44로 당파 조사 2건(각 D+4)·RCP 평균 D+3.7~4.0과 정합했다. 다만 같은 조사의 <strong>등록유권자 기준은 44–44 동률</strong>이고 무당파의 3분의 1이 미결정이다. 프랭클린 소장 본인이 “소폭 우위든 완전 동률이든 둘 다 가능한 해석”이라고 했다 — 이 사이트도 그 이상으로 좁히지 않는다.</p>
<p><strong>아이오와</strong>에서는 Suffolk(8/20–23, LV 500)가 첫 비당파 실측으로 샌드 48 – 란 44를 냈고, 벨웨더인 머스커틴 카운티도 마진이 같았다. 트럼프 +13 주에서 민주가 4포인트 앞선 것이다. 여기서도 지난주 적었던 등급 표기 문제가 남는다 — 이 사이트가 종합하는 주정부 트랙 원문은 사바토를 <strong>Lean R</strong>로 적었지만 자동 취득 피드(8/26)는 <strong>Toss-up</strong>이다. Cook(Lean D)과 갈리는 유일한 주라는 사실은 같으나 교차 폭은 원문보다 한 눈금 좁고, 이 사이트는 피드값을 싣는다.</p>
<p><strong>오하이오는 이 표에서 가장 이상한 주다.</strong> 비당파 실측이 <strong>한 건도 없는데</strong> 예측시장만 액턴 쪽으로 뒤집혔다(52¢ → 57¢, Polymarket도 ~54). 방아쇠가 된 사건은 식별되지 않았다. 조사가 없는 곳에서 시장이 선행한 구도이므로, 첫 비당파 조사가 나오는 순간이 이 이동의 정합성을 판별하는 지점이 된다. 후보 구도 자체도 뒤집혀 있다 — 민주 액턴이 경찰노조 지지를 받고 ICE 협력을 지지하는 한편, 공화 라마스와미는 감시카메라 확대를 우려한다.</p>
<p><strong>애리조나</strong>는 방향이 만장일치인데 폭이 안 맞는 주다. 이번 주 확인된 홉스 우위 조사 5건이 전부 같은 방향이지만 마진은 <strong>D+1.5에서 D+15.2까지</strong> 벌어진다. 원인 후보는 적극투표층 스크린과 미결정 비중이고, 미결정을 세게 배분할수록 한 자릿수로 수렴한다. Cook의 Likely D 상향 압력은 유지되지만 한 자릿수 조사군의 존재가 지연 요인이다. 신규 HighGround(8/15–18, LV 400)는 DB에 넣었고, Veridus 경유로만 확인된 GrayHouse·NextGenP·Stealth 3건은 <strong>표본·원문 릴리스가 확인되지 않아 넣지 않았다.</strong></p>
<p>주의회 쪽에서는 지난주 기록이 정정됐다. <strong>8/18 펜실베이니아 하원 12구 특별선거를 이 사이트가 종합하는 트랙이 누락했다가 소급 확정했다</strong> — 1999년 이래 공화가 보유해 온 트럼프 +18 지역구에서 민주가 88~97표 차로 이겼고, <strong>스윙은 D+18.6</strong>이다. Dukes가 9월 선서하면 PA 하원은 민주 103–100이 된다. 누적 지표(MultiState 기준)는 2026년 경합 특별선거 42건, <strong>중위 스윙 D+10.4 · 투표율 가중 D+12.6 · 공화 플립 0건</strong>이다. 2018년에는 여름 들어 스윙이 D+17.9에서 D+2.0으로 식었는데, 8월의 D+18.6은 그 완화 패턴이 이번에는 오지 않았다는 증거 한 건이다. (<a href="https://alaskawatchman.com/2026/08/26/bronson-is-not-stepping-aside-in-bid-to-become-alaskas-next-governor/">Alaska Watchman(브론슨)</a> · <a href="https://www.wpr.org/news/governors-race-poll-tiffany-crowley-marquette">WPR(Marquette)</a> · <a href="https://iowacapitaldispatch.com/2026/08/26/new-poll-shows-tight-races-for-iowa-governor-u-s-senate-in-2026/">Iowa Capital Dispatch(Suffolk)</a> · <a href="https://www.veridus.com/post/in-focus-aug-28-2026">Veridus(애리조나)</a> · <a href="https://penncapital-star.com/election-2026/democrats-declare-victory-after-tight-special-election-in-trump18-state-house-district/">PA Capital-Star(HD-12)</a> · <a href="https://www.multistate.us/elections/special-elections-2026">MultiState</a>)</p>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>23주차(8/24~8/30) 거시 환경은 여당에 불리한 기조를 유지한 채, 변동성이 총량 지표에서 제도·정책 변수로 이동했다.</strong> 트럼프 순지지는 전 성인 −20~−24 / 투표가능층 −14~−16, 제너릭 밸럿은 독립 평균들이 D+6.0~6.7(LV 보정 D+8.1)에서 5주째 고착 — 대법원 우편투표 결정, 이란 제재 개시, 매파 잭슨홀, PCE 발표가 연달아 왔음에도 어느 것도 회랑을 깨지 못했다. 주간 최대 신규 악재는 워시 의장의 잭슨홀 매파 데뷔로, 9월 인상 확률이 약 57.5%까지 가격화되며 ‘11월 전 금리 완화’ 시나리오가 ‘선거 전 인상’ 리스크로 역전됐고, PCE 3.7% 고착·기대인플레 5.8%·사상 첫 ‘매일 $4 위 8월’ 휘발유가 생활비 프레임을 떠받친다. 반면 반증 방향으로는 유가 주간 −5.5%와 이란–오만 회랑 제안이라는 실재하는 디스인플레이션 경로가 처음 열렸고 BLS 벤치마크 수정도 −7.9만에 그쳐 노동시장 서사가 방어됐으며, 우편투표 규칙은 시행 시 민주당 투표 메커니즘에 불리한 구조 변수로 9/3 심리(현재는 TRO로 차단)에 걸려 있다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(중) — 전주 판정 유지, 확신도 보합(금리 인상 신규 악재와 유가 하락 완충의 상쇄).</strong> 트럼프의 “내가 투표용지에 있다” 전국화 선언은 이 환경 숫자가 그대로 각 지역구의 작동 프레임이 됨을 의미한다. (인용: <code>national_weekly/2026-08-30</code> §6-4)</p>
</blockquote>
<p>여기에 두 가지를 덧붙인다.</p>
<p>첫째, <strong>트럼프가 중간선거를 스스로 전국화했다.</strong> 사우스캐롤라이나 유세에서 “내가 투표용지에 있다고 생각하라”고 했다. 순지지 −20~−23의 대통령이 선거를 자신에 대한 신임투표로 규정하는 것은, 역사적으로 야당이 원하는 바로 그 프레임이다. 이 사이트가 감시하는 9개 주 전부에 D+6 환경을 이식하는 구도이고, 특히 조지아·미시간처럼 민주가 지켜야 하는 주에 우호적이다. 9/9–10 댈러스 ‘트럼팔루자’ 컨벤션이 그 다음 무대다.</p>
<p>둘째, <strong>그 반대 방향의 증거도 같은 주에 나왔다.</strong> 8/25 사우스캐롤라이나 결선에서 트럼프가 지지한 달린 그레이엄이 노먼을 약 52–48로 이겼다. 지난주 이 자리에서 “트럼프 지지 후보 예비선거 3주 9패”를 공화 기반 이완의 첫 행동 증거로 적었는데, 그 서사에 대한 직접 반증이다. 결선 직전 조사는 동률이었고 그레이엄에게는 “국가안보는 잘 모른다”는 실언과 현직 주지사의 상대 지지라는 악재가 있었다. 그런데 트럼프의 90분 유세와 MAGA Inc.의 마지막 날 82.7만 달러가 그것을 뒤집었다. <strong>닫힌 공화 유권자층 안에서 트럼프 지지는 여전히 작동한다</strong> — 지난주의 관찰을 이번 주 증거로 수정해 적는다. 같은 주 주지사 예선에서도 오클라호마의 트럼프 지지 후보 마제이가 약 2,020표(0.4%p) 차로 이겨, 지지 효과는 주지사 예선 기준 <strong>2승(FL·OK) 2패(MN·WY)</strong>가 됐다. ’연패 서사’로는 더 이상 단순화할 수 없다.</p>
</section>
<section id="상원-산수-등급이-안-움직이면-산수도-안-움직인다" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-등급이-안-움직이면-산수도-안-움직인다">상원 산수 — 등급이 안 움직이면 산수도 안 움직인다</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 무소속 3인 중 민주 코커스를 약속한 사람은 없다 — <strong>+4 산술에 우회로는 없다.</strong></p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 8/20·사바토 8/26 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .50 + IA .375</td>
<td><strong>+3.125석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td>GA .125 + MI .50 + NH .25</td>
<td><strong>−0.875석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.25석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>동일</td>
<td>+2.25석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td>등급 이동 0건(사바토 TX는 8/28 피드에 이미 반영)</td>
<td><strong>0.00석</strong></td>
</tr>
</tbody>
</table>
<p><strong>이번 주 이 표는 지난주와 소수점까지 같다.</strong> 8/24~8/30 사이에 일어난 상원 등급 이동은 사바토의 텍사스 한 건인데, 이 사이트의 자동 취득 피드가 8/28에 그것을 이미 반영해 지난주 값에 들어가 있었기 때문이다. 원문 트랙은 같은 이동을 이번 주에 계산해 넣어 <strong>+2.0 → +2.1~+2.2석</strong>으로 보고했다 — 값이 다른 게 아니라 <strong>같은 이동을 언제 반영했느냐가 다르다.</strong></p>
<p>산수가 정지해 있다는 사실보다 중요한 건 <strong>그 정지가 얼마나 얇은가</strong>다. 뉴햄프셔가 등급까지 Toss-up으로 밀리면 방어 손실이 0.875에서 1.125로 늘고, 순 기대의석은 <strong>+2.0 아래로</strong> 돌아간다. 즉 이번 달에 텍사스·아이오와·다시 텍사스로 세 번에 걸쳐 쌓은 개선분을, <strong>뉴햄프셔 한 곳의 등급 이동이 통째로 지울 수 있다.</strong> 이것이 이번 주의 구조 변화다 — 총량은 그대로인데 <strong>리스크의 무게중심이 ’탈환 미달’에서 ’수성 실패와 탈환 미달의 결합’으로 이동했다.</strong></p>
<p>네 종류의 숫자는 이번 주에 처음으로 서로에게 다가왔다.</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>48¢</strong></td>
<td>46¢</td>
<td>거래액 $333만·미결제 $167만. 가격은 확률의 근사일 뿐</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (DDHQ)</td>
<td><strong>48.0%</strong> (평균 의석 D 50 – R 50)</td>
<td>46.0%</td>
<td>모델 갱신 8/28. 50–50 의석은 부통령 캐스팅보트로 <strong>공화 다수</strong>를 뜻한다</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>54.3%</strong> (예상 의석 D 50.9 – R 49.1)</td>
<td>55.5%</td>
<td>Infogram 라이브 시계열 직접 취득(마지막 관측 8/30, 132점)</td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.25석</strong></td>
<td>+2.25석</td>
<td>서수적 등급을 확률로 환산 — 전국 환경이 들어갈 자리가 구조적으로 없다</td>
</tr>
</tbody>
</table>
<p>지난주 이 자리에서 “DDHQ와 시장이 46에서 만났고 그 반대편에 Race to the WH 55.5%가 홀로 서 있다”고 썼다. 이번 주에는 <strong>셋이 같이 움직였다</strong> — 시장 +2¢, DDHQ +2.0%p, RtWH −1.2%p.&nbsp;두 모델의 격차는 9.5%p에서 <strong>6.3%p</strong>로 좁혀졌고, 좁혀진 방식이 한쪽의 항복이 아니라 양쪽의 접근이다. 3주 만에 처음 있는 일이다.</p>
<p>그래도 판단은 지난주와 같다. <strong>평균 내지 말 것.</strong> 격차의 원인은 데이터가 아니라 가정이다 — 등급·시장은 각 주를 사실상 독립으로 보고, 여론조사 기반 모델은 전국 환경이 주별 결과를 함께 밀어 올린다고 본다. 6.3%p로 좁혀졌다는 건 그 가정 차이가 사라졌다는 뜻이 아니라, 이번 주의 재료(텍사스 상방 + 뉴햄프셔 하방)가 <strong>두 가정 아래에서 부호가 반대로 나왔다</strong>는 뜻일 가능성이 크다.</p>
</section>
<section id="텍사스와-뉴햄프셔-같은-주에-열린-두-개의-문" class="level2">
<h2 class="anchored" data-anchor-id="텍사스와-뉴햄프셔-같은-주에-열린-두-개의-문">텍사스와 뉴햄프셔 — 같은 주에 열린 두 개의 문</h2>
<p>이번 주 상원의 이야기는 한 문장으로 줄일 수 있다. <strong>리치 티어의 상방과 필수 사수 티어의 하방이 동시에 커졌다.</strong></p>
<p>텍사스 쪽부터. 등급 두 기관이 일치했고, 조사 두 건이 같은 방향이었고, 시장이 51¢로 반반을 넘었다. 하지만 이 사이트가 더 무겁게 보는 신호는 그 셋이 아니라 <strong>트럼프의 행동</strong>이다. 8/27 휴스턴에서 부부당 1만 달러짜리 RNC 모금행사를 직접 주재하고 “텍사스에서 많은 시간을 보내겠다”고 말한 것은, 1994년 이후 민주당이 주 전체 선거에서 이겨 본 적 없는 주의 방어에 <strong>전국 자원을 쓰겠다는 공개 인정</strong>이다. 광고비 합계는 이미 약 2억 달러이고 최종 4.4억 달러 전망이 나온다. 팩스턴이 폭스에 출연해 자신이 왜 뒤지는지를 해명하는 것도, 여당 후보로서는 이례적인 장면이다.</p>
<p>뉴햄프셔 쪽은 정반대다. UNH 시리즈가 1년에 걸쳐 8포인트 이동했고, 그 결과 민주당이 반드시 지켜야 하는 세 의석 중 세 번째가 측정 가능한 압박권에 들어왔다. 여기서 주의할 것은 <strong>이 주의 성격</strong>이다. 파파스와 수누누는 둘 다 이념적 극단을 피하는 후보라, 전국 환경이 개별 결과를 밀어 올리는 폭이 다른 감시주보다 작다. 세인트앤셀름 D+7이 UNH D−2를 반박하는 상황에서, 9/8 예비선거 직후에 나올 첫 본선 조사가 두 기관 중 어느 쪽이 이상치인지를 판정할 것이다.</p>
<p>이 두 문이 같은 주에 열렸다는 사실이 등급가중 산수가 0.00석 움직인 이유이기도 하다. <strong>산수는 이번 주에 상방과 하방을 둘 다 놓쳤다</strong> — 텍사스의 등급 이동은 이미 반영돼 있었고, 뉴햄프셔의 조사 악화는 등급에 아직 도달하지 않았기 때문이다. 등급가중 방식이 후행 지표라는 말의 구체적 의미가 이것이다.</p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (8/24~8/30).</strong> 주간 DB는 <strong>8행 추가(누적 144행)</strong>로 전주 24행에서 밀도가 3분의 1로 떨어졌다. 의회가 휴지기라 워싱턴 발화가 없었던 주다. 그런데 <strong>중심이 이동했다</strong> — 안보 3 · 산업 3 · 북한 2로, ’북한·안보 발화’에서 <strong>‘산업 집행’</strong>으로 무게가 옮겨갔고, 그것도 발표가 아니라 자본이 실제로 움직인 건들이다.</p>
<p>가장 중요한 것은 <strong>한미일 ’프리덤 에지 2026’의 확정</strong>이다. 미 태평양사령부가 8/26 준비를 확인했고 한국 합참이 8/28 <strong>9/7~11 제주 동·남방 국제수역</strong> 실시를 공식 발표했다(로이터는 9/9~11로 보도 — 1차 출처인 합참 공지를 따른다). 실시간 데이터 공유 확대·공중방어·의무후송·해상차단이 새로 들어갔고, 규모·범위는 “예년과 대체로 동일”이다. 지난주 이 자리에서 트럼프의 연합훈련 축소 지시를 다루며 남긴 질문이 “3자 트랙도 축소되는가”였는데, 답은 <strong>‘유지’</strong>로 나왔다. <strong>한미 양자 훈련 축소와 캠프 데이비드발 3자 제도화 트랙이 분리돼 있음이 공식화된 것</strong>이고, 9월 FY27 NDAA 조정회의에서 공화당이 “실무 동맹은 온전하다”는 논거로 쓸 수 있는 재료다.</p>
<p>산업 쪽에서는 <strong>SK하이닉스가 인디애나 웨스트라피엣에서 40억 달러 이상 규모의 HBM 패키징 공장을 착공했다</strong>(8/27). 클린룸 2028년 10월 가동, 차세대 HBM 양산 2029년 하반기, 직·간접 고용 약 7,000명이다. 러트닉 상무장관이 미국 내 메모리 생산 확대를 공개 요구한 바로 그 주의 첫 실물 착공이라는 점이 의미다 — <strong>한국 반도체 대미 투자가 발표에서 집행으로 넘어간 표지다.</strong> 조선 쪽에서는 한화가 미 방산·투자 자회사 유상증자(최대 2.99억 달러)와 오스탈USA(앨라배마 모빌) 인수를 검토하고 HD현대가 미 조선소 후보를 샌디에이고·텍사스만 2곳으로 압축하면서, MASGA가 단일 기업 파일에서 <strong>양강 경쟁 구도</strong>로 바뀌는 첫 관측이 나왔다(양사 딜 미확정).</p>
<p><strong>서울이 처음으로 조건 목록을 한 묶음으로 내놨다.</strong> 위성락 국가안보실장이 8/28 미국의 북미 대화 재개 노력을 지지하되 “실질적 비핵화 진전으로 이어져야” 하고 한국이 “배제되지 않아야” 한다고 밝히면서, 무역합의 대미투자·쿠팡 처우·안보협력·정보공유·전작권을 함께 거론했다. 트럼프는 8/16 훈련 축소 게시문을 시제만 바꿔 재게시하고 싱가포르·판문점 사진 3장을 올렸다 — <strong>신규 내용이 없다는 것 자체가 정보다.</strong> 양보 없이 정상회담 트랙을 공중에 띄워두는 메시지 규율이고, 11월 선전 APEC 계기 회동 관측과 정합한다.</p>
<p>여론 쪽 수치도 하나 기록해 둔다. 퓨리서치(8/24 발표, 조사 3/3~4/4)에서 <strong>한국인의 대미 비호감이 55%로 2003년 이후 처음 과반</strong>이 됐다(전년 39%). 호감은 45%로 2018년 80%에서 35%p 떨어졌고 “신뢰할 수 있는 파트너”는 57%(2022년 83%)다. 그런데 같은 조사에서 미국을 “가장 중요한 동맹”으로 꼽은 응답은 <strong>84%</strong>다. <strong>“동맹은 유지하되 미국은 불신”이라는 비대칭 구조</strong>가 2천억 달러 패키지·전작권 협상에서 서울의 국내 정치 제약으로 작동한다. 조사 시점이 8월 훈련 축소 국면 <strong>이전</strong>이라는 점에 유의해야 한다 — 이미 그 전에 과반이었다.</p>
<p><strong>선거 연계는 이번 주 0건이다.</strong> 상원·하원 감시 레이스 후보의 한국 관련 발언·표결이 7일 내내 없었고, SC 결선에도 한국 관련 쟁점은 없었다. CA-40 영 김(하원 외교위 인도·태평양 소위원장)의 훈련 축소 관련 입장은 <strong>이번 주에도 미확인</strong>이다. 지난주 관찰 과제로 남겨 둔 ‘두 번째 공화 상원 이탈’(틸리스 이후)도 미관측인데, 의회 발화가 아예 없던 주라 이것은 부재의 증거가 아니다. 9월 회기 복귀 후 재점검한다. 통상 항목이 0건인 것도 침묵이 아니라 <strong>시한 미이행의 기록</strong>이다 — 2천억 달러 1호 프로젝트와 섹션 301 과잉생산 판정이 모두 “8월 말” 시한을 넘겼다. (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>8/31(월) — 알래스카 인증·후보 사퇴 시한.</strong> 브론슨이 남으면 민주 2 대 공화 2의 RCV 본선이 확정된다. 등급(Likely R)과 시장(55¢)의 괴리가 이 시점 이후에도 유지되는지가 등급 기관들의 응답 여부를 재는 지표다.</li>
<li><strong>9/3(목) — 우편투표 예비금지명령 심리. 주간 최대 분수령.</strong> TRO가 연장되면 봉쇄가 유지되고 대법원 긴급 재상정으로 갈 공산이 크며, 기각되면 규칙이 투표용지 발송 시즌까지 가동된다. 우편투표 비중이 높은 토스업 지역구(PA-07/08/10 · WA-03 · IA-01/03 · AZ-01/06 · CO-08, 이제 FL-14 포함)의 투표 실무에 직결된다.</li>
<li><strong>9/4(금) — 8월 고용보고서 + 노스캐롤라이나 부재자 신청 개시.</strong> 고용지표의 성격이 바뀌었다는 점이 중요하다 — 이제 ’경기 판단’이 아니라 <strong>‘금리 인상 판단’</strong> 재료다. 같은 날 감시 9주 중 설득 기간이 가장 먼저 닫히기 시작한다.</li>
<li><strong>9/6 주간 — 메인 첫 토론.</strong> 잭슨의 수락 여부가 걸려 있고, <strong>스캔들 이후 첫 공개 조사</strong>가 나오는지를 병행 감시한다. 3주째 비어 있는 지도 최대 미확보 데이터다.</li>
<li><strong>9/8(화) — 세 개가 겹친다.</strong> <strong>뉴햄프셔 예비선거</strong>(본선 공식 개막 + UNH 대 세인트앤셀름의 판정) · <strong>캐나다 보복관세 발효</strong>(농기계·펄프 — 아이오와의 ‘관세→투표’ 채널 실전 개시) · 미주리 대법원 재획정 판결 시한.</li>
<li><strong>9/9–10 — 댈러스 ‘트럼팔루자’ 공화 중간선거 컨벤션.</strong> 텍사스 공중전에 대한 공화당의 응답과 트럼프 슈퍼팩의 가을 선매 투입 여부가 여기서 드러난다. 로브가 지목한 분기점이다.</li>
<li><strong>등급 감시 4건</strong> — Cook의 애리조나 주지사 Likely D 상향, Cook·사바토의 알래스카 주지사 응답, 사바토의 아이오와 주지사 응답, 그리고 <strong>Cook의 TX-15·NC-11</strong>(둘 다 3개 기관 중 Cook만 단독 홀드아웃).</li>
<li><strong>9/16 — FOMC.</strong> 약 57.5%까지 가격화된 인상 확률의 검증대. 선거 7주 전이다.</li>
<li><strong>한국 함의.</strong> 9/7~11 프리덤 에지 실시(직전 주가 평양 담화 창) · 9월 FY27 NDAA 조정회의 일정 특정(주한미군 28,500명 하한·전작권·해외 건조 군함 조항) · 2천억 달러 패키지 화상회의와 섹션 301 판정의 시한 경과분 · 영 김의 훈련 축소 관련 입장 확인 여부.</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 08/24~08/30 — 일간 35/35건, <strong>5개 트랙 전부 결손 없음</strong>). 환경 지표 — FiftyPlusOne·Silver Bulletin·RealClearPolling·USPollingData·Decision Desk HQ·Morning Consult·Washington Post/Ipsos·Rasmussen. 경제 — 워시 잭슨홀 기조연설·BEA(PCE)·컨퍼런스보드·미시간대·BLS 벤치마크 예비 수정·AAA. 상원 실측 — UNH 그래닛스테이트·세인트앤셀름 조사센터·Texas Public Opinion Research·UT/Texas Politics Project·Suffolk 대학·Susquehanna·AARP(파브리지오 워드/임팩트). 주지사 실측 — Marquette 로스쿨·Suffolk 대학·HighGround. 하원 실측 — 텍사스서던대 바버라 조던 센터. 상원·주지사 등급 — Cook(상원 8/20·주지사 8/27)·Sabato(8/26)·Inside Elections(8/6)·Fox(8/25) 270towin 재게시분 자동 취득(8/30 실행). 하원 등급 — Cook 8/25 보드 자동 취득(435개구 해독, 합계 435 검증). 예측시장 — Kalshi 공개 API 원가격(8/30, 상원 35/35·주지사 35/36 취득 — 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). <strong>취득 로그 기록: SENATENJS 시리즈 1건 조회 실패 — 결측이 아니라 ’못 받은 것’이므로 다음 실행에서 재시도한다(뉴저지는 감시 9주 밖).</strong> 외부 모델 — Decision Desk HQ(모델 갱신 8/28)·Race to the WH(라이브 시계열 마지막 관측 8/30). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. 다음 조사는 이 사이트 DB에 넣지 않고 서술로만 반영했다 — 조지아 오소프 +13(<strong>조사기관 미공개</strong>) · 애리조나 GrayHouse·NextGenP·Stealth(표본 또는 원문 릴리스 미확인) · 미시간 GBAO(실사 상세 미확인) · 텍사스 Slingshot Strategies(실사기간 미공개) · MI-07 HMP(조사기관·기간 미공개). 노스캐롤라이나 상원과 아이오와 주지사의 사바토 등급은 원문 트랙 기재와 자동 취득 피드가 어긋나며, 이 사이트는 피드값을 싣는다(본문 참조). 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>