<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="이번 주에는 예측·등급·자금 세 층이 처음으로 같은 방향을 가리켰다. 상원 등급은 세 칸 움직였고 전부 민주 쪽이었다 — Cook이 조지아를 Likely D로, 사바토가 미시간을 Leans D로, 아이오와를 Toss-up으로 옮겨 이 사이트의 등급가중 산수가 +2.125석에서 +2.5석이 됐다. 트럼프 순지지는 사상 최저(−22.4)로 내려갔고 제너릭 밸럿은 같은 날 사이클 최고(D+8.1, LV D+8.8)를 찍었다. 공화당 상원위원회는 조지아·노스캐롤라이나를 방어 명단에서 뺐다는 보도가 나왔다. 그런데 반대 방향의 실측도 정확히 급소에서 나왔다 — 메인에서 후보 확정 후 첫 콜린스 우위 고품질 조사가 나왔고, Kalshi 메인 가격은 한 주에 7센트 내렸다.">

<title>27주차 · 09/21~09/27 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-74ff1634fb01614563b1cf772d4ae389.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">27주차 · 09/21~09/27</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../legal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">선거 법·제도 분쟁 트래커</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trade-canada.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캐나다 무역전쟁과 상원 선거</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dsa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">민주당 내부 지형 — DSA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ne.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네브래스카 Nebraska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 Kansas</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">District Focus</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house/ny17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">NY-17 New York 17th — Lawler</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house/pa01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PA-01 Pennsylvania 1st — Fitzpatrick</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-cook이-14일-동결을-풀고-15건을-한꺼번에-옮겼다" id="toc-하원-cook이-14일-동결을-풀고-15건을-한꺼번에-옮겼다" class="nav-link" data-scroll-target="#하원-cook이-14일-동결을-풀고-15건을-한꺼번에-옮겼다">하원 — Cook이 14일 동결을 풀고 15건을 한꺼번에 옮겼다</a></li>
  <li><a href="#주지사-값은-멈췄는데-분포가-하방으로-기울었다" id="toc-주지사-값은-멈췄는데-분포가-하방으로-기울었다" class="nav-link" data-scroll-target="#주지사-값은-멈췄는데-분포가-하방으로-기울었다">주지사 — 값은 멈췄는데, 분포가 하방으로 기울었다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-세-칸-움직였고-세-칸-전부-위로" id="toc-상원-산수-세-칸-움직였고-세-칸-전부-위로" class="nav-link" data-scroll-target="#상원-산수-세-칸-움직였고-세-칸-전부-위로">상원 산수 — 세 칸 움직였고, 세 칸 전부 위로</a></li>
  <li><a href="#전주-관전-포인트-채점" id="toc-전주-관전-포인트-채점" class="nav-link" data-scroll-target="#전주-관전-포인트-채점">전주 관전 포인트 채점</a></li>
  <li><a href="#두-개의-숫자가-어긋난-곳-기록해-둘-불일치" id="toc-두-개의-숫자가-어긋난-곳-기록해-둘-불일치" class="nav-link" data-scroll-target="#두-개의-숫자가-어긋난-곳-기록해-둘-불일치">두 개의 숫자가 어긋난 곳 — 기록해 둘 불일치</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">27주차 · 09/21~09/27</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    이번 주에는 예측·등급·자금 세 층이 처음으로 같은 방향을 가리켰다. 상원 등급은 세 칸 움직였고 전부 민주 쪽이었다 — Cook이 조지아를 Likely D로, 사바토가 미시간을 Leans D로, 아이오와를 Toss-up으로 옮겨 이 사이트의 등급가중 산수가 +2.125석에서 +2.5석이 됐다. 트럼프 순지지는 사상 최저(−22.4)로 내려갔고 제너릭 밸럿은 같은 날 사이클 최고(D+8.1, LV D+8.8)를 찍었다. 공화당 상원위원회는 조지아·노스캐롤라이나를 방어 명단에서 뺐다는 보도가 나왔다. 그런데 반대 방향의 실측도 정확히 급소에서 나왔다 — 메인에서 후보 확정 후 첫 콜린스 우위 고품질 조사가 나왔고, Kalshi 메인 가격은 한 주에 7센트 내렸다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 9월 27일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 9/21~9/27 일간 브리핑 — 전국·상원·하원 각 7/7, 주정부 6/7(<strong>9/27 결손</strong> — 9/25 저녁 이후 주말 뉴스 창 미반영), Korea Watch 6/7(<strong>9/25 결손</strong> — 결손일의 타 트랙 [K] 유실 0건 확인). 뉴스 기준: 미 동부시간 9/26(토)까지. 선거일(11/3)까지 38일. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>상원 등급이 세 칸 움직였고, 세 칸 전부 민주 쪽이었다.</strong> 사바토가 9/22 <strong>미시간 Toss-up → Leans D · 아이오와 Leans R → Toss-up</strong>, Cook이 9/23 <strong>조지아 Lean D → Likely D</strong>. 공화 방향 이동은 0건이다. 전주에 뉴햄프셔 한 칸이 공화 쪽으로 움직여 +2.25석이 +2.125석으로 내려갔는데, 이번 주에 이 사이트의 등급가중 순 기대의석은 <strong>+2.5석</strong>으로 올라갔다. <strong>사수 3곳 중 2곳(GA·MI)이 토스업 위로 올라선 것은 이번 사이클 처음이다.</strong> 그래도 필요치 +4에는 모자란다.</li>
<li><strong>환경의 두 층위가 같은 날 극값을 찍었다.</strong> Silver Bulletin 기준 트럼프 순지지가 −19.5에서 <strong>−22.4로 양 임기 사상 최저</strong>를 새로 썼고, 같은 9/23에 제너릭 밸럿이 <strong>D+8.1(투표가능층 보정 D+8.8)로 사이클 최고</strong>를 재경신했다. 전주까지 “밸럿은 움직이는데 지지율은 바닥에서 멈췄다”던 괴리가 해소됐다. 동력은 9/17 이후 실사된 조사 다섯 건이다. 가장 무거운 수치는 총계보다 <strong>공화 지지층 안의 이완</strong>이다 — 공화 지지층의 트럼프 지지율이 1주 만에 <strong>82% → 73%</strong>(Reuters/Ipsos)로 떨어졌다.</li>
<li><strong>공화당 조직도 같은 지도를 그렸다.</strong> NRSC 팀 스콧 위원장이 9/23 비공개 회의에서 우선순위를 <strong>방어 5곳(ME·AK·OH·IA·TX) + 공격 2곳(MI·NH)</strong>으로 정하고 <strong>조지아·노스캐롤라이나를 뺐다</strong>는 보도가 나왔다(공개적으로는 “100% 가짜뉴스”라고 부인). 노스캐롤라이나에서는 공화 외곽단체가 10월 예약 650만 달러를 취소했다 — <strong>이번 사이클 첫 공화 자금 철수</strong>다. 광고 약정에서 공화가 민주보다 적게 쓰는 경합주는 조지아 하나뿐이다(두 데이터셋 교차 확인). 이 사이트가 매주 적어 온 “방어의 자백”이 이번 주에는 명단으로 나왔다.</li>
<li><strong>예측 층위에서는 범주가 바뀌었다.</strong> Silver Bulletin이 상원을 공식적으로 토스업이라 부르기를 멈췄다 — FLIPR Deluxe <strong>65%</strong>, 세 버전 63~69%로 자체 토스업 상한(60%)을 넘었다. 이 사이트가 직접 받는 값도 모두 올랐다 — <strong>Kalshi 62¢ · Race to the WH 70.7% · DDHQ 54.0%</strong>. <strong>그런데 FLIPR와 DDHQ의 예측 의석은 둘 다 정확히 51 D – 49 R이다.</strong> 확률이 얼마로 나오든 오차 여유가 0인 최소 과반에 대한 값이다.</li>
<li><strong>반증도 나왔고, 하필 급소에서 나왔다.</strong> 메인에서 <strong>NYT/시에나가 콜린스 49–46</strong>을 냈다. 후보 확정 이후 첫 콜린스 우위 고품질 조사다. 네이트 콘 본인은 이 결과를 “이례치”라고 평가했다. 같은 창의 UNH는 잭슨 +4였다. 같은 주 ProPublica는 콜린스 주변 FBI 수사가 트럼프 행정부의 수사조직 해체로 종결됐다고 보도했다. 보도 이후 실사된 조사는 아직 없다. <strong>Kalshi 메인은 67¢ → 60¢로 감시 9주 중 유일하게 크게 내렸다.</strong> 오하이오는 신규 조사 없이 평균이 브라운 +4로 압축됐다.</li>
<li><strong>하원은 Cook이 14일 동결을 풀면서 15건을 한꺼번에 민주 쪽으로 옮겼다.</strong> 토스업은 22석(D5/R17)이 됐고, 등급을 문자 그대로 읽은 기대의석이 이번 사이클 처음으로 과반(약 219석)을 넘었다. 전주에 이 사이트가 편입 1순위로 적은 TX-15와 역방향 감시였던 NJ-07이 한 회차에 예고대로 움직였다.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>트럼프 순지지도 — <strong>이번 주 최대 사건</strong></td>
<td><strong>−22.4</strong>(Silver Bulletin, 9/23 — 양 임기 사상 최저) · USPD <strong>−23</strong>(37/60, 9/25) · FiftyPlusOne <strong>−25.8</strong>(35.5/61.3, 9/23 확인) · 개별 최저 <strong>ARG −39</strong>(29/68)</td>
<td>9/23~9/25</td>
<td><strong>2주간 −19.5에 가격형성돼 있다던 판독이 기각됐다.</strong> 주간 −2.9p다. 동력은 9/17(연준 인상·유가 급등·언론 출입금지) 이후 실사된 조사 다섯 건이다 — Reuters/Ipsos <strong>32%</strong>(경력 최저) · ARG <strong>29%</strong>(1·2기 통틀어 첫 30% 미만) · CNN/SSRS <strong>33/67</strong> · Verasight <strong>33/63</strong> · Emerson <strong>39%</strong>. 다섯 건 모두 같은 방향을 가리켰다. 원천은 밴드 폭(−15~−39)의 대부분을 조사기관 편차가 아니라 <strong>실사 시점의 차이</strong>로 읽는다(9/17 이후를 담은 조사일수록 나쁘다). 1기 동기 약 −11.6·바이든 동기 약 −9.6 대비 열위가 <strong>6.5~8%p에서 약 11~13%p로</strong> 벌어졌다</td>
</tr>
<tr class="even">
<td>일반투표(제너릭) — 사이클 최고 재경신</td>
<td><strong>D+8.1</strong>(Silver Bulletin) · <strong>LV 보정 D+8.8</strong> · RCP D+8.1(50.4/42.3, 9/21) · USPD D+7.4(보합) · FPO 약 D+7</td>
<td>9/21~9/26</td>
<td><strong>지지율 사상 최저와 같은 날(9/23) 찍혔다.</strong> 경로는 9/1 D+6.7 → 9/17 D+7.5 → 9/23 D+8.1이고, 되돌림이 한 번도 없었다. 9/17 이후 실사 조사로 채워진 상단 — <strong>Marist RV D+12 · Verasight RV D+9 → LV D+10 → “확실히 투표” D+12 · CNN D+8 · Emerson 약 D+11~12.</strong> RCP의 D+8.6 → D+8.1은 NBC D+5 편입에 따른 산술 효과이고, 원천이 전주에 예고한 대로다</td>
</tr>
<tr class="odd">
<td><strong>LV 역전 — 4중 확인</strong></td>
<td>Silver 보정 +0.7 · Marquette +5 · Economist/YouGov LV D+12 · <strong>Verasight 계단(RV+9 → LV+10 → 확실+12)</strong></td>
<td>9/2~9/21</td>
<td>전주 3중 확인에 네 번째 독립 방법이 더해졌다. <strong>모집단을 좁힐수록 민주 마진이 커지는 계단이 한 조사 안에서 실측됐다.</strong> 보조 증거로 CNN 민주 성향 “매우 투표 의욕” +16p가 있다. 중간선거에서 LV 스크린은 보통 공화 쪽으로 기울었는데, <strong>네 기관·네 방법에서 이번 사이클은 반대다.</strong> 하단 앵커 <strong>NBC/하트+POS D+5</strong>는 실사가 9/11~15로 충격 이전이고, NBC도 “2018년 동시점 D+12”를 함께 적었다</td>
</tr>
<tr class="even">
<td><strong>공화 연합의 이완 — 3중 실측</strong></td>
<td>공화 지지층 지지 <strong>82 → 73%</strong>(Reuters/Ipsos, 1주) · 공화당 내 순지지 <strong>+54 → +43</strong>(Verasight, 1개월) · 공화당원 “강한 지지” <strong>35%</strong>(CNN — 2018년 동기 66%)</td>
<td>9/16~9/21</td>
<td>하락을 이끈 것은 무당층이 아니라 <strong>자기 연합</strong>이다. 행동 증거가 같은 주에 나왔다 — 접전지 공화 상원 후보 <strong>로저스(MI)·힌슨(IA)·허스티드(OH)</strong>가 조기 종전을 요구했고, <strong>RNC는 이를 처벌하지 않고 용인한다고 공언</strong>했다(“우리는 승리에 관심이 있다”). 1기 때의 충성 강요 방식과 대비되는 이 변화 자체가 환경 판독이다</td>
</tr>
<tr class="odd">
<td>“국민투표” 구조 — 30년래 최고</td>
<td>의회 투표 = 트럼프 <strong>반대 신호 43%</strong> vs 지지 신호 27%</td>
<td>NBC 9/11~15</td>
<td>NBC 계열 중간선거 직전 조사로는 <strong>30년래 최고</strong>다(2018년 38% — 민주 +41석의 해, 2022년 35%). Marist도 45 대 약 25로 같은 구조를 보였다. <strong>반대표는 도전 정당에 대한 호감을 요구하지 않는다</strong> — 민주당의 낮은 호감도가 방파제가 되지 못하는 이유다</td>
</tr>
<tr class="even">
<td>이슈 — 물가가 시리즈 최저</td>
<td>물가·생활비 <strong>−54</strong>(21/75) · 의료 −33 · 경제 −28 · 관세 −27 · AI −27 · 이민 −11</td>
<td>Verasight 9/16~21</td>
<td><strong>−54는 이 시리즈에서 전 이슈 통틀어 사상 최저다.</strong> 서베이 지표도 같은 신호를 냈다 — 미시간대 확정치 <strong>48.1</strong>(4개월 최저), <strong>1년 기대인플레이션 4.0 → 4.6%</strong>(6월 이후 최고). Marist에서는 휘발유·경제·외교·이민 네 항목 모두 “민주당이 더 잘할 것” 쪽이 우위였다</td>
</tr>
<tr class="odd">
<td>금리 — 두 번째 생활비 경로</td>
<td>10년물 <strong>5.11~5.14%</strong>(9/23, 2007년 이후 최고, 하루 +15bp) · 9월 플래시 PMI 종합 <strong>58.4</strong>, 투입비용 2022-10 이후 최고</td>
<td>9/23</td>
<td>성장과 비용이 동시에 과열인 조합이다. 바(Barr) 이사는 “추가 조정 필요 가능성”을 언급했다. 모기지·자동차·카드 금리가 <strong>수준 자체로 굳었다.</strong> 반대 재료도 있다 — 신규 실업수당 <strong>19.7만</strong>(7월 중순 이후 최저), 나스닥 9/21 사상 최고</td>
</tr>
<tr class="even">
<td>연료 — 원유와 주유소가 갈라졌다</td>
<td>브렌트 <strong>$100 하향 이탈</strong>(9/21) · 휘발유 <strong>$4.47~4.48 고원</strong> · 경유 <strong>$6.5050</strong>(9/20, AAA 시리즈 사상 최고 — 2022년 기록 경신) · 경합주 경유 MI 약 $6.88 · IA 약 $6.31</td>
<td>AAA·주간</td>
<td><strong>원유는 정점을 지났는데 주유소 가격은 따라 내려오지 않았다.</strong> 사우디 수출이 월 400만 b/d를 넘어 회복했다. 원천은 전가 시차를 2~3주로 보고, <strong>10/14 CPI는 완화가 아니라 고점을 잰다</strong>고 판단한다. 행정부의 90일 경유 수출 금지안은 상공회의소·비즈니스라운드테이블·정유업계의 공동 반대 서한만 낳은 채 결정되지 않았다</td>
</tr>
<tr class="odd">
<td>전쟁 — 열렸다가 대통령 손으로 닫혔다</td>
<td>9/22 유엔 <strong>위트코프·쿠슈너–아라그치 약 3시간 회담</strong>(개전 후 첫 구조화된 직접 접촉) → 이란 <strong>“7일 내 호르무즈 재개방”</strong> 제안 → <strong>9/26 트럼프 공개 거부</strong></td>
<td>9/22~9/26</td>
<td>트럼프는 유엔 연설에서 합의 시점을 <strong>“선거 직후”</strong>로 공언했다. 참모들에게는 <strong>중간선거 이후 폭격 재개</strong>를 예상한다고 말했다는 보도가 나왔다. 원천이 전주에 “최대 반전 경로”로 지목한 조기 종전이 이번 주에 실체를 갖췄다가 <strong>대통령의 결정으로 닫혔다.</strong> 전쟁 지속 지지 후보를 덜 지지한다는 응답은 57%다(NBC)</td>
</tr>
<tr class="even">
<td>제도·통상 — 종결 두 건, 완화 한 건</td>
<td>언론 출입금지 → 9/25(금) <strong>판사 명령으로 세 매체 복귀</strong> · 미주리 → 9/25 <strong>연방대법원 만장일치 2022년 지도</strong> · 미·중 → 휴전 <strong>2027-01-10까지 연장</strong>, “비민감” 품목 <strong>약 $300억 관세 인하</strong></td>
<td>9/21~9/26</td>
<td>출입금지 소송은 트럼프가 지명한 판사가 맡았고, <strong>NBC·ABC·CBS·FOX 4사가 대통령 일정 취재를 전면 중단</strong>하며 연대했다. 미주리는 공화당의 막판 ~1석 추가 시도가 최종 저지됐다(하원 절 참조). 미·중 합의는 <strong>행정부가 실현한 유일한 생활비 완화 카드</strong>이지만, 기존 관세율(<sub>30</sub>36%)이 유지돼 규모가 작다</td>
</tr>
</tbody>
</table>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p><strong>이번 주 상원 등급 이동은 3건이고, 셋 다 민주 쪽이다.</strong> 전주에는 1건(뉴햄프셔)이었고 그 1건이 공화 쪽이었다. 이번 주 표는 세 층으로 읽는다. 첫째, <strong>등급 열에서 조지아·미시간·아이오와가 움직였다.</strong> 그 결과 조지아는 Cook·Sabato가 처음으로 같은 칸(Likely D)에 섰고, 아이오와도 같은 칸(Toss-up)에 섰다. 둘째, <strong>시장 열은 방향이 갈렸다</strong> — MI +6¢ · NH +3¢ · TX +2¢ · IA +2¢ · NC +1¢ · OH +1¢ · GA +0.5¢, 하락은 AK −1¢, 그리고 <strong>메인 −7¢</strong>다. 상원 다수 계약은 59¢에서 <strong>62¢</strong>가 됐다. 셋째, 핵심 열에서 <strong>메인과 오하이오가 하방을 떠맡았다.</strong> 원천의 표현으로 남은 하방 경로는 “ME 축 + OH 압축 + NH 괴리”로 재편됐다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 9/23 / Sabato 9/22 / IE 9/17)</th>
<th>시장 (Kalshi 9/27)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td><strong>Likely D (9/23 ↑)</strong> / Likely D / Tilt D</td>
<td>94.1¢ (▲0.5)</td>
<td><strong>전주에 “리스크 신규 진입”으로 적은 항목이 한 주 만에 반대로 닫혔다.</strong> 등급·조사·자금 세 층이 같은 주에 같은 쪽을 가리켰다. Cook은 자금을 근거로 올렸다(오소프 현금 약 4,250만 대 콜린스 약 200만 달러 — “경쟁력을 갖출 시간도 돈도 없다”). <strong>YouGov 오소프 51–41</strong>(RV 3,447 — 시리즈 최대 격차)과 <strong>InsiderAdvantage +8</strong>이 이를 뒷받침했다. 공화가 민주보다 광고를 적게 쓰는 유일한 경합주이고, NRSC 명단에서도 빠졌다는 보도가 나왔다. 같은 YouGov 표본의 주지사 문항은 <strong>잭슨 45–44</strong>다. 판별 지표는 10/13 사전투표 전 SLF 증액 명단에 조지아가 들어가느냐다 (<strong>개선 확정</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / <strong>Lean D (9/22 ↑)</strong> / Toss-up</td>
<td><strong>72¢ (▲6)</strong></td>
<td><strong>전주 Bear 서사의 유일한 기제가 첫 시험에서 꺾였다.</strong> NRSC의 CAIR 기부자 공세(9/15) 이후 실사된 첫 조사인 <strong>Suffolk가 엘사예드 47–40</strong>(무당층 +16)을 냈고, 공세 효과는 보이지 않았다. 공화계 라스무센(9/22)도 +3이었다. 반대 재료는 <strong>공화 PAC이 의뢰한 Torchlight의 로저스 +1.3</strong> 한 건이다. 보수계 두 기관이 정반대를 가리켜, 미시간은 사수 3곳 중 데이터가 가장 엇갈리는 곳으로 남는다. 로저스는 9/21 <strong>조기 종전·경유 수출 금지·유류세 중단</strong>으로 입장을 틀었다(미시간 경유 사상 최고). 시장은 감시 9주 중 주간 최대로 올랐다 (<strong>개선·Bear 기제 1차 반증</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Toss-up / Lean D / Toss-up</td>
<td><strong>86¢ (▲3)</strong></td>
<td><strong>등급 대 조사의 괴리가 3주째 풀리지 않았고, 이번 주에는 양쪽 모두에 재료가 붙었다.</strong> 조사 쪽에서는 <strong>NYT/시에나가 파파스 49.8–44.8(+5)</strong>을 냈다. 경선 후 첫 비당파 고품질 조사다. 등급 쪽에서는 <strong>NRSC가 뉴햄프셔를 공격 목표 2곳 중 하나로 공식 지정</strong>했다. NRSC 의뢰 내부 조사는 수누누 37–36이다. <strong>전주 이 사이트가 판별 시험으로 지목한 Kalshi 가격은 83¢에서 86¢로 되돌아왔다</strong> — “계속 내려가면 전망기관이 빨랐던 것”이라는 가설은 이번 주에는 지지되지 않았다 (<strong>유지·시장 반등</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D / Tilt D</td>
<td>93.7¢ (▲1.0)</td>
<td><strong>이번 사이클 첫 공화 자금 철수가 여기서 나왔다.</strong> Old North Action이 10월 예약 <strong>650만 달러를 취소</strong>했다(잔여 1,450만). 트럼프 개스토니아 유세 6일 뒤라 유세가 자금 결정을 바꾸지 못했다는 뜻이다. NRSC 명단 제외 보도(공개 부인 병행)와 함께 <strong>협조지출 800만 달러</strong>가 계속된다 — “공개 부인 + 내부 후퇴 + 협조지출 지속”의 혼재 신호다. 공공기록 조사에서는 왯틀리가 헐린 “복구 총괄”을 맡은 1년간 복구 기관과 소통한 기록이 <strong>문자 6건·통화 5건(38분)</strong>으로 나왔다. 이번 주 보도된 High Point +8은 <strong>8월 초 실사</strong>라 새 추세가 아니다 (<strong>개선·닻 강화</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td><strong>60¢ (▼7)</strong></td>
<td><strong>이번 주 지도 최대 변동성의 진앙이다.</strong> NYT/시에나/프레스헤럴드 <strong>콜린스 49–46</strong>(9/15~22, LV 619)은 후보 확정 후 첫 콜린스 우위 고품질 조사다. 다만 <strong>네이트 콘 본인이 “이례치”라고 평가</strong>했다. 같은 창의 <strong>UNH는 잭슨 51–47</strong>, UMass로웰은 잭슨 +5였다. 세 조사가 콜린스 +3 ~ 잭슨 +5로 갈렸고, 갈린 원인은 콜린스 호감도 측정이다(NYT 51% 대 37~40%). 같은 주 <strong>ProPublica의 FBI 수사 종결 경위 보도</strong>가 콜린스 주장과 배치됐다(콜린스 “완전한 허위”). 보도 이후 실사된 조사는 아직 없다. NRSC는 메인을 방어 1순위에 올렸다 (<strong>혼조·시장 최대 하락</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss-up / Toss-up / Tilt R</td>
<td>71¢ (▼1)</td>
<td><strong>상반된 재료가 겹쳤는데 계기판은 움직이지 않았다.</strong> NYT가 전직 보좌관 9명을 인용해 펠톨라의 <strong>참모 처우 의혹</strong>을 보도했다(캠프 “과장·명백한 거짓”). 그런데 <strong>공화당 머카우스키 상원의원이 펠톨라를 공개 옹호</strong>했다. 자당 최대 격전지에서 상대 당 후보를 감싼 이례적 장면이다. Alaska Survey Research 자체 발표(펠톨라 우세, RCV 2라운드 약 50%)는 정확한 마진이 공개되지 않아 DB에 넣지 않았다. SLF 예약이 8개 주 중 최소(1,500만)인 공백은 트럼프 계열 신규 자금이 메운다 (<strong>혼조·시장 부동</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td>58¢ (▲1)</td>
<td><strong>핵심 4곳 중 유일하게 민주 쪽으로 나빠진 주다.</strong> 신규 조사는 없는데 <strong>RCP 평균이 브라운 +4로 압축</strong>됐다(8월 Fox +8 대비). 전주 “3억 달러 포화 광고 속에서 우위가 압축되느냐가 유일한 판별 지표”라고 적었는데, 첫 신호가 압축 쪽으로 나왔다. 다만 평균의 산술이라 단일 조사로 확인해야 한다. 광고는 <strong>3억 700만 달러</strong>로 사이클 최대가 확정됐다. 허스티드는 9/23 종전을 요구한 다음 날 <strong>9/24 전쟁권한 결의안(50–49 부결)에 반대표</strong>를 던졌다 (<strong>소폭 악화·미확인</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Toss-up / Toss-up / Lean R</td>
<td>61¢ (▲2)</td>
<td><strong>세 조사가 전부 탈라리코 쪽이다</strong> — Marist 50–44(RV) · TSU 47–46(LV 1,800 — 시리즈 최대 표본) · Mason-Dixon 46–43. TSU에서 공화당원의 팩스턴 지지는 <strong>84%</strong>이고, 팩스턴은 같은 투표용지의 애벗보다 약 3p 뒤진다. 자금: <strong>SLF가 텍사스를 1억 달러로 증액</strong>했고 공화 외곽은 총 1.4억 달러를 넘는다. 9월 광고가 약 5:1인데도 조사는 움직이지 않았다. 공화 내분도 공개됐다 — <strong>코닌이 텍사스를 “모금 블랙홀”, 팩스턴을 “게으르다”고 직격</strong>했다. 10월 예약장은 양당 모두 비어 있다 (<strong>개선·공화 재정 불안 공개화</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Toss-up / <strong>Toss-up (9/22 ↑)</strong> / Tilt R</td>
<td>43¢ (▲2)</td>
<td><strong>전주 “경합도 불명”이 민주 쪽으로 정리됐다.</strong> 10%p 측정 격차에 처음 들어온 비당파 다중모드 계기인 <strong>Marist가 투렉 50–42</strong>를 냈다. 같은 조사에서 트럼프 41/58, 주 단위 밸럿 D+5다. 다만 RV 발표이고, <strong>응답자 59%는 여전히 힌슨 승리를 예상한다</strong>(인식과 수치의 괴리). 사바토가 토스업으로 합류해 Cook과 같은 칸에 섰다. 힌슨은 9/21~25 <strong>“즉각적” 종전</strong>으로 선회했다(전쟁권한 결의안 6~7회 반대 이력 위에서). NRSC 방어 목록에 편입됐고 890만 달러 방어 메모가 나왔다 (<strong>개선·등급 이동</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 이 사이트 조사 DB(<code>senate_polls.csv</code>)에 들어간 본선 조사는 <strong>아홉 건</strong>이다. 일일 경로가 자동으로 넣은 다섯 건(IA Marist · TX TSU · GA YouGov · MI Suffolk · ME NYT/시에나)과 이번 주간 정리에서 원문 URL을 확인해 넣은 네 건(GA InsiderAdvantage · MI 라스무센 · MI Torchlight[공화 PAC 의뢰] · ME UNH)이다. <strong>원문 URL을 원천에서 확인하지 못한 조사는 넣지 않았다</strong> — NH NYT/시에나 파파스 +5와 TX Marist 탈라리코 +6은 기간·표본이 확인되지만 링크가 없어 서술로만 반영했다. NH NRSC 내부 조사(실사일 미확인)와 AK Alaska Survey Research(마진 미공개)도 넣지 않았다. ME UMass로웰(8/28~9/14)과 NC High Point(8/3~12)는 실사가 오래됐고 링크도 확인되지 않아 제외했다.</p>
</section>
<section id="하원-cook이-14일-동결을-풀고-15건을-한꺼번에-옮겼다" class="level2">
<h2 class="anchored" data-anchor-id="하원-cook이-14일-동결을-풀고-15건을-한꺼번에-옮겼다">하원 — Cook이 14일 동결을 풀고 15건을 한꺼번에 옮겼다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cook 토플라인 — <strong>사이클 최대 일괄 이동</strong></td>
<td>Solid D <strong>185</strong> / Likely D 12 / Lean D <strong>11</strong> / <strong>Toss Up 22 (D5 · R17)</strong> / Lean R <strong>10</strong> / Likely R <strong>19</strong> / Solid R <strong>176</strong> (9/25 보드, 자동 취득 — 합계 435 검증). <strong>15건 전부 민주 방향, 공화 방향 0건.</strong> 민주 우세 열(Solid+Likely+Lean D)은 206 → 208, 공화 우세 열은 208 → 205</td>
</tr>
<tr class="even">
<td>토스업 편입 3 · 이탈 2</td>
<td>편입 <strong>TX-15</strong>(델라크루즈 — 신지도 트럼프 +17.8) · <strong>NC-11</strong>(공석 — 볼컴 vs 에이거) · <strong>FL-22</strong>(신지도 공석, 후보군 원천 미확인) / 이탈(→Lean D) <strong>AZ-01</strong>(공석 — Cook “민주 최고 탈환 기회”) · <strong>NJ-07</strong>(킨 — 사바토 9/16 추종). <strong>전주 편입 1순위로 적은 TX-15와 역방향 감시 NJ-07이 한 회차에 예고대로 움직였다</strong></td>
</tr>
<tr class="odd">
<td>하위층 10건</td>
<td>Likely R → Lean R <strong>CO-05 · TX-35 · MT-01 · FL-27 · FL-13 · WI-01</strong> / Solid R → Likely R <strong>NV-02 · VA-05 · NY-21 · TX-09</strong>. TX-35는 텍사스 재획정 의석 가운데 두 번째로 경합권에 들어왔고, FL-13·FL-27은 플로리다 24-4 지도가 더 깎여 나가고 있다는 신호다</td>
</tr>
<tr class="even">
<td>잔존 괴리</td>
<td><strong>TX-34</strong>(곤잘레스·D): Cook Toss-up / 사바토 Lean D — <strong>마지막 남은 역방향 감시</strong>(Cook이 따라가면 토스업 21석·D4). <strong>MI-04·IA-02</strong>: 사바토 Toss-up인데 Cook은 Lean R. 사바토(9/16)·IE(9/17)는 이번 주 이동이 없다 — <strong>두 기관의 Cook 대응 회차가 다음 주 최대 등급 이벤트</strong>다</td>
</tr>
<tr class="odd">
<td>기대의석 — 문자적 해석이 처음으로 과반을 넘었다</td>
<td>문자적 등급 가중 <strong>약 219석</strong>(전주 216) · 모리스 경험 보정 <strong>약 227석</strong>(전주 224 — 9/18 공표 가중치를 새 분포에 적용한 원천 재계산) · Cook 공표 프레임 “민주 +5~15석” · IE “민주 +2~10석”(최보수)</td>
</tr>
<tr class="even">
<td>시장·모델</td>
<td><strong>Kalshi 91.6¢</strong>(9/27 이 사이트 직접 취득, 전주 91.2¢) · Polymarket 92~93% · <strong>DDHQ 72% · 평균 D 232</strong>(모델 갱신 9/25 — 45일 정체 끝에 61% → 70% → 72%) · FiftyPlusOne 98%·D 238(9/18 이월) · Smarter.Vote 71%·D 228. 주초 2차 출처에 돌던 “Kalshi 약 81%”는 원천이 9/24 직접 조회(90.4¢)로 반증했다 — <strong>“시장 간 12%p 괴리” 서사는 폐기</strong></td>
</tr>
<tr class="odd">
<td>미주리 — 종결</td>
<td>9/21 제8순회항소법원이 2025년 지도(7R–1D)를 되살렸으나 <strong>9/25 연방대법원이 만장일치(무서명·반대의견 없음)로 2022년 지도(6R–2D)를 명령</strong>했다. 클리버(MO-05)를 겨냥한 막판 ~1석 추가가 저지됐고, 민주당의 <strong>실질 필요 순증 ~+7이 조건부에서 확정</strong>으로 바뀌었다</td>
</tr>
<tr class="even">
<td>자금 — 크지만 방어적</td>
<td>NY-17 공화 예약 <strong>1,430만 vs 민주 210만(약 7:1)</strong> · CLF NY-17 단일 700만 · CLF 클리블랜드 490만(OH-07 방어) · HMP 첫 TV 245만(롤러·킨) · <strong>DCCC 공동 광고 800만/26개구 — 처음으로 공격이 방어보다 많다.</strong> 3,000만 달러를 넘는 3개구(FL-25·IA-01·NC-01)는 전부 트럼프 +9 이상 지형이고, 양당 유의미 예약 43개구 중 해리스 승리 지역구는 3곳뿐이다. 위원회는 NRCC가 앞선다(8월 현금 8,900만 vs 7,600만)</td>
</tr>
<tr class="odd">
<td>지역구 실측 — 전면 공백</td>
<td><strong>Tier-1 신규 독립 지역구 조사 0건.</strong> 새로 나온 것은 민주 성향 PPP NC-11 에이거 +3과 HMP 의뢰 NC-01 데이비스 +7뿐이고, 둘 다 스폰서·성향 연계다. 그 공백을 캠페인 행동이 메웠다 — <strong>골든(D-ME-02)이 롤러(R-NY-17)를 지지</strong>했고(9/21), 밀러-믹스·넌(IA)·배럿(MI)은 전쟁권한 찬성 표결로 트럼프와 거리를 뒀다</td>
</tr>
</tbody>
</table>
<p><strong>이번 주 하원의 사건은 Cook이 전주에 이 사이트가 걸어 둔 트리거를 전부, 최대 폭으로 당긴 것이다.</strong> 전주에는 “Cook이 처음 다시 움직일 때의 방향(TX-15·NC-11 편입이면 22석, NJ-07·TX-34 추종이면 20석)”을 등급 감시 항목으로 적었다. 결과는 둘 다였다 — TX-15·NC-11이 들어왔고 NJ-07이 나갔으며, FL-22가 더해져 22석이 됐다. 그리고 등급을 문자 그대로 읽어도 과반(218)을 넘는 첫 주가 됐다. <strong>전주까지 “문자적 해석은 과반 미달”이라는 최소주의적 하한이 버티고 있었는데, 이번 주 Cook 자신의 재조정으로 그 하한이 사라졌다.</strong></p>
<p><strong>그런데 그 모든 상향이 지역구 독립 조사가 한 건도 없는 주에 일어났다.</strong> Cook이 이동의 근거로 든 것도 상당 부분 자금·구조 데이터다. 가장 큰 표적인 NY-17에서는 공화가 광고 예약에서 7:1로 앞서고 있고, 민주당 현역 의원(골든)이 공화 후보를 지지했다. 위원회 현금도 NRCC가 앞선다. 공화가 개별 방어전에서 이길 자원과 포지션은 실재한다. <strong>가장 보수적인 모델(DDHQ 72%)과 시장(91~93%) 사이의 약 20%p 괴리도 그대로다.</strong> 원천은 중심 시나리오를 <strong>D 226~232석</strong>, 다수 확률 중심을 <strong>88~90%</strong>로 올렸고(전주 D 224<sub>230·85</sub>88%), 이 사이트도 같은 범위를 쓴다. 다음 판별 데이터는 9/28 NY-17 첫 토론 이후 나올 첫 조사다. (<a href="https://www.washingtonpost.com/elections/2026/09/25/cook-political-report-moves-15-house-races-into-democrats-favor/">WaPo/Cook 9/25</a> · <a href="https://www.axios.com/2026/09/25/house-republicans-majority-democrats-battleground">Axios</a> · <a href="https://missouriindependent.com/2026/09/25/us-supreme-court-again-blocks-missouris-gerrymandered-congressional-map/">Missouri Independent</a> · <a href="https://punchbowl.news/article/campaigns/house-map-mapped/">Punchbowl/AdImpact</a> · <a href="https://punchbowl.news/article/campaigns/dccc-coordinated-ad-buy/">DCCC 공동 광고</a> · <a href="https://votes.decisiondeskhq.com/forecast/2026/house">DDHQ</a>)</p>
</section>
<section id="주지사-값은-멈췄는데-분포가-하방으로-기울었다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-값은-멈췄는데-분포가-하방으로-기울었다">주지사 — 값은 멈췄는데, 분포가 하방으로 기울었다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (9/27)</th>
<th>전주(9/20)</th>
<th>등급 (Cook 9/18 / Sabato 9/22 / IE 9/17)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td>93.3¢</td>
<td>94.2¢</td>
<td>Solid D / Likely D / Solid D</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>92.9¢</td>
<td>90.8¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="odd">
<td>애리조나</td>
<td>89¢</td>
<td>88¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="even">
<td>위스콘신</td>
<td>83¢</td>
<td>84¢</td>
<td>Toss-up / Lean D / Toss-up</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>83¢</td>
<td>80¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="even">
<td><strong>알래스카</strong></td>
<td><strong>74¢</strong></td>
<td>82¢</td>
<td>Toss-up / Toss-up / Lean R</td>
</tr>
<tr class="odd">
<td><strong>오하이오</strong></td>
<td><strong>63¢</strong></td>
<td>57¢</td>
<td>Toss-up / <strong>Toss-up (9/22↑)</strong> / Tilt R</td>
</tr>
<tr class="even">
<td><strong>조지아</strong></td>
<td><strong>51¢</strong></td>
<td>56¢</td>
<td>Toss-up / Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td>46¢</td>
<td>47¢</td>
<td>Toss-up / <strong>Toss-up (9/22↑)</strong> / Tilt R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>26¢</td>
<td>30¢</td>
<td>Lean R / Lean R / Tilt R</td>
</tr>
</tbody>
</table>
<p><strong>조지아에서 전주에 걸어 둔 조건이 충족됐다.</strong> 전주 이 사이트의 조지아 주지사 레이스 요약에 “라스무센 잭슨 +3은 공화계 단독이라 하방 감시로만 두고, 비당파 재현이 나오면 하향 심사를 연다”고 적었다. 이번 주 대형 표본 <strong>YouGov(9/15~18, RV 3,447)가 잭슨 45–44(RV) / 47–44(LV)</strong>를 냈다. 의뢰 주체는 확인되지 않았다. 원천 주정부 트랙은 <strong>하향 심사를 공식 개시</strong>했다. 등급을 따르는 규약상 가중치는 .50으로 유지된다. <strong>같은 표본의 상원 문항은 오소프 51–41이다</strong> — 한 표본 안에서 11~14%p가 갈린 이번 사이클 최대의 분할투표 신호다. 토론 장부도 나빠졌다 — 9/22 11Alive 토론이 <strong>잭슨 거부로 취소</strong>됐고, 10/12 애틀랜타 프레스클럽도 주최 측이 “공식 거부”를 확인했다. 잭슨이 수락한 무대는 10/6 ANF 한 건이다. 시장은 56¢에서 <strong>51¢</strong>로 내려갔다.</p>
<p><strong>원천 트랙이 새로 판독한 자원배분 계통은 비대칭을 드러냈다.</strong> 공중전에서 공화가 앞서는 세 곳 — <strong>조지아 약 9.5:1</strong>(친잭슨 7,600만 대 바텀스+우군 800만 — 바텀스 캠프 자체 전통 TV 예약은 4만 2천 달러) · <strong>오하이오 약 7.4:1</strong>(펜실베이니아 억만장자 야스 1인의 V-PAC 3,000만+가 액턴 캠페인 전체 모금을 넘는다) · <strong>위스콘신 약 3:1</strong> — 은 <strong>셋 다 등급상 민주에 유리한 주</strong>다. 원천은 이 세 곳의 합산 노출(1.50석)이 기대 순증 전부(+1.000석)보다 크다고 계산했다. 다만 원천의 규칙은 <strong>“철수는 자신감이라는 단일 해석, 투입은 우세·열세 양쪽이 가능한 양의적 신호”</strong>다. 그래서 공화 투입이 우세의 증거인지 열세 만회의 증거인지는 아직 가를 수 없고, 가중치 변경 근거로도 쓰지 않는다. 반대편 계통도 단단하다 — <strong>아이오와 28.8:1</strong>(본선 진입 보유현금 샌드 1,830만 대 란 63만 달러 — 전주 이 사이트가 “원문 대조 전까지 사실로 쓰지 않는다”고 적었던 수치가 실증됐다)이고, 메인은 신규 비당파 <strong>NYT/시에나 핀그리 48–찰스 36–베넷 8(D+12)</strong>로 정렬이 다시 확인됐다.</p>
<p><strong>알래스카는 한 주에 세 번 모습을 바꿨고, 시장은 82¢에서 74¢로 내려갔다.</strong> ① AARP 결과 페이지에서 <strong>순위선택 결선 시뮬레이션 JKT 55–윌슨 45(D+10)</strong>가 소급 확보됐다. ② 조사 실무자가 “그 값은 <strong>미결정 18%를 뺀 결정층 기준</strong>이고, 미결정층은 <strong>트럼프 +30%p 이상 우편향</strong>”이라고 유보했다. ③ 공화 후보 브론슨·테일러는 “윌슨 배제” 공조 광고를 사흘 만에 <strong>“공화 3인 전부 랭크(JKT 제외)”로 뒤집었다.</strong> 원천의 최종 서술은 “결선 D+10(결정층 기준)·미결정 R 편향·방향 불확정”이다. <strong>10/4 후보 등록 마감이 구도를 바꿀 수 있는 유일한 기한</strong>이라는 판단은 그대로다.</p>
<p><strong>그리고 이 사이트의 피드는 원천이 기록하지 않은 이동 두 건을 보여준다.</strong> 사바토 주지사 스탬프가 9/3에서 9/22로 바뀌면서 <strong>오하이오 Lean R → Toss-up · 네바다 Lean R → Toss-up</strong>(감시 밖 플로리다·텍사스 Likely R → Lean R)이 잡혔다. 같은 날 사바토 상원 기사의 제목(“other key statewide races to Toss-up”)과도 맞아떨어진다. 원천은 이번 주 사바토 주지사 이동을 0건으로 적었고, 9/26 일일은 사바토 로그 접근 오류를 명기했다. 이 사이트는 피드를 따르고, 같은 방식의 순증 산수는 원천 <strong>+1.000석</strong> 대 피드 기준 <strong>+1.125석</strong>이 된다(차이는 오하이오 한 칸). <strong>FOMC(9/16) 이후 위스콘신·미시간·네바다 조사는 주간 종료 기준 11일째 0건</strong>이다 — 환경이 주지사 레이스로 얼마나 전달되는지를 재는 핵심 시험이 2주째 시작도 못 했다. (<a href="https://www.atlantanewsfirst.com/2026/09/23/new-poll-ossoff-holds-double-digit-lead-over-collins-governors-race-dead-heat/">ANF/YouGov</a> · <a href="https://www.fox5atlanta.com/news/georgia-gubernatorial-debate-canceled-jackson-declines-face-bottoms">FOX 5 Atlanta</a> · <a href="https://www.ajc.com/politics/2026/09/can-keisha-lance-bottoms-withstand-rick-jacksons-spending-blitz-in-georgia/">AJC(자금)</a> · <a href="https://signalohio.org/billionaire-jeff-yass-ohio-governor-race-november-election-2026/">Signal Ohio(야스)</a> · <a href="https://iowacapitaldispatch.com/2026/07/20/sand-breaks-iowa-fundraising-record-lahn-receives-large-party-pac-donations/">Iowa Capital Dispatch(28.8:1)</a> · <a href="https://www.pressherald.com/2026/09/25/hannah-pingree-continues-to-hold-a-big-lead-in-new-poll-of-maine-governors-race/">Press Herald(ME)</a> · <a href="https://alaskapublic.org/news/politics/elections/2026-09-22/poll-shows-democrat-with-lead-in-alaska-governors-race-but-large-swaths-remain-undecided">Alaska Public Media</a> · <a href="https://alaskawatchman.com/2026/09/25/2-republican-gubernatorial-hopefuls-urge-alaskans-to-rank-all-3-gop-candidates/">Alaska Watchman</a>)</p>
<hr>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>27주차(9/21~9/27) 거시 환경은 ’바닥이 무너진 주간’이었다 — 2주간 −19.5에 가격형성돼 있던 트럼프 순지지율이 9/17 이후 실사된 조사 다섯 건(Reuters/Ipsos 32%·ARG 29%·CNN 33%·Verasight 33%·Emerson 39%)의 연쇄 착지로 Silver Bulletin 기준 −22.4까지 밀려 양 임기 사상 최저를 새로 썼고, 같은 날 제너릭 밸럿은 D+8.1(투표가능층 보정 D+8.8)로 사이클 최고점을 재경신하며 두 층위가 처음으로 동시에 여당 반대 방향의 극값을 기록했다.</strong> 하락의 기제는 무당층이 아니라 자기 연합이다 — 공화당 지지층 지지율이 1주 만에 82%에서 73%로, 월간 순 +54에서 +43으로 이완됐고, 접전지 상원 후보들(로저스·힌슨)의 조기 종전·유류세 면제 요구와 RNC의 공개 용인(“우리는 승리에 관심이 있다”)이 그 수치를 행동으로 확인했으며, 물가 이슈 순지지 −54(사상 최저)·10년물 5.1%(19년 최고)·경유 사상 최고 $6.5050·기대인플레이션 4.6% 급등이 생활비 압박의 하중을 떠받쳤다. 반증 재료도 실재했다 — 원유는 사우디 수출 회복으로 $100선을 하향 이탈해 급등 정점을 지났고, 미·중 정상회담은 휴전 연장과 $300억 관세 인하라는 유일한 완화 카드를 실현했으며, 유엔에서 개전 후 첫 미·이란 직접 회담과 이란의 “7일 내 호르무즈 재개방” 제안까지 나왔다 — 그러나 토요일 트럼프가 그 제안을 공개 거부하고 “선거 후 합의·선거 후 폭격 재개”의 시계를 두 번 공언하면서, 최대 반전 경로였던 조기 종전을 대통령 스스로 닫았고 어떤 유가 완화도 선거 전 마지막 물가 지표인 10/14 CPI에는 늦는다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(강) — 전주 판정 유지, 확신도 추가 상승(확신의 대상이 ’방향·수준 D+8 부근, LV 기준 상회’에 더해 ’기제: 지지율-밸럿 동시 이동과 공화 연합 내부 이완’까지 확장). 직전 주 대비 변화 방향: 지지율 층위가 사상 최저로 추가 악화되며 전주의 밸럿 이동을 추인했고, 남은 반전 경로는 원유 정점 통과분의 10월 중순 주유소 도달뿐이나 그 강도는 경유 신기록·전가 시차·전쟁 지속 결정으로 제약된다.</strong> (인용: <code>national_weekly/2026-09-27</code> §6)</p>
</blockquote>
<p>여기에 세 가지를 덧붙인다.</p>
<p>첫째, <strong>전주에 이 사이트가 걸어 둔 검증이 이번 주에 끝났다.</strong> 전주에는 “이번 주 조사 대부분이 인상 전후의 경계에 걸쳐 있고, 인상과 유가 최고가가 완전히 반영된 첫 조사는 다음 주부터 나온다”고 적었다. 그리고 “다음 주 조사가 더 좋게 나오면 그것은 새 정보이지 잡음이 아니다”라고 덧붙였다. 결과는 여당 쪽에서 봤을 때 더 나빴다. 9/17 이후 구간을 담은 지지율 조사 다섯 건이 모두 아래로 착지했고, 같은 구간을 처음 담은 밸럿 조사(Verasight·Emerson)는 D+9~12로 상단에 붙었다. <strong>원천의 표현을 빌리면 “필드 날짜가 하우스 이펙트를 이겼다.”</strong> 이번 주 밴드 폭이 넓었던 이유는 기관 차이보다 실사 시점 차이다.</p>
<p>둘째, <strong>이번 주의 새 정보는 수준보다 기제다.</strong> 지지율이 2.9p 빠진 것보다 공화 지지층 지지율이 9p 빠진 것이 더 무겁다. 대통령에 대한 자당 지지는 여론조사에서 가장 안정적인 수치로 꼽힌다. 그 수치가 흔들리자 곧바로 행동이 따라왔다 — 미시간·아이오와·오하이오의 공화 상원 후보가 대통령의 간판 정책(전쟁)에서 이탈했고, 당은 이를 막지 않았다. <strong>후보와 당 기관은 공개 조사보다 좋은 내부 데이터를 본다.</strong> 그들이 이렇게 움직였다는 것은 공개 조사가 재는 연합 이완을 당이 스스로 확인했다는 뜻이다.</p>
<p>셋째, <strong>반증 재료는 “원유 정점 통과”에 몰려 있다. 이것은 방향이 맞는 반증이지만 도착 시점이 늦다.</strong> 브렌트가 100달러 밑으로 내려갔고 사우디 수출이 회복됐다. 원천의 가장 무거운 반증이 이것이다. 하지만 주유소 가격은 따라오지 않았고, 경유는 오히려 사상 최고를 찍었다. 전가 시차 2~3주를 감안하면 완화가 체감되는 시점은 10월 중순이다. 선거 전 마지막 물가 지표인 10/14 CPI가 담는 것은 9월이다. 그리고 완화의 가장 큰 경로였던 조기 종전은 대통령이 스스로 닫았다. <strong>남은 38일에서 이 반증이 작동할 창은 좁다.</strong></p>
</section>
<section id="상원-산수-세-칸-움직였고-세-칸-전부-위로" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-세-칸-움직였고-세-칸-전부-위로">상원 산수 — 세 칸 움직였고, 세 칸 전부 위로</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 50–50은 밴스 부통령의 캐스팅보트로 공화 다수이므로 부족하다. <strong>NRSC가 이번 주 그린 자체 지도(방어 ME·AK·OH·IA·TX / 공격 MI·NH)가 이 사이트의 감시 9주와 같은 구조다</strong> — 사수 3곳 + 핵심 탈환 4곳(NC·ME·AK·OH를 모두 가져가면 정확히 +4) + 확장 2곳.</p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 9/23·사바토 9/22 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .50 + <strong>IA .50</strong></td>
<td><strong>+3.25석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td><strong>GA 0</strong> + <strong>MI .375</strong> + NH .375</td>
<td><strong>−0.75석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.5석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>탈환 3.125(IA .375) − 방어 1.00(GA .125 · MI .50 · NH .375)</td>
<td>+2.125석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td><strong>Cook GA Likely D(손실 −.125) · 사바토 MI Leans D(손실 −.125) · 사바토 IA Toss-up(탈환 +.125)</strong></td>
<td><strong>+0.375석</strong></td>
</tr>
</tbody>
</table>
<p><strong>세 이동의 방향이 같다.</strong> 이번 주 이동은 사수 라인(GA·MI)과 확장주(IA)에서 나왔다. <strong>메인·오하이오·뉴햄프셔 등급은 한 칸도 움직이지 않았는데, 이번 주 하방 신호는 바로 이 세 곳에서 나왔다.</strong> 산수가 오른 주에 위험의 위치도 바뀐 것이다.</p>
<p><strong>원천 상원 브리핑은 같은 방식으로 +2.4석을 적는다.</strong> 차이는 이번에도 사바토 뉴햄프셔 한 칸이다. 원천은 사바토 NH를 Toss-up(.50)으로 보고, 이 사이트가 받는 피드는 <strong>Lean D(.25)</strong>다. 전주에는 피드의 사바토 스탬프가 8/26자에 멈춰 있어 “둘 중 하나는 틀렸다”고만 적었다. <strong>이번 주에는 피드 스탬프가 9/22로 갱신됐고, 같은 회차에 미시간·아이오와가 바뀌었는데도 뉴햄프셔는 Lean D 그대로다.</strong> 이 사이트는 피드를 따른다. 결론(+4 미달)은 어느 쪽이든 같다.</p>
<p>네 종류의 숫자는 이번 주 <strong>넷 다 올랐다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>62¢</strong></td>
<td>59¢</td>
<td>거래액 $479만·미결제 $230만. 2주 연속 상승이고, 5주 동안 48~49¢에 머물던 값이 2주 사이 13센트 올랐다. 원천이 기록한 9/22 Polymarket은 65%다</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (Decision Desk HQ)</td>
<td><strong>54.0%</strong> (평균 의석 D 51 – R 49)</td>
<td>52.0%</td>
<td>모델 갱신 9/25. 2주 연속 상승인데 <strong>평균 의석은 3주째 D 51이다</strong> — 확률만 오르고 의석은 그대로다. 원천은 DDHQ를 “4주체 중 이상치”로 분류한다(Piper Sandler 45%와 함께 하단)</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>70.7%</strong> (예상 의석 D 52.4 – R 47.6)</td>
<td>68.7%</td>
<td>Infogram 라이브 시계열 직접 취득(마지막 관측 9/27, 139점). 3주 연속 상승. <strong>이번 주에는 Silver Bulletin FLIPR Deluxe 65%(세 버전 63~69%)도 같은 구간에 들어와 혼자 높은 모델이 아니게 됐다</strong></td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.5석</strong></td>
<td>+2.125석</td>
<td>서수적 등급을 확률로 환산한 값이라 전국 환경이 들어갈 자리가 구조적으로 없다. <strong>이번 주에는 등급 자체가 환경 쪽으로 움직였다</strong></td>
</tr>
</tbody>
</table>
<p><strong>순서는 전주와 같다 — 54 &lt; 62 &lt; 70.7.</strong> 시장이 두 모델 사이에 앉아 있고, 두 모델의 격차는 16.7%p로 전주와 똑같다. 새로 달라진 점은 전문가와 모델이 공개적으로 부딪쳤다는 것이다. 실버는 9/20 포스트(“전문가 등급이 블루웨이브 징후를 무시하고 있다”)에서 Cook의 토스업 7곳을 직접 겨냥했다. 그리고 사흘 안에 사바토와 Cook이 민주 쪽으로 움직였다. 다만 움직인 곳은 실버가 특히 지목한 뉴햄프셔가 아니었다. 실버의 핵심 논거는 벤치마크다. 2차대전 후 캘리브레이션 기준으로 현재 지지율·양극화에서 기대되는 밸럿이 <strong>D+8.7</strong>이고, 실측 LV는 <strong>D+8.6</strong>이다. <strong>“지금 환경은 과열이 아니라 역사가 예측하는 값”이라는 주장이고, 이는 “9월 수치는 되돌아온다”는 축소 논거를 겨냥한다.</strong></p>
<p><strong>그래도 평균 내지 말 것이라는 규칙은 그대로다.</strong> 이번 주 가장 중요한 숫자는 확률이 아니라 의석이다 — <strong>FLIPR와 DDHQ가 확률에서는 11%p 갈리는데 예측 의석은 둘 다 정확히 51 D – 49 R이다.</strong> 두 모델이 같은 데이터를 먹고 같은 의석에 도달한 뒤, 그 의석이 지켜질 확률에서만 다른 가정을 쓴다는 뜻이다. <strong>65%든 54%든 여유가 0인 최소 과반에 대한 확률이다.</strong> 원천의 등급 산술 기준 탈환 확률 <strong>35~45%(중심 40 안팎, 전주 30~40%)</strong>와 모델 상단 65%의 약 25p 격차도 같은 이유로 생긴다 — 등급 산술은 토스업 7곳이 한 방향으로 함께 넘어갈 상관 리스크를 반영하지 못한다. 실제 불확실성은 그 사이 어딘가다.</p>
</section>
<section id="전주-관전-포인트-채점" class="level2">
<h2 class="anchored" data-anchor-id="전주-관전-포인트-채점">전주 관전 포인트 채점</h2>
<p><strong>전주에 이 사이트가 적어 둔 관전 포인트가 이번 주에 어떻게 풀렸는지 기록해 둔다.</strong> 맞힌 것과 틀린 것을 같이 적어야 다음 주의 예고도 읽을 가치가 있다.</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>전주 관전 포인트</th>
<th>결과</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>9/22 트럼프–걸프 회담 — 조기 종전 갈래</strong></td>
<td><strong>열렸다가 닫혔다.</strong> 걸프 정상회담 자체의 결과는 원천에 따로 기재되지 않았다. 같은 날 유엔에서 첫 미·이란 직접 회담이 열렸고 이란이 “7일 내 재개방”을 제안했으나, 9/26 트럼프가 공개 거부했다. “10/14 CPI에는 늦는다”는 전주 판단은 그대로 유효하다</td>
</tr>
<tr class="even">
<td>9/22 텍사스 토론 D-데이</td>
<td><strong>원천 주간에 결과가 기록되지 않았다(미확인).</strong> 같은 주 SLF가 텍사스를 1억 달러로 증액했다</td>
</tr>
<tr class="odd">
<td>9/22 한국 3,500억 달러 패키지 국회 보고</td>
<td><strong>열렸다.</strong> 1호 사업이 텍사스 엔시널로 확정 보고됐다(Korea Watch 박스)</td>
</tr>
<tr class="even">
<td>9/22 조지아 주지사 토론 — 바텀스 두 번째 단독 무대 여부</td>
<td><strong>토론 자체가 취소됐다</strong>(잭슨 거부). 단독 무대도 성립하지 않았다</td>
</tr>
<tr class="odd">
<td><strong>뉴햄프셔 — Kalshi 가격이 계속 내려가는지</strong></td>
<td><strong>아니었다.</strong> 83¢ → 86¢로 되돌아왔고, NYT/시에나가 파파스 +5를 냈다. 등급 대 조사의 괴리는 풀리지 않은 채 4주차로 넘어간다</td>
</tr>
<tr class="even">
<td><strong>메인 — Quantus 콜린스 +0.7이 단독 이탈값인지 추세 전환인지</strong></td>
<td><strong>판정 보류, 긴장은 커졌다.</strong> NYT/시에나 콜린스 +3이 두 번째 콜린스 방향 계기가 됐지만, 같은 창의 UNH는 잭슨 +4였고 콘 본인이 “이례치”라고 했다. 시장은 −7¢</td>
</tr>
<tr class="odd">
<td>9/24 켐프+튠 콜린스 모금</td>
<td><strong>예정대로 열렸다.</strong> 그런데 같은 주 Cook이 조지아를 Likely D로 올렸다</td>
</tr>
<tr class="even">
<td><strong>오하이오 — 포화 광고 속 브라운 우위 압축 여부</strong></td>
<td><strong>평균이 +4로 압축됐다.</strong> 첫 신호가 압축 쪽으로 나왔지만 신규 실사가 아닌 평균 산술이라 확인이 필요하다</td>
</tr>
<tr class="odd">
<td><strong>등급 감시 — Cook이 MI·NC를 민주 쪽으로 옮기는지(대칭성 시험)</strong></td>
<td><strong>절반 적중.</strong> Cook은 MI·NC가 아니라 조지아를 올렸고, 미시간은 사바토가 올렸다. 방향 대칭성은 확인됐다 — 전주 공화 1건, 이번 주 민주 3건</td>
</tr>
<tr class="even">
<td><strong>Cook 하원 첫 재가동 방향(TX-15·NC-11 편입 22석 / NJ-07·TX-34 추종 20석)</strong></td>
<td><strong>둘 다였다.</strong> TX-15·NC-11·FL-22 편입과 NJ-07·AZ-01 이탈이 동시에 일어나 22석이 됐다</td>
</tr>
<tr class="odd">
<td>사바토 상원 스탬프 갱신 여부</td>
<td><strong>갱신됐다(8/26 → 9/22).</strong> 그런데 원천이 적은 뉴햄프셔 Toss-up은 피드에 나타나지 않았다</td>
</tr>
</tbody>
</table>
</section>
<section id="두-개의-숫자가-어긋난-곳-기록해-둘-불일치" class="level2">
<h2 class="anchored" data-anchor-id="두-개의-숫자가-어긋난-곳-기록해-둘-불일치">두 개의 숫자가 어긋난 곳 — 기록해 둘 불일치</h2>
<p><strong>첫째, 원천이 【수집 필요】로 남긴 항목 하나를 이 사이트 피드가 풀었다.</strong> 원천은 Cook의 9/23 상원 이동을 보도상 “3개 레이스”로 적고, 조지아 외 2건을 특정하지 못했다. <strong>이 사이트가 받은 Cook 9/23 피드를 전주 피드와 대조하면 나머지 두 건은 사우스캐롤라이나(Solid R → Likely R)와 캔자스(Likely R → Lean R)다.</strong> 둘 다 감시 9주 밖이고 둘 다 민주 방향이다. 캔자스는 사바토도 같은 날 Likely R → Leans R로 옮겼으므로, 원천이 “콘/실버의 ‘11p 스윙이면 레드월이 뚫린다’ 프레임이 등급에 처음 착지한 지점”이라고 쓴 이동이 두 기관에서 동시에 확인된 셈이다. 사우스캐롤라이나에 대해서는 원천도 DDHQ가 Lean R(74%)로 본다고 기록했었다.</p>
<p><strong>둘째, 사바토 뉴햄프셔(상원)다.</strong> 위 산수 절에 적었다. 원천은 Toss-up, 9/22자 피드는 Lean D다. 원천은 알래스카를 사바토 “Tilt R”로도 적는데, <strong>사바토는 Tilt 등급을 쓰지 않는다</strong>(Tilt는 Inside Elections·RaceToTheWH·Kalshi 계열이 쓴다). 피드상 사바토 알래스카는 Toss-up이다.</p>
<p><strong>셋째, 사바토 주지사 두 건이다.</strong> 위 주지사 절에 적었다 — 원천은 이번 주 사바토 주지사 이동을 0건으로 적지만, 피드는 9/22자로 오하이오·네바다를 Toss-up으로 보여준다. 원천 표는 사바토 네바다를 이미 Toss-up, 애리조나를 Likely D, 메인을 Lean D로 적는다. 이 사이트 피드는 애리조나 <strong>Lean D</strong>, 메인 <strong>Likely D</strong>다. 두 칸의 차이는 순증 산수에서 서로 상쇄되지만(.875+.875 대 .75+1.0), 원천과 피드가 사바토 주지사 표를 서로 다르게 읽고 있다는 사실은 남는다. 이 사이트는 피드를 따른다.</p>
<p><strong>넷째, 시장·모델의 시점 차이다.</strong> 원천은 Kalshi 상원 다수를 <strong>61%(9/22)</strong>, DDHQ를 <strong>52%(9/21)</strong>로 적는다. 이 사이트가 직접 받은 값은 <strong>62.0¢(9/27)</strong>, <strong>54.0%(모델 갱신 9/25)</strong>다. 둘 다 시점 차이로 설명되는 폭이고 방향도 같다. <strong>이 사이트는 직접 취득한 원가격·원값만 싣는다.</strong></p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (9/21~9/27).</strong> 주간 DB는 <strong>13건 추가</strong>(총 210행)로 5주 만에 처음 줄었다(8→15→17→21→13). 원천은 이것을 신호가 사라진 것이 아니라 <strong>무대가 바뀐 것</strong>으로 읽는다. 전주까지 안보 건수를 끌어올리던 호르무즈 파병 파일이 닫힌 뒤, 이번 주의 중심은 유엔총회라는 한 무대에서 압축적으로 열린 정상외교였다. 건수는 줄었지만 유의도 3 항목은 1건에서 2건으로 늘었다.</p>
<p><strong>첫째, 이재명–트럼프 뉴욕 깜짝 정상회담(9/22, 약 30분).</strong> 전작권·원잠·조선·투자를 모두 다뤘고, 양 정상은 투자 협상의 “상당한 진전”을 함께 평가했다. 산출물은 선언 수준에 머물렀다. 전작권에서는 <strong>한국이 희망하는 2027~28년과 미군 실무 평가상 조건 충족 최이른 시점인 2029년 1분기</strong>의 격차가 처음 수치로 확인됐다. 원잠·조선은 ’지속 협의’에 그쳤다. 12월 마이애미 G20 계기 골프 회동이 거론됐다.</p>
<p><strong>둘째, 3,500억 달러 패키지의 1호 사업이 텍사스 엔시널 가스복합화력으로 확정됐다</strong>(총사업비 223억 달러·약 6.3GW, 9/22 국회 산업위 예비 보고). 원전 8기·알래스카 LNG는 보류됐고, ‘PPA 거부’ 메모와 <strong>미측의 연내 약 100억 달러 송금 요구(한국 검토분의 약 4.5배)</strong>가 풀리지 않았다. 그리고 산업위 위원 한 명이 이렇게 전했다. <strong>“MOU는 트럼프가 직접 발표할 것이고, 미국 선거 일정과 맞물려 정치적 효과를 극대화할 시점에 발표할 것.”</strong> 관측이지 확정은 아니다. 다만 행정부 최대 외국인 투자 약속이 중간선거 성과 서사로 쓰일 경로가 처음 구체적으로 기록됐다. <strong>엔시널은 토스업 텍사스(라살 카운티)에 있는데, 텍사스 상원 후보의 언급은 3주째 0건이다.</strong> 발표가 실제로 이뤄지면 경합주 착지와 대통령 직접 발표가 겹치는 이 트랙 사상 첫 사례가 된다.</p>
<p><strong>셋째, 대북 메시지가 두 층위로 나뉘었다.</strong> 이 대통령은 유엔 기조연설(“북미대화 지체 없이 재개”)과 NYT 인터뷰(‘제재–핵동결 교환’ 제안, 한국 정부 추정 <strong>북한 연 10~20기 신규 핵무기 생산</strong> 공개)로 대북 제안 수위를 올렸다. 그런데 <strong>트럼프의 같은 날 유엔 연설은 북한을 언급하지 않았다.</strong> 하루 앞선 9/21 한미일 외교장관 성명은 ‘북한 완전한 비핵화’와 대만해협 현상유지 문구를 함께 담았다. 북한은 9/20 <strong>올해 14번째 탄도미사일</strong>로 답했다(김여정 9/18 ’상응행동’ 담화 이틀 뒤).</p>
<p><strong>넷째, 미 의회·경합 레이스 후보의 한국 발화는 이번 주도 0건이다</strong>(상원 [K] 7일 전부 부재). 미측 공개 발화는 국무부 3자 성명과 정상회담뿐이고, <strong>전부 행정부 채널</strong>이다. 경합 밖에서는 한화 디펜스 USA가 아칸소 파인블러프에 7년 22억 달러 규모 탄약 생산단지를 발표했다(아칸소에는 2026 경합 레이스가 없다).</p>
<p><strong>다음 주 검증 구간</strong>: 안규백–헤그세스 워싱턴 회담 실제 개최 여부(날짜를 명시한 1차 보도 미확인) · 엔시널 MOU 발표의 시점과 주체 · 웨스팅하우스 지분 5~10%의 의결권 확보 방식과 연내 100억 달러 요구 수용 여부 · 10/2 상원 이란 전쟁권한 표결. (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>메인 — ProPublica 보도(9/22) 이후 실사된 첫 비당파 조사.</strong> 원천은 이것을 <strong>현재 판 위에서 가장 값비싼 단일 데이터</strong>로 꼽는다. 가능한 결과는 셋이다 — 콜린스 우위 확인, 잭슨 복귀, 동률 고착. 각각이 Bear·Bull·Base의 무게를 직접 바꾼다. 10/6 첫 토론 전까지 조사 창은 열흘이다.</li>
<li><strong>오하이오 — 평균 +4 압축의 실사 확인.</strong> 신규 단일 조사로 확인되면 3억 달러 포화 광고의 효과가 이번 사이클 처음으로 실측되는 것이다. 부정되면 집계 산술이 만든 인공물로 기각한다.</li>
<li><strong>미시간 — 당파 조사 충돌의 판정.</strong> Torchlight(로저스 +1.3) 대 Suffolk(+7)·라스무센(+3)을 가를 비당파 조사가 필요하다. 10/8 토론 전 기준선이 된다.</li>
<li><strong>뉴햄프셔 — 등급 대 조사 괴리 4주차.</strong> NRSC가 공격 목표로 지정한 만큼 실제 자금이 들어오는지, Kalshi 가격, Cook·IE의 재검토 여부를 본다.</li>
<li><strong>9/28(월) — NY-17 첫 토론(News 12).</strong> 조사 공백이 14일 넘은 전국 최대 하원 표적의 유일한 예정 이벤트다. 토론 뒤 첫 조사가 하원 보드에서 가장 가치 높은 수집물이다. 같은 날 알래스카 APOC 재반박 기한이 있다.</li>
<li><strong>사바토·IE의 Cook 9/25 대응 회차</strong> — 하원 3사 토스업 지도가 다시 짜인다. TX-34(마지막 역방향)를 Cook이 따라가는지, IE가 TX-15·NC-11을 Tilt R에서 올리는지.</li>
<li><strong>9/30(수) — 2분기 GDP 확정치 + 8월 PCE, 3분기 FEC 분기 마감</strong>(보고서는 10/15).</li>
<li><strong>10/2(금) — 상원 H.Con.Res.89 이란 전쟁권한 상정 시한.</strong> 선거 전 유일한 의회 일정이다. 트럼프의 호르무즈 제안 거부와 “선거 후 폭격” 보도 직후의 표결이라, 이미 이탈한 접전지 공화 후보들의 소속 주 표가 관전 포인트다. 원천은 9/24 표결에서 콜린스(ME)·설리번(AK)이 어떻게 투표했는지를 아직 확인하지 못했다고 적는다.</li>
<li><strong>10/4(일) — 알래스카 주지사 후보 등록 마감.</strong> 공화 3인 구도가 2인으로 바뀔 수 있는 유일한 기한이다. 브론슨은 사퇴 거부를 공식화했다.</li>
<li><strong>10/6~8 — 토론 블록.</strong> ME 상원 10/6(ProPublica 보도 후 첫 대면) · MI 주지사·GA ANF 타운홀·IA 주지사 1차 10/6 · IA 상원 10/7(단일, 측정 격차 해소 이벤트) · MI·GA 상원 10/8.</li>
<li><strong>10/13 — 조지아 사전투표 개시.</strong> 그 전에 발표될 SLF 증액 명단에 조지아가 들어가는지가 공화의 조지아 재투자 여부를 가르는 마지막 시험이다. 이어 10/14 9월 CPI(선거 20일 전), 10/15 Q3 FEC, 10/19 텍사스 사전투표가 온다.</li>
<li><strong>주지사 — FOMC 후 위스콘신·미시간·네바다 첫 조사(2주째 0건)</strong>와 <strong>조지아 Cook·Sabato의 Toss-up 재검토 신호</strong>.</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 09/21~09/27 — 일간 전국·상원·하원 각 7/7, 주정부 6/7(9/27 결손), Korea Watch 6/7(9/25 결손, 결손일 [K] 유실 0건 확인)). 환경 지표 — Silver Bulletin·FiftyPlusOne·RealClearPolling·USPollingData·Reuters/Ipsos·ARG·CNN/SSRS·Strength In Numbers/Verasight·Emerson·NPR/PBS/Marist·NBC/하트+POS·Fox News·Quantus Insights. 경제 — S&amp;P Global PMI·노동부(신규청구)·미시간대·인구조사국(내구재)·AAA·미니애폴리스 연준. 상원 실측 — YouGov(의뢰처 미확인)·InsiderAdvantage·Suffolk University·Rasmussen Reports(공화계)·Torchlight Strategies(공화 PAC 의뢰)·NYT/시에나/프레스헤럴드·UNH 서베이센터·UMass로웰/YouGov·High Point/YouGov·East Carolina University·Mason-Dixon/NBC5·Telemundo·텍사스서던대/Barbara Jordan 센터·Marist·Alaska Survey Research(자체 발표). 주지사 실측 — YouGov(GA)·NYT/시에나/프레스헤럴드(ME)·AARP/Fabrizio Ward–Impact Research(AK, 결선 시뮬레이션 소급)·BGSU/YouGov(OH 크로스탭)·KSTP/SurveyUSA(MN). 하원 — Cook(9/25 재조정)·PPP(민주 성향)·House Majority PAC(스폰서)·Punchbowl/AdImpact·Zoose(목록만). 상원·주지사 등급 — Cook(상원 <strong>9/23</strong>·주지사 9/18)·Sabato(상원·주지사 <strong>9/22</strong>)·Inside Elections(상원·주지사 9/17) 270towin 재게시분 자동 취득(9/27 실행 — 상원 10개 기관·주지사 8개 기관). 하원 등급 — Cook <strong>9/25 보드</strong> 자동 취득(435개구 해독, 합계 435 검증). 예측시장 — Kalshi 공개 API 원가격(9/27 — 상원 35/35·주지사 35/36, 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). 외부 모델 — Decision Desk HQ(모델 갱신 9/25)·Race to the WH(라이브 시계열 마지막 관측 9/27, 139점). Silver Bulletin FLIPR 65%·Polymarket 65%는 원천 기재값이며 이 사이트가 직접 취득한 값이 아니다. 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. <strong>다음 조사는 이 사이트 DB에 넣지 않고 서술로만 반영했다</strong> — NH NYT/시에나 파파스 +5(원문 URL 미확인) · TX Marist 탈라리코 +6(원문 URL 미확인) · NH NRSC 의뢰 수누누 37–36(실사일 미확인, 전주 Fabrizio 건과 동일 여부 미확인) · AK Alaska Survey Research(정확 마진 미공개) · ME UMass로웰/YouGov(8/28~9/14, URL 미확인) · NC High Point/YouGov(8/3~12 구 실사) · ME 주지사 NYT/시에나(메인은 주지사 State Focus 8주 밖). <strong>기록해 둘 불일치 4건</strong>: ① 원천이 미특정으로 남긴 Cook 9/23 상원 이동 잔여 2건은 이 사이트 피드 대조로 <strong>사우스캐롤라이나 Solid R→Likely R · 캔자스 Likely R→Lean R</strong>로 확인된다(둘 다 감시 밖). ② 원천은 사바토 뉴햄프셔(상원)를 Toss-up으로 적으나 9/22자 피드는 <strong>Lean D</strong>다 — 등급가중 산수 +2.5(피드) 대 +2.4(원천), 결론 불변. 원천이 쓴 사바토 알래스카 “Tilt R”은 사바토가 쓰지 않는 등급이다. ③ 원천은 이번 주 사바토 주지사 이동을 0건으로 적으나 피드는 9/22자 <strong>오하이오·네바다 Lean R→Toss-up</strong>을 보여준다. 애리조나(원천 Likely D / 피드 Lean D)·메인(원천 Lean D / 피드 Likely D)도 갈린다 — 이 사이트는 피드를 따른다. ④ Kalshi 상원 다수(원천 61%, 9/22 / 직접 취득 62.0¢, 9/27)와 DDHQ(원천 52%, 9/21 / 직접 취득 54.0%, 모델 갱신 9/25)는 시점 차이다. <strong>주의회 확인(월 1회 항목)은 9월분을 전주에 마쳤다</strong> — 이번 주 원천 주의회 서술(제이콥슨 1/22 구성 기준)에 등급 변동은 없고, <code>state_legislatures.json</code>은 손대지 않았다. 이번 주 자동 취득 로그에 조회 실패로 빠진 항목은 <strong>Kalshi 캔자스 상원 시리즈(KXSENATEKS) 1건</strong>(감시 밖 — 결측이 아니라 ‘못 받은 것’)과 뉴햄프셔 주지사 시장(2026 만기 계약 부재)이다. 이번 주 조사 대부분(실사 9/14~9/23)은 9/17 충격(연준 인상·유가 급등·출입금지)을 부분 반영하며, <strong>트럼프의 호르무즈 제안 거부(9/26) 이후 실사된 조사는 아직 없다.</strong> 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>