<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="선거 전 마지막 고용보고서가 +2.9만 명으로 나오면서 ’고용은 견조하다’는 여당의 마지막 방어선이 빠졌다. 트럼프 순지지는 −22.7로 사상 최저를 다시 썼고, 제너릭 밸럿은 D+8~9 고원을 4주째 지켰다. 상원에서는 메인의 판별 조사가 50–50 동률로 나왔고, Fox가 미시간·텍사스·아이오와에서 같은 주에 민주 우위를 실측했으며, 노스캐롤라이나에서는 공화 외곽자금이 10월 지출을 0으로 줄였다. 역류는 알래스카 하나였다 — 그리고 그 알래스카에 한국의 LNG 투자 발표가 얹혔다.">

<title>28주차 · 09/28~10/04 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e77bf345fb96193e69d6a5f0e0c55192.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">28주차 · 09/28~10/04</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../legal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">선거 법·제도 분쟁 트래커</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trade-canada.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캐나다 무역전쟁과 상원 선거</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dsa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">민주당 내부 지형 — DSA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">District Focus</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house/ny17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">NY-17 New York 17th — Lawler</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house/pa01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PA-01 Pennsylvania 1st — Fitzpatrick</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-돌아온-계측은-전부-접전이었고-움직인-쪽은-사바토였다" id="toc-하원-돌아온-계측은-전부-접전이었고-움직인-쪽은-사바토였다" class="nav-link" data-scroll-target="#하원-돌아온-계측은-전부-접전이었고-움직인-쪽은-사바토였다">하원 — 돌아온 계측은 전부 접전이었고, 움직인 쪽은 사바토였다</a></li>
  <li><a href="#주지사-기대-순증-1.125석-하방은-조지아-하나로-좁혀졌다" id="toc-주지사-기대-순증-1.125석-하방은-조지아-하나로-좁혀졌다" class="nav-link" data-scroll-target="#주지사-기대-순증-1.125석-하방은-조지아-하나로-좁혀졌다">주지사 — 기대 순증 +1.125석, 하방은 조지아 하나로 좁혀졌다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-등급은-멈췄고-측정값은-움직였다" id="toc-상원-산수-등급은-멈췄고-측정값은-움직였다" class="nav-link" data-scroll-target="#상원-산수-등급은-멈췄고-측정값은-움직였다">상원 산수 — 등급은 멈췄고, 측정값은 움직였다</a></li>
  <li><a href="#전주-관전-포인트-채점" id="toc-전주-관전-포인트-채점" class="nav-link" data-scroll-target="#전주-관전-포인트-채점">전주 관전 포인트 채점</a></li>
  <li><a href="#기록해-둘-불일치" id="toc-기록해-둘-불일치" class="nav-link" data-scroll-target="#기록해-둘-불일치">기록해 둘 불일치</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">28주차 · 09/28~10/04</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    선거 전 마지막 고용보고서가 +2.9만 명으로 나오면서 ’고용은 견조하다’는 여당의 마지막 방어선이 빠졌다. 트럼프 순지지는 −22.7로 사상 최저를 다시 썼고, 제너릭 밸럿은 D+8~9 고원을 4주째 지켰다. 상원에서는 메인의 판별 조사가 50–50 동률로 나왔고, Fox가 미시간·텍사스·아이오와에서 같은 주에 민주 우위를 실측했으며, 노스캐롤라이나에서는 공화 외곽자금이 10월 지출을 0으로 줄였다. 역류는 알래스카 하나였다 — 그리고 그 알래스카에 한국의 LNG 투자 발표가 얹혔다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 10월 4일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 9/28~10/4 일간 브리핑 — 전국·상원·하원·Korea Watch 각 7/7, 주정부 6/7(<strong>10/1 결손</strong> — 10/2호가 수집 창을 48시간으로 넓혀 결손 창을 소급 포괄). 뉴스 기준: 미 동부시간 10/3(토)까지. 선거일(11/3)까지 30일. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>환경의 마지막 버팀목이 빠졌다.</strong> 10/2 발표된 9월 고용보고서가 비농업 <strong>+2.9만 명</strong>(예상 약 +8.4만) · 실업률 <strong>4.2%</strong> · 7~8월 합산 <strong>−6만 하향 수정</strong> · 임금 상승률 3.0%가 물가 3.4%를 밑도는 조합으로 나왔다. 다음 고용보고서는 11/6, 선거 뒤다. <strong>유권자가 보는 마지막 고용 지표가 이것으로 확정됐다.</strong> 트럼프 순지지는 Silver Bulletin 기준 <strong>−22.4 → −22.7</strong>로 사상 최저를 다시 썼고(경제 지지 31%, Quinnipiac — 양 임기 최저), 제너릭 밸럿은 <strong>D+8~8.9</strong>의 고원을 4주째 되돌림 없이 지켰다. 고용 쇼크 이후 실사된 조사는 아직 없다.</li>
<li><strong>메인의 판별 조사가 도착했고, 답은 동률이다.</strong> ProPublica 보도(9/22) 이후 구간만 담은 첫 대형 조사 CBS News/YouGov가 잭슨–콜린스 <strong>50–50</strong>을 냈다. 전주 이 사이트가 적은 세 갈래(콜린스 우위 확인 · 잭슨 복귀 · 동률 고착) 중 세 번째다. 원천은 메인을 핵심 4곳 중 유일한 ’사실상 동전 던지기’로 공식화했다.</li>
<li><strong>Fox News가 같은 실사 창(9/24~28)에서 미시간·텍사스·아이오와 세 곳 모두 민주 우위를 냈다</strong> — 미시간 엘사예드 <strong>50–49</strong>(8월 로저스 +4에서 역전) · 텍사스 탈라리코 <strong>51–49</strong> · 아이오와 투렉 <strong>49–47</strong>. 셋 다 오차범위 안이지만 방향이 같다. 미시간은 원천 집계로 공개 비당파 조사 4연속 엘사예드 우위가 됐다.</li>
<li><strong>공화 자금이 노스캐롤라이나에서 빠져 텍사스로 갔다.</strong> 노스캐롤라이나의 공화 외곽단체들이 <strong>10월 지출 계획을 0으로</strong> 했고(철수 전 10월 예약 $3,300만+), SLF 계열 신설 PAC는 텍사스에서 <strong>17일간 $1억 3,100만</strong>(약 5:1)을 팩스턴 방어에 썼다. 확장 공격이 아니라 자기 의석 방어다.</li>
<li><strong>역류는 알래스카 하나다 — 그리고 거기에 한국이 얹혔다.</strong> NYT 참모 처우 보도 이후 실사가 포함된 두 조사가 모두 설리번 +1 안팎이다. 9/30 백악관은 <strong>한국의 알래스카 LNG 약 540억 달러 투자</strong>를 발표하며 설리번을 “최대 공로자”로 불렀다. 한국 산업부는 “투자 여부도 규모도 결정된 바 없다”고 공식 항의했고, 펠톨라 지원 PAC는 이를 “엄청난 거짓말”로 공격했다. <strong>한국 자본이 경합 레이스에서 공수 양쪽의 선거 소재가 된 첫 사례다.</strong></li>
<li><strong>이 사이트가 직접 받는 숫자는 전부 올랐다</strong> — Kalshi 상원 다수 <strong>64¢</strong>(전주 62¢) · Race to the WH <strong>72.9%</strong> · DDHQ <strong>56.0%</strong>. Cook·Sabato 상원 등급은 이번 주 한 칸도 움직이지 않았고, Inside Elections가 10/2 상원 5곳을 전부 민주 쪽으로 옮겼다.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>9월 고용보고서 — 이번 주 최대 사건</strong></td>
<td>비농업 <strong>+2.9만</strong> · 실업률 <strong>4.2%</strong> · 시간당 임금 전년비 <strong>+3.0%</strong> · 7월 −1만·8월 +13.3만으로 하향(합산 <strong>−6만</strong>)</td>
<td>10/2 발표</td>
<td>예상은 +8.4만~9만 · 4.1% · +3.2%였다. 원천은 이것을 “‘물가는 아프지만 고용은 견조하다’는 여당의 유일한 실물 방어선이 제거됐다”고 판독한다. 연준이 9/16 금리를 <em>인상</em>한 직후라 ’물가는 높은데 고용은 식는’ 조합이 됐다. 세부: 의료 +1.7만 · 건설 +1.1만 · 제조 +0.9만 · 정부 −1.7만. <strong>다음 고용보고서는 11/6 — 선거 이후다.</strong> 발표 당일 S&amp;P는 +0.96%였다(금리 완화 기대)</td>
</tr>
<tr class="even">
<td>트럼프 순지지도</td>
<td><strong>−22.7</strong>(Silver Bulletin, 10/2 — 사상 최저 재경신) · 주간 −0.3p</td>
<td>9/25 → 10/2</td>
<td>전주 급락(−2.9p) 뒤 속도는 줄었지만 저점 경신은 계속됐다. 원천 판독은 “바닥 형성이 아니라 저점의 지속 갱신”이다. 신규 개별 조사 — <strong>WSJ 37/61</strong>(9/16~21, 1990년 이후 WSJ 집계상 중간선거 직전 최저) · <strong>Quinnipiac 34/61</strong>(9/24~27 — <strong>경제 지지 31% 양 임기 최저</strong>, 이란 대응 28%) · Harvard CAPS/Harris 42%(공화 우호 기관, 상단 이상치). 1기 동기 −11.0 · 바이든 −8.8 대비 열위 약 12~14p. FiftyPlusOne·USPollingData 지지율 페이지는 원천이 이번 주 재확인하지 못했다</td>
</tr>
<tr class="odd">
<td>일반투표(제너릭) — 고원 4주째</td>
<td><strong>Silver D+8.9</strong>(50.0–41.1, 9/30 보도 기준) · FiftyPlusOne <strong>D+7.7~8</strong>(50.8–43.1, 10/2~3 — 보합) · NYT/Siena 단일 <strong>D+8</strong>(51–43, 9/15 실사) · LV 보정 D+8.8(이월)</td>
<td>9/30~10/3</td>
<td>경로는 9/1 D+6.7 → 9/17 D+7.5 → 9/23 D+8.1 → 9/30 D+8.9다. <strong>다만 이번 주 상승분(+0.8)은 Silver 단독 확인이고 FiftyPlusOne은 보합이다</strong> — 원천의 작업 추정은 “원자료 D+8 안팎, LV 기준 D+8.8~9 부근”이다. 하단 조사군(Morning Consult D+4 · NBC D+5 등)은 이번 주에도 신규 웨이브가 없다</td>
</tr>
<tr class="even">
<td>소비 심리 — 12년 최저</td>
<td>컨퍼런스보드 9월 <strong>81.9</strong>(−6.7p, 2014년 이후 최저) · 미시간대 9월 확정 48.1 · 1년 기대인플레 <strong>4.6%</strong></td>
<td>9/25~9/29</td>
<td>컨퍼런스보드 응답에서 물가·유가 언급 빈도가 사상 최고였다. JOLTS 8월 구인 −25.6만은 사후적으로 고용 쇼크의 전조로 읽힌다</td>
</tr>
<tr class="odd">
<td><strong>반증 재료 — 이번 주 가장 무거운 것</strong></td>
<td>8월 PCE 전년비 <strong>3.4%</strong>(예상 약 3.7% 하회) · 근원 <strong>3.0%</strong> · FOMC 기대 ‘추가 인상 ~70%’(9/28) → <strong>‘동결 ~79.5%’</strong>(10/2, CME)</td>
<td>9/30~10/2</td>
<td>금리 채널의 추가 악화가 멈출 수 있다는 첫 신호다. 원천은 “금융 조건의 완화이지 체감 생활비의 완화가 아니다”라고 선을 긋는다. BEA 측정방식 변경 효과도 일부 섞였다. 10년물은 오히려 주중 <strong>5.29%</strong>(9/30, 20년+ 최고)까지 올랐다</td>
</tr>
<tr class="even">
<td>유가 — ’정점 통과’가 ’100달러 고원’으로</td>
<td>브렌트 9/28 약 $107~108(+3%) → 10/1 <strong>$102.31</strong> · WTI $92.87</td>
<td>9/28~10/1</td>
<td>전주 원천이 반증 재료로 적은 ’원유 정점 통과’가 한 주 만에 사라졌다. 9/26 호르무즈 재개방안 거부가 완화 경로를 직접 막았다. 8월 CPI 휘발유 전년비 +27.4% — <strong>10/14 CPI는 이 고원을 측정한다</strong></td>
</tr>
<tr class="odd">
<td>전쟁 — 선거일까지 고정</td>
<td>거부 유지 · TIME 인터뷰 “이란과의 평화는 불가능에 가깝다” · <strong>협상 실패 시 중간선거 이후 공격 재개</strong> 시사(세 번째 공언) · 항모 3개 전단 10월 말까지 배치 · 해병 약 2,000명 이동</td>
<td>9/28~10/3</td>
<td>이란 IRGC는 미국 유권자에게 트럼프 측 후보 낙선을 촉구하는 25쪽 서한을 냈다. 원천은 이것을 공화당의 ‘외국 개입’ 역공 재료가 되는 양방향 변수로 보되 생활비 서사를 대체할 크기는 아니라고 판단한다</td>
</tr>
<tr class="even">
<td>$5,000 관세 배당 — 신뢰 붕괴 실측</td>
<td>중립 표현 순지지 <strong>+18</strong> → 실제 조건(공화 승리 조건부) 고지 시 <strong>−18</strong> · “실제 지급” 신뢰 13% · “선거용 술책” 62%</td>
<td>Morris/Verasight 프레이밍 실험</td>
<td>여당의 마무리용 간판 공약이 세부가 알려질수록 부채가 된다는 것이 수치로 나왔다</td>
</tr>
<tr class="odd">
<td>재정·제도</td>
<td>하원 370–48 CR 통과 → <strong>12/11까지 셧다운 리스크 없음</strong> · CIT, 약 60개국 ‘강제노동’ 관세 위법 소송 심리(9/30)</td>
<td>9/28~9/30</td>
<td>관세 체제의 법적 불확실성은 11월까지 이어진다. 미주리는 9/25 연방대법원 결정으로 종결됐고 이번 주 신규 재획정 판결은 없다</td>
</tr>
</tbody>
</table>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p><strong>이번 주 Cook·Sabato 상원 등급 이동은 0건이다.</strong> 원천도 “이번 주는 등급의 주가 아니라 조사·자금의 주였다”고 적는다. 그런데 이 사이트 피드에서는 <strong>Inside Elections가 10/2 상원 5곳을 한꺼번에 옮겼고, 다섯 곳 전부 민주 쪽이다</strong> — GA·NC Tilt D → Lean D · MI Toss-up → Tilt D · AK Tilt R → Toss-up · TX Lean R → Tilt R. 시장 열은 <strong>OH +7¢ · TX +4¢ · AK +3¢ · IA +2¢ · NC +1.6¢ · GA +0.8¢</strong>가 오르고 MI·NH·ME가 1센트씩 내렸다. 상원 다수 계약은 62¢에서 <strong>64¢</strong>가 됐다. 핵심 열에서 읽을 것은 둘이다. 메인이 동률로 ’착지’했고, 알래스카에서는 <strong>조사와 시장이 반대 방향으로 움직였다.</strong></p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 9/23 / Sabato 9/22 / IE 10/2)</th>
<th>시장 (Kalshi 10/4)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Likely D / Likely D / <strong>Lean D (10/2 ↑)</strong></td>
<td>94.9¢ (▲0.8)</td>
<td><strong>’뉴스가 없다는 것이 뉴스’다.</strong> 신규 조사는 우파 성향 InsiderAdvantage <strong>+8</strong>(9/22~23)과 집계 경유 Big Data <strong>+10</strong>뿐이고, 주 후반엔 7일로 넓혀도 새 기사가 없었다. 툰 원내대표의 애틀랜타 유세(9/25)에도 “의석이 손에서 벗어나고 있다”는 주 매체 프레임이 남았다. 현금 오소프 약 $4,200만 대 콜린스 약 $220만. IE가 Lean D로 올려 세 기관이 모두 토스업 위에 섰다 (<strong>유지 — 안정 고착</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / Lean D / <strong>Tilt D (10/2 ↑)</strong></td>
<td>71¢ (▼1)</td>
<td><strong>전주 “당파 조사 충돌의 판정”으로 걸어 둔 비당파 조사가 왔다.</strong> Fox <strong>50–49</strong>(9/24~28, LV 1,028 — 8월 로저스 +4에서 역전) · Marist <strong>51–44</strong>(RV) · Trafalgar 47–45 · Rasmussen 47–44. 반대편은 공화계 Torchlight R+1.3 · co/efficient 동률. 원천은 8월의 “민주당 최대 위험 의석” 평가가 사실상 기각됐다고 적는다. 지출은 주 역사상 최대(공개 $2.05억+, 트럼프 계열 No Going Back PAC $1,300만+). 지역 언론은 갈렸다(Free Press 엘사예드 · News 로저스) (<strong>개선</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Toss-up / Lean D / Toss-up</td>
<td>85¢ (▼1)</td>
<td><strong>등급 대 조사의 괴리가 5주차에 들어섰다.</strong> UNH <strong>+8</strong>(9/17~21) · NYT/Siena +5 · <strong>공화 성향 Trafalgar조차 +6</strong>(9/27) — 원천 5개 조사 평균 48.2–42.8이다. 그런데 Cook은 Toss-up을 유지하고, 외곽자금 약 $5,000만은 대부분 반파파스다. NHPR은 유권자의 광고 피로를 보도했다. 주 후반 신규 이벤트는 없었다 (<strong>유지</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D / <strong>Lean D (10/2 ↑)</strong></td>
<td>95.3¢ (▲1.6)</td>
<td><strong>공화 외곽자금의 ’2차 철수’가 공식화됐다</strong>(Axios Raleigh 10/2, Politico 인용). SLF는 9월 $1,700만을 쓴 뒤 자금을 다른 주로 돌렸고, Prosperity Action·Old North Action은 <strong>10월 지출 계획이 없다</strong>(철수 전 10월 예약 $3,300만+). 공화 관계자는 “캔자스·텍사스·알래스카에 돈이 필요하다”고 토로했다. 조사도 같은 쪽이다 — AARP 쿠퍼 <strong>53–42</strong>(무당층 58–33) · Big Data 51–39 · YouGov 53–41. 원천은 Lean D → Likely D 상향 압력을 적는다 (<strong>개선 — 핵심 탈환 중 최안정</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td>59¢ (▼1)</td>
<td><strong>판별 조사가 도착했고, 답은 동률이다.</strong> CBS News/YouGov <strong>50–50</strong>(9/23~10/1, RV 1,144 — ProPublica 이후 첫 대형 조사) · AARP 잭슨 50–47(9/20~22). 부속 수치는 양쪽에 숙제를 남긴다. 콜린스는 트럼프 반대 유권자 5명 중 1명을 가져오고(AARP 50세 이상 분할투표층 70–17), <strong>잭슨은 민주당원 40%가 “다른 후보였으면”</strong> 하는 약한 결집 위에서 주지사 후보 핑그리보다 뒤처진다. NPR은 애루스툭 카운티를 풍향계로 보도했다 (<strong>혼조 — 동전 던지기 공식화</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss-up / Toss-up / <strong>Toss-up (10/2 ↑)</strong></td>
<td>74¢ (▲3)</td>
<td><strong>원천이 적은 이번 주 유일한 공화 방향 역류다 — 그런데 시장과 등급은 반대로 움직였다.</strong> NYT 참모 처우 보도(9/23)에 걸치거나 그 이후 실사된 두 조사가 모두 설리번 근소 우위다 — Trafalgar 46.8–45.5(9/22~24, 동명이인 2.8%) · Quantus 48–47(10/2 등재, 무소속은 펠톨라 +22). <strong>9/30 백악관이 한국의 알래스카 LNG 약 540억 달러 투자를 발표</strong>했다 [K]. 현지 전문가는 보도 파장을 제한적으로 봤고, 펠톨라는 전국 민주당과 거리를 두는 광고로 대응했다. Political Wire 10/3 “Peltola Leads” 조사는 원천이 접근하지 못해 미특정이다 (<strong>조사 소폭 악화 · 시장 상승</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td><strong>65¢ (▲7)</strong></td>
<td><strong>조사 괴리가 감시 9주 중 최대다</strong> — Marist 브라운 <strong>51–43</strong>(9/24~27, RV 1,298, 무당층 +25) · Suffolk 47–44 대 InsiderAdvantage(우파 성향) <strong>44–43</strong>(9/28~29). 그 위에 트럼프가 10/3 데이턴 인근에서 허스티드 첫 직접 지원 유세를 했고, NRSC 팀 스콧 위원장은 격차가 “몇 포인트였는데 이제 정확히 동률”이라고 공개 발언했다. 스프링필드 트럭 공장 약 1,400명 해고가 브라운의 공세 재료로 더해졌다. Fairshake 반브라운 $3,000만 계획 (<strong>혼조 · 시장 최대 상승</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Toss-up / Toss-up / <strong>Tilt R (10/2 ↑)</strong></td>
<td>65¢ (▲4)</td>
<td><strong>돈은 공화가, 서사는 민주가 가진 주다.</strong> Fox 탈라리코 <strong>51–49</strong>(9/24~28, LV 881)는 고품질 비당파 기관이 이 주에서 실측한 첫 탈라리코 우위다(호감도 +8 대 팩스턴 −18, 코닌 경선 지지자 약 20% 이탈). 공화의 대응은 <strong>SLF 계열 PAC 17일간 $1억 3,100만</strong>이다. 팩스턴의 “트럼프 전당대회가 지지율을 깎았다” 유출 녹음 보도도 나왔다(NYT발, 캠프 부인 — 원천은 NYT 원문 미확인). 조기투표 10/19 (<strong>개선</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Toss-up / Toss-up / Tilt R</td>
<td>45¢ (▲2)</td>
<td><strong>편차 최대 경합의 지위가 유지됐다.</strong> Fox 투렉 <strong>49–47</strong>(LV, RV 50–46) · InsiderAdvantage 투렉 +1.7 대 Quantus 힌슨 +1.3(9/28~29). 전주 Marist 투렉 +8은 이월이다. PolitiFact는 “투렉 본회의 표결 58% 불참”을 True로 판정했다(공화 광고 소재 공산). SLF는 힌슨 지원 $2,000만을 추가했다. <strong>TV토론 10/7·10/13</strong>이 사이클 첫 대면 검증이다 (<strong>유지</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 이 사이트 조사 DB(<code>senate_polls.csv</code>)에 들어간 본선 조사는 <strong>열 건</strong>이다. 일일 경로가 자동으로 넣은 여섯 건(IA Fox · TX Fox · OH Marist · OH InsiderAdvantage, 그리고 실사가 이전 주인 NH UNH · ME UMass로웰)과 이번 주간 정리에서 원문 URL을 확인해 넣은 네 건(<strong>ME CBS/YouGov · ME AARP · MI Fox · OH Suffolk</strong>)이다. <strong>넣지 않은 것</strong>: 날짜나 득표율이 원천에 없는 조사(IA Quantus·InsiderAdvantage, TX Rasmussen·Big Data, NC Big Data·AARP, NH Trafalgar, AK Quantus — 마진만 있거나 ’등재일’만 있다), 원천이 상세를 이월 과제로 남긴 MI Marist·Trafalgar. 그리고 <strong>AK Trafalgar(9/22~24)는 원천에 기간·표본이 있지만 넣지 않았다</strong> — 원천이 적은 표본·오차(LV 1,079, ±2.9)가 이 DB에 이미 있는 <strong>MI Trafalgar(9/7~9)와 정확히 같아서</strong>, 원문으로 표본을 확인하기 전까지 보류한다(아래 불일치 ⑤).</p>
</section>
<section id="하원-돌아온-계측은-전부-접전이었고-움직인-쪽은-사바토였다" class="level2">
<h2 class="anchored" data-anchor-id="하원-돌아온-계측은-전부-접전이었고-움직인-쪽은-사바토였다">하원 — 돌아온 계측은 전부 접전이었고, 움직인 쪽은 사바토였다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cook 토플라인 — Tier-1 무변동</td>
<td>Solid D 185 / Likely D 12 / Lean D 11 / <strong>Toss Up 22 (D5 · R17)</strong> / Lean R 10 / Likely R 19 / Solid R 176 (9/25 보드, 자동 취득 — 합계 435 검증, 이번 주 재취득에서도 같은 보드). Cook의 이번 주 이동은 Tier-2 <strong>NY-21(스터파닉 공석) Solid R → Likely R</strong>(9/28, 원천 보도 기준) 한 건이고, 자동 취득 보드에는 아직 반영되지 않았다</td>
</tr>
<tr class="even">
<td><strong>사바토 9/29 — 11건 전부 민주 방향</strong></td>
<td>Tier-1 <strong>PA-07(매켄지)·VA-02(키건스) Toss-up → Lean D</strong> — 토스업을 ‘위로’ 이탈 · VA-01 Lean R → <strong>Toss-up</strong> · KY-06·ME-02·MO-02·MT-01·VA-05 Likely R → Lean R · NC-03·OH-15 Solid R → Likely R · CA-45 Lean D → Likely D. Cook은 PA-07·VA-02를 Toss-up으로 유지 — <strong>Cook이 따라가면 토스업은 22 → 20석</strong>이 된다. 보도된 사바토 집계(민주 우세 213 / 공화 우세 202 / 토스업 20)는 단일 2차 출처이고 원천이 원문에 접근하지 못해 미검증이다</td>
</tr>
<tr class="odd">
<td><strong>독립 계측의 복귀</strong></td>
<td><strong>NY-17 에머슨/PIX11</strong>(독립, 9/27~29, n=400) 콘리 <strong>48–46</strong> — 민주 지지층의 롤러 교차 지지 20% → 12%, “매우 투표 열의” 층 콘리 +7 · <strong>PA-10 프랭클린앤마셜</strong>(무당파, 9/9~20, n=390) 스텔슨 <strong>47–44</strong> — 4월 이후 첫 공개 조사 · <strong>CO-08 매클로플린</strong>(공화 스폰서, 9/16~17, n=400) 에번스 <strong>48–46</strong>. 전주 “상향이 유권자 직접 계측 없이 일어났다”는 유보가 부분 해소됐다 — <strong>세 건 모두 오차범위 안</strong>이다</td>
</tr>
<tr class="even">
<td>FL-22 — 자료 공백 종결</td>
<td>대진 확정 — 아스카르(R, 해병대 출신 사업가) 대 단디야(D, 전직 교장). 신지도 트럼프 +11 · PVI R+4. 조사 2건은 HMP/Impact(민주 성향, 8/24~31) 단디야 46–44 · Tavern(8월 중순) 50–50. Cook은 “아스카르가 유리한 위치의 매우 경쟁적 공석”으로 본다</td>
</tr>
<tr class="odd">
<td>기대의석</td>
<td>문자적 등급 가중 <strong>Cook 약 219석</strong>(불변) · <strong>사바토 보도 분포 기준 약 223석</strong>(미검증) · 모리스 경험 보정 약 227석. <strong>등급기관 스프레드의 양끝이 처음으로 모두 과반(218) 위에 섰다</strong></td>
</tr>
<tr class="even">
<td>시장·모델</td>
<td><strong>Kalshi 91.8¢</strong>(10/4 이 사이트 직접 취득) · <strong>DDHQ 76% · 평균 D 235</strong>(10/4 모델 갱신, 직접 취득 — 원천은 9/28 갱신분 75%·D 234를 적는다) · 3사 합의 토스업 14석(Almanac 9/28 — 2주간 19석 민주 방향 이동)</td>
</tr>
<tr class="odd">
<td>조용한 주</td>
<td>재획정 신규 판결 없음 · 보궐·예선 없음 · NY-17 1차 토론(9/28)은 결정적 장면 없이 끝났다. 공화가 기존 ‘안전’ 지역구 수십 곳에 자금을 넣고 있다는 보도(Detroit News 9/28)는 제목 수준이라 수치가 없다</td>
</tr>
</tbody>
</table>
<p><strong>전주 이 사이트가 하원 보드에서 가장 가치 높은 수집물로 꼽은 것이 “NY-17 토론 이후 첫 조사”였고, 그것이 이번 주에 왔다 — 콘리 +2.</strong> 전국 최대 표적에서 광고 예약 7:1 열세인 도전자가 오차범위 안에서 앞선다는 결과다. 같은 주 PA-10과 CO-08에서도 독립·공화계 계측이 돌아왔는데, <strong>방향은 등급 이동과 같았고 크기는 전부 접전이었다.</strong> 원천의 정리가 정확하다 — ’민주 우위 확정’이 아니라 ’현역 공화의 접전 고착’이다. 원천은 민주 다수 확률 중심을 <strong>88~90%로 유지</strong>하고, 중심 시나리오를 D 226~234석으로 상단만 조금 넓혔다(DDHQ 234 반영). <strong>DDHQ(76%)와 시장(91.8%) 사이의 약 16%p 괴리는 그대로다.</strong> 다음 판별 데이터는 Cook의 PA-07·VA-02 대응, 3분기 FEC 공개(10/15), NY-17 2차 토론(10/14)이다. (<a href="https://emersoncollegepolling.com/ny-17-2026-poll/">Emerson NY-17</a> · <a href="https://www.witf.org/2026/09/24/new-poll-voters-cite-economy-as-top-issue-in-perry-stelson-race/">WITF/F&amp;M PA-10</a> · <a href="https://www.kunc.org/politics/2026-09-27/8th-congressional-district-race-is-essentially-tied-poll-shows-with-warning-signs-for-both-gabe-evans-and-manny-rutinel">KUNC CO-08</a> · <a href="https://centerforpolitics.org/crystalball/will-republicans-wake-up-as-september-ends-11-more-house-ratings-changes-towards-democrats/">Sabato 9/29</a> · <a href="https://northcountrypublicradio.org/news/story/54021/20260930/election-forecaster-shifts-ny-21-race-from-solid-to-likely-republican">North Country PR NY-21</a> · <a href="https://www.thehousemajoritypac.com/news/hmp-poll-pia-dandiya-leads-casey-askar-in-fl-22">HMP FL-22</a> · <a href="https://votes.decisiondeskhq.com/forecast/2026/house">DDHQ</a>)</p>
</section>
<section id="주지사-기대-순증-1.125석-하방은-조지아-하나로-좁혀졌다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-기대-순증-1.125석-하방은-조지아-하나로-좁혀졌다">주지사 — 기대 순증 +1.125석, 하방은 조지아 하나로 좁혀졌다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (10/4)</th>
<th>전주(9/27)</th>
<th>등급 (Cook 10/1 / Sabato 9/29 / IE 10/2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td>95.1¢</td>
<td>93.3¢</td>
<td>Solid D / Likely D / Solid D</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>93.3¢</td>
<td>92.9¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="odd">
<td>애리조나</td>
<td>90¢</td>
<td>89¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="even">
<td><strong>아이오와</strong></td>
<td><strong>86¢</strong></td>
<td>83¢</td>
<td>Lean D / Lean D / Tilt D</td>
</tr>
<tr class="odd">
<td>위스콘신</td>
<td>80¢</td>
<td>83¢</td>
<td>Toss-up / Lean D / Toss-up</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>77¢</td>
<td>74¢</td>
<td>Toss-up / Toss-up / <strong>Toss-up (10/2↑)</strong></td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>65¢</td>
<td>63¢</td>
<td>Toss-up / Toss-up / <strong>Toss-up (10/2↑)</strong></td>
</tr>
<tr class="even">
<td><strong>조지아</strong></td>
<td><strong>48¢</strong></td>
<td>51¢</td>
<td>Toss-up / Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td>47¢</td>
<td>46¢</td>
<td>Toss-up / Toss-up / Tilt R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>26¢</td>
<td>26¢</td>
<td>Lean R / Lean R / Tilt R</td>
</tr>
</tbody>
</table>
<p><strong>비당파 실측이 한꺼번에 돌아왔고, 분포는 “민주 방어선 경화 + 공화 방어 두 곳(OH·IA) 악화 + 조지아만 역류”다.</strong> 오하이오 Marist 액턴 <strong>50–44</strong>(D+6) · Suffolk <strong>50–41</strong>(D+9) — 원천은 사바토의 9/22 Toss-up 이동을 12일 만에 소급 확인해 오하이오 가중치를 .375에서 .50으로 올렸고, 주지사 기대 순증이 <strong>+1.000 → +1.125석</strong>이 됐다. 이 사이트는 전주에 피드로 같은 이동을 잡아 이미 +1.125석을 적었다 — <strong>이번 주에는 원천과 이 사이트의 주지사 산수가 같아졌다.</strong> 아이오와 Fox 샌드 <strong>53–44</strong>(D+9)와 원천 기준 Marist D+12가 겹쳤고, 미시간 Fox 벤슨 54–45 · Marist 53–41로 벌어졌다. 원천은 <strong>IA·MI에 상향(Likely D) 감시를 새로 열었다.</strong> Cook은 10/1 분석에서 “민주가 아이오와를 뒤집을 위치”라고 썼다.</p>
<p><strong>FOMC 감도 시험은 셋 중 둘이 풀렸고, 같은 충격에 반대 방향으로 답했다.</strong> 위스콘신 마케트는 LV <strong>D+5 → D+3</strong>(RV D+1)으로 압축됐고, 미시간은 D+4~5에서 D+9~12로 벌어졌다. 원천은 이것을 “환경은 상수이고 굴절 변수는 후보·구도”라는 판정의 세 번째 실측으로 기록한다. 네바다는 4주째 신규 조사가 없다. 애리조나는 8/19 이후 6주 넘게 조사가 없는 채로 10/7 조기투표에 들어간다.</p>
<p><strong>조지아는 하향 심사 3주차다.</strong> 신규 비당파 조사는 0건이고, 공화 성향 InsiderAdvantage 잭슨 48–46과 성향 미상 Big Data 50–50이 더해졌다 — 원천은 둘 다 비당파 재현으로 세지 않는다. <strong>10/6 ANF 타운홀이 선거 전 유일한 양자 대면으로 확정</strong>됐고, 등록 마감 10/5 · 조기투표 10/13이라 바텀스의 반전 기회는 사실상 10/6 하나다. 같은 주 상원은 오소프 +8~10 — 사이클 최대 분할투표가 유지된다. 원천은 12/1 결선 시나리오를 감시로 올렸다. 시장은 51¢에서 <strong>48¢</strong>로 내려가 50센트 밑이 됐다.</p>
<p><strong>알래스카는 구도가 확정됐고, 같은 주에 한국 변수가 들어왔다.</strong> 10/4 등록·사퇴 마감까지 공화 3인(윌슨·브론슨·테일러) 중 누구도 사퇴하지 않았다. Cygnal(공화 성향 추정, 9/24~27)은 크라이스톰킨스 44 – 윌슨 24 – 기타 공화 합 17 – 미결정 15를 냈다 — 윌슨이 8월 예비 10%에서 24%로 올랐고, 미결정층의 60%가 트럼프 투표자라는 우편향이다. 원천은 “공화가 윌슨 뒤로 결집하면 경합권”이라는 시나리오의 첫 수치로 읽는다. <strong>한국 LNG 투자 발표는 주지사 레이스에서는 초당적으로 작동했다</strong> — 후보 4인 전원이 사업 자체를 환영했다. 밴스 10/5, 트럼프 10/16(예상) 방문이 예정돼 있다.</p>
<p><strong>Cook이 10/1 플로리다·텍사스 주지사를 Likely R → Lean R로 옮기며 “트럼프 낮은 지지율의 하위 선거 파급”을 명시했다.</strong> 원천은 이것을 “등급기관이 환경→주지사 전달 함수를 공식 채택한 첫 사례”로 기록하고, 두 주를 1순위로 올리는 것은 사바토 등급 확인까지 보류했다. <strong>이 사이트 피드는 그 보류 조건 하나를 풀어 준다</strong> — 사바토 FL·TX는 피드상 9/22부터 Lean R이다(아래 불일치 ③). (<a href="https://maristpoll.marist.edu/polls/midterm-elections-in-ohio-september-2026/">Marist OH</a> · <a href="https://static.foxnews.com/foxnews.com/content/uploads/2026/10/fox_september-24-28-2026_iowa_topline_october-1-release.pdf">Fox IA 토플라인</a> · <a href="https://maristpoll.marist.edu/polls/midterm-elections-in-michigan-september-2026/">Marist MI</a> · <a href="https://law.marquette.edu/poll/2026/09/30/mlsp91-press-release/">Marquette WI</a> · <a href="https://www.cygn.al/wp-content/uploads/2026/10/AK_GOV_Memo.pdf">Cygnal AK</a> · <a href="https://thecookpoliticalreport.substack.com/p/texas-and-florida-governors-races">Cook FL·TX</a> · <a href="https://actonforgovernor.com/ratings-change-larry-sabatos-crystal-ball-moves-ohio-governors-race-to-toss-up/">Acton 캠프 — Sabato 9/22 전재</a> · <a href="https://www.walb.com/2026/10/02/how-watch-bottoms-jackson-face-off-town-hall-style-debate-oct-6-walb/">WALB — GA 타운홀</a>)</p>
<hr>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>28주차(9/28~10/4) 거시 환경은 ’마지막 버팀목이 빠진 주간’이었다 — 선거 전 마지막 9월 고용보고서가 비농업 +2.9만 명(예상 약 +8.4만)·실업률 4.2%·실질임금 잠식(임금 3.0% &lt; 물가 3.4%)·두 달 합산 −6만 하향 수정으로 착지하면서, ’물가는 아프지만 고용은 견조하다’는 여당의 유일한 실물 방어선이 제거됐고, 트럼프 순지지율은 Silver Bulletin 기준 −22.4에서 −22.7로 사상 최저를 재경신했으며(경제 지지 31%, Quinnipiac 기준 양 임기 최저), 제너릭 밸럿은 D+8~8.9(LV 보정 D+8.8)의 사이클 최고 고원을 4주째 되돌림 없이 유지했다.</strong> 전쟁 변수는 대통령이 이란의 호르무즈 재개방안 거부를 유지하고 “중간선거 이후 공격 재개”를 재공언하며 항모 3개 전단을 증강 배치함으로써 선거일까지 고정됐고, 브렌트유는 $100 안팎 고원으로 되돌아와 10/14 CPI가 완화가 아니라 고점을 측정하게 됐다. 반증 재료는 실재한다 — 8월 PCE가 예상을 하회(3.4%, 근원 3.0%)했고 FOMC 기대가 ’추가 인상 70%’에서 ’동결 79.5%’로 반전되며 금리 채널의 추가 악화가 멈출 수 있는 첫 신호가 나왔다 — 그러나 이는 금융 조건의 완화이지 체감 생활비의 완화가 아니며, 고용 쇼크 이후 실사된 여론조사는 아직 없다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(중~강) — 전주 판정 유지, 확신도 유지~소폭 상승(확신의 대상에 ’드라이버 확장: 물가 단일 전선 → 물가+고용 복합 전선’이 추가). 직전 주 대비 변화 방향: 수준은 유지, 구성은 악화 — 남은 반전 경로는 10/28 FOMC 동결의 서사 효과와 유가 고원의 조기 해소뿐이나, 후자는 대통령 자신의 전쟁 결정으로 막혀 있다.</strong> (인용: <code>national_weekly/2026-10-04</code> §6)</p>
</blockquote>
<p>여기에 세 가지를 덧붙인다.</p>
<p>첫째, <strong>원천의 판정 강도가 전주 ’강’에서 이번 주 ’중~강’으로 적혀 있다.</strong> 원천 스스로 “전주 판정 유지”라고 쓰므로 이 사이트는 이것을 후퇴로 읽지 않는다. 다만 이유는 기록해 둔다. 이번 주 새 증거의 대부분은 <strong>아직 여론에 도착하지 않은 사건</strong>이다. 고용 쇼크는 금요일(10/2)에 나왔고, 그 뒤에 실사된 조사는 없다. 이번 주 수치(−22.7, D+8.9)는 고용 쇼크 이전 데이터로 만든 값이다. 9/17 충격(연준 인상·유가 급등)이 1~2주 시차로 지지율에 착지했던 전례를 원천이 적어 두었다. 이번에도 같은 시차라면 판정은 다음 주 조사가 정한다.</p>
<p>둘째, <strong>반증 재료의 무게중심이 ’유가’에서 ’금리’로 옮겨 갔다.</strong> 전주 원천의 가장 무거운 반증은 ’원유 정점 통과’였는데, 이번 주 브렌트가 $100 고원으로 돌아오며 사라졌다. 대신 PCE 예상 하회와 FOMC 동결 기대가 그 자리를 채웠다. 그러나 이것은 <strong>유권자가 주유소와 마트에서 체감하는 경로가 아니다.</strong> 10년물이 오히려 20년 최고(5.29%)로 오른 것도 같은 한계를 보여 준다. 시장은 고용 쇼크에 주가 상승(S&amp;P +0.96%)으로 반응했다 — 나쁜 고용이 금리 완화 기대로 읽힌 것이다. 시장의 반응과 유권자의 체감이 다시 반대로 갔다.</p>
<p>셋째, <strong>선거 전 지표 달력이 고정됐다.</strong> 남은 30일에 나오는 큰 지표는 10/14 9월 CPI(유가 고원을 측정)와 10/28 FOMC 둘이다. 고용보고서는 더 없다. 원천의 정리대로 남은 반전 경로는 FOMC 동결의 서사 효과뿐이고, 유가 경로는 대통령의 전쟁 결정이 막고 있다. 그리고 <strong>선거는 사전투표 구간에 들어섰다</strong>(미시간 부재자 용지 발송 완료, 이어 오하이오 10/6 · 애리조나 10/7 · 조지아 10/13 · 텍사스 10/19). 현재 환경의 일부가 매일 확정 표로 잠기고 있다.</p>
</section>
<section id="상원-산수-등급은-멈췄고-측정값은-움직였다" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-등급은-멈췄고-측정값은-움직였다">상원 산수 — 등급은 멈췄고, 측정값은 움직였다</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 50–50은 밴스 부통령의 캐스팅보트로 공화 다수이므로 부족하다. 감시 9주 = 사수 3곳(GA·MI·NH) + 핵심 탈환 4곳(NC·ME·AK·OH — 모두 가져가면 정확히 +4) + 확장 2곳(TX·IA).</p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 9/23·사바토 9/22 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .50 + IA .50</td>
<td><strong>+3.25석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td>GA 0 + MI .375 + NH .375</td>
<td><strong>−0.75석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.5석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>같음</td>
<td>+2.5석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td><strong>Cook·Sabato 이동 0건</strong></td>
<td><strong>0</strong></td>
</tr>
</tbody>
</table>
<p><strong>산수는 한 칸도 움직이지 않았다.</strong> 원천 상원 브리핑은 같은 방식으로 <strong>+2.4석</strong>(범위 +1.5~+3.25)을 적고, 탈환 확률을 등급 가중 기준 <strong>35~45%(중심 40 안팎)로 유지</strong>했다. 차이는 3주째 사바토 뉴햄프셔 한 칸이다(원천 Toss-up / 피드 Lean D). 결론은 어느 쪽이든 같다 — +4에 미달한다.</p>
<p><strong>그런데 원천은 “평균은 유지, 구성은 바뀌었다”고 쓴다.</strong> 원천의 정리를 옮긴다. 사수 라인은 GA·MI 두 곳이 사실상 완성됐고, NC는 ‘돈의 자백’ 2차로 사실상 확보에 가까워졌다. 그래서 하방 꼬리는 짧아졌다. 대신 +4에 필요한 마지막 조각은 <strong>ME(동률) · OH(괴리 최대) · AK(역류)</strong> 세 동전 던지기와 TX·IA 확장로 사이에 더 넓게 흩어졌다. 원천의 Base 시나리오 문장은 이번 주 이렇게 좁아졌다 — <strong>“알래스카를 지키고, 오하이오를 되돌리고, 메인에서 콜린스의 막판 상회를 재연한다.”</strong> Bear는 “추가로 좁아졌다”고 적혔다.</p>
<p>이번 주 이 표에 들어가지 않은 이동이 있다. <strong>Inside Elections가 10/2 상원 5곳을 전부 민주 쪽으로 옮겼다</strong>(GA·NC Lean D · MI Tilt D · AK Toss-up · TX Tilt R). 이 사이트의 산식은 Cook·Sabato 두 기관만 쓰므로 반영되지 않는다. 원천은 이 이동을 기록하지 않았다. 원천이 다음 등급 갱신에서 민주 방향 압력이 가장 크다고 본 두 곳(NC·MI)이 IE에서는 이미 움직였다.</p>
<p>네 종류의 숫자는 이번 주 <strong>셋이 올랐고 하나는 그대로다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>64¢</strong></td>
<td>62¢</td>
<td>거래액 $572만·미결제 $298만, 3주 연속 상승. 원천은 이번 주 Kalshi·Polymarket·FLIPR·DDHQ의 신규 수치를 확인하지 못했다고 적는다 — 이 사이트 값은 10/4 공개 API 직접 취득분이다</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (Decision Desk HQ)</td>
<td><strong>56.0%</strong> (평균 의석 D 51 – R 49)</td>
<td>54.0%</td>
<td>모델 갱신 10/4. 3주 연속 상승인데 <strong>평균 의석은 4주째 D 51</strong>이다</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>72.9%</strong> (예상 의석 D 52.7 – R 47.3)</td>
<td>70.7%</td>
<td>Infogram 라이브 시계열 직접 취득(마지막 관측 10/4, 140점). 4주 연속 상승</td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.5석</strong></td>
<td>+2.5석</td>
<td>이번 주 Cook·Sabato 이동이 없어 그대로다. 서수적 등급을 확률로 환산한 값이라 전국 환경이 들어갈 자리가 구조적으로 없다</td>
</tr>
</tbody>
</table>
<p><strong>순서는 3주째 같다 — 56 &lt; 64 &lt; 72.9.</strong> 시장이 두 모델 사이에 있고, 두 모델의 격차는 16.9%p(전주 16.7%p)다. 원인은 데이터가 아니라 가정이라는 판독도 그대로다.</p>
<p><strong>이번 주 가장 눈여겨볼 숫자는 알래스카 시장가다.</strong> 원천은 알래스카를 “민주 우호 흐름의 유일한 역류”로 적었다. 보도 이후 조사 두 건이 설리번 쪽이고, 백악관발 LNG 호재도 설리번에게 갔다. 그런데 같은 주 <strong>Kalshi 알래스카는 71¢에서 74¢로 올랐고, Inside Elections는 Tilt R에서 Toss-up으로 민주 쪽에 올렸다.</strong> 조사와 시장·등급이 반대로 움직인 것이다. 이 사이트는 어느 쪽이 맞는지 판단하지 않는다. 대신 다음 두 가지를 확인 대상으로 남긴다. 하나는 두 조사(Trafalgar·Quantus)가 모두 공화 성향이거나 집계 경유라는 점이다. 다른 하나는 원천이 접근하지 못한 Political Wire 10/3 “Peltola Leads” 조사다. 알래스카의 순위선택투표(RCV)와 동명이인(2.8%) 변수 때문에 1순위 수치의 예측력이 제한적이라는 원천의 유보도 함께 적어 둔다.</p>
</section>
<section id="전주-관전-포인트-채점" class="level2">
<h2 class="anchored" data-anchor-id="전주-관전-포인트-채점">전주 관전 포인트 채점</h2>
<p><strong>전주에 이 사이트가 적어 둔 관전 포인트가 이번 주에 어떻게 풀렸는지 기록해 둔다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>전주 관전 포인트</th>
<th>결과</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>메인 — ProPublica 보도 이후 첫 비당파 조사(세 갈래: 콜린스 우위 · 잭슨 복귀 · 동률 고착)</strong></td>
<td><strong>세 번째 갈래로 착지했다.</strong> CBS/YouGov 50–50. 원천은 Bear의 1번 기둥(‘콜린스 우위 확인’)이 실현되지 않았다고 판정했다</td>
</tr>
<tr class="even">
<td><strong>오하이오 — 평균 +4 압축의 실사 확인</strong></td>
<td><strong>확인도 기각도 아니다.</strong> Marist +8 · Suffolk +3이 압축을 반박하고 InsiderAdvantage +1이 뒷받침한다. 괴리가 감시 9주 중 최대로 커졌다. 판정은 트럼프 10/3 유세 이후 첫 조사로 넘어간다</td>
</tr>
<tr class="odd">
<td><strong>미시간 — Torchlight R+1.3 대 Suffolk +7 판정</strong></td>
<td><strong>엘사예드 쪽으로 판정됐다.</strong> Fox +1 · Marist +7 · Trafalgar +2. 원천 집계로 비당파 4연속 엘사예드 우위다</td>
</tr>
<tr class="even">
<td>뉴햄프셔 — 괴리 4주차, NRSC 자금 유입 여부</td>
<td><strong>풀리지 않고 5주차로 넘어갔다.</strong> 외곽자금 약 $5,000만(대부분 반파파스)이 확인됐다. Kalshi는 86¢ → 85¢. Cook·IE 모두 Toss-up 유지</td>
</tr>
<tr class="odd">
<td>9/28 NY-17 첫 토론 → 토론 뒤 첫 조사</td>
<td><strong>열렸고, 조사도 왔다.</strong> 토론은 결정적 장면 없이 끝났고, 에머슨 콘리 48–46이 나왔다</td>
</tr>
<tr class="even">
<td>사바토·IE의 Cook 9/25 대응 회차</td>
<td><strong>사바토가 9/29 11건 전부 민주 방향으로 움직였다.</strong> Tier-1 PA-07·VA-02는 Cook보다 한 칸 앞서 Lean D로 갔다. TX-34는 여전히 Cook 미추종이다</td>
</tr>
<tr class="odd">
<td>9/30 GDP 확정치·8월 PCE · 3분기 FEC 마감</td>
<td><strong>PCE는 예상을 밑돌았다</strong>(3.4%, 근원 3.0%). GDP 확정치는 원천 주간에 별도 기재가 없다(미확인). FEC 보고는 10/15</td>
</tr>
<tr class="even">
<td><strong>10/2 상원 H.Con.Res.89 이란 전쟁권한</strong></td>
<td><strong>결과가 원천에 기록되지 않았다(미확인).</strong> 전국·상원·KW 주간 모두 이월 항목으로 남겼다</td>
</tr>
<tr class="odd">
<td>10/4 알래스카 주지사 등록 마감</td>
<td><strong>사퇴 0건 — 공화 3인 구도 확정.</strong> ‘3R → 2R’ 시나리오는 소멸했다</td>
</tr>
<tr class="even">
<td>주지사 — FOMC 후 WI·MI·NV 첫 조사, 조지아 재검토 신호</td>
<td><strong>셋 중 둘이 왔다(WI 압축 · MI 확대). 네바다는 4주째 0건.</strong> 조지아 Cook·Sabato 재검토 신호는 없었다</td>
</tr>
</tbody>
</table>
</section>
<section id="기록해-둘-불일치" class="level2">
<h2 class="anchored" data-anchor-id="기록해-둘-불일치">기록해 둘 불일치</h2>
<p><strong>① 사바토 뉴햄프셔(상원)</strong> — 3주째다. 원천은 Toss-up, 이 사이트 피드(사바토 스탬프 9/22, 10/4 재취득)는 Lean D다. 산수 +2.4(원천) 대 +2.5(피드)의 차이가 전부 여기서 나온다.</p>
<p><strong>② 원천은 사바토 알래스카(상원)를 이번 주에도 “Tilt R”로 적는다.</strong> 사바토는 Tilt 등급을 쓰지 않는다. 피드상 사바토 알래스카는 Toss-up이다. 같은 원천 표의 Cook 열은 정확하다.</p>
<p><strong>③ 원천이 “최우선 수집 필요”로 남긴 사바토 9/22 주지사 이동 잔여 3곳은, 이 사이트가 전주 피드로 이미 확인해 둔 값이다</strong> — 네바다 Lean R → Toss-up, 플로리다·텍사스 Likely R → Lean R. 원천은 이번 주 오하이오 이동만 캠프 전재 발표문으로 소급 확인했다. 따라서 원천이 FL·TX 1순위 편입을 보류한 이유(“사바토 등급 미확인”)는 피드 기준으로 풀린 상태다. 사바토 주지사 스탬프는 9/29로 한 번 더 바뀌었지만 감시 10주는 변동이 없다(움직인 곳은 감시 밖 네브래스카·버몬트). 사바토 애리조나(원천 Likely D / 피드 Lean D) 차이는 그대로다.</p>
<p><strong>④ Inside Elections 10/2 상원 이동 5건은 원천에 없다.</strong> 원천은 “Cook·Sabato 이번 주 신규 이동 없음”을 정확히 적었지만 IE는 다루지 않았다. 같은 날 IE는 주지사 알래스카(Lean R → Toss-up)와 오하이오(Tilt R → Toss-up)도 옮겼다.</p>
<p><strong>⑤ 알래스카 Trafalgar(9/22~24)의 표본·오차가 미시간 Trafalgar(9/7~9)와 똑같다.</strong> 원천은 알래스카 조사를 LV 1,079, ±2.9로 적는다. 이 사이트 DB에 이미 들어 있는 미시간 Trafalgar 조사도 LV 1,079, ±2.9다. 우연일 수 있지만 전사 오류일 수도 있다. 그래서 알래스카 행은 원문으로 표본을 확인하기 전까지 DB에 넣지 않았다. 득표율(46.8–45.5)은 위 표에 원천 값 그대로 적었다.</p>
<p><strong>⑥ 시장·모델 시점 차이.</strong> 원천은 이번 주 상원 시장·모델 신규 수치를 확인하지 못했다고 적는다(전주 기준 Kalshi 61%·DDHQ 52%). 하원 DDHQ는 원천 75%·D 234(9/28 갱신분), 이 사이트 직접 취득 76%·D 235(10/4 갱신분)다. <strong>이 사이트는 직접 취득한 원가격·원값만 싣는다.</strong> Cook 하원 NY-21(9/28) 이동은 자동 취득 보드(9/25)에 아직 없다.</p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (9/28~10/4).</strong> 주간 DB는 <strong>10건 추가</strong>(총 220행)로 4주 연속 줄었다(17→21→13→10). 그런데 이번 주는 건수보다 무대가 중요하다. 원천의 표현으로 <strong>“한국발 뉴스가 아니라 미국 선거 시계가 파일을 채운” 주</strong>였다. 유형도 안보 중심(9월 중순 주 12~13건)에서 <strong>통상 중심(이번 주 5건)</strong>으로 옮겨 갔다.</p>
<p><strong>첫째, 알래스카 LNG — 발표, 부인, 공격이 사흘 안에 이어졌다.</strong> 트럼프 대통령은 9/30 백악관에서 2,000억 달러 전략투자 패키지의 일부로 <strong>한국의 알래스카 LNG 약 540억 달러 투자</strong>를 발표했다. 그리고 경합 상원 현직 <strong>설리번(R-AK)을 “이 파이프라인의 전적인 공로자”로 호명</strong>했다. 서울의 대응은 세 단계였다. 김정관 장관은 현 비용 구조로는 연 200억 달러 송금 상한을 넘을 수 있다며 사업 축소를 요청했다. 이어 “발표가 합의를 훨씬 넘어섰다”며 러트닉 상무장관에게 공식 항의했다. 산업부가 공식 확인한 전략투자 사업은 텍사스 엔시널 1건뿐이고, 알래스카 LNG와 원전은 “추가 협의 대상”이다. <strong>그러자 펠톨라 지원 상원다수PAC(SMP)가 이를 “설리번이 표를 얻으려 되풀이한 엄청난 거짓말”로 공격했다.</strong> 지금까지 이 트랙의 기본값은 ’경합 후보의 한국 발언 0건’이었다. 이번 주 처음으로 한국 자본이 경합 레이스의 공수 양쪽 소재가 됐다.</p>
<p><strong>둘째, 트럼프가 관세를 지렛대로 꺼냈다.</strong> 10/2 “한국이 속히 합의하지 않으면 부과액을 두 배로 할 수 있다”고 했다. 현행 관세 15% 인하(25% → 15%)와 투자 약속의 연계를 직접 거론한 첫 발언이다. 같은 날 트럼프가 “한국 합의에 원유증진회수(EOR) 84억 달러 포함”이라고 게시하자 산업부가 “합의 대상 아님”이라고 정정했다 — <strong>사흘 새 두 번째 공개 부인</strong>이다. 국무부는 “윈-윈”으로 진화했다.</p>
<p><strong>셋째, 같은 한국 변수가 상원과 주지사에서 다르게 작동했다.</strong> 상원에서는 당파적이었다(설리번 수혜 서사 대 SMP 공격). 주지사에서는 초당적이었다 — 알래스카 주지사 후보 4인 전원이 사업 자체를 환영했고, ‘외국 자본’ 반대 프레임은 없었다. 쟁점은 투자 확정 여부다. 원천의 정리를 빌리면 <strong>서울이 물러서면 설리번은 소재를 잃고, 투자가 확정되면 펠톨라 측 공격이 무력화된다</strong> — 한국 정부의 협상 결정이 미국 경합 레이스의 메시지 지형에 직접 변수가 되는 구조다. 다만 상원 조사의 설리번 근소 우위 가운데 LNG 발표가 기여한 몫은 측정되지 않았다.</p>
<p><strong>넷째, 서울의 자체 기술 헤지.</strong> 이재명 대통령은 10/1 국군의 날 기념사에서 <strong>“2030년대 중반까지 우리 기술로 핵추진 잠수함 건조”</strong>를 처음 대통령 발언으로 못박았다. 9월 내내 기록된 한미 연료·농축·전작권 협의 교착에 대한 공개 헤지 신호다. 실제 추진에는 여전히 미국 동의와 의회 관여가 필요하다. 그 밖에 한화 필리조선소는 연 20척·인력 7,000~10,000명 목표를 처음 공개했다(펜실베이니아 — 후보 쟁점화는 미확인). 유엔사는 DMZ 지뢰 폭발을 정전협정 위반으로 공식 결론지었다(의회 반응 0건).</p>
<p><strong>미 의회·경합 후보의 한국 발언은 알래스카 밖에서는 0건이다.</strong> 하원 트랙은 7일 연속 [K] 단서가 없었고, 엔시널(223억 달러) 소재지 텍사스의 상원 후보 무반응은 4주째다. <strong>다음 주 검증 구간</strong>: 밴스 부통령 페어뱅크스 집회(10/5) · <strong>트럼프 알래스카 방문 예상(10/16, 미공식) — 선거 2주 반 전 추가 일방 발표 리스크가 가장 큰 지점</strong> · ‘두 배’ 위협의 구체화 여부 · 엔시널 MOU 발표 시점. (<a href="https://www.alaskasnewssource.com/2026/09/30/president-trump-announce-54-billion-investment-lng-pipeline/">Alaska’s News Source</a> · <a href="https://www.koreatimes.co.kr/southkorea/others/20261001/korea-protests-us-unilateral-announcement-on-alaska-lng-project">Korea Times — 항의</a> · <a href="https://alaskabeacon.com/2026/10/01/korean-officials-confirm-no-deal-exists-to-invest-in-alaska-natural-gas-pipeline/">Alaska Beacon — SMP</a> · <a href="https://en.sedaily.com/international/2026/10/03/trump-threatens-to-double-charges-if-korea-skips-alaska-lng">서울경제 — ‘두 배’</a> · <a href="https://www.koreatimes.co.kr/world/20261003/trump-says-s-korea-deal-keeps-getting-better-includes-84-bil-for-oil-recovery">Korea Times — EOR</a> · <a href="https://en.sedaily.com/politics/2026/10/01/lee-vows-nuclear-submarine-build-by-mid-2030s">서울경제 — 핵잠</a> · <a href="https://adn.com/politics/2026/10/02/south-korean-official-says-trump-announcement-on-alaska-lng-went-far-beyond-what-was-agreed">ADN</a>) (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>고용 쇼크(10/2)·트럼프 오하이오 유세(10/3) 이후 실사된 첫 조사들.</strong> 이번 주 모든 판단의 재검증점이다. 전국에서는 지지율 −22.7과 D+8~9 고원의 다음 단, 경합주에서는 제조업 주(OH·MI·WI·IA)의 반응을 본다. 9/17 충격은 1~2주 시차로 착지했다.</li>
<li><strong>10/5(월)</strong> — 조지아 유권자 등록 마감 · 밴스 부통령 알래스카 페어뱅크스 집회(LNG 추가 발언 여부).</li>
<li><strong>10/6(화) 집중일</strong> — 조지아 주지사 ANF 타운홀(선거 전 유일 양자 대면, 바텀스의 사실상 마지막 반전 기회) · 오하이오 조기투표 개시 · 아이오와 주지사 첫 토론 · 미시간 주지사 WOOD TV8 토론.</li>
<li><strong>10/7(수)</strong> — <strong>아이오와 상원 첫 TV토론(Iowa PBS)</strong> — Fox 투렉 +2 대 Quantus 힌슨 +1.3의 측정 격차를 가를 첫 대면 · 애리조나 조기투표 개시. 2차 토론은 10/13(WHO-TV).</li>
<li><strong>10/8(목)</strong> — 미시간·조지아 상원 토론 · 알래스카 주지사 4자 토론과 APOC 본안. 메인 상원 토론 일정은 원천이 재확인 중이다(【수집 필요】).</li>
<li><strong>알래스카 2차 검증</strong> — 보도 이후 비당파 조사, Political Wire 10/3 “Peltola Leads” 조사의 특정, LNG 발표의 지지율 전이 여부. 조사와 시장의 엇갈림이 어느 쪽으로 풀리는지.</li>
<li><strong>등급 갱신</strong> — Cook의 하원 PA-07·VA-02 대응(따라가면 토스업 22 → 20석), Cook·Sabato의 상원 NC·MI 상향 여부(IE는 이미 움직였다), 조지아 주지사 Toss-up 재검토, 아이오와·미시간 주지사 Likely D 상향 여부.</li>
<li><strong>10/13(월) 조지아 사전투표 개시</strong> — 그 전에 SLF 증액 명단에 조지아가 들어가는지. 이어 <strong>10/14 9월 CPI</strong>(선거 20일 전, 유가 고원 측정) · NY-17 2차 토론 · <strong>10/15 3분기 FEC 보고</strong> · 10/16 트럼프 알래스카 방문 예상 · <strong>10/19 텍사스 조기투표</strong> · 10/28 FOMC.</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 09/28~10/04 — 일간 전국·상원·하원·Korea Watch 각 7/7, 주정부 6/7(10/1 결손, 10/2호가 48시간 창으로 소급 포괄)). 환경 지표 — Silver Bulletin·FiftyPlusOne·WSJ·Quinnipiac·Harvard CAPS/Harris·NYT/Siena·Morris/Verasight. 경제 — 노동부(BLS 9월 고용·JOLTS)·BEA(8월 PCE)·컨퍼런스보드·미시간대·ADP·CME FedWatch. 상원 실측 — CBS News/YouGov·AARP(Fabrizio Ward–Impact Research)·Fox News(Beacon·Shaw)·Marist·Suffolk/USA Today·InsiderAdvantage·Trafalgar Group(공화 성향)·Rasmussen Reports(공화계)·Quantus Insights·Big Data Poll·UNH 서베이센터·Torchlight·co/efficient. 주지사 실측 — Marist(OH·MI)·Suffolk/USA Today(OH)·Fox News(IA·MI)·마케트 로스쿨(WI)·AARP·CBS/YouGov(ME)·Cygnal(AK, 공화 성향 추정)·InsiderAdvantage·Big Data Poll(GA). 하원 — 에머슨/PIX11(NY-17)·프랭클린앤마셜(PA-10)·매클로플린(CO-08, 공화 스폰서)·Impact Research/HMP·Tavern(FL-22)·Sabato 9/29·Almanac. 상원·주지사 등급 — Cook(상원 <strong>9/23</strong> · 주지사 <strong>10/1</strong>)·Sabato(상원 9/22 · 주지사 <strong>9/29</strong>)·Inside Elections(상원·주지사 <strong>10/2</strong>) 270towin 재게시분 자동 취득(10/4 실행 — 상원 10개 기관·주지사 8개 기관). 하원 등급 — Cook 9/25 보드 자동 취득(435개구 해독, 합계 435 검증 — 10/4 재취득도 같은 보드). 예측시장 — Kalshi 공개 API 원가격(10/4 — 상원 35/35·주지사 35/36, 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). 외부 모델 — Decision Desk HQ(상원·하원 모델 갱신 10/4)·Race to the WH(라이브 시계열 마지막 관측 10/4, 140점). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. <strong>이 사이트 조사 DB에 이번 주간 정리로 넣은 조사</strong>: 상원 ME CBS/YouGov · ME AARP · MI Fox · OH Suffolk(표본은 같은 조사 주지사 문항의 원천 기재값), 주지사 OH Marist · OH Suffolk · IA Fox · MI Marist · WI 마케트(LV). <strong>넣지 않은 조사</strong>: AK Trafalgar(표본·오차가 MI Trafalgar 9/7~9와 동일 — 원문 확인 전 보류) · 날짜나 득표율 없이 마진·등재일만 있는 상원 조사들 · MI Marist·Trafalgar 상원(원천이 상세를 이월 과제로 남김) · MI Fox 주지사(원문 URL 미확인) · MI Cygnal/Beacon·GA InsiderAdvantage·Big Data·OH Big Data·AK Cygnal 주지사(원문 미대조 또는 1순위 선택 기준). <strong>기록해 둘 불일치 6건은 본문 참조</strong> — 요지: ① 사바토 NH(상원) 원천 Toss-up / 피드 Lean D, ② 원천의 사바토 AK “Tilt R”은 사바토가 쓰지 않는 등급, ③ 원천이 미특정으로 남긴 사바토 9/22 주지사 잔여 3곳은 피드상 NV·FL·TX(FL·TX 사바토 Lean R 확인), ④ IE 10/2 상원 5건 이동은 원천 미기재, ⑤ AK Trafalgar 표본 의심, ⑥ 시장·모델 시점 차이. <strong>주의회 확인(10월 월 1회 항목)</strong> — 원천 주정부 주간에 Sabato 주의회 새 등급 라운드 보도가 없고, 토스업 9체임버·슈퍼다수 문턱이 불변이며 이번 주 특별선거 결과도 0건이다. 변동이 없어 <code>state_legislatures.json</code>은 손대지 않았다(특별선거 누계 민주 +13석/공화 0은 Ballotpedia 10/1 집계로 기존 서술과 같다). 이번 주 Kalshi·등급 취득에서 조회 실패로 빠진 항목은 뉴햄프셔 주지사 시장(2026 만기 계약 부재)뿐이다. <strong>이번 주 모든 수치는 10/2 고용 쇼크 이전에 실사된 조사에 기반한다.</strong> 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>