<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="등급이 한 주 만에 10건 민주 쪽으로 움직였는데, 그걸 의석으로 환산하면 4분의 1석이다. Cook이 텍사스·아이오와를 토스업으로 올리며 상원 전체를 ’공화 약간 우위의 토스업’으로 규정했고, 알래스카에서는 트럼프 지지 현직이 예비선거 실측에서 5.3%p 뒤졌다. 그런데 같은 주 예측시장의 상원 다수 가격은 오히려 2¢ 내렸다. 거시 쪽에서는 불리함의 ’질’이 바뀌었다 — 월마트 동일점포 +2.6%와 트럼프 지지 후보 예비선거 3연패로, 조사 응답에 머물던 압박이 소비와 투표라는 행동에 도달했다. 메인은 스캔들 이후 11일째 공개 조사가 없다.">

<title>22주차 · 08/17~08/23 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-aa6545344d23f4fd6946d43371182561.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">22주차 · 08/17~08/23</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-등급은-0건-움직인-건-예선-실측" id="toc-하원-등급은-0건-움직인-건-예선-실측" class="nav-link" data-scroll-target="#하원-등급은-0건-움직인-건-예선-실측">하원 — 등급은 0건, 움직인 건 예선 실측</a></li>
  <li><a href="#주지사-아이오와가-사이클-첫-민주-우위-경합이-됐다" id="toc-주지사-아이오와가-사이클-첫-민주-우위-경합이-됐다" class="nav-link" data-scroll-target="#주지사-아이오와가-사이클-첫-민주-우위-경합이-됐다">주지사 — 아이오와가 사이클 첫 ‘민주 우위’ 경합이 됐다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-등급-10건이-4분의-1석인-이유" id="toc-상원-산수-등급-10건이-4분의-1석인-이유" class="nav-link" data-scroll-target="#상원-산수-등급-10건이-4분의-1석인-이유">상원 산수 — 등급 10건이 4분의 1석인 이유</a></li>
  <li><a href="#텍사스-등급을-움직인-건-환경이-아니라-후보였다" id="toc-텍사스-등급을-움직인-건-환경이-아니라-후보였다" class="nav-link" data-scroll-target="#텍사스-등급을-움직인-건-환경이-아니라-후보였다">텍사스 — 등급을 움직인 건 환경이 아니라 후보였다</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">22주차 · 08/17~08/23</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    등급이 한 주 만에 10건 민주 쪽으로 움직였는데, 그걸 의석으로 환산하면 4분의 1석이다. Cook이 텍사스·아이오와를 토스업으로 올리며 상원 전체를 ’공화 약간 우위의 토스업’으로 규정했고, 알래스카에서는 트럼프 지지 현직이 예비선거 실측에서 5.3%p 뒤졌다. 그런데 같은 주 예측시장의 상원 다수 가격은 오히려 2¢ 내렸다. 거시 쪽에서는 불리함의 ’질’이 바뀌었다 — 월마트 동일점포 +2.6%와 트럼프 지지 후보 예비선거 3연패로, 조사 응답에 머물던 압박이 소비와 투표라는 행동에 도달했다. 메인은 스캔들 이후 11일째 공개 조사가 없다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 8월 17일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 8/17~8/23 일간 브리핑 29건(전국·상원·하원·Korea Watch 각 6/7 — 8/19 누락 · 주정부 5/7 — 8/17·8/19 누락, 8/20호가 back-fill해 뉴스 창 공백은 없음). 뉴스 기준: 미 동부시간 8/22(토) 저녁까지. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>등급 10건이 민주 쪽으로 갔는데, 산술은 4분의 1석 움직였다</strong> — 72시간 안에 4개 평가기관이 상원 등급 10건을 민주 쪽으로 옮겼고, 그 마지막이 <strong>Cook의 텍사스·아이오와 토스업 편입(8/20)</strong>이다. Cook은 이 이동으로 상원 전체를 “공화 약간 우위의 토스업”으로 규정했다. 그런데 같은 가중치(Lean 75%·Toss-up 50%)로 순 기대의석을 다시 계산하면 <strong>+1.88석 → +2.13석</strong>, 변화는 <strong>정확히 +0.25석</strong>이고 전부 Cook의 두 건에서 나온다. 다수에 필요한 <strong>+4</strong>와의 거리는 거의 그대로다.</li>
<li><strong>불리함의 ’질’이 바뀌었다 — 조사에서 행동으로</strong> — 월마트 미국 동일점포 매출이 <strong>+2.6%</strong>(2020년 이후 최저, 예상 3.7~3.8%)로 나왔고 CFO가 원인으로 “갤런당 4달러” 심리 임계를 명시했다. 같은 주 8/18 예비선거에서 트럼프 지지 후보 3명이 졌다(3주 누적 9패). 지지율 총량(<strong>−20.4</strong>)과 제너릭 밸럿(<strong>D+6.7</strong>)은 4주째 안 움직였는데, 움직인 것은 하위 집단과 행동 지표다.</li>
<li><strong>알래스카에서 나온 건 조사가 아니라 개표다</strong> — 8/18 top-4 예비에서 <strong>펠톨라 48.2 – 현역 설리번 42.9</strong>(개표 93%). 200만 달러+가 투입된 ’동명이인 스포일러’는 합산 약 3.5%로 실패했고 법무부는 전신사기 혐의 대배심 소환장을 발부했다. 다만 통합 예비 득표율은 본선 마진이 아니다 — 민주는 한 명에 결집했고 공화는 갈렸다.</li>
<li><strong>등급과 시장이 반대로 움직였다</strong> — Kalshi 상원 다수 가격은 민주 <strong>48¢ → 46¢</strong>로 내렸다. 개별 주 가격은 대부분 올랐는데(알래스카 +8¢·미시간 +5¢) 다수 계약은 내렸고, <strong>등급이 상향된 텍사스·아이오와는 오히려 1¢씩 내렸다.</strong> 같은 주에 Decision Desk HQ가 45%→46%로 올라 시장가와 같은 값이 됐고, 그 반대편에 Race to the WH 55.5%가 홀로 서 있다.</li>
<li><strong>미시간은 조사 4건이 11포인트 벌어졌다</strong> — TIPP D+3·폭스 R+4(<strong>실사기간이 같은데 부호가 반대</strong>)·AARP D+1·Susquehanna D+7. 이건 움직이는 판세가 아니라 하우스 이펙트 문제다. 초당 합동팀 AARP가 앵커이고, 그 내부의 세대 균열이 이 주의 핵심 변수다 — 로저스가 50세 이상 +9인데 <strong>투표 의향은 고령층이 훨씬 높다</strong>(86% 대 71%).</li>
<li><strong>메인은 11일째 아무 숫자도 없다</strong> — 8/12 스캔들 보도 이후 공개 조사가 하나도 나오지 않았다. 4개 기관이 10건을 옮기는 동안 <strong>메인만 아무도 옮기지 않았다</strong> — 핵심 탈환 대상에서 그 사실 자체가 이번 주의 신호다.</li>
<li><strong>주지사 — Cook이 아이오와를 사이클 첫 ‘민주 우위’ 경합으로 올렸다</strong> — Toss-up → <strong>Lean D</strong>(8/20). 사유는 관세·비료·디젤로, 같은 날 아이오와 상원을 옮긴 사유와 같다. <strong>상원·주지사가 동반 이동한 유일한 주다.</strong> 반대로 조지아는 상원 오소프 +7과 주지사 동률이 <strong>같은 조사 안에서</strong> 나왔다 — 티켓 분화의 가장 깨끗한 사례.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>트럼프 순지지도</td>
<td><strong>−20.4</strong> (38.1/58.5)</td>
<td>8/11 (Silver Bulletin, 페이지 수정 8/21)</td>
<td>주중 갱신 서술 없음 — <strong>고정 게시값</strong>으로 취급. <strong>평균 간 편차 7.4p</strong>(DDHQ −16.9 ~ FiftyPlusOne −23.8)가 이번 주의 발견이며 원인은 추세가 아니라 모집단 스크린이다. 방어 가능한 판독: <strong>전 성인 −21~−24 / 투표가능층 −16~−17</strong></td>
</tr>
<tr class="even">
<td>일반투표(제너릭)</td>
<td><strong>D+6.7</strong> (RCP 48.7/42.0)</td>
<td>8/19~8/22</td>
<td>독립 평균 4개가 <strong>D+6.0~6.7</strong>에 밀집(편차 0.7p) — FiftyPlusOne 6.1 · USPollingData 6.6 · RCP 6.7 · Silver Bulletin 6.7. 적극투표층 보정판은 별도로 D+8 부근(SB 8.1 · 에머슨 8). <strong>DDHQ가 제시한 상원 접전 임계선 D+7.5를 사이에 둔 위치</strong></td>
</tr>
<tr class="odd">
<td>공화 기반 강도</td>
<td>공화 지지층 내 지지 <strong>79%</strong>(2기 최저) · ‘강한 지지’ <strong>68→48</strong></td>
<td>8/17~</td>
<td>총량이 아니라 하위 집단이 움직인 주. 미시간대 공화층 소비심리 월간 <strong>−9.5p</strong>, 무당층 CNN/SSRS 시계열은 −35 → −52로 단조 악화</td>
</tr>
<tr class="even">
<td>소비 행동</td>
<td>월마트 미 동일점포 <strong>+2.6%</strong> (2020년 이후 최저)</td>
<td>8/20</td>
<td>예상 3.7~3.8%. CFO가 <strong>“갤런당 $4 심리 임계”</strong>를 명시적 원인으로 지목. 관세 환급 $29억으로 3분기 1.1만 품목 인하 예고 — 후반부 완충판</td>
</tr>
<tr class="odd">
<td>유가·휘발유</td>
<td>브렌트 <strong>$93.96</strong> (2주 연속 상승) · AAA 전국 평균 <strong>$4.1092</strong></td>
<td>8/21~22</td>
<td><strong>역대 최고 8월</strong>(1년 전 $3.138). 8월 말 $94는 9~10월 주유소 가격</td>
</tr>
<tr class="even">
<td>총량 경기</td>
<td>S&amp;P Global 8월 종합 PMI <strong>56.0</strong> (2022-04 이후 최강) · 필라델피아 연준 <strong>+47.4</strong> (5년 최고)</td>
<td>8/20~21</td>
<td>반증 재료. <strong>“총량 가속·가계 압박”의 괴리</strong>가 이 사이클 환경의 구조적 형태로 확정</td>
</tr>
<tr class="odd">
<td>재정·금리</td>
<td>30년물 <strong>5.30~5.31%</strong> (2007년 이후 최고) · 공공부채 첫 <strong>$40.047조</strong> 돌파</td>
<td>8/17~18</td>
<td>재무부가 바이백을 2배(회당 최소 $40억, 9/9~11/4) 확대했으나 효과가 <strong>한 세션 만에 소진</strong>, 주말 ~5.25%</td>
</tr>
<tr class="even">
<td>신규 관세</td>
<td>미·캐나다 협상 결렬 → <strong>50% 관세 발효</strong>, 약 $200억</td>
<td>8/22</td>
<td>유제품·주류·의류·건축자재 등 ‘매대에 뜨는’ 품목. 전가 시차 1~3개월 = <strong>10월 물가</strong>. 캐나다 보복은 9/8(농기계·펄프 등 공화 지지 지역 겨냥)</td>
</tr>
</tbody>
</table>
<p>지난주 이 자리에서 “물가는 안도했는데 소비가 꺾였다”고 썼다. 이번 주는 그 다음 장면이다. <strong>총량 지표는 오히려 강해졌다</strong> — PMI 56.0은 2022년 4월 이후 최강이고 필라델피아 연준은 5년 최고, 컨퍼런스보드 LEI는 6개월 증가율이 4년 만에 플러스로 돌아섰다. ‘침체’ 프레임은 성립하지 않는다. 그런데 같은 주에 월마트가 미국 동일점포 +2.6%를 냈고, CFO는 그 이유를 갤런당 4달러라는 심리 임계로 지목했다. <strong>경기는 가속하는데 가계는 눌린다.</strong> 이 괴리가 이번 사이클 환경의 임시 현상이 아니라 구조적 형태라는 것이 이번 주에 굳어졌다.</p>
<p>여기에 새 물가 채널이 하나 붙었다. 미·캐나다 협상이 깨지면서 8/22 자정에 50% 관세가 발효됐는데, 대상이 유제품·주류·의류·건축자재처럼 <strong>매대에서 가격표로 보이는 품목</strong>이다. 전가 시차 1~3개월을 감안하면 10월 물가다. 무역·관세는 이미 트럼프 순마이너스 이슈이고, 캐나다 보복관세(9/8)는 농기계·펄프처럼 공화 지지 지역을 겨냥한다. (<a href="https://www.cnbc.com/2026/08/20/walmart-wmt-q2-2027-earnings.html">CNBC(월마트)</a> · <a href="https://www.cnbc.com/2026/08/22/us-canada-trade-talks-collapse-ushering-in-wave-of-new-tariffs.html">CNBC(캐나다 관세)</a> · <a href="https://www.cnbc.com/2026/08/19/us-government-debt-passes-40-trillion-mark-for-the-first-time.html">CNBC($40조)</a> · <a href="https://gasprices.aaa.com/">AAA</a> · 상세 <code>national_weekly/2026-08-23</code>)</p>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p>등급(Toss Up/Lean)은 확률이 아니다 — 그리고 이번 주가 그 원칙이 왜 필요한지 보여준다. <strong>4개 기관이 72시간 안에 10건을 민주 쪽으로 옮겼다.</strong> 헤드라인만 보면 지도가 크게 흔들린 것처럼 보인다. 그런데 같은 등급을 확률로 환산해 순 기대의석을 계산하면 <strong>+1.88 → +2.13석</strong>, 주간 변화는 <strong>+0.25석</strong>이다. 이유는 두 가지다. 첫째, 10건 중 이 사이트의 자동 취득 피드가 <strong>이번 주 새 이동으로 확인한 것은 Cook의 2건(TX·IA)</strong>이다 — 사바토의 NC·AK·OH는 이 사이트 매트릭스에서 <strong>6월부터</strong> 그 값이었고, 인사이드일렉션스의 GA·NC·TX는 8/6자 피드에 이미 반영돼 있었으며, 폭스 피드는 아직 7/22자다. 둘째, Lean R → Toss Up 이동은 그 주의 민주 승률을 25%에서 50%로 올리는 것이고, 두 기관 평균으로는 한 건당 <strong>+0.125석</strong>이다. 등급 이동의 <em>건수</em>와 <em>의석 함의</em>는 서로 다른 단위다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 8/20 / Sabato 8/19)</th>
<th>시장 (Kalshi 8/23)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Lean D / Likely D</td>
<td>92¢ (=)</td>
<td><strong>InsiderAdvantage 오소프 50–43</strong>(8/16~17, LV 800). RCP +7.5와 함께 <strong>+7이 중심값</strong>. 코버리지에 도는 AARP 52–43(7/13~16)·폭스 56–43(6/23~27)은 <strong>재게시된 옛 조사</strong> (<strong>안정</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / Toss-up</td>
<td>61¢ (▲5)</td>
<td><strong>8월 4건이 11포인트 산포</strong> — TIPP D+3·폭스 R+4(동일 실사기간, 반대 부호)·AARP D+1·Susquehanna D+7. RCP D+0.7. 폭스가 8/17 Lean D→Toss-up으로 <strong>이번 주 유일한 친공화 이동</strong> (<strong>혼조</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Lean D / Lean D</td>
<td>91¢ (▲3)</td>
<td><strong>세인트앤셀름 파파스 48–41</strong>(8/17~18, LV 1,411, ±2.6) — 사이클 최대 표본이 편차를 정리. 같은 조사 주지사는 <strong>에이요트 R+11</strong> (<strong>소폭 강화</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D</td>
<td>91¢ (▼2)</td>
<td><strong>High Point 쿠퍼 50–45</strong>(8/3~12, LV 660, ±5.2) — 첫 실질 축소 신호이나 쿠퍼는 50% 유지. 8월 산포 D+5~12.5. 부재자 신청 <strong>9/4 개시</strong> (<strong>소폭 냉각</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss Up / Toss Up</td>
<td>69¢ (▲3)</td>
<td><strong>스캔들 보도 이후 11일째 공개 조사 없음.</strong> 4개 기관이 10건을 옮기는 동안 메인만 이동 0건. 콜린스 ‘All of Maine’ 버스투어로 공세 전환 (<strong>미확인</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss Up / Toss Up</td>
<td>61¢ (▲8)</td>
<td><strong>예비선거 실측 펠톨라 48.2–설리번 42.9</strong>(개표 93%). 동명이인 스포일러 합산 ~3.5%로 실패 + DOJ 대배심 소환장. RCV 시뮬 +1.6~+6 (<strong>강화</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss Up / Toss Up</td>
<td>52¢ (▲1)</td>
<td>Wedgewood 브라운 48–44(8/13 종료). <strong>집계기관끼리 부호가 갈린다</strong> — RCP +0.6 · PollingSource +5.3 · Pollsmax R+1.8. 감시 9주 중 편차 최대 (<strong>변동 없음</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td><strong>Toss Up (8/20↑)</strong> / Lean R</td>
<td>48¢ (▼1)</td>
<td><strong>Cook이 Lean R→Toss Up.</strong> 사유는 환경이 아니라 후보 자질. 광고비 <strong>210:1</strong>($2,500만+ 대 $11.9만), 공화 가을 선매 0원. 에머슨 팩스턴 47–46은 <strong>실사기간 상충(미확인)</strong> (<strong>등급↑, 시장↓</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td><strong>Toss Up (8/20↑)</strong> / Lean R</td>
<td>44¢ (▼1)</td>
<td><strong>Cook이 Lean R→Toss Up.</strong> 사유는 후보가 아니라 <strong>관세·유가·투입원가</strong>. 같은 날 주지사도 Lean D로 이동 — 동반 이동한 유일한 주. 신규 조사 없음 (<strong>등급↑, 시장↓</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 신규 조사는 <strong>미시간 3건과 뉴햄프셔·조지아·노스캐롤라이나 각 1건</strong>이다. 미시간이 특히 읽을 만하다 — <strong>TIPP/TechnoMetrica</strong>(8/6–10, RV 1,528, ±2.6) 엘사예드 45–42와 <strong>폭스뉴스</strong>(8/6–10, RV 1,006) 로저스 51–47은 <strong>실사기간이 같은데 부호가 반대</strong>다. 여기에 <strong>AARP/파브리지오 워드·임팩트</strong>(8/9–11, LV 877, ±3.3) 48–47과 <strong>Susquehanna</strong>(8/11–17, LV 800, ±3.46) 46–39가 더해져 극단 사이가 11포인트 벌어졌다. 실사창이 겹치는 조사들이 이만큼 갈리면 그건 판세가 움직이는 게 아니라 하우스 이펙트다.</p>
<p><strong>뉴햄프셔</strong>는 세인트앤셀름 조사센터(8/17–18, LV 1,411, ±2.6)가 이 사이클 이 주의 최대 표본·최소 오차로 파파스 48–41(수누누)·49–37(브라운)을 냈다. 그동안 이 주의 문제는 UNH +7과 에머슨 동률 사이의 편차였는데, 이 조사가 에머슨 쪽을 이상치로 밀었다. <strong>노스캐롤라이나</strong>는 High Point대(8/3–12, LV 660, ±5.2)가 쿠퍼 50–45로 사이클 첫 축소 신호를 냈다. 다만 실사창이 Carolina Journal/Harper(8/9–10, 51.5–39.0)와 거의 겹치는데 답이 7포인트 다르고, ±5.2에서 D+5와 D+11은 통계적으로 구분되지 않는다. 정직한 서술은 “한 주 만에 5포인트 움직였다”가 아니라 <strong>“참값은 한 자릿수 중후반이고 8월 조사들이 그 위치에 대해 서로 다르다”</strong>이다.</p>
<p>세 건은 <strong>일부러 이 사이트의 조사 DB에 넣지 않았다.</strong> 오하이오 Wedgewood(브라운 48–44)는 8/13 종료로만 보고되고 실사 상세가 공표되지 않았다. 미시간 TIPP의 주지사 문항(벤슨 D+16)과 위스콘신 TIPP(D+4)는 실사기간이 확인되지 않았다. 애리조나 Quantus(홉스 D+5.9)는 실사기간은 있으나 원문 릴리스를 확인하지 못하고 집계 사이트 수록으로만 도는 상태다. 넷 다 표의 서술에는 반영하되 데이터에는 넣지 않는다 — 날짜와 원문이 확인되지 않은 조사는 다음 주의 평균을 오염시킨다. (<a href="https://rollcall.com/2026/08/17/rating-changes-10-of-11-races-shift-toward-democrats/">Roll Call(등급 이동 10건)</a> · <a href="https://www.cookpolitical.com/analysis/senate/senate-overview/texas-and-iowa-senate-races-move-toss-races-governor-also-move">Cook(TX·IA)</a> · <a href="https://www.anselm.edu/about/anselmian-hub/news/new-saint-anselm-college-poll-finds-republicans-facing-midterm-headwinds-democratic-lead-widens">Saint Anselm</a> · <a href="https://thehill.com/homenews/campaign/6043934-cooper-leads-whatley-nc-senate/">The Hill(HPU)</a> · <a href="https://www.aarp.org/government-elections/michigan-election-poll-2026/">AARP(미시간)</a> · <a href="https://www.nbcnews.com/politics/2026-election/gop-sen-dan-sullivan-democrat-mary-peltola-advance-battleground-senate-rcna592389">NBC(알래스카 예비)</a>)</p>
</section>
<section id="하원-등급은-0건-움직인-건-예선-실측" class="level2">
<h2 class="anchored" data-anchor-id="하원-등급은-0건-움직인-건-예선-실측">하원 — 등급은 0건, 움직인 건 예선 실측</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>등급 이동</td>
<td><strong>Cook 토스업 19석(D4/R15) 멤버십 무변동.</strong> 하원 트랙이 8/21~23 사흘 연속 직접 대조해 확인했고, 무변동은 발행 공백이 아니라 판단이다(사바토도 8/20 FL-07·FL-25 등급을 명시적으로 유지)</td>
</tr>
<tr class="even">
<td>Cook 토플라인</td>
<td>Solid D 184 / Likely D 11 / Lean D 10 / <strong>Toss-up 19(D 4 · R 15)</strong> / Lean R 9 / Likely R 20 / Solid R 182 (8/13 기준, 자동 취득 — 합계 435 검증)</td>
</tr>
<tr class="odd">
<td>예선 실측</td>
<td><strong>코리 밀스(FL-07) 낙마</strong> — 일라이자 46.9–34.5. 이번 사이클 <strong>11번째</strong> 현역 탈락(1970년 이후 최다) · <strong>FL-25 모스코위츠 63–37</strong>로 DSA 도전자 제압</td>
</tr>
<tr class="even">
<td>편입 감시</td>
<td><strong>FL-14 1순위</strong>(벨트란(R) 공천 46–30 확정, 재획정 후 트럼프+10, 사바토 이미 토스업) · <strong>NC-11 2순위</strong>(사바토·IE Toss-up, 쿡만 Lean R) · ME-02(던랩 Red to Blue 편입, Likely R 탈피 여부)</td>
</tr>
<tr class="odd">
<td>구조 변수</td>
<td><strong>미주리 게리맨더 1심 통과(8/19)</strong> — 주대법원 변론 9/2·판결 시한 9/8. 원고 승소 없는 한 이번 사이클 지도 확정(재획정 공화 이동 +5~9석 고정)</td>
</tr>
<tr class="even">
<td>자금</td>
<td>DCCC ‘Red to Blue’ 5명 추가(총 <strong>37석</strong>, 4곳이 트럼프 두 자릿수 승리 지역구) vs NRCC 역대 최고 7월 누계 <strong>$9,060만</strong> — “당 위원회 자금은 공화, 예약 광고는 민주”</td>
</tr>
<tr class="odd">
<td>모델·시장</td>
<td>Kalshi 하원 다수 <strong>85¢</strong>(8/23, 전주와 동일) · DDHQ <strong>66%</strong>(원천 직접 취득, 모델 갱신 8/21 — 평균 의석 D 229 – R 206. 브리핑 원문 기재값은 61%·D 226으로, 이 사이트는 원천값을 싣는다) · Smarter.Vote 90.3%(AI 생성 명시 — 쿡과 동급 취급 금지) · FiftyPlusOne ~89% · Silver Bulletin 87% — <strong>중심 80% 안팎</strong>, 정태 등급가중 기대의석은 약 214석</td>
</tr>
</tbody>
</table>
<p>이번 주 하원의 이야기는 등급이 아니라 <strong>후보 자질 리스크가 두 방향으로 정리됐다</strong>는 것이다. 코리 밀스(FL-07)가 예선에서 졌는데, 결과는 역설적으로 민주당에 손해다 — 민주당의 FL-07 논리는 애초에 ’상처 입은 밀스’를 전제로 했으므로, 그가 사라지자 트럼프 +12~13 지역구는 표적 보드에서 멀어진다. 반대로 FL-25에서는 모스코위츠가 DSA 도전자를 63–37로 제압해, 고령·유대계 비중이 큰 트럼프+9 지역구에서 후보 교체 리스크를 스스로 닫았다.</p>
<p><strong>오하이오 7구는 이 사이트가 계속 지켜보는 결측치다.</strong> PollingSource 평균은 포인덱스터(D) 47.0–38.3으로 D+8.7인데, 그 평균에 들어간 <strong>4건이 전부 당파·스폰서 조사</strong>로 판명됐다. 독립 필드워크는 아직 0건이다. Cook이 8/10 여기를 두 단계 내려 사이클 첫 신규 토스업으로 만든 근거가 후보 개인 사정이었던 만큼, R+10.3 지역구에서 당파적 중력이 되살아나는지를 볼 독립 조사가 보드 전체에서 가치가 가장 높다. (<a href="https://rollcall.com/2026/08/18/florida-rep-cory-mills-loses-primary-as-wasserman-schultz-moskowitz-prevail/">Roll Call(밀스)</a> · <a href="https://rollcall.com/2026/08/20/dccc-adds-maines-matt-dunlap-and-4-others-to-red-to-blue-program/">Roll Call(Red to Blue)</a> · <a href="https://missouriindependent.com/briefs/missouri-supreme-court-sets-hearing-date-for-referendum-initiative-case-appeals/">Missouri Independent</a> · <a href="https://pollingsource.com/house/OH-07">PollingSource(OH-07)</a>)</p>
</section>
<section id="주지사-아이오와가-사이클-첫-민주-우위-경합이-됐다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-아이오와가-사이클-첫-민주-우위-경합이-됐다">주지사 — 아이오와가 사이클 첫 ‘민주 우위’ 경합이 됐다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (8/23)</th>
<th>전주(8/16)</th>
<th>등급 (Cook 8/20 / Sabato 8/13)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td>96¢</td>
<td>96¢</td>
<td>Solid D / Likely D</td>
</tr>
<tr class="even">
<td>애리조나</td>
<td>89¢</td>
<td>87¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="odd">
<td>미시간</td>
<td>87¢</td>
<td>87¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="even">
<td>아이오와</td>
<td><strong>78¢</strong></td>
<td>74¢</td>
<td><strong>Lean D (8/20↑)</strong> / Toss-up</td>
</tr>
<tr class="odd">
<td>위스콘신</td>
<td><strong>78¢</strong></td>
<td>73¢</td>
<td>Toss-up / Lean D</td>
</tr>
<tr class="even">
<td>조지아</td>
<td>59¢</td>
<td>60¢</td>
<td>Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>52¢</td>
<td>50¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>46¢</td>
<td>51¢</td>
<td>Likely R / Likely R</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td>42¢</td>
<td>37¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>32¢</td>
<td>31¢</td>
<td>Lean R / Lean R</td>
</tr>
</tbody>
</table>
<p><strong>Cook이 7주 침묵을 깨고 아이오와를 Toss-up → Lean Democrat으로 올렸다(8/20).</strong> 이번 사이클 어느 주지사 경합에서든 처음 나온 ‘민주 우위’ 판정이다. 사유는 에머슨 D+5와 무당파 이동, 그리고 관세·농산물 압박이다 — 전국 트랙이 추적하는 생활비 채널과 정확히 같은 원인이고, 같은 날 Cook은 아이오와 <strong>상원</strong>도 토스업으로 옮겼다. 감시 목록에서 상원과 주지사가 같은 날 같은 사유로 함께 움직인 주는 아이오와뿐이다.</p>
<p>그 반대편에 <strong>조지아</strong>가 있다. InsiderAdvantage 조사(8/16–17, LV 800)에서 상원은 오소프 50–43(D+7)인데 주지사는 잭슨 46.3 – 바텀스 46.2로 사실상 동률이다. <strong>같은 표본 안에서</strong> 두 레이스가 7포인트 갈렸다는 것은 이 접전이 정당 스윙이 아니라 후보 요인이라는 뜻이다. 뉴햄프셔는 더 극단적이다 — 세인트앤셀름 한 조사에서 상원 파파스 D+7과 주지사 에이요트 R+11이 동시에 나왔다. <strong>전국 환경이 D+6.7이어도 현직 주지사의 개인 브랜드는 그것을 상당 폭 상쇄한다.</strong></p>
<p>한 가지 정정을 적어 둔다. 이 사이트가 종합하는 주정부 트랙 원문은 사바토의 아이오와 주지사를 <strong>Lean R</strong>로 적고 “양사가 정면 교차하는 유일한 주”라고 서술했는데, 이 사이트가 자동 취득하는 270towin 재게시 피드(사바토 8/13자)에서는 <strong>Toss-up</strong>이다. Cook과 갈리는 유일한 주라는 사실은 같지만, 교차 폭은 원문보다 한 눈금 좁다. 이 사이트는 자동 취득 피드값을 싣는다.</p>
<p><strong>알래스카는 이 표에서 유일하게 시장이 내려간 주다</strong>(51¢ → 46¢). 8/18 top-4 예비에서 민주 후보 2명이 1·2위를 했는데도(Kreiss-Tomkins 21.62% · Begich 20.07%) 가격이 내린 이유는 총득표에 있다 — 공화 계열 합계가 66,743표로 민주 54,479표를 앞선다. 관건은 공화 단일화이고, 브론슨의 거취는 8/25 집계 후 결정, 사퇴 시한은 8/31이다. 위스콘신은 반대다 — Platform Communications(8/12–13, LV 500)가 크롤리 48–44로 <strong>크롤리–티파니 대진의 첫 본선 실측</strong>을 냈고 별개 조사인 TIPP도 D+4로 붙었다. <strong>8/26 Marquette가 예선 후 첫 확립된 비당파 검증</strong>이다. (<a href="https://thehill.com/homenews/campaign/6041925-cook-report-iowa-texas-democrat-governor-edge/">The Hill(Cook IA)</a> · <a href="https://alaskapublic.org/news/politics/elections/2026-08-18/kreiss-tomkins-begich-wilson-and-bronson-lead-in-early-governor-primary-results">Alaska Public Media</a> · <a href="https://www.wpr.org/news/crowley-leading-tiffany-four-points-new-poll">WPR(위스콘신)</a> · <a href="https://www.noblepredictiveinsights.com/post/katie-hobbs-leads-andy-biggs-in-the-grand-canyon-state">Noble Predictive(애리조나)</a>)</p>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>22주차(8/17~8/23) 거시 환경은 여당에 불리한 방향을 유지한 채, 불리함의 ’질’이 조사에서 행동으로 이동했다.</strong> 월마트 미국 동일점포 +2.6%(2020년 이후 최저)와 CFO의 “갤런당 4달러” 임계 지목으로 역대 최고 8월 휘발유($4.10대)가 소비 행동을 실제로 꺾고 있음이 확인됐고, 트럼프 지지 후보의 예비선거 3연패(3주 누적 9패)는 공화 기반 이완의 첫 행동 증거다. 지지율은 전 성인 −21~−24 / 투표가능층 −16~−17로 모집단별 이중 판독이 필요하며, 제너릭 밸럿은 독립 평균 4개가 D+6.0~6.7(LV 보정 D+8)로 수렴한 채 4주째 고착 — DDHQ의 상원 접전 임계선 D+7.5를 사이에 둔 위치다. 미·이란 MoU 무합의 만료와 “경제판 D-데이” 제재 격상(8/24 발표), 미·캐나다 50% 관세 발효(보복 9/8)로 유가·물가 상방 리스크는 10월까지 고정됐고, 테헤란이 미 중간선거를 명시적으로 기다린다는 보도까지 나왔다. 반증 재료(PMI 56.0 등 총량 경기 강세, LV 지지율 상단 방어, 월마트의 3분기 가격 인하 예고)는 수준을 방어할 뿐 방향을 바꾸지 못했다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(중~강) — 전주 판정 유지, 행동 증거 추가로 확신도 소폭 상승.</strong> (인용: <code>national_weekly/2026-08-23</code> §6-4)</p>
</blockquote>
<p>여기에 한 가지를 덧붙인다. 지난주 이 자리에서 백악관 참모진이 양원 상실 흐름을 내부적으로 인정했다는 CNN 보도를 두고, <strong>“−20의 지지율과 D+7의 환경을 차등 투표율만으로 뒤집겠다는 베팅”</strong>이라고 썼다. 이번 주 예비선거 결과는 그 베팅의 전제를 직접 건드린다. 트럼프 지지 후보 3명이 같은 날 졌고, <strong>2026년 누적 12패 가운데 9패가 최근 3주에 몰려 있다.</strong> 총 313건의 지지에 승률 약 96%라는 수준값만 보면 브랜드는 멀쩡하다. 신호는 수준이 아니라 시간 분포에 있다.</p>
<p>이게 왜 지지율 조사보다 무거운가. 기반 동원 전략은 <strong>저투표성향 지지층이 실제로 투표하러 나온다</strong>는 가정 위에 서 있는데, 공화 예비선거는 그 가정을 검증하는 가장 가까운 자연실험이다. 거기서 트럼프가 지목한 후보가 지고 있다는 것은, 여론조사에서 관측된 ’강한 지지 68→48’이 응답이 아니라 행동으로 나타나기 시작했다는 뜻으로 읽힌다. 다음 시험대는 <strong>8/25 사우스캐롤라이나 결선</strong>이다.</p>
</section>
<section id="상원-산수-등급-10건이-4분의-1석인-이유" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-등급-10건이-4분의-1석인-이유">상원 산수 — 등급 10건이 4분의 1석인 이유</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 단서 하나: NE·ID·SD의 민주 후보가 사퇴했고 무소속 3인 중 민주 코커스를 약속한 사람은 없다 — <strong>+4 산술에 우회로는 없다.</strong></p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 8/20·Sabato 8/19 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .375 + IA .375</td>
<td><strong>+3.00석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td>GA .125 + MI .50 + NH .25</td>
<td><strong>−0.875석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.13석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .25 + IA .25 − 0.875</td>
<td>+1.88석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td>Cook TX(+0.125) + Cook IA(+0.125)</td>
<td><strong>+0.25석</strong></td>
</tr>
</tbody>
</table>
<p><strong>등급 10건이 움직인 주의 산술 상승분이 4분의 1석이다.</strong> 이 숫자가 작아 보인다면, 그건 등급 이동의 건수와 의석 함의가 다른 단위이기 때문이다. Lean R → Toss Up 한 건은 두 기관 평균에서 정확히 +0.125석이고, 나머지 8건은 이 사이트의 등급 원장에서 이미 반영돼 있던 값이거나(사바토 NC·AK·OH는 6월분, 인사이드일렉션스 GA·NC·TX는 8/6자 피드분) 이 매트릭스가 추적하는 2개 기관 밖이다(폭스). 원문 트랙이 계산한 <strong>+2.0석</strong>과 이 사이트의 <strong>+2.13석</strong>은 0.13석 차이인데, 원문은 인사이드일렉션스의 Tilt 눈금을 함께 평균한 결과라 그 정도 차이는 방법 차이로 설명된다.</p>
<p>이번 주에는 네 종류의 숫자가 <strong>처음으로 두 무리로 갈렸다.</strong></p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>46¢</strong></td>
<td>48¢</td>
<td>거래액 $318만·미결제 $161만. 가격은 확률의 근사일 뿐</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (DDHQ)</td>
<td><strong>46.0%</strong> (평균 의석 D 50 – R 50)</td>
<td>45.0%</td>
<td>모델 갱신 8/21. 50–50 의석은 부통령 캐스팅보트로 <strong>공화 다수</strong>를 뜻한다</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>55.5%</strong> (예상 의석 D 50.9 – R 49.1)</td>
<td>55.2%</td>
<td>Infogram 라이브 시계열 직접 취득(8/23, 131점)</td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.13석</strong></td>
<td>+1.88석</td>
<td>서수적 등급을 확률로 환산 — 전국 환경이 들어갈 자리가 구조적으로 없다</td>
</tr>
</tbody>
</table>
<p><strong>시장과 DDHQ가 46에서 만났다.</strong> 지난주 이 자리에서 두 값의 3%p 격차를 두고 “독립적인 모델과 시장이 사실상 같은 곳을 가리킨다”고 썼는데, 이번 주에 그 격차가 0이 됐다. 그리고 그 반대편에 Race to the WH 55.5%가 홀로 남았다. 두 값의 차이는 9.5%p이고, 이건 데이터가 아니라 <strong>가정의 차이</strong>다 — 등급·시장은 각 주를 사실상 독립으로 보고, 여론조사 기반 모델은 전국 환경이 주별 결과를 함께 밀어 올린다고 본다. 어느 쪽이 맞는지는 11월에 판명되지만, 독자가 지금 할 수 있는 판단은 지난주와 같다. <strong>평균 내지 말 것.</strong></p>
<p>한 가지가 더 눈에 띈다. <strong>등급이 민주 쪽으로 크게 움직인 주에 시장은 반대로 갔다.</strong> Kalshi 상원 다수 가격은 48¢에서 46¢로 내렸고, 등급이 상향된 텍사스·아이오와는 각각 1¢씩 내렸다. 반면 등급이 안 움직인 알래스카(+8¢)·미시간(+5¢)·메인(+3¢)·뉴햄프셔(+3¢)에서는 올랐다. 개별 주 가격이 오르는데 다수 계약이 내리는 조합은 <strong>시장이 개별 레이스의 개선을 인정하면서도 그것들이 필요한 만큼 동시에 성립할 확률은 낮게 본다</strong>는 뜻으로 읽힌다 — 등급가중 산수가 구조적으로 만들어내는 것과 같은 결론이다.</p>
</section>
<section id="텍사스-등급을-움직인-건-환경이-아니라-후보였다" class="level2">
<h2 class="anchored" data-anchor-id="텍사스-등급을-움직인-건-환경이-아니라-후보였다">텍사스 — 등급을 움직인 건 환경이 아니라 후보였다</h2>
<p>Cook이 8/20 텍사스를 Lean R에서 Toss Up으로 옮긴 사유는 읽어볼 만하다. 전국 환경도, 제너릭 밸럿도 아니다. <strong>“팩스턴은 공화 자체 조사에서도 generic Republican보다 저조하다”</strong> — 후보 자질이다.</p>
<p>숫자가 그 판단을 뒷받침한다. 8월 광고비는 탈라리코 <strong>$2,500만+</strong> 대 팩스턴 <strong>$11.9만</strong>으로 약 <strong>210:1</strong>이고, 공화 쪽 가을 선매는 현재 <strong>0원</strong>이다. 순호감도는 탈라리코 +12(주 최고) 대 팩스턴 −13(주 최저)이고, 지난 분기 모금은 $30M 대 $9M이다. 1994년 이후 민주당이 주 전체 선거에서 이긴 적이 없는 주에서 이 정도 비대칭이 나오면, 등급 기관이 반응하는 것이 오히려 자연스럽다.</p>
<p>그런데 시장은 따라오지 않았다. Kalshi 탈라리코 가격은 49¢에서 <strong>48¢로 내렸다.</strong> 등급과 시장이 정확히 반대로 움직인 유일한 주다. 시장이 보고 있는 것은 아마 로브가 지목한 분기점일 것이다 — <strong>트럼프 슈퍼팩 5억 달러+의 텍사스 투입 여부</strong>이고, 시점은 9/1 전후 가을 선매다. 210:1이라는 숫자는 공화당이 아직 돈을 쓰지 않았다는 뜻이지 쓸 수 없다는 뜻이 아니다.</p>
<p>반대 신호는 하나뿐인데, 그것도 확정적이지 않다. 에머슨/넥스타의 팩스턴 47–46은 탈라리코의 7연속 우위를 끊은 유일한 조사인데 <strong>실사기간이 원천 파일 간에 상충한다</strong>(8/9~10 대 8/16~17). 이 사이트는 확인 전까지 미확인으로 둔다. RCP 평균은 여전히 탈라리코 +1.2다. 상세는 <a href="../states/tx.html">텍사스 State Focus</a>.</p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (8/17~8/23).</strong> 주간 DB 24행으로 <strong>4주 최고 밀도</strong>(13→13→24)이고, 중심은 안보·북한 동시 급등이다. 사건은 하나로 이어진다 — 트럼프가 <strong>UFS 개시 몇 시간 전에 연합훈련 “대폭 축소”를 지시</strong>했고(8/16 트루스소셜), 훈련은 11일에서 5일로 반토막 나고 2단계(반격)가 삭제된 채 <strong>8/21 조기 종료</strong>됐다. 조현 외교장관은 한미 어느 쪽 당국자도 사전에 몰랐다고 국회에서 답변했다. 지시 사유로 트럼프가 든 것 중 하나가 <strong>한국의 이란 비핵화 불참(“No thanks!”)</strong>이다 — 한반도 안보 공약이 무관한 전역의 지렛대로 전환된 첫 사례다.</p>
<p>같은 주에 트럼프는 <strong>연내 김정은 회동을 명시</strong>했고(“Yeah, I will be”) <strong>북핵 “57기”를 미 대통령 최초로 공개 특정</strong>했다(한국 정부 추정은 80~120기). 이 사이트는 “57기”를 확인된 사실이 아니라 <strong>주장으로 취급</strong>한다. WSJ은 11월 선전 APEC 계기 회동 추진을 보도했으나 공식 준비는 착수되지 않았다. 북한은 축소를 “불충분”으로 일축하고 8/20 SRBM 약 10발을 쐈다(연 11번째).</p>
<p><strong>선거와의 연결은 이번 주에 처음으로 당 메시지 층위로 올라왔다.</strong> 8/17 상임위 차원의 준비태세 언어에 머물던 민주당의 이의제기가 8/21 코커스 계정의 <strong>“김정은은 아무것도 내주지 않았다”</strong>로 전환됐고 슈머·밴 홀런·덕워스가 동시 게시했다. 프레임이 동맹관리가 아니라 ’거래 손실’이라는 점이 이전과 다르다. 공화당에서 이탈한 것은 <strong>톰 틸리스(R-NC)</strong> 한 명뿐이다 — 은퇴 예정이라 본인 선거 동기는 없지만, NC는 이 사이트의 Tier-1 감시주이고 하위 티켓 공화 후보들이 답해야 할 균열이 생겼다. <strong>민주당이 상원을 탈환하면 군사위원장은 리드</strong>이고, 이번 주 성명으로 훈련 축소와 주한미군 28,500명 하한 조항이 위원회 최우선 의제임이 확인됐다. 성명이 문안으로 바뀌는 관문은 <strong>9월 FY27 NDAA 조정회의</strong>다.</p>
<p>통상은 반대 방향으로 움직였다. <strong>여한구 통상교섭본부장이 전격 경질</strong>됐고 2천억 달러 패키지는 “예상보다 많은 쟁점”으로 9월 화상회의로 밀렸다. 조현 장관은 훈련 축소 지시에 <strong>“3,500억 달러 투자 이행 가속 압박” 성격</strong>도 있다고 국회에서 판단을 제시했는데, 준비태세와 통상이 하나의 협상임을 한국 각료가 공개 기록으로 확인한 첫 사례다. 반면 산업·장비 트랙은 정상 가동 중이다 — <strong>한화가 미 육군 MTC(K9MH) 시제 계약</strong>을 따내 한국 방산 최초의 완성 무기체계 미군 사업이 됐고, <strong>AIM-9X 103발 FMS</strong>(8/21, $1.25억)도 승인됐다. FMS가 평시대로 도는데 훈련만 잘렸다는 사실 자체가, 이번 축소가 부처를 경유한 태세 전환이 아니라 <strong>대통령 수준의 단일 파일 결정</strong>이었다는 방증이다. (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>8/24(월) — 베선트 이란 제재 발표.</strong> 주간 최대 분산 이벤트다. 관건은 <strong>중국 구매자 2차 제재 여부</strong>(이란 수출의 80%+, ~140만 b/d)이고, 그게 10월 유가 경로를 정한다. 생활비는 이 사이트가 감시하는 모든 주에서 1위 쟁점이다.</li>
<li><strong>8/25(화) — 세 개가 겹친다.</strong> <strong>SC 상원 공화 결선</strong>(달린 그레이엄 vs 노먼 — 3주 9패 이후 트럼프 지지 효력의 직접 시험대) · <strong>GA-13 하원 보궐 결선</strong>(투표율이 보궐 스윙 시계열의 입력값) · <strong>OK 주지사 공화 결선</strong> · <strong>AK 조기투표 최종 집계</strong>(브론슨 거취 = 공화 단일화 성사 여부).</li>
<li><strong>8/26(수) — 위스콘신 Marquette 첫 본선 조사.</strong> D+4 두 건(Platform·TIPP)과 RCP 평균 D+3.7을 확립된 비당파 기관이 검증한다. 같은 날 내구재 주문·소비자신뢰가 “월마트 대 PMI” 괴리의 가계 측 시험대다.</li>
<li><strong>메인 — 스캔들 이후 첫 공개 조사.</strong> 11일째 비어 있는 지도 최대 미확보 데이터. 탈환 축 전체의 향방이 여기서 갈린다.</li>
<li><strong>미시간 — 두 번째 LV 조사.</strong> AARP의 ‘50세 이상 R+9’ 세대 균열이 재현되는지, 아니면 하우스 아티팩트인지. 이 주의 핵심 미해결 변수다.</li>
<li><strong>9/1 전후 — 공화 가을 선매.</strong> MAGA Inc.(4억 달러 예고)와 SLF가 <strong>텍사스</strong>에 예약을 넣는지. 로브가 지목한 분기점이고, 210:1이라는 광고비 비대칭이 유지될지가 여기서 정해진다.</li>
<li><strong>9월 초 연쇄</strong> — 9/2 미주리 대법원 변론 → 9/4 NC 부재자 신청 개시(감시주 중 설득 기간이 가장 먼저 닫힘) → 9/8 미주리 판결 시한 + NH 예비선거 + <strong>캐나다 보복관세 발효</strong>(아이오와의 관세→투표 채널).</li>
<li><strong>한국 함의.</strong> 9월 FY27 NDAA 조정회의(주한미군 28,500명 하한·전작권 조항 대 대통령 축소 지시), 2천억 달러 트랜치 한미 화상회의, 두 번째 공화 상원 이탈 여부, 북미 정상회담 공식 준비 착수 여부(11월 선전 APEC 창).</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 08/17~08/23 — 일간 29/35건, 8/19 전 트랙 결손·주정부 8/17 추가 결손, 8/20호 back-fill로 뉴스 창 공백 없음). 환경 지표 — Silver Bulletin·RealClearPolling·USPollingData·FiftyPlusOne·Decision Desk HQ·Morning Consult. 경제 — 월마트 2분기 실적·S&amp;P Global 플래시 PMI·필라델피아 연준·재무부·AAA. 상원 실측 — InsiderAdvantage/James Magazine·High Point대·Harper Polling(Carolina Journal 의뢰)·TIPP/TechnoMetrica·AARP(파브리지오 워드/임팩트)·Susquehanna·세인트앤셀름 조사센터. 주지사 실측 — Platform Communications·InsiderAdvantage·Noble Predictive Insights·AARP. 상원·주지사 등급 — Cook(8/20)·Sabato(8/19)·Inside Elections(8/6)·Fox(7/22) 270towin 재게시분 자동 취득. 하원 등급 — Cook 8/13 자동 취득(435개구 해독, 합계 435 검증), 이번 주 토스업 멤버십 무변동. 예측시장 — Kalshi 공개 API 원가격(8/23, 상원 35/35·주지사 35/36 취득 — 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). 외부 모델 — Decision Desk HQ(모델 갱신 8/21)·Race to the WH(라이브 시계열 직접 취득 8/23). 등급 이동 건수는 이 사이트의 자동 취득 피드 기준이며, 원문 트랙의 “10건”과 세는 방식이 다르다(본문 참조). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. 다음 조사는 이 사이트 DB에 넣지 않고 서술로만 반영했다 — 오하이오 Wedgewood(실사 상세 미공표)·위스콘신 TIPP·미시간 TIPP 주지사(실사기간 미확인)·애리조나 Quantus(원문 릴리스 미확인). 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>