<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="지난주에 열린 두 개의 문 가운데 하나가 이번 주에 등급으로 번졌다 — Inside Elections가 뉴햄프셔를 토스업으로 내리면서 민주당 필수 사수 3곳 중 처음으로 등급상 토스업이 나왔다. 그런데 같은 날 같은 기관이 오하이오와 알래스카를 민주 쪽으로 올렸고, 예측시장은 뉴햄프셔에서 1센트도 움직이지 않았다. 조사가 한쪽을 가리키고 가격이 반대쪽을 가리키는 이 괴리가 지금 판 전체에서 가장 선명한 불일치다. 총량은 여전히 정지해 있다 — Cook과 사바토가 8월 하순 이후 상원 등급표를 한 칸도 바꾸지 않아 이 사이트의 등급가중 산수는 2주 연속 +2.25석으로 같다. 대신 바닥이 내려갔다. 트럼프 지지율의 개별 조사 바닥이 32~33%로 확정됐고, 전쟁 재개가 노동절 사상 최고 유류가로 물화됐으며, 미주리 대법원이 공화당 중간주기 재획정 지도를 이번 선거에서 처음으로 실효적으로 뒤집었다.">

<title>24주차 · 08/31~09/06 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1e3c7c377496ca8ba84db3a882ec124b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">24주차 · 08/31~09/06</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-지도-하나가-사라졌다" id="toc-하원-지도-하나가-사라졌다" class="nav-link" data-scroll-target="#하원-지도-하나가-사라졌다">하원 — 지도 하나가 사라졌다</a></li>
  <li><a href="#주지사-알래스카가-두-칸-벌어졌다" id="toc-주지사-알래스카가-두-칸-벌어졌다" class="nav-link" data-scroll-target="#주지사-알래스카가-두-칸-벌어졌다">주지사 — 알래스카가 두 칸 벌어졌다</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-두-기관이-멈추면-산수도-멈춘다" id="toc-상원-산수-두-기관이-멈추면-산수도-멈춘다" class="nav-link" data-scroll-target="#상원-산수-두-기관이-멈추면-산수도-멈춘다">상원 산수 — 두 기관이 멈추면 산수도 멈춘다</a></li>
  <li><a href="#시장이-갈린-방식-세-개의-탈환-의석에서-값이-빠졌다" id="toc-시장이-갈린-방식-세-개의-탈환-의석에서-값이-빠졌다" class="nav-link" data-scroll-target="#시장이-갈린-방식-세-개의-탈환-의석에서-값이-빠졌다">시장이 갈린 방식 — 세 개의 탈환 의석에서 값이 빠졌다</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">24주차 · 08/31~09/06</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    지난주에 열린 두 개의 문 가운데 하나가 이번 주에 등급으로 번졌다 — Inside Elections가 뉴햄프셔를 토스업으로 내리면서 민주당 필수 사수 3곳 중 처음으로 등급상 토스업이 나왔다. 그런데 같은 날 같은 기관이 오하이오와 알래스카를 민주 쪽으로 올렸고, 예측시장은 뉴햄프셔에서 1센트도 움직이지 않았다. 조사가 한쪽을 가리키고 가격이 반대쪽을 가리키는 이 괴리가 지금 판 전체에서 가장 선명한 불일치다. 총량은 여전히 정지해 있다 — Cook과 사바토가 8월 하순 이후 상원 등급표를 한 칸도 바꾸지 않아 이 사이트의 등급가중 산수는 2주 연속 +2.25석으로 같다. 대신 바닥이 내려갔다. 트럼프 지지율의 개별 조사 바닥이 32~33%로 확정됐고, 전쟁 재개가 노동절 사상 최고 유류가로 물화됐으며, 미주리 대법원이 공화당 중간주기 재획정 지도를 이번 선거에서 처음으로 실효적으로 뒤집었다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 9월 6일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 8/31~9/6 일간 브리핑 35건(전국·상원·하원·주정부·Korea Watch 각 7/7 — <strong>5개 트랙 전부 결손 없음</strong>). 뉴스 기준: 미 동부시간 9/5(토) 저녁까지. 선거일(11/3)까지 58일. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>뉴햄프셔가 필수 사수 3곳 중 처음으로 등급상 토스업을 받았다 — 그런데 시장은 1센트도 안 움직였다.</strong> 본선 조사가 2연속 공화 우위로 나온 끝에(UNH 45–43 · 공화계 Fabrizio Lee 37–36) <strong>Inside Elections가 9/3 Tilt D → Toss-up</strong>으로 내렸다. 나머지는 전부 반대편이다 — Cook·사바토 <strong>Lean D 유지</strong>, 세인트앤셀름 <strong>D+7</strong>, 그리고 Kalshi <strong>83¢·Polymarket 84%로 전주와 정확히 같다</strong>. <strong>여론조사 서사와 가격의 이 괴리가 지금 판 전체에서 가장 큰 불일치</strong>이고, 9/8 예비선거 투표율이 첫 실측 판정이다.</li>
<li><strong>같은 날 같은 기관이 반대 방향으로도 두 건을 옮겼는데 그건 보도되지 않았다</strong> — <strong>오하이오 Tilt R → Toss-up · 알래스카 Lean R → Tilt R</strong>, 둘 다 민주 방향이다. 9/3 일괄 조정의 순방향은 <strong>민주 2 대 공화 1</strong>인데 전국 매체가 다룬 것은 뉴햄프셔 강등뿐이었다. 부호가 뒤집혀 유통된 셈이다.</li>
<li><strong>총량은 2주째 정지해 있다 — 등급가중 순 기대의석 +2.25석으로 소수점까지 같다.</strong> Cook(8/20)과 사바토(8/26)가 그 뒤로 상원 등급표를 <strong>한 칸도</strong> 바꾸지 않았기 때문이다. 이번 주에 실제로 움직인 것은 Inside Elections인데, 이 산수는 두 기관 평균이라 그 이동이 들어갈 자리가 없다. IE를 제3 기관으로 넣어 보면 NH 하방과 OH·AK 상방이 대체로 상쇄돼 <strong>+2.0~+2.2 범위</strong>가 된다 — 지난주 경고한 “NH 등급 하락 시 +2.0 아래로 회귀”는 <strong>3분의 1만 현실화됐다.</strong></li>
<li><strong>환경은 한 단계 더 내려갔다.</strong> 개별 조사 바닥이 <strong>32~33%로 확정</strong>됐고(UMass −32 · 로이터/입소스 33% 3연속 · Economist/YouGov 33%), 전쟁이 한 달 소강을 깨고 재개되며 <strong>휘발유 $4.14(노동절 사상 최고)·경유 $5.85(사상 최고)</strong>로 물화됐으며, <strong>갤럽 정당일체감 D+10</strong>(2024년 말 R+4에서 14%p 반전)이라는 더 느린 층위의 지표가 얹혔다. 반대편에는 <strong>+16.2만 고용 서프라이즈</strong>와 <strong>하버드 CAPS/해리스 44%·LV R+2</strong>가 있다.</li>
<li><strong>하원에서는 지도 자체가 하나 사라졌다</strong> — 미주리주 대법원이 9/3 <strong>만장일치로</strong> 2025년 공화당 지도를 무효화했다. 11월은 2022년 선거구로 치러지고 지도는 주민투표에 부쳐진다. <strong>중간주기 재획정 지도가 이번 선거에서 실효적으로 뒤집힌 첫 사례</strong>이고, 유지되면 민주당의 실질 필요 순증이 약 <strong>+8에서 약 +7</strong>로 내려간다. 다만 9/5 밤 연방대법원 긴급 신청이 들어갔고 캐버노 대법관이 답변 기한을 <strong>9/7 정오</strong>로 지정했다 — 아직 끝나지 않았다.</li>
<li><strong>아이오와는 이번 주 유일하게 크게 빠진 주다.</strong> Cook의 토스업 이동 후 첫 양질 조사(Emerson/Nexstar)가 <strong>힌슨 50–45</strong>로 반대 방향이었고, 시장은 43¢ → <strong>36¢</strong>로 감시 9주 중 최대 낙폭을 냈다. 그런데 같은 표본의 <strong>주지사 문항은 샌드 +3</strong>이다 — 환경이 아니라 후보 경쟁력 문제라는 뜻이다.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>트럼프 순지지도</td>
<td><strong>−23.9</strong> (35.8/59.7)</td>
<td>9/1 (FiftyPlusOne)</td>
<td>주간 −23.2(8/29) → <strong>−23.9(9/1)</strong>로 <strong>−0.7p 악화</strong>. 주 후반은 사이트 접근 불가로 이월돼 대체 기준은 <strong>Silver Bulletin −19.5</strong>(9/4 — 3주 고정 게시값이 이번 주 갱신, 사상 최저 −20.6에서 +1.1p 반등)와 <strong>USPollingData −20.0</strong>(38.3/58.3, 9/5)이다. <strong>이번 주 실질 뉴스는 평균이 아니라 바닥의 확정</strong>이다 — UMass 애머스트 <strong>32/64(−32, 2기 최저)</strong> · 로이터/입소스 <strong>33%(3회 연속)</strong> · Economist/YouGov 33%로 양질 기관 셋이 동시에 30%대 초반을 찍었다. 반대편 상단은 하버드 CAPS/해리스 <strong>44%</strong>로, 같은 2주 안에 실사된 조사들 사이에 <strong>11%p 밴드</strong>가 열려 있다. 기준선 비교가 처음 명시적으로 확정됐다 — <strong>1기 동기(−11.6) 대비 약 8%p 열위</strong></td>
</tr>
<tr class="even">
<td>일반투표(제너릭)</td>
<td><strong>D+6.3</strong> (USPollingData 48.1/41.8)</td>
<td>9/5</td>
<td>9/1~9/5 <strong>닷새 연속 D+6.3</strong>, 회랑으로는 <strong>6주째</strong> 고착. Silver Bulletin D+6.6(LV 보정 <strong>D+7.6</strong>) · RCP D+5.7 · FiftyPlusOne D+6.3(9/2) · Morning Consult·DDHQ D+4. 지지율이 −0.7p 빠진 주에 밸럿이 정지했다는 사실이 중요하다</td>
</tr>
<tr class="odd">
<td><strong>투표층(LV) 모형 균열 — 이번 주 신규</strong></td>
<td>하버드 CAPS/해리스 전체 <strong>D+2</strong> / <strong>LV R+2</strong> vs Silver Bulletin LV 보정 <strong>민주 +1.0</strong></td>
<td>8/28~30 · 9/5</td>
<td>집계 간 스프레드가 <strong>D+4~D+8</strong>로 벌어졌는데 그 격차가 <strong>거의 전적으로 투표층 스크린의 산물</strong>이다. 같은 조작에서 방향이 5p 어긋난다. 감시 9주 중 <strong>네 곳(MI·AK·OH·IA)이 오차범위 안</strong>이라, 이 방법론 이견이 조사 간 격차보다 크다 — 이번 사이클 최대 미해결 쟁점이 이번 주 공식화됐다</td>
</tr>
<tr class="even">
<td>전쟁·유류가 — 이번 주 최대 악재</td>
<td>브렌트 $89대 → <strong>$95.63</strong>(9/2) · 휘발유 <strong>$4.14</strong> · 경유 <strong>$5.85</strong></td>
<td>9/2~9/5</td>
<td>8/30 라라크섬 타격으로 재개된 미·이란 상호 보복이 주말 유조선 전까지 <strong>5회전</strong>을 돌았다. 휘발유는 <strong>노동절 기준 사상 최고</strong>(종전 $3.82), 경유도 사상 최고다. <strong>경유는 소비자가가 아니라 투입비용이므로 물가 충격은 아직 CPI 앞에 있다.</strong> UMass에서 <strong>80%가 전쟁이 식료품·기름값을 올렸다</strong>고 답했다</td>
</tr>
<tr class="odd">
<td>금리</td>
<td>9월 인상 확률 <strong>57.5% → 66%(9/1) → ~49%(9/3) → ~60%(9/4)</strong> · 10년물 장중 <strong>4.818%</strong>(2023년 11월 이후 최고)</td>
<td>9/1~9/4 (CME)</td>
<td>48시간에 25%p를 왕복했다. 월러 이사가 9/3 “8월 물가 개선 시 동결 지지”로 워시 의장과 공개 균열을 냈고, 9/4 고용 서프라이즈가 확률을 되돌렸다. <strong>결정은 사실상 9/11 CPI에 위임</strong>됐다. 트럼프는 고용 호조 당일 “금리를 내리지 않으면 무역적자국과 교역을 중단하겠다”는 게시로 압박 광학을 자초했다</td>
</tr>
<tr class="even">
<td>고용 — 이번 주 최대 반증</td>
<td><strong>+16.2만</strong> / 실업률 4.1% (컨센서스 +5.3만) · 6·7월 합계 <strong>+5.5만 상향</strong></td>
<td>9/4 (BLS)</td>
<td>사이클 최대 서프라이즈이자 “아무도 채용하지 않는다” 프레임을 처음 반박한 달이다. 다만 <strong>증가분의 62%가 식당·지방교육 계절요인</strong>이고 정보산업은 −2.3만, <strong>임금 +3.1%가 물가를 밑돌아 실질임금은 계속 하락</strong>하며 참가율은 1월 대비 −0.5%p다. 선행 지표는 반대다 — ADP +3.8만(1월 이후 최저) · JOLTS 727만</td>
</tr>
<tr class="odd">
<td>물가·활동</td>
<td>ISM 서비스 <strong>55.4</strong> (물가 <strong>72.6 — 4년 최고</strong> / 고용 <strong>47.8 위축</strong>) · ISM 제조 54.6(신규주문 53.7, −3.0)</td>
<td>9/1~9/3</td>
<td>“산출은 좋고 체감은 나쁨”의 압축. 베이지북(9/2)은 연준 스스로 K자 경제를 서술했다</td>
</tr>
<tr class="even">
<td>구조 지표 — 이번 주 신규</td>
<td><strong>갤럽 정당일체감 D+10</strong> (성향 포함 민주 49 / 공화 39) · UMass <strong>의회 지지 22%</strong></td>
<td>9월 초</td>
<td>2015년 이후 최대이자 <strong>2024년 말 R+4에서 14%p 반전</strong>이다. 지지율보다 느리고 끈적한 층위에서 나온 신호라 <strong>밸럿 D+6이 오히려 보수적 추정일 가능성</strong>을 열지만, 정체성 이동이 투표율로 전환되지 않으면 무의미하다는 반론이 병존한다. 의회 지지 22%(강한 지지 3%)는 반현직 정서가 당파를 넘어 제도 전반을 향한다는 뜻으로, 역사적으로 <strong>다수당에 더 불리</strong>하다</td>
</tr>
<tr class="odd">
<td>제도전 — 두 건 동시</td>
<td><strong>9/4 우편투표 규칙 예비적 금지명령</strong> · <strong>9/3 미주리 지도 만장일치 무효화</strong></td>
<td>9/3~9/4</td>
<td>공화 측 구조적 완충 두 개가 같은 주에 약화됐다. 탈와니 판사는 USPS 최종규칙을 선거관리조항 위반으로 판시했고 법무부의 대법원 긴급신청은 실익을 잃었다. <strong>양건 모두 연방대법원 재상륙 대기</strong>이므로 되돌아올 수 있다</td>
</tr>
</tbody>
</table>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p>이번 주 상원 등급 이동은 <strong>Inside Elections 3건이 전부</strong>다(9/3). 그런데 이 사이트의 등급가중 산수는 Cook·사바토 두 기관 평균이라 <strong>그 이동이 들어갈 자리가 없고, 결과적으로 순 기대의석은 2주 연속 +2.25석으로 소수점까지 같다.</strong> 대신 읽어야 할 것은 두 가지다. 첫째, <strong>같은 날 같은 기관의 세 건 중 둘은 민주 방향(OH·AK)인데 보도된 것은 공화 방향 한 건(NH)뿐</strong>이었다. 둘째, <strong>시장이 갈렸다</strong> — 탈환 쪽 세 주에서 동시에 값이 빠졌는데(IA −7¢ · OH −2¢ · TX −2¢) 상원 다수 계약은 48¢로 정확히 그대로다. 사수 쪽 세 주(GA·MI·NH)는 사실상 무변동이다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook 8/20 / Sabato 8/26 / IE 9/3)</th>
<th>시장 (Kalshi 9/6)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Lean D / Likely D / Tilt D</td>
<td><strong>93.3¢ (▲0.6)</strong></td>
<td><strong>IE 9/3 일괄 조정에서 빠진 유일한 감시주.</strong> 창 내 신규 조사 없음. 오소프가 콜린스의 하원 윤리위 조사(윤리원 ‘상당한 근거’ 인정·소환장 권고)에 <strong>선서 증언</strong>을 요구하며 공세 지속, 백인민족주의 연계 보도 재점화. 현금 20:1(4,200만 대 210만), 양당 통틀어 상원 모금 1위 (<strong>안정</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss-up / Toss-up / Toss-up</td>
<td>64¢ (=)</td>
<td><strong>독립 조사 3연속 엘사예드.</strong> Epic-MRA 47–43(8/22–28)은 같은 기관 7월 조사에서 <strong>7포인트 스윙</strong>, MSU/IPPSR은 RV D+4 / LV D+5. 반증도 같은 조사 안에 있다(무슬림 후보 기피 37%). <strong>9/11 25주기에 맞춘 공세가 예고돼 있다.</strong> IE는 14개월째 Toss-up 동결 (<strong>강화</strong>)</td>
</tr>
<tr class="odd">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Lean D / Lean D / <strong>Toss-up (9/3↓)</strong></td>
<td>83¢ (=)</td>
<td><strong>필수 사수 3곳 중 첫 등급상 토스업.</strong> 본선 조사 2연속 공화 우위(UNH D−2 · 공화계 Fabrizio Lee D−1, 미결정 23%). 반대편에 세인트앤셀름 D+7·Cook·사바토 Lean D·<strong>시장 무반응</strong>. 민주 예비 파파스 47–만주르 34(4월 61–18에서 30p 압축). 법무부 참관인 배치. 9/8 예비 (<strong>등급 악화·시장 무변동</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Lean D / Tilt D</td>
<td>91.5¢ (=)</td>
<td><strong>9/4 전국 최초로 투표가 시작됐다</strong> — 100개 카운티 부재자 발송, 사전투표 10/15~31. 우편투표 규칙은 금지명령으로 차단됐고 NC 봉투는 USPS 사전 승인 유일. 단 같은 날 주 선관위가 <strong>3–2 당파 표결로 거부 기준을 강화</strong>했다. 신규 조사 없음 — <strong>6주 연속 무변동 자체가 발견</strong> (<strong>변동 없음</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss Up / Toss Up / Tilt R(낡음)</td>
<td>69¢ (▼1)</td>
<td><strong>스캔들 이후 조사 4주째 0건 — 이 지도 최대의 미확보 데이터.</strong> 잭슨이 9/4 토론 4건을 전부 수락했으나 <strong>전 일정이 사전투표 개시(10/5) 이후</strong>다. 자금난을 지상전으로 대체 중(르위스턴 타운홀 약 400명, 콜린스 자리엔 빈 의자). IE Tilt R은 <strong>2025-07-24 이후 미갱신</strong>이라 증거가 아니라 낡은 값이다 (<strong>미확인</strong>)</td>
</tr>
<tr class="even">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss Up / Toss Up / <strong>Tilt R (9/3↑)</strong></td>
<td>65¢ (▲1)</td>
<td><strong>9/1 본선 용지 확정 — 펠톨라 단독 대 공화 3인</strong>(현직 설리번·동명이인 댄 J. 설리번·하이키스). 민주 4위 사퇴로 표 분산 위험 소멸, <strong>동명이인 혼동 위험은 용지에 고정</strong>. IE 상향은 이번 주 가장 과소 보도된 사안. SLF 누적 1,700만 달러로 주 역대 최대 (<strong>강화</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss Up / Toss Up / <strong>Toss-up (9/3↑)</strong></td>
<td>54¢ (▼2)</td>
<td><strong>데이터센터 협공 완성.</strong> 브라운 신규 광고 + 유출된 NRSC 메모(“허스티드 목에 걸린 닻… 전통적 메시지보다 현저히 효과적”) + 그 전제를 인정하는 허스티드의 Ratepayer Protection Act. <strong>공격받는 쪽이 공격의 유효성을 문서로 자인한 사례.</strong> 비용도 있다 — 브라운은 건설직 노조와 정면 충돌 중 (<strong>등급↑·시장↓</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Toss Up / Toss Up / Lean R</td>
<td>48¢ (▼2)</td>
<td><strong>팩스턴이 토론을 전면 회피했다</strong> — CNN 거절 + 9/22 리오그란데밸리 수락 기한 도과. 탈라리코는 4건 수락 후 그것을 광고로 만들었다. <strong>당내 자금 설전도 공개됐다</strong>(로브 “시간이 없다”). 실측은 TPPF/Overton 44–43(성향 배분 시 50–50), RCP 평균 +2.4 (<strong>시장 −2¢</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Toss Up / Lean R / Tilt R</td>
<td><strong>36¢ (▼7)</strong></td>
<td><strong>이번 주 민주 지도의 최약 고리.</strong> Cook 이동 후 첫 양질 조사 <strong>Emerson/Nexstar 힌슨 50–45</strong>, 최근 4건 중 3건 힌슨 우위. 다만 <strong>같은 표본의 주지사는 샌드 +3</strong>이고 무당층은 주지사 +12 대 상원 +2, 분할투표 약 6% — 환경이 아니라 후보 경쟁력 문제다. <strong>9/8 캐나다 보복관세 발효</strong> (<strong>약화</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 이 사이트 조사 DB에 새로 들어간 본선 조사는 <strong>다섯 건</strong>이다 — 미시간 2건(Epic-MRA · MSU/IPPSR), 뉴햄프셔 1건(Fabrizio Lee), 텍사스 1건(TPPF/Overton), 아이오와 1건(Emerson/Nexstar).</p>
<p><strong>뉴햄프셔가 이 주의 사건이고, 그 사건의 정체는 “조사가 등급까지 갔는데 가격은 안 따라왔다”는 것이다.</strong> 지난주 UNH 그래닛스테이트가 시리즈 사상 처음 수누누 우위(45–43)를 냈을 때 이 자리에서 “등급이 조사에 후행하는 전형적 구간”이라고 썼다. 이번 주에 공화계 Fabrizio Lee(8/27–30)가 37–36으로 부분 재현했고, 그 끝에 Inside Elections가 9/3 Toss-up으로 내렸다. 여기까지는 예상대로다. 예상 밖은 <strong>시장이 83¢에서 소수점 하나도 안 움직였다</strong>는 사실이다 — 지난주 −8¢로 반응했던 그 시장이다. 두 가지 해석이 가능하다. 지난주에 이미 다 반영했거나, 아니면 시장이 세인트앤셀름 D+7 쪽을 믿고 있거나. <strong>9/8 예비선거 투표율이 그 판정 데이터다</strong> — 만주르 득표율이 UNH가 잰 13포인트 차를 검증하고, 양당 투표율 격차가 경쟁하는 LV 스크린의 첫 실측이 된다.</p>
<p><strong>같은 날 나온 나머지 두 건은 반대 방향이었는데 유통되지 않았다.</strong> Inside Elections는 9/3에 <strong>오하이오를 Tilt R → Toss-up으로, 알래스카를 Lean R → Tilt R로</strong> 올렸다. 순방향은 민주 2 대 공화 1이다. 그런데 전국 매체가 다룬 것은 뉴햄프셔 강등뿐이었다 — 이번 사이클 들어 등급 일괄 조정이 가장 선택적으로 보도된 사례다. 이 사이트가 이것을 기록해 두는 이유는 단순하다. <strong>같은 기관의 같은 날 판단을 부분만 인용하면 부호가 뒤집힌다.</strong> 다만 균형을 위해 반대쪽도 적어야 한다 — IE의 전체 지도에서 Tilt·Lean을 확정 처리하면 민주 순증은 <strong>약 +1</strong>로 필요치 +4에 크게 못 미친다. 즉 IE의 지도는 여전히 “전국 환경은 D+6인데 상원 지도가 그것을 흡수한다”는 Base 시나리오의 지도다.</p>
<p><strong>아이오와가 유일하게 크게 빠졌다.</strong> Emerson/Nexstar(8/31–9/1, LV 750)가 힌슨 50–45를 냈다. Cook이 8/20 토스업으로 올린 뒤 처음 나온 양질 조사가 반대 방향이고, 최근 4건 중 3건이 힌슨 우위다(+5/+4/+3 대 폭스 투렉 +4). 현재 데이터로는 <strong>8/20 Cook 이동이 추세의 시작이 아니라 정점이었을 가능성</strong>을 배제할 수 없다. 시장은 43¢ → 36¢로 감시 9주 중 최대 낙폭을 냈다. 그런데 하방을 막는 신호가 <strong>같은 표본 안에</strong> 있다 — 주지사 문항은 샌드 49–46이고, 무당층은 주지사 샌드 +12 대 상원 투렉 +2로 갈리며, 분할투표가 약 6%다. <strong>환경이 아니라 후보 경쟁력 문제</strong>라는 뜻이고, 그것은 남은 58일에 좁혀질 수 있는 종류다. 반대로 이슈 환경은 민주 쪽인데(캐나다산 관세 반대 58%·보복관세 우려 71%) 그 <strong>보복관세가 9/8 발효</strong>되므로, 다음 주가 ‘관세→투표’ 채널의 실전 개시다.</p>
<p><strong>미시간은 이제 리스크 목록에서 사실상 빠졌다.</strong> Epic-MRA(8/22–28)의 엘사예드 +4는 같은 기관 7월 조사(로저스 +3)에서 7포인트가 뒤집힌 것이고, MSU/IPPSR(8/10–20)은 등록유권자 D+4·적극투표층 D+5다. 8월 이후 독립 조사 3연속이다. 그래도 이 사이트가 미시간을 안전 목록으로 옮기지 않는 이유는 세 가지다 — MSU 같은 조사에서 <strong>무슬림 후보 기피 응답이 37%</strong>이고, 로저스가 무당파에서 앞서며, <strong>로저스·NRSC가 9/11 25주기에 맞춘 공세를 예고</strong>했다. 날짜가 박힌 리스크는 아직 검증되지 않은 리스크다. (<a href="https://insideelections.com/ratings/senate/">Inside Elections</a> · <a href="https://www.washingtonexaminer.com/news/campaigns/congressional/4713580/inside-elections-shifts-new-hampshire-senate-race-toss-up-john-sununu/">Washington Examiner(NH 강등)</a> · <a href="https://www.newsweek.com/chris-pappas-faces-second-polling-blow-in-new-hampshire-race-against-sununu-12400956">Newsweek(NH 조사)</a> · <a href="https://www.forbes.com/sites/saradorn/2026/08/31/latest-2026-senate-polls-el-sayed-leads-rogers-by-4-points-in-michigan/">Forbes(Epic-MRA)</a> · <a href="https://ippsr.msu.edu/news/msu-poll-shows-democrats-lead-republicans-coalesce-behind-rogers">MSU IPPSR</a> · <a href="https://emersoncollegepolling.com/iowa-2026-poll-hinson-leads-turek/">Emerson(IA)</a> · <a href="https://www.ncsbe.gov/news/press-releases/2026/09/02/voting-2026-general-election-begins-week-nc">NCSBE(투표 개시)</a> · <a href="https://www.nbcnews.com/politics/2026-election/alaska-finalizes-senate-race-3-republicans-2-dan-sullivan-1-democrat-rcna595617">NBC(AK 용지 확정)</a> · <a href="https://mainemorningstar.com/2026/09/04/maine-u-s-senate-candidates-agree-to-debates-though-format-remains-up-in-the-air/">Maine Morning Star(ME 토론)</a>)</p>
</section>
<section id="하원-지도-하나가-사라졌다" class="level2">
<h2 class="anchored" data-anchor-id="하원-지도-하나가-사라졌다">하원 — 지도 하나가 사라졌다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>미주리 — 이번 주 최대 구조 변수</strong></td>
<td><strong>9/3 주 대법원 만장일치 무효화.</strong> 연방 하원 재획정안도 주민투표 대상이고, People Not Politicians의 30만+ 유효 서명 제출로 2025년 지도는 2025년 12월부로 <strong>이미 정지 상태였다</strong>고 판시. 11월은 <strong>2022년 선거구</strong>로 치르고 지도 자체가 투표용지에 오른다. <strong>공화당 중간주기 재획정 지도가 이번 선거에서 실효적으로 뒤집힌 첫 사례</strong></td>
</tr>
<tr class="even">
<td>미주리 — 아직 안 끝났다</td>
<td>9/4 정지 신청 기각(이유 불기재) → <strong>9/5 밤 주 법무장관의 연방대법원 긴급 신청</strong> → <strong>캐버노 대법관이 반대 측 답변 기한을 9/7(월) 정오로 지정</strong>(주가 요구한 것보다 빠른 일정). 주 투표용지 마감 <strong>9/8</strong>, 주 요구 결정 시한은 보도가 9/13·9/14로 엇갈린다. 모두 9/19 재외·군인 용지 발송에서 역산한 시계다</td>
</tr>
<tr class="odd">
<td>필요 순증</td>
<td>명목 <strong>+3</strong> 불변. 실질은 이번 주부로 <strong>조건부 쌍</strong>이 됐다 — <strong>미주리 환원 유지 시 ~+7 / 연방대법원이 복원하면 ~+8.</strong> 메릴랜드 개헌안(9/3 등재 허용)은 효과가 <strong>2028년</strong>이라 이번 산술에 넣지 않는다</td>
</tr>
<tr class="even">
<td>Cook 토플라인</td>
<td>Solid D 184 / Likely D 12 / Lean D 9 / <strong>Toss Up 21 (D 5 · R 16)</strong> / Lean R 7 / Likely R 20 / Solid R 182 (8/25 보드, 자동 취득 — 합계 435 검증). <strong>8/31~9/6 7일 연속 무변동, 순변동 0건</strong></td>
</tr>
<tr class="odd">
<td>등급 이동</td>
<td><strong>Inside Elections 9/3 — 4건 전부 민주 방향</strong>(FL-14·TX-15 Lean R → Tilt R, MN-01 Safe R → Likely R, TX-35 Likely R → Lean R). <strong>역방향 0건인 주가 2주 연속</strong>이다</td>
</tr>
<tr class="even">
<td>평가기관의 침묵</td>
<td>Cook·사바토·IE <strong>모두 미주리를 2025년 지도 기준으로 평가 중</strong>이다. 환원이 확정되면 MO-02·03·05·06 재등급이 강제된다 — <strong>판결 후 사흘째 어느 기관도 움직이지 않은 것 자체가 “연방대법원 대기” 신호</strong>다</td>
</tr>
<tr class="odd">
<td>교차압력 지도</td>
<td><strong>반사회주의 결의안 220–192 가결(9/1).</strong> 민주 찬성 8명 중 셋이 민주 보유 토스업 주인공이다 — <strong>캐스터(FL-14)·곤잘레스(TX-34)·글루센캠프 페레스(WA-03) 찬성 / 캅투어(OH-09)·모스코위츠(FL-25) 반대.</strong> 유권자 신분증(SAVE법) 끼워넣기가 2025년 11월 유사 결의안의 민주 찬성 86명을 8명으로 붕괴시킨 가격표였다</td>
</tr>
<tr class="even">
<td>당내 분쟁</td>
<td>글루센캠프 페레스·골든(ME-02)의 규칙안 표결 이탈에 제프리스·클라크·아길라가 <strong>“중대한 신뢰 위반”</strong>을 선언하고 코커스 규칙위 회부·상임위 배정 박탈안을 회람했다. NRCC의 “독립 브랜드는 사기” 프레임에 대한 반증 자료이면서 동시에 당내 리스크라는 양날</td>
</tr>
<tr class="odd">
<td>셧다운 소멸</td>
<td><strong>CR 370–48 가결(9/1) — 12/11까지.</strong> 10월에 하원 지도를 재전국화할 수 있었던 유일한 확정 이벤트가 제거됐다. 방향으로는 <strong>공화당 하방 꼬리 하나가 잘린 것</strong>이므로 그렇게 적는다</td>
</tr>
<tr class="even">
<td>투표 실무</td>
<td>연방에서는 <strong>9/4 예비적 금지명령</strong>으로 우편투표 비중 큰 토스업(AZ·CA·CO·WA·IA·PA·FL-14)의 리스크가 일단 봉인됐다. 반대로 주 단위에서는 <strong>NC가 발송 당일 3–2로 거부 기준을 강화</strong>했다 — 한 자릿수 승부인 <strong>NC-11·NC-01</strong>의 초기 거부율이 첫 실측 시험대다</td>
</tr>
<tr class="odd">
<td>실측</td>
<td><strong>신규 지역구 조사 0건 — 7일 연속.</strong> 전주 텍사스서던대 조사(TX-15 D+5 · TX-34 D+3 · TX-28 D+11)가 여전히 최신 독립 수치다. <strong>OH-07 독립 조사 공백도 지속</strong>(공개 4건이 전부 당파 의뢰)</td>
</tr>
<tr class="even">
<td>모델·시장</td>
<td>Kalshi 하원 다수 <strong>84¢</strong>(9/6, 전주 84¢) · <strong>DDHQ 67%</strong>(모델 갱신 9/4 — 평균 의석 D 229 – R 206, 이 사이트 자동 취득분) · Smarter.Vote 97%(AI 생성 명시 — 동급 취급 금지) · Polymarket ~89% · 등급가중 기대의석 약 <strong>215석</strong>(218 미달)</td>
</tr>
</tbody>
</table>
<p><strong>미주리 판결이 이번 주 이 사이트가 가장 무겁게 보는 한 건이다.</strong> 이 사이트는 그동안 하원을 “명목 필요 순증 +3 / 실질 약 +8”의 이중 구조로 써 왔다. 그 실질 쪽 숫자는 공화당이 중간주기에 다시 그은 지도들이 흡수한 민주 이득을 뜻한다. 지난 두 주 동안 그 흡수가 <strong>액면대로 실현되지 않는다는 증거</strong>가 두 갈래로 쌓였다 — Cook이 트럼프+11 지역구(FL-14)를 동전 던지기로 판정했고, 트럼프+18 지역구(TX-15)에서 독립 조사가 민주 +5를 냈다. 이번 주에는 세 번째 갈래가 열렸다. <strong>지도 자체가 사법적으로 소멸할 수 있다.</strong> 판결이 유지되면 실질 필요 순증은 ~+7이 되고, 그건 등급 기반 기대의석 215석과 218석 사이의 간격을 한 석 좁힌다.</p>
<p><strong>그런데 확률을 올리지는 않는다.</strong> 이 사이트가 이번 주 민주 다수 확률의 중심값을 <strong>85% 안팎에서 그대로 두는</strong> 이유는 세 가지다. 첫째, <strong>미주리는 아직 끝나지 않았다</strong> — 캐버노의 신속한 답변 명령 자체는 중립이지만, 이번 사이클 연방대법원은 재획정에서 일관되게 주 지도 제작자 측에 신속 개입해 왔다. 둘째, <strong>제너릭 밸럿이 완전히 정지했다</strong>(D+6.3, 닷새 연속). 등급과 제도가 크게 움직인 주에 환경 지표가 멈춰 있었다는 것은, 이번 주 이동의 동인이 환경 개선이 아니라 <strong>제도·측정의 재가격화</strong>라는 뜻이다. 셋째, <strong>어느 기관도 아직 미주리를 재등급하지 않았다.</strong> 기관 재등급 확인 전에 헤드라인 수치를 바꾸지 않는 것이 이 사이트의 규율이다. (<a href="https://www.kcur.org/politics-elections-and-government/2026-09-03/missouri-supreme-court-redistricting-referendum-congress-november-election">KCUR/STLPR(미주리)</a> · <a href="https://www.notus.org/missouri/missouri-asks-scotus-to-allow-new-republican-congressional-map-for-midterms">NOTUS(대법원 신청)</a> · <a href="https://marylandmatters.org/2026/09/03/maryland-supreme-court-redistricting-constitutional-amendment-ruling/">Maryland Matters(2028년 효과)</a> · <a href="https://clerk.house.gov/evs/2026/roll289.xml">호명투표 289</a> · <a href="https://www.axios.com/2026/09/02/golden-perez-jeffries-house-democrats-punishment">Axios(당내 징계)</a> · <a href="https://thehill.com/homenews/house/6063667-house-government-funding-cr-shutdown-midterms/">The Hill(CR)</a> · <a href="https://www.notus.org/north-carolina-approves-new-mail-in-ballot-policies-hours-before-sending-them-out">NOTUS(NC 거부 기준)</a>)</p>
</section>
<section id="주지사-알래스카가-두-칸-벌어졌다" class="level2">
<h2 class="anchored" data-anchor-id="주지사-알래스카가-두-칸-벌어졌다">주지사 — 알래스카가 두 칸 벌어졌다</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (9/6)</th>
<th>전주(8/30)</th>
<th>등급 (Cook 8/27 / Sabato 9/3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>메인</td>
<td><strong>95.8¢</strong></td>
<td>94.4¢</td>
<td>Solid D / Likely D</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>88¢</td>
<td>87¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="odd">
<td>애리조나</td>
<td>87¢</td>
<td>86¢</td>
<td>Lean D / Lean D</td>
</tr>
<tr class="even">
<td>위스콘신</td>
<td>80¢</td>
<td>80¢</td>
<td>Toss-up / Lean D</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>76¢</td>
<td>76¢</td>
<td>Lean D / <strong>Lean D (9/3↑)</strong></td>
</tr>
<tr class="even">
<td>알래스카</td>
<td><strong>63¢</strong></td>
<td>55¢</td>
<td>Likely R / <strong>Toss-up (9/1↑)</strong></td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>58¢</td>
<td>57¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>조지아</td>
<td><strong>56¢</strong></td>
<td>60¢</td>
<td>Toss-up / Toss-up</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td>42¢</td>
<td>42¢</td>
<td>Toss-up / Lean R</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td><strong>32¢</strong></td>
<td>36¢</td>
<td>Lean R / Lean R</td>
</tr>
</tbody>
</table>
<p><strong>지난주 이 자리에서 “등급 이동 0건인데 실측·구조는 넷이 민주 쪽으로 갔다”고 썼다. 이번 주에 등급이 따라왔다.</strong> 사바토가 9/1~9/3 사흘 사이에 세 건을 옮겼다 — <strong>알래스카 Likely R → Toss-up</strong>, <strong>아이오와 Toss-up → Lean D</strong>, 펜실베이니아 Likely D → Safe D. Inside Elections도 오하이오를 Lean R → Tilt R로 좁혔다. 콘딕은 “민주당이 1994년 이후 거의 내내 공화가 다수였던 주지사직에서 이번 사이클 우위를 잡을 기회가 있다”고 명시했다. 지난주 판정(“지연의 소재가 실측에서 등급으로 이동했다”)이 그대로 검증된 셈이다.</p>
<p><strong>알래스카가 사이클 최대의 격변 주간을 보냈다.</strong> 순서대로 적으면 이렇다. 8/28 베기치(D)가 사퇴하고 JKT를 지지해 <strong>민주 단일화가 완성</strong>됐고, 8/31 인증 마감일에 5위 트렉 테일러(R)가 재산공개 위반으로 실격되고 6위 비숍(R)이 자진 사퇴했으며, <strong>9/4 심야에 달스트롬 부지사가 자신의 실격 처분을 스스로 번복해 테일러를 복권</strong>시켰다(주 공직윤리위 4-1 권고를 무시했고 근거인 법무부 내부 검토는 비공개다). 최종 구도는 <strong>JKT(D) 대 공화 3인</strong>이다. 예선 1위 윌슨은 “랭크 더 레드” 협력을 공개 거부했다 — 조정 실패가 아니라 조정 거부다. 관측통들은 “민주당이 22년 만에 주지사직을 잡을 위치”로 읽는다.</p>
<p><strong>그런데 반증도 같은 자료에 있다.</strong> 1차 득표를 넓은 분모로 보면 <strong>공화 12인 합산 49.5% 대 민주 2인 합산 43.3%</strong>로 공화 진영이 앞선다. 승부는 RCV 이양에서 갈린다 — 베기치 20.8%가 JKT로 얼마나 넘어가느냐 대 공화 3인이 서로를 얼마나 순위 지정하느냐다. 이번 주 증거(윌슨의 협력 거부)는 공화 협력 실패 쪽을 가리키지만, 이건 <strong>아직 표가 아니라 발언</strong>이다. <strong>9/18 투표용지 발송이 실질 확정 시점</strong>이고, 주 공직윤리위 재심과 소송 리스크가 남아 있다. 시장은 55¢ → <strong>63¢</strong>로 8센트를 올렸고, <strong>Cook은 8/27 이후 무응답이라 양사 등급이 두 칸(Likely R 대 Toss-up) 벌어졌다</strong> — 이 표에서 단독 최우선 감시 대상이다.</p>
<p><strong>캔자스는 상태 정의를 고쳐 적는다.</strong> 그동안 “실측 공백”으로 써 온 이 주는 실제로는 <strong>“양당 의뢰 조사만 존재하는 상태”</strong>다. 8/28 양당 의뢰 조사 2건이 동시에 공개된 것이 이번 주 소급 확인됐다 — 민주계 GSG(홀셔 캠프 의뢰, LV 600, ±4.0)는 <strong>홀셔 47 – 매스터슨 46</strong>으로 오차 내 동률이고 무당파에서 두 자릿수 홀셔 우세, 공화계 co/efficient는 <strong>수치가 유료 구간이라 미확보</strong>다. <strong>공개된 유일한 본선 수치가 양사 Lean R 등급과 정면으로 어긋난다.</strong> 다만 이 사이트 조사 DB에는 넣지 않았다 — 실사 기간이 공표되지 않았기 때문이다. 시장은 오히려 36¢ → 32¢로 내렸다.</p>
<p><strong>오하이오는 여전히 이 표에서 가장 이상한 주다.</strong> 비당파 실측이 <strong>한 건도 없는 채로</strong> 세 계통이 정면 충돌한다 — 평가기관은 접전으로 수렴하는데(IE가 9/3 한 칸 좁혔다) 펀더멘털 모델 Pollsmax는 라마스와미 <strong>76.5%</strong>, 예측시장은 액턴 쪽(58¢)이다. 집계평균끼리도 부호가 반대다(RCP D+0.3 대 Pollsmax R+0.7). 이번 주 움직인 것은 수치가 아니라 쟁점이었다 — 라마스와미가 9/3 “무료 주거용 전기”를 “전력 요금분만 면제”로 후퇴시켰고 재산세 환원 금액은 제시하지 않았으며, 액턴은 토론을 전면 거부했다. <strong>첫 비당파 조사가 나오는 순간이 이 세 계통의 정합성을 판별하는 유일한 지점이다.</strong></p>
<p>주의회 쪽에서는 이번 주 신규 특별선거가 <strong>0건</strong>이다. 누적 지표에 두 건이 추가됐다 — 트럼프 2기 개시 후 민주 플립 누적 <strong>약 12석·11개 주, 공화 플립 0건</strong>이고, 최대 스윙 사례는 <strong>텍사스 주상원 9구 D+31.8</strong>(트럼프 +17.4 지역 탈환)이다. 중위 스윙 D+10.4 · 투표율 가중 D+12.6은 불변이다. 다만 <strong>집계 주체 본인의 경고를 함께 적는다</strong> — MultiState는 “이 마진이 11월까지 유지되면 역사상 최대급 웨이브가 되겠지만, 거의 확실히 그 수준으로 유지되지는 않는다”고 명시했다. 지난주 이 자리에 쓴 “2018년식 여름 완화가 이번에는 오지 않았다”는 관찰에 대한 공식 제한으로 기록해 둔다. (<a href="https://centerforpolitics.org/crystalball/the-governors-a-trio-of-rating-changes-toward-democrats-as-they-chase-a-rare-edge-in-overall-seats-held/">Crystal Ball(주지사 3건)</a> · <a href="https://alaskabeacon.com/2026/09/05/alaska-lt-gov-dahlstrom-reverses-herself-puts-former-attorney-general-treg-taylor-back-in-governors-race/">Alaska Beacon(부지사 번복)</a> · <a href="https://www.adn.com/politics/2026/09/04/bernadette-wilson-says-republicans-should-not-rank-the-red-in-alaska-governors-race/">ADN(랭크 더 레드 거부)</a> · <a href="https://alaskabeacon.com/2026/09/03/amid-fractured-gop-field-a-democrat-could-be-headed-for-the-alaska-governors-mansion/">Alaska Beacon(득표 구조)</a> · <a href="https://sunflowerstatejournal.com/a-battle-of-polls-what-is-state-of-the-kansas-governors-race/">Sunflower State Journal(KS)</a> · <a href="https://ohiocapitaljournal.com/2026/09/04/ohio-democratic-candidate-for-governor-amy-acton-refuses-to-debate/">Ohio Capital Journal(액턴 토론 거부)</a> · <a href="https://www.multistate.us/elections/special-swing">MultiState</a>)</p>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>24주차(8/31~9/6) 거시 환경은 여당에 불리한 방향으로 한 단계 더 기울었다.</strong> 미·이란 전쟁이 한 달 소강을 깨고 전면 재개되며 휘발유 $4.14(노동절 사상 최고)·경유 $5.85(사상 최고)로 물화됐고, 트럼프 순지지는 평균 −19.5~−24에 개별 조사 바닥 32~33%가 확정됐으며(1기 동기 대비 약 8%p 열위), 제너릭 밸럿은 D+6 회랑 6주째 고착 속에 갤럽 정당일체감 D+10(2015년 이후 최대, 2024년 말 대비 14%p 반전)이라는 구조 지표 반전이 추가됐다. 제도전에서는 미주리 대법원의 만장일치 지도 무효화와 우편투표 규칙 예비적 금지명령으로 공화 측 구조적 완충 두 개가 동시에 약화됐다(양건 모두 연방대법원 재상륙 대기). 반증 방향으로는 +16.2만 고용 서프라이즈(단 구성 62%가 계절요인, 실질임금 하락 지속), 하버드 CAPS/해리스의 상단 이상치(44%·LV R+2)가 드러낸 투표층 모형 불확실성, 그리고 위트코프·쿠슈너–푸틴 회담으로 열린 우크라이나 외교 트랙이 있다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(중~강) — 전주 판정 유지, 확신도 소폭 상승.</strong> 다만 연준의 9/15–16 인상 여부가 9/11 CPI에 위임돼 있어, 다음 주는 환경 재료가 한꺼번에 재가격화되는 주가 된다. (인용: <code>national_weekly/2026-09-06</code> §6-4)</p>
</blockquote>
<p>여기에 두 가지를 덧붙인다.</p>
<p>첫째, <strong>이번 주에 확정된 것은 방향이 아니라 바닥이다.</strong> 지난 몇 주 동안 트럼프 지지율의 하단은 개별 조사 한두 건이 찍는 이상치처럼 다뤄졌다. 이번 주에는 UMass 애머스트(32/64) · 로이터/입소스(33%, 3회 연속) · Economist/YouGov(33%)가 <strong>동시에</strong> 같은 자리를 찍었다. 양질 기관 셋이 겹치면 그건 이상치가 아니라 분포의 왼쪽 끝이다. 그리고 여기에 <strong>1기 동기 대비 약 8%p 열위</strong>라는 기준선 비교가 처음 명시적으로 붙었다. 2018년에 하원 40석을 잃은 그 대통령보다 8포인트 아래에서 중간선거로 들어간다는 뜻이다.</p>
<p>둘째, <strong>그럼에도 이 사이트는 이번 주에 어떤 확률도 올리지 않았다.</strong> 이유는 하나로 압축된다 — <strong>밸럿이 멈춰 있다.</strong> 지지율이 −0.7p 빠지고, 유가가 사상 최고를 찍고, 제도전에서 두 건이 민주 쪽으로 갔는데, 제너릭 밸럿은 D+6.3에서 닷새 연속 미동이 없었다. 이건 두 가지 중 하나다. 새 정보가 이미 가격에 들어가 있거나, 아니면 <strong>지지율 하락이 밸럿으로 전환되지 않는 구간</strong>에 들어와 있거나. 후자라면 이번 주의 모든 악재는 야당 득표로 번역되지 않는다. 하버드 CAPS/해리스의 LV R+2가 실재한다면 그 번역 실패는 이미 측정된 것일 수도 있다. <strong>판단을 유보하는 것이 정직한 위치다.</strong></p>
</section>
<section id="상원-산수-두-기관이-멈추면-산수도-멈춘다" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-두-기관이-멈추면-산수도-멈춘다">상원 산수 — 두 기관이 멈추면 산수도 멈춘다</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 무소속 3인 중 민주 코커스를 약속한 사람은 없다 — <strong>+4 산술에 우회로는 없다.</strong></p>
<p>등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)을 Cook 8/20·사바토 8/26 두 기관 평균에 적용하면:</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>계산</th>
<th>값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>탈환 기대</td>
<td>ME .50 + NC .75 + AK .50 + OH .50 + TX .50 + IA .375</td>
<td><strong>+3.125석</strong></td>
</tr>
<tr class="even">
<td>방어 손실</td>
<td>GA .125 + MI .50 + NH .25</td>
<td><strong>−0.875석</strong></td>
</tr>
<tr class="odd">
<td>순 기대의석</td>
<td></td>
<td><strong>+2.25석</strong></td>
</tr>
<tr class="even">
<td>전주 동일 방식</td>
<td>동일</td>
<td>+2.25석</td>
</tr>
<tr class="odd">
<td><strong>주간 변화</strong></td>
<td>Cook·사바토 등급 이동 0건 (이번 주 이동은 Inside Elections 3건)</td>
<td><strong>0.00석</strong></td>
</tr>
</tbody>
</table>
<p><strong>이 표가 2주 연속 소수점까지 같다.</strong> 이유는 지난주와 다르다. 지난주에는 등급 이동이 한 건 있었는데 이 사이트 피드가 이미 반영한 뒤였다. <strong>이번 주에는 Cook과 사바토가 아예 아무것도 하지 않았다</strong> — 8/20과 8/26 라운드 이후 상원 등급표를 한 칸도 바꾸지 않았다. 그 사이 Inside Elections가 세 건을 옮겼지만, 이 산수는 두 기관 평균이라 들어갈 자리가 없다.</p>
<p>그래서 감도 분석을 한 번 돌려 둔다. <strong>IE를 제3 기관으로 평균에 넣으면</strong> 뉴햄프셔 상실 위험이 .25에서 약 .33으로 늘고, 알래스카·오하이오 탈환 기대가 그만큼 오른다. 두 방향이 대체로 상쇄돼 순 기대의석은 <strong>+2.0~+2.2 범위</strong>로 유지된다. 지난주 이 자리에서 “뉴햄프셔 한 곳의 등급 이동이 이번 달 누적 개선분을 통째로 지울 수 있다”고 썼는데, <strong>그 시나리오는 3분의 1만 현실화됐다</strong> — 세 기관 중 하나만 움직였고, 같은 기관이 반대편에서 두 건을 올렸기 때문이다.</p>
<p>정직하게 덧붙일 것이 하나 있다. <strong>등급가중 산수와 등급 확정 독법은 이번 주에 특히 크게 벌어졌다.</strong> IE의 Tilt·Lean을 전부 확정 처리하면 민주 순증은 약 <strong>+1</strong>이고, 확률 가중으로 읽으면 <strong>+2.1~+2.2</strong>다. 이 간극은 데이터 차이가 아니라 <strong>토스업이 6~7곳이나 된다는 사실의 함수</strong>다. 토스업이 많을수록 “동전 던지기를 반씩 나눠 갖는다”는 가정이 결과를 좌우한다. 실제 선거는 동전을 하나씩 던지지 않고 <strong>같은 바람에 함께 흔들린다</strong> — 그래서 이 산수는 환경이 좋을 때 과소, 나쁠 때 과대 추정한다.</p>
<p>네 종류의 숫자는 이번 주에 거의 움직이지 않았다.</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>전주</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>48¢</strong></td>
<td>48¢</td>
<td>거래액 $345만·미결제 $172만. 다수 계약이 멈춘 사이 개별 주는 갈렸다 — IA −7¢·OH −2¢·TX −2¢ 대 AK +1¢</td>
</tr>
<tr class="even">
<td><strong>구조 모델</strong> (DDHQ)</td>
<td><strong>49.0%</strong> (평균 의석 D 50 – R 50)</td>
<td>48.0%</td>
<td>모델 갱신 9/4. 시장가를 처음으로 1%p 넘어섰다. 50–50 의석은 부통령 캐스팅보트로 <strong>공화 다수</strong>를 뜻한다</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong> (Race to the WH)</td>
<td><strong>54.2%</strong> (예상 의석 D 50.8 – R 49.2)</td>
<td>54.3%</td>
<td>Infogram 라이브 시계열 직접 취득(마지막 관측 9/6, 135점). 사실상 정지</td>
</tr>
<tr class="even">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+2.25석</strong></td>
<td>+2.25석</td>
<td>서수적 등급을 확률로 환산 — 전국 환경이 들어갈 자리가 구조적으로 없다</td>
</tr>
</tbody>
</table>
<p>두 모델의 격차는 6.3%p에서 <strong>5.2%p</strong>로 한 번 더 좁혀졌다. 2주 연속 축소다. 그런데 이번 축소는 지난주와 성격이 다르다 — 지난주에는 양쪽이 서로에게 다가왔고, <strong>이번 주에는 RtWH가 멈춘 채 DDHQ 혼자 올라왔다.</strong> 판단은 같다. <strong>평균 내지 말 것.</strong> 격차의 원인은 데이터가 아니라 가정이고, 5.2%p가 남아 있다는 건 그 가정 차이가 사라지지 않았다는 뜻이다.</p>
</section>
<section id="시장이-갈린-방식-세-개의-탈환-의석에서-값이-빠졌다" class="level2">
<h2 class="anchored" data-anchor-id="시장이-갈린-방식-세-개의-탈환-의석에서-값이-빠졌다">시장이 갈린 방식 — 세 개의 탈환 의석에서 값이 빠졌다</h2>
<p>이번 주 상원 시장에서 가장 읽을 만한 것은 <strong>다수 계약이 정확히 멈춘 채 개별 주가 한 방향으로 갈렸다</strong>는 사실이다.</p>
<p>빠진 곳은 셋이고 전부 <strong>공화가 보유한 탈환 목표</strong>다 — 아이오와 −7¢, 오하이오 −2¢, 텍사스 −2¢. 오른 곳은 알래스카 +1¢와 조지아 +0.6¢뿐이다. 그리고 <strong>민주당이 지켜야 하는 세 곳(GA·MI·NH)은 사실상 전혀 움직이지 않았다.</strong> 뉴햄프셔는 등급이 강등된 주에 83¢ 그대로다.</p>
<p>이 배치가 뜻하는 바를 과대 해석하지 않으면서 말하면 이렇다. <strong>시장은 이번 주에 “민주당이 다수를 잡을 확률”을 바꾸지 않았고, 대신 “그 확률이 어느 주를 통과하느냐”를 바꿨다.</strong> 아이오와·오하이오·텍사스에서 값이 빠졌는데 다수 계약이 그대로라는 건, 시장이 이 세 곳을 이미 다수 경로의 <strong>주변부</strong>로 취급하고 있었다는 뜻으로 읽힌다. 다수를 잡는 경로가 여전히 NC + 사수 3곳을 지나가고, 그 축은 이번 주에 건드려지지 않았다.</p>
<p>그렇다면 이 사이트가 지난주에 쓴 문장 — <strong>“리스크의 무게중심이 탈환 미달에서 수성 실패와 탈환 미달의 결합으로 이동했다”</strong> — 은 이번 주에 어떻게 되는가. 절반만 유지된다. 뉴햄프셔의 등급 리스크는 실제로 현실화됐다(3개 기관 중 1곳). 그런데 <strong>시장은 그 수성 리스크를 아직 가격에 넣지 않았고, 대신 탈환 쪽 확장 실패를 가격에 넣었다.</strong> 원문 상원 트랙도 같은 판정을 내렸다 — 하방의 무게중심이 ’MI 상실’에서 <strong>‘NH 상실 + IA·TX 확장 실패’</strong>로 옮겨갔다. 미시간은 3연속 반대 방향으로 움직여 사실상 목록에서 빠졌다.</p>
<p>한 가지 규율 항목을 적어 둔다. <strong>메인은 여전히 측정되지 않았다.</strong> 스캔들 보도 이후 실사된 공개 조사가 4주째 0건이고, 이 주에 대해 존재하는 네 개의 수치가 전부 다른 시점에 멈춰 있다 — Kalshi 69¢는 8/16 스캔들 이전 가격에서 흘러내린 값이고, IE Tilt R은 2025년 7월 값이며, Cook·사바토 Toss-up만이 현재 판단이다. <strong>어느 Bull 경로도 메인을 필요로 하고, 그 주의 참값을 이 사이트는 모른다.</strong> 첫 조사가 나오는 순간이 이번 가을 최대의 단일 정보 갱신이 될 수 있다.</p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (8/31~9/6).</strong> 주간 DB는 <strong>15건 추가</strong>로 전주 8건에서 밀도가 두 배가 됐다. 그런데 <strong>진원지가 다르다</strong> — 이번 주 신규 재료의 다수가 워싱턴 발화가 아니라 <strong>서울의 결정과 절차</strong>다. 미 의회는 한 주 내내 한국을 말하지 않았다(상원 [K] 닷새 연속 0건, 하원 7일 내내 신규 없음). 한국 파일은 행정부(러트닉·USTR)와 서울에서 움직였다.</p>
<p><strong>최대 사건은 서울이 닫아 두었던 호르무즈 파병 파일의 재개다.</strong> 한국 정부가 9/4 호르무즈 해협 미 안보 노력에 대한 ‘기여’ 검토를 공식 확인했다 — 검토 전력은 <strong>P-8A 포세이돈 해상초계기·해군 군수지원함·EOD팀</strong> 3종으로 전부 ‘비전투’로 규정되며, 성사되면 한국의 첫 해상초계기 역외 파견이다. 절차는 NSC 승인 → 국무회의 의결 → <strong>국회 동의</strong>이고, 표결은 이재명 대통령의 유엔총회 방문(9/18~28) 일정과 맞물릴 것으로 관측된다. 순서가 중요하다 — 블룸버그·코리아프로에 따르면 서울은 <strong>지난달 이미 워싱턴에 파견 의향을 통보</strong>했다(운용 소요 약 150명). 즉 8월 물밑 제안 → 트럼프의 공개 ’거부당했다’ 프레이밍 → 9/4 공개 확인이다.</p>
<p><strong>하루 만에 여권이 갈렸다.</strong> 민주당 이기헌 의원이 “비전투 병력이라 하더라도 그 본질은 명백히 전쟁 참여”라며 동의 거부를 선언했고, 지도부는 2003~04년 이라크 파병 분열(당시 여당 찬성 49 대 반대 43)을 의식해 입장을 유보했으며, 조국혁신당·진보당은 헌법 제5조를 원용해 반대했다. 여론은 3월 한국갤럽 기준 <strong>반대 55% / 찬성 30%</strong>이고, 지난해 호르무즈 경유 원유 수입은 <strong>61%</strong>다. <strong>아직 결정이 아니라 공개 확인된 검토이며, 국회 표결이 검증 지점이다.</strong></p>
<p>이 사이트가 이 건을 상원 트래커와 나란히 놓는 이유는 하나다. <strong>미집행 3,500억 달러 투자 공약과 같은 협상판에서 안보 기여가 ’제2의 통화’로 기능하는 구도</strong>이고, 그 협상판을 압박하는 유가·전쟁이 <strong>바로 이 브리핑의 환경 지표 그 자체</strong>이기 때문이다. 한국 파일이 미 중간선거의 거시 변수와 같은 뿌리에서 움직인 첫 주간이다.</p>
<p><strong>통상에서는 반도체가 품목별 관세 전선에 편입됐다.</strong> 러트닉 상무장관이 9/2 CNBC에서 “표적화되고 사려 깊은” 반도체 관세 준비를 확인하며 관세-미국 내 팹 투자 연동 구조에 “정확히 그렇다”고 답했다 — 요지는 <strong>“여기서 지으면 안 내고, 안 지으면 낸다”</strong>다. 하루 뒤 김정관 산업장관은 한미 무역합의 공동 팩트시트의 <strong>‘경쟁국 대비 불리하지 않은 대우’</strong> 조항을 방어선으로 제시했고, 대만 모델(건설 중 설비능력 2.5배·완공 후 1.5배 관세 쿼터)이 가능하나 <strong>대만 합의 자체가 입법원 미비준</strong>임을 함께 지적했다. 1호 대미투자 프로젝트는 “9월 내 마무리 계획 불변”이라고 했는데, 미측의 사업비 상향 요구(약 200억 → 250억 달러)를 지연 원인으로 지목한 국내 보도와 <strong>불일치가 기록에 남았다.</strong></p>
<p><strong>산업에서는 절차 리스크가 처음 노출됐다.</strong> 현대제철-포스코 루이지애나 제철소(58억 달러·연 조강 270만 톤·직접고용 1,300명)가 9/4 착공했는데, <strong>대기오염 허가가 확정되지 않은 상태</strong>다 — 9/1 공청회가 찬반으로 갈리고 공개의견 마감이 9/2에서 9/15로 연장된 직후였다. 지난주 SK하이닉스 인디애나 착공이 무마찰이었던 것과 대비되는, <strong>대미 투자 실행 리스크의 첫 절차적 노출</strong>이다.</p>
<p><strong>북한 쪽에서는 공개 수사와 물밑 채널이 갈라졌다.</strong> 국정원이 9/1 국회 정보위 비공개 보고에서 북미 정상회담이 “언제든 가능한 것으로 봐야 한다”고 평가했다 — 다만 간사 브리핑 기준으로 <strong>“구체적 접촉이 확인된 사실은 없지만 대화 징후는 있다”</strong>이고 근거는 비공개다. 바로 전날 북 외무성은 미국의 적대시 정책 불변을 주장하며 프리덤 에지(9/7~11)를 근거로 지목했다. <strong>과대 해석은 금물이다.</strong></p>
<p><strong>선거 연계는 이번 주 한 건이 확인됐고, 무대가 예상 밖이었다.</strong> 엘라벨 단속 1주기(9/4)에 맞춰 법무부가 <strong>기소 전무·사건 종결</strong>을 확인했다 — 약 475명이 체포됐고 고용 기업 처분은 0이다. 같은 날 <strong>조지아 주상원 1선거구</strong>(서배너 일원)에서 민주당 후보 코리 포먼(단속 당시 현장에 있었다)이 “노동자에게 책임을 묻는다면 고용한 사람들에게는 왜 묻지 않는가”라고 공격했고 공화당 현역 벤 왓슨이 응수했다. <strong>이 단속이 미국 선거의 쟁점이 된 첫 확인 사례이고, 무대는 주지사 선거가 아니라 주의회 선거다.</strong> 한국계·아시아계 유권자 규모가 주 전체가 아니라 카운티·주의회 산술에서 작동한다는 뜻이므로, 이 사이트의 조지아 감시 초점도 그쪽으로 옮긴다. CA-40 영 김(하원 외교위 인도·태평양 소위원장)의 훈련 축소 관련 입장은 <strong>이번 주에도 미확인</strong>이다. (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>9/7(월) 정오 — 미주리 건 캐버노 대법관 앞 답변 기한.</strong> 전원재판부 회부 여부가 여기서 갈린다. 유지되면 하원 실질 필요 순증이 ~+7로 고정되고, 복원되면 ~+8로 되돌아간다. 이번 주 하원 지도의 유일한 분기점이다.</li>
<li><strong>9/8(화) — 세 개가 겹친다.</strong> <strong>뉴햄프셔 예비선거</strong>(본선 공식 개막 + 만주르 득표율과 양당 투표율 격차가 LV 모형 균열의 첫 실측) · <strong>캐나다 보복관세 발효</strong>(700여 품목 — 아이오와의 ‘관세→투표’ 채널 실전 개시) · <strong>미주리 투표용지 마감.</strong></li>
<li><strong>9/9–10 — 댈러스 공화 중간선거 전당대회.</strong> 텍사스 구제 자금 투입 여부에 대한 로브 발 공개 압박의 응답 시점이자, <strong>수누누의 불참</strong>이 확인해 준 ‘거리두기 대 결집’ 딜레마의 전국 전시장이다.</li>
<li><strong>9/11(금) — 8월 CPI와 9·11 25주기가 같은 날이다.</strong> CPI는 9/15–16 FOMC 인상 여부(확률 약 60%)의 결정적 입력값이고, 경유발 전가가 관건이다. 같은 날 로저스·NRSC가 미시간에서 예고한 공세의 개시 시점이기도 하다 — <strong>미시간 3연속 D 우위 흐름의 첫 스트레스 테스트.</strong></li>
<li><strong>메인 — 스캔들 이후 첫 공개 조사.</strong> 4주째 비어 있는 지도 최대 미확보 데이터다. 나오는 순간 이 주의 네 수치(시장·모델·Cook·IE) 괴리가 일거에 정리된다.</li>
<li><strong>9/14 — 미주리 측이 요구한 연방대법원 결정 시한</strong>(재외·군인 용지 발송 9/19 역산) · <strong>9/15–16 FOMC</strong> · <strong>9/18 — 알래스카 투표용지 발송</strong>(주지사 구도의 실질 확정 시점).</li>
<li><strong>등급 감시 4건</strong> — Cook·사바토의 <strong>뉴햄프셔 이동 여부</strong>(IE를 따라가면 감도의 하방이 실현된다) · <strong>Cook의 알래스카 주지사 응답</strong>(8/27 이후 무응답, 사바토와 두 칸 격차) · Cook의 <strong>TX-15·NC-11</strong>(둘 다 3개 기관 중 Cook만 단독 홀드아웃) · 평가기관들의 <strong>미주리 재등급 개시 여부.</strong></li>
<li><strong>NC 우편투표 초기 거부율</strong> — 9/4 강화된 기준 아래 첫 반송분이 다음 주 실측된다. 한 자릿수 승부인 NC-11·NC-01에 직결된다.</li>
<li><strong>한국 함의.</strong> 호르무즈 국회 동의안 제출 여부(유엔총회 9/18~28 연동) · 프리덤 에지 실시(9/7~11) · 3,500억 달러 1호 프로젝트 ‘9월 중순’ 발표 · 반도체 품목 관세의 구체안과 ‘불리하지 않은 대우’ 조항의 실효 · 영 김의 입장 확인 여부.</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·주정부·Korea Watch, 08/31~09/06 — 일간 35/35건, <strong>5개 트랙 전부 결손 없음</strong>). 환경 지표 — FiftyPlusOne·Silver Bulletin·RealClearPolling·USPollingData·Morning Consult·Decision Desk HQ·UMass 애머스트·Reuters/Ipsos·Economist/YouGov·하버드 CAPS/해리스·갤럽. 경제 — BLS(고용보고서·JOLTS)·ADP·ISM(제조·서비스)·연준 베이지북·CME FedWatch·AAA. 상원 실측 — Epic-MRA·MSU/IPPSR(YouGov)·Fabrizio, Lee &amp; Associates·Texas Public Policy Foundation/Overton Insights·Emerson College/Nexstar. 주지사 실측 — Emerson College/Nexstar(상원과 동일 표본). 상원·주지사 등급 — Cook(상원 8/20·주지사 8/27)·Sabato(상원 8/26·주지사 9/3)·Inside Elections(9/3) 270towin 재게시분 자동 취득(9/6 실행 — 상원 35/35·주지사 35/36, 뉴햄프셔 주지사는 2026 만기 계약이 없어 제외). 하원 등급 — Cook 8/25 보드 자동 취득(435개구 해독, 합계 435 검증). 예측시장 — Kalshi 공개 API 원가격(9/6). 외부 모델 — Decision Desk HQ(모델 갱신 9/4)·Race to the WH(라이브 시계열 마지막 관측 9/6, 135점). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. <strong>다음 조사는 이 사이트 DB에 넣지 않고 서술로만 반영했다</strong> — 오하이오 Abacus Data 브라운 +6(8/28, 실사기간·표본 원출처 미확인) · 아이오와 Wedgewood 힌슨 +2(8/29, 미평가 기관) · 캔자스 GSG 홀셔 +1(8/28 공개, 실사기간 미공표) · 캔자스 co/efficient(수치 유료 구간 미확보) · 애리조나 RCP 평균 D+10.8(구성 미확인). <strong>기록해 둘 불일치 2건</strong>: ① Inside Elections의 메인 등급(Tilt R)은 2025-07-24 이후 갱신되지 않아 잭슨 지명·스캔들 국면 전체를 반영하지 않는다 — 이 사이트는 이를 증거가 아니라 낡은 값으로 취급한다. ② 미주리 측이 요구한 연방대법원 결정 시한은 보도가 9/13과 9/14로 엇갈리며, 이 사이트는 전국 트랙을 따라 9/14로 적는다. 이번 주 자동 취득 로그에 조회 실패·정렬 불일치로 건너뛴 항목은 뉴햄프셔 주지사 시장(2026 만기 계약 부재) 1건뿐이다. 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>