<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="서사가 한 주 안에서 두 번 뒤집혔다. 7월 CPI 3.4%·PPI 0.0%로 물가가 두 번 연속 안도하자 여당에 숨통이 트이는 듯했지만, 금요일 소매판매 −0.6%와 소비심리 51.0이 그 안도를 ’수요가 꺾여서 생긴 물가 안정’으로 재해석시켰다. 백악관은 8/15 CNN 보도로 양원 상실 흐름을 내부적으로 인정하고 트럼프 개인 PAC 3,000만 달러를 풀었다. 상원에서는 주류 여론조사 모델이 처음으로 민주 과반을 favorite로 판정했는데, 정작 필수 방어주 미시간은 경선 후 첫 주요 조사에서 로저스 +4로 내려앉았고 메인 지명자에게는 새 스캔들이 붙었다. 하원은 Cook이 OH-07을 사이클 첫 신규 토스업으로 올렸고, 주지사에서는 위스콘신 경선 반전 하나로 예측시장이 35포인트 움직였다.">

<title>21주차 · 08/10~08/16 – 미국 중간선거 한국어 브리핑</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1e3c7c377496ca8ba84db3a882ec124b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;700&amp;family=JetBrains+Mono:wght@400;600&amp;family=Noto+Serif+KR:wght@600;700&amp;display=swap" rel="stylesheet">


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">미국 중간선거 한국어 브리핑</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">홈</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../archive.html"> 
<span class="menu-text">브리핑</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../national.html"> 
<span class="menu-text">전국 환경</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../senate.html"> 
<span class="menu-text">상원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../house.html"> 
<span class="menu-text">하원</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../governors.html"> 
<span class="menu-text">주지사</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../korea-watch.html"> 
<span class="menu-text">Korea Watch</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/us-elections-2026/us-elections-2026.github.io"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">21주차 · 08/10~08/16</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">시작</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">홈 — 컨트롤 패널</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">전국 환경</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../national.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">지지율·경제·외교</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">상원 Senate</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../dashboard.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">전망 대시보드 — 주별 확률</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../senate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합주 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">시나리오 — 소수·50:50·다수</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (9주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 Georgia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 Michigan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">뉴햄프셔 New Hampshire</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/me.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">메인 Maine</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/nc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노스캐롤라이나 North Carolina</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/tx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">텍사스 Texas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 Ohio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">알래스카 Alaska</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../states/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 Iowa</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">하원 House</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../house.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경합구 트래커 — 토스업·재획정</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">재획정 — 왜·어디서 (설명)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">주지사·주의회</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주지사 — 36개 주 경합</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">State Focus (경합 8주)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/az.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">애리조나 주지사 Arizona Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ga.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">조지아 주지사 Georgia Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/oh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">오하이오 주지사 Ohio Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/mi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">미시간 주지사 Michigan Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/wi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">위스콘신 주지사 Wisconsin Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/nv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">네바다 주지사 Nevada Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아이오와 주지사 Iowa Governor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../governors/ks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">캔자스 주지사 Kansas Governor</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../redistricting.html#legislature" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주의회 — 다음 지도를 그리는 주체</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Korea Watch</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../korea-watch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">한국 정책 함의</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">데이터·방법론 (부록)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../trackers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">트래커 — 전체 표</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">방법론</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">소개</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">주간 브리핑</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../archive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">아카이브 — 발행된 모든 호</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#part-1.-데이터" id="toc-part-1.-데이터" class="nav-link active" data-scroll-target="#part-1.-데이터">PART 1. 데이터</a>
  <ul class="collapse">
  <li><a href="#환경-스냅샷-주간" id="toc-환경-스냅샷-주간" class="nav-link" data-scroll-target="#환경-스냅샷-주간">환경 스냅샷 (주간)</a></li>
  <li><a href="#상원-경합주-스냅샷-9주" id="toc-상원-경합주-스냅샷-9주" class="nav-link" data-scroll-target="#상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</a></li>
  <li><a href="#하원-cook-사이클-첫-신규-토스업" id="toc-하원-cook-사이클-첫-신규-토스업" class="nav-link" data-scroll-target="#하원-cook-사이클-첫-신규-토스업">하원 — Cook, 사이클 첫 신규 토스업</a></li>
  <li><a href="#주지사-위스콘신-후보-한-명에-시장이-35포인트" id="toc-주지사-위스콘신-후보-한-명에-시장이-35포인트" class="nav-link" data-scroll-target="#주지사-위스콘신-후보-한-명에-시장이-35포인트">주지사 — 위스콘신, 후보 한 명에 시장이 35포인트</a></li>
  </ul></li>
  <li><a href="#part-2.-분석" id="toc-part-2.-분석" class="nav-link" data-scroll-target="#part-2.-분석">PART 2. 분석</a>
  <ul class="collapse">
  <li><a href="#환경-종합-판단" id="toc-환경-종합-판단" class="nav-link" data-scroll-target="#환경-종합-판단">환경 종합 판단</a></li>
  <li><a href="#상원-산수-이번-주엔-숫자가-네-종류로-갈렸다" id="toc-상원-산수-이번-주엔-숫자가-네-종류로-갈렸다" class="nav-link" data-scroll-target="#상원-산수-이번-주엔-숫자가-네-종류로-갈렸다">상원 산수 — 이번 주엔 숫자가 네 종류로 갈렸다</a></li>
  <li><a href="#미시간-조사는-r4-시장은-d-57" id="toc-미시간-조사는-r4-시장은-d-57" class="nav-link" data-scroll-target="#미시간-조사는-r4-시장은-d-57">미시간 — 조사는 R+4, 시장은 D 57¢</a></li>
  <li><a href="#다음-관전-포인트" id="toc-다음-관전-포인트" class="nav-link" data-scroll-target="#다음-관전-포인트">다음 관전 포인트</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">21주차 · 08/10~08/16</h1>
  <div class="quarto-categories">
    <div class="quarto-category">주간브리핑</div>
  </div>
  </div>

<div>
  <div class="description">
    서사가 한 주 안에서 두 번 뒤집혔다. 7월 CPI 3.4%·PPI 0.0%로 물가가 두 번 연속 안도하자 여당에 숨통이 트이는 듯했지만, 금요일 소매판매 −0.6%와 소비심리 51.0이 그 안도를 ’수요가 꺾여서 생긴 물가 안정’으로 재해석시켰다. 백악관은 8/15 CNN 보도로 양원 상실 흐름을 내부적으로 인정하고 트럼프 개인 PAC 3,000만 달러를 풀었다. 상원에서는 주류 여론조사 모델이 처음으로 민주 과반을 favorite로 판정했는데, 정작 필수 방어주 미시간은 경선 후 첫 주요 조사에서 로저스 +4로 내려앉았고 메인 지명자에게는 새 스캔들이 붙었다. 하원은 Cook이 OH-07을 사이클 첫 신규 토스업으로 올렸고, 주지사에서는 위스콘신 경선 반전 하나로 예측시장이 35포인트 움직였다.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">공개</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026년 8월 10일</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>종합 대상: 8/10~8/16 일간 브리핑(전국·상원·하원·Korea Watch 각 7건 — 총 28/28건, 누락 없음). 뉴스 기준: 미 동부시간 8/9(일) 저녁 ~ 8/15(토) 저녁. 모든 마진은 <strong>양수 = 민주 우위</strong>(D+/R−). 여론조사 평균·추세를 단일 조사보다 우선하며, 모델·등급·예측시장은 성격이 달라 직접 비교하지 않는다.</p>
</blockquote>
<div class="summary">
<ul>
<li><strong>물가는 안도했는데 소비가 꺾였다 — 서사가 주 안에서 두 번 뒤집힌 주</strong> — 7월 CPI(8/12) 3.4% y/y·코어 2.5%로 컨센서스에 정확히 부합했고 7월 PPI(8/13)는 0.0% m/m로 컨센서스를 하회했다. 여기까지는 여당에 제한적 호재였다. 그런데 금요일(8/14) <strong>7월 소매판매 −0.6%</strong>(2025년 5월 이후 최대 낙폭)와 <strong>미시간대 8월 예비 소비심리 51.0</strong>(7월 55.2에서 급락)이 나오면서 물가 안정이 “수요가 약해져서 생긴 것”으로 재해석됐다. 1년 기대인플레이션은 오히려 4.3%로 올랐다. 트럼프 순지지는 <strong>−20.4에서 5일째 횡보</strong>, 제너릭 밸럿은 <strong>D+6.7</strong>(적극투표층 보정 D+8.1)이다.</li>
<li><strong>백악관이 먼저 인정했다</strong> — 8/15 CNN 보도에서 트럼프 참모진이 <strong>양원 상실 흐름을 내부적으로 인정</strong>하고, 트럼프가 취약 공화 후보 지원에 개인 PAC 1차분 <strong>약 3,000만 달러</strong>를 승인했다. 참모들은 이란 전쟁과 유가가 공화 지지층의 투표 의욕을 꺾는다고 보며 당의 운명이 “거의 전적으로” MAGA 저투표성향층 동원에 달렸다고 말했다. <strong>설득(무당층)이 아니라 기반 동원 일변도</strong> 전략이다.</li>
<li><strong>상원 — 모델은 처음 민주 쪽으로 갔는데, 판세의 두 축은 동시에 흔들렸다</strong> — G.E. Morris 모델이 민주 상원 장악 <strong>55%</strong>, 8/14 공개된 Silver Bulletin FLIPR이 <strong>민주 51–49·과반 확률 약 57%</strong>를 제시해 주류 모델이 처음으로 민주 과반을 명목상 favorite로 판정했다. 반대편에서 <strong>필수 방어주 미시간</strong>은 경선 후 첫 주요 언론 조사에서 <strong>로저스 51–엘사예드 47(R+4)</strong>로 내려앉았고, <strong>메인</strong>에서는 지명자 잭슨의 1988년 경찰 기록이 보도됐다. <strong>Cook·Sabato 하드 등급 이동은 0건.</strong></li>
<li><strong>미시간에서 조사와 시장이 정면으로 갈렸다</strong> — 공개 조사는 엘사예드가 뒤지거나 동률인 것이 4연속인데, Kalshi는 엘사예드를 <strong>57¢</strong>로 매긴다. 어느 한쪽이 틀렸다고 정리하지 말고 격차를 그대로 보는 편이 낫다.</li>
<li><strong>메인 3조사는 전부 ’보도 이전’이다</strong> — 잭슨 +2(폭스)·+3(UNH 파인트리)·+4(하트/SMP)가 모두 잭슨 근소 우위지만, 셋 다 8/12 경찰 기록 보도 <strong>이전에 실사</strong>됐다. 지금 도는 숫자는 스캔들을 반영하지 않은 판세다.</li>
<li><strong>하원 — Cook이 OH-07을 사이클 첫 신규 토스업으로 올렸다(18→19)</strong> — 전처 가정폭력 의혹에도 맥스 밀러(R)가 후보 교체 시한을 넘겨 완주를 확정하자, Cook은 <strong>Likely R → Toss-Up으로 두 단계</strong> 내렸고 인사이드일렉션스도 같은 날 따라왔다. 트럼프 PAC 1차분의 표적(미시간·오하이오·노스캐롤라이나)이 <strong>당파성이 아니라 후보 자질이 등급을 움직인 바로 그 의석들</strong>이라는 점이 이번 주 하원 이야기의 핵심이다.</li>
<li><strong>주지사 — 위스콘신에서 하루 만에 35포인트가 움직였다</strong> — 8/11 민주 경선에서 밀워키 카운티 행정관 <strong>David Crowley가 민주사회주의자 Francesca Hong을 1%p 미만 차로 꺾었다</strong>(경선 직전 조사는 홍이 크게 앞섰다). 예측시장의 위스콘신 민주 가격은 <strong>38¢ → 73¢</strong>로 뛰었고 사바토는 8/13 Toss-up → <strong>Lean D</strong>로 옮겼다. 주 지형은 그대로인데 후보 한 명이 바뀌었을 뿐이다.</li>
</ul>
</div>
<section id="part-1.-데이터" class="level1">
<h1>PART 1. 데이터</h1>
<section id="환경-스냅샷-주간" class="level2">
<h2 class="anchored" data-anchor-id="환경-스냅샷-주간">환경 스냅샷 (주간)</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>지표</th>
<th>값</th>
<th>기준</th>
<th>비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>트럼프 순지지도</td>
<td><strong>−20.4</strong> (38.1/58.5)</td>
<td>8/11 (Silver Bulletin, 페이지 갱신 8/14)</td>
<td>−20.6에서 노이즈 수준 이동 후 <strong>5일째 고착</strong>. 1기 동기(−11.3)를 9p 이상, 바이든 동기(약 −14)도 하회. 이슈별로 인플레이션 −42.3·경제 −29.9·무역 −23.7이고 <strong>이민(약 +2.5)만 순플러스</strong></td>
</tr>
<tr class="even">
<td>일반투표(제너릭)</td>
<td><strong>D+6.7 ~ D+7.0</strong></td>
<td>8/12~15 (SB D+6.7 · RCP D+6.8 · USPollingData D+7.0)</td>
<td>적극투표층 보정 시 약 <strong>D+8.1</strong>(SB). 하단은 Morning Consult D+4·ActiVote D+5. RCP의 8/14 D+7.1 → 8/15 D+6.8은 추세 전환이 아니라 평균 산출 통상 변동</td>
</tr>
<tr class="odd">
<td>7월 물가</td>
<td>CPI <strong>3.4%</strong> y/y(m/m +0.1%·코어 2.5%) · PPI <strong>0.0%</strong> m/m(y/y 5.5→4.7%)</td>
<td>8/12·8/13 (BLS)</td>
<td>CPI는 컨센서스 부합, PPI는 컨센서스(+0.2%) 하회 — 도매 단계 “피크 통과”</td>
</tr>
<tr class="even">
<td>7월 소매판매·소비심리</td>
<td><strong>−0.6%</strong> (예상 ~+0.1%) · UMich 8월 예비 <strong>51.0</strong> (7월 55.2)</td>
<td>8/14</td>
<td>소매판매는 2025년 5월 이후 최대 낙폭, 심리는 3개월 만 첫 하락. <strong>1년 기대인플레 4.3%로 재상승</strong></td>
</tr>
<tr class="odd">
<td>유가·휘발유</td>
<td>브렌트 주간 <strong>약 +6%</strong> · 전국 휘발유 평균 <strong>$4.07/갤런</strong></td>
<td>8/15 (AAA)</td>
<td>호르무즈 교착(60일 MoU 8/16 만료). 전쟁 이전 대비 갤런당 약 $1 높음</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>지난주 이 자리에서 “고용이 꺾였는데 지표가 안 움직인 것은 시차 문제”라고 썼다. 이번 주에 그 시차가 어떻게 풀렸는지가 나왔는데, 방향이 예상과 달랐다. <strong>물가 지표 두 건은 실제로 온건하게 나왔다.</strong> CPI가 컨센서스에 부합하고 PPI가 하회했으니 여당에는 “인플레 피크 통과” 서사의 재료가 생긴 셈이다. 그런데 같은 주 금요일에 소비가 꺾이면서, 그 물가 안정이 <strong>“수요가 약해져서 생긴 디스인플레이션”</strong>으로 읽히게 됐다. 물가가 잡히는 이유가 경기가 식어서라면 집권당에는 호재가 아니다. 여기에 트럼프가 폭스뉴스 인터뷰에서 “중간선거 전에 전쟁이 끝나든 말든 상관없다”고 말하면서, 공화당이 기대해온 <strong>‘10월 긴장 완화 → 유가 하락’ 경로를 스스로 봉쇄</strong>했다. 금요일 두 지표가 지지율과 밸럿에 어떻게 찍히는지는 다음 주 초 조사에서 처음 확인된다. (<a href="https://www.cnbc.com/2026/08/12/cpi-inflation-report-july-2026.html">CNBC(7월 CPI)</a> · <a href="https://finance.yahoo.com/economy/articles/us-retail-sales-weakest-over-133017202.html">Yahoo(소매판매)</a> · <a href="https://finance.yahoo.com/economy/article/us-consumers-sour-on-economy-as-inflation-concerns-remain-in-focus-umich-survey-says-144047259.html">Yahoo(UMich)</a> · <a href="https://newsroom.aaa.com/2026/08/after-falling-for-a-week-national-average-climbing-again/">AAA</a> · 상세 <code>national_weekly/2026-08-16</code>)</p>
</blockquote>
</section>
<section id="상원-경합주-스냅샷-9주" class="level2">
<h2 class="anchored" data-anchor-id="상원-경합주-스냅샷-9주">상원 경합주 스냅샷 (9주)</h2>
<div class="lookfor">
<p>등급(Toss Up/Lean)은 확률이 아니다. 이번 주도 <strong>Cook·Sabato의 하드 등급 이동은 0건</strong>이다. 그런데 그 아래에서는 두 축이 <strong>서로 반대 방향으로 동시에</strong> 움직였다. <strong>노스캐롤라이나</strong>는 같은 주에 두 조사(Elon +11·Carolina Forward +7)로 최상급 탈환 기회임을 재확인했고 <strong>조지아</strong>는 상대 후보의 악재가 겹치며 더 안정됐다. 반대로 <strong>미시간</strong>은 경선 후 첫 주요 언론 조사에서 로저스 +4가 나와 민주 필수 방어주가 실질 열세로 내려앉았고, <strong>메인</strong>은 지명자 스캔들이 탈환 축에 균열을 냈으며, <strong>텍사스</strong>는 탈라리코의 7연속 우위가 끊겼다. 등급이 안 움직였다는 것은 두 기관이 이 상충하는 벡터들을 아직 순증으로 판단하지 않았다는 뜻이지, 아무 일도 없었다는 뜻이 아니다.</p>
</div>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>구도 (D vs R)</th>
<th>방어</th>
<th>등급 (Cook / Sabato)</th>
<th>핵심 (전주 대비)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>조지아</td>
<td>Ossoff vs M. Collins</td>
<td>민주</td>
<td>Lean D / Likely D</td>
<td><strong>AARP(초당 합동) 오소프 52–43</strong>·콜린스의 1·6 폭동 보상 기금 지지 발언 역풍(AJC)·하원 윤리위 인턴 급여 심리·사위 백인우월주의 보도 (<strong>방어 추가 강화</strong>)</td>
</tr>
<tr class="even">
<td>미시간</td>
<td>El-Sayed vs Rogers</td>
<td>민주(공개석)</td>
<td>Toss Up</td>
<td><strong>폭스 로저스 51–엘사예드 47</strong> — 경선 후 첫 주요 언론 조사. Glengariff +10·EPIC-MRA 46–43과 함께 <strong>열세·동률 4연속</strong>. SLF 총 $51M 확정 (<strong>이번 주 유일한 민주 이탈 방향</strong>)</td>
</tr>
<tr class="odd">
<td>메인</td>
<td>Jackson vs S. Collins</td>
<td>공화</td>
<td>Toss Up (Cook·DDHQ)</td>
<td><strong>잭슨 1988년 포트켄트 경찰 기록 보도(8/12)</strong> → RNC “플래트너 2.0” 공세. 3조사(폭스 +2·UNH +3·하트 +4) 모두 <strong>보도 이전 필드</strong> (<strong>혼조</strong>)</td>
</tr>
<tr class="even">
<td>노스캐롤라이나</td>
<td>Cooper vs Whatley</td>
<td>공화(공개석)</td>
<td>Lean D / Tilt D(IE)</td>
<td><strong>Elon 쿠퍼 53–42</strong>·Carolina Forward 50–43. 단 Elon·WRAL 모두 와틀리 인지도 상승에 따른 축소 전망 병기 (<strong>우위 재확인</strong>)</td>
</tr>
<tr class="odd">
<td>알래스카</td>
<td>Peltola vs Sullivan</td>
<td>공화</td>
<td>Toss Up</td>
<td><strong>ASR 최종 라운드 펠톨라 50.8–49.2</strong>·동명이인 “댄 J. 설리번” FBI·법무부 수사 확대·<strong>8/18 top-4 예비</strong> (<strong>소폭 강화</strong>)</td>
</tr>
<tr class="even">
<td>텍사스</td>
<td>Talarico vs Paxton</td>
<td>공화</td>
<td>Lean R</td>
<td><strong>에머슨 팩스턴 47–탈라리코 46</strong> — 봄 이후 팩스턴이 앞선 첫 공개 조사로 <strong>7연속 우위 중단</strong>. 연령 분화(&lt;50 D+15 / 50+ R+11) (<strong>소폭 냉각</strong>)</td>
</tr>
<tr class="odd">
<td>오하이오</td>
<td>Brown vs Husted</td>
<td>공화(특별)</td>
<td>Toss Up</td>
<td><strong>폭스 브라운 53–허스티드 45</strong> — 6월 폭스와 동일한 +8. <strong>같은 조사에서 주지사 라마스와미는 우위</strong>라 후보 개인 문제로 분리 확인. SB 평균은 브라운 +3.1 (<strong>소폭 강화</strong>)</td>
</tr>
<tr class="even">
<td>뉴햄프셔</td>
<td>Pappas vs Sununu</td>
<td>민주(공개석)</td>
<td>Lean D</td>
<td>신규 조사 없음 — <strong>트럼프의 수누누 지지 선언</strong>으로 9/8 경선 사실상 종결. 공화는 경선 전인데도 파파스 겨냥 광고 개시 (<strong>변동 없음</strong>)</td>
</tr>
<tr class="odd">
<td>아이오와</td>
<td>Turek vs Hinson</td>
<td>공화(공개석)</td>
<td>Lean R / Tilt R(IE)</td>
<td>_NIS 상원 트랙이 8개 주만 추적해 이번 주 서술 대상 밖 — 등급 피드·시장가로만 갱신. 예측시장 민주 <strong>44¢</strong>(전주 43¢) (<strong>신규 조사 없음</strong>)</td>
</tr>
</tbody>
</table>
<p>이번 주 신규 조사는 <strong>폭스뉴스/Beacon&amp;Shaw의 3개 주 패키지(8/6–10)</strong>가 중심이다 — 미시간 로저스 51–47(RV 1,006), 오하이오 브라운 53–45(RV 1,008), 메인 잭슨 48–46(RV 1,000). 여기에 <strong>에머슨/넥스타 텍사스</strong>(8/9–10, LV 1,000) 팩스턴 47–46, <strong>Elon대 노스캐롤라이나</strong>(7/23–31, LV 800) 쿠퍼 53–42, <strong>Carolina Forward/Change Research</strong>(8/3–6, LV 915) 쿠퍼 50–43, <strong>ASR 알래스카</strong>(8/2–5, LV 1,371) 펠톨라 50.8–49.2가 더해졌다. 조지아 AARP 조사(오소프 52–43)는 실사기간·표본이 공개되지 않아 이 사이트의 조사 DB에는 넣지 않고 표의 서술로만 반영했다. 메인 UNH 파인트리도 실사기간이 공표되지 않아 같은 처리를 했다. <strong>폭스의 조지아 오소프 56–43은 6/23–27 초여름 조사로 이번 주 신규가 아니다</strong> — 집계 사이트에서 최신인 것처럼 도는 수치라 따로 적어 둔다. (<a href="https://www.foxnews.com/politics/fox-news-poll-senate-battle-looms-michigan">Fox(미시간)</a> · <a href="https://www.foxnews.com/politics/fox-news-poll-economic-anxiety-candidate-concerns-define-ohio-senate-race">Fox(오하이오)</a> · <a href="https://emersoncollegepolling.com/texas-2026-poll-paxton-and-talarico/">Emerson(텍사스)</a> · <a href="https://www.elon.edu/u/news/2026/08/12/elon-poll-cooper-continues-to-lead-in-north-carolina-u-s-senate-race/">Elon(NC)</a> · <a href="https://www.newsweek.com/dan-sullivan-within-striking-distance-of-mary-peltola-in-alaska-senate-race-12311449">Newsweek(알래스카 ASR)</a>)</p>
<p><strong>사우스캐롤라이나는 이번 주 유일하게 실제 개표가 나온 상원 이벤트였다.</strong> 고 린지 그레이엄 의석의 8/11 공화 특별 예비선거에서 임명 현역 <strong>달린 그레이엄이 33%, 랠프 노먼 하원의원이 25%</strong>로 과반 미달, <strong>8/25 결선</strong>이 확정됐다. 사전 에머슨 조사는 노먼 22·그레이엄 19로 노먼 선두를 예상했으니 임명 현역이 뒤집은 셈이다. Safe R 의석이라 다수 산술은 바뀌지 않지만, <strong>트럼프가 지지한 후보가 33%에 그쳤다</strong>는 사실은 같은 주 TN-5에서 트럼프 지지 현역이 경선에서 진 것과 함께 읽힌다. (<a href="https://www.270towin.com/news/2026/08/10/live-results-south-carolina-special-republican-senate-primary_1835.html">270toWin</a>)</p>
</section>
<section id="하원-cook-사이클-첫-신규-토스업" class="level2">
<h2 class="anchored" data-anchor-id="하원-cook-사이클-첫-신규-토스업">하원 — Cook, 사이클 첫 신규 토스업</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>이번 주 내용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>등급 이동</td>
<td><strong>OH-07(맥스 밀러·R) Likely R → Toss-Up (8/10)</strong> — 토스업 18→19석, 사이클 첫 신규 편입. 인사이드일렉션스도 같은 날 이동(3번째 기관). <strong>8/13에는 OH-10·OH-15·CO-03을 Solid R → Likely R</strong>로 하향(토스업 층 밖)</td>
</tr>
<tr class="even">
<td>Cook 토플라인</td>
<td>Solid D 184 / Likely D 11 / Lean D 10 / <strong>Toss-up 19(D 4 · R 15)</strong> / Lean R 9 / Likely R 20 / Solid R 182 (8/13 기준, 자동 취득)</td>
</tr>
<tr class="odd">
<td>예선 실측</td>
<td><strong>WI-03 쿡(Cooke) 58–42로 버지 격파</strong> → 밴 오든 리매치 확정 · MN-02 리틀(DFL) 47.4% · <strong>CT-01 브로닌 53.5–34.7로 14선 라슨 축출</strong> · AL-02 마키스(R, ~50%) vs 피겨스(D)</td>
</tr>
<tr class="even">
<td>공석·대진</td>
<td><strong>NC-11 볼컴(R) 공천 확정(8/10)</strong> — 중량급 4명이 48시간 내 연달아 고사한 끝에 63인 집행위가 1차 투표로 선출. 사바토·인사이드는 이미 Toss-up, <strong>Cook만 Lean R</strong></td>
</tr>
<tr class="odd">
<td>자금</td>
<td>지도부 계열 <strong>AAN이 41개 지역구에 2,200만 달러(8/13~9/3)</strong> 추가 — 누적 6,200만으로 이 시점 역대 최대 조기 지출, Tier-1 토스업 16곳 커버. <strong>트럼프 개인 PAC 1차분 3,000만 달러</strong>는 미시간·오하이오·노스캐롤라이나 표적</td>
</tr>
<tr class="even">
<td>모델·시장</td>
<td>FiftyPlusOne 민주 <strong>~89%</strong>·중앙값 230석 · Kalshi 하원 다수 <strong>86¢</strong>(8/16) · Polymarket ~85.5% · <strong>DDHQ 64%</strong>(평균 228석, 모델 갱신 8/14 — 원천 직접 취득) — 정태 등급가중 기대의석은 <strong>약 214석</strong>으로 218 문턱에 4석 미달</td>
</tr>
</tbody>
</table>
<p>OH-07이 왜 중요한가. 이 지역구는 <strong>Cook 기준 R+10.3의 옅은 적색</strong>이고, 6월까지 어느 기관도 경합 지도에 올리지 않았다. 등급을 두 단계 움직인 것은 전국 환경이 아니라 <strong>후보 개인 사정</strong>이다 — 전처에 대한 가정폭력 의혹이 제기된 상태에서 밀러가 후보 교체 시한(8/9~8/11)을 넘겨 완주를 확정하자, Cook은 “평년엔 공화 우위이나 민주 물결 해엔 경쟁이 성립할 만큼 옅은 적색”으로 판정했다. 여기서 이번 주 하원 이야기가 하나로 이어진다. <strong>트럼프 개인 PAC 3,000만 달러의 1차 표적(MI-07·OH-07/09·NC-01/11)은 정확히 후보 자질 문제가 등급을 움직인 의석들이다.</strong> 자금은 투표율을 올릴 수 있지만 가정폭력 의혹에 답을 주지는 못한다.</p>
<p>다만 상방을 확증하기엔 이르다. <strong>OH-07의 공개 조사는 당파 조사 2건뿐</strong>이다(공화계 co/efficient 포인덱스터 47–33, 민주계 Tavern 54–46 — 방향은 같지만 격차가 6포인트 다르다). 독립 필드워크는 아직 없고, R+10.3 지역구에서 3개월 사이 당파적 중력이 되살아날 여지가 남아 있다. (<a href="https://www.cookpolitical.com/analysis/house/ohio-house/ohio-rep-max-millers-district-moves-likely-republican-toss">Cook(OH-07)</a> · <a href="https://insideelections.com/ohio-7-miller-makes-a-toss-up/">Inside Elections</a> · <a href="https://www.axios.com/2026/08/13/house-republican-american-action-network-midterm-ad-campaign">Axios(AAN)</a> · <a href="https://www.cnn.com/2026/08/15/politics/trump-midterms-campaign-strategy">CNN(트럼프 PAC)</a>)</p>
</section>
<section id="주지사-위스콘신-후보-한-명에-시장이-35포인트" class="level2">
<h2 class="anchored" data-anchor-id="주지사-위스콘신-후보-한-명에-시장이-35포인트">주지사 — 위스콘신, 후보 한 명에 시장이 35포인트</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>주</th>
<th>Kalshi 민주 가격 (8/16)</th>
<th>전주(8/10)</th>
<th>등급</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>위스콘신</td>
<td><strong>73¢</strong></td>
<td>38¢</td>
<td>Toss-up (Cook·IE) / <strong>Lean D (Sabato 8/13↑)</strong></td>
</tr>
<tr class="even">
<td>애리조나</td>
<td>87¢</td>
<td>85¢</td>
<td>Lean D (Cook·Sabato)</td>
</tr>
<tr class="odd">
<td>미시간</td>
<td>87¢</td>
<td>84¢</td>
<td>Lean D (Cook·Sabato)</td>
</tr>
<tr class="even">
<td>아이오와</td>
<td>73¢</td>
<td>65¢</td>
<td>Toss-up (Cook·Sabato) / Tilt D (IE)</td>
</tr>
<tr class="odd">
<td>조지아</td>
<td>60¢</td>
<td>57¢</td>
<td>Toss-up (Cook·Sabato·IE)</td>
</tr>
<tr class="even">
<td>오하이오</td>
<td>50¢</td>
<td>50¢</td>
<td>Toss-up (Cook) / Lean R (Sabato·IE)</td>
</tr>
<tr class="odd">
<td>네바다</td>
<td><strong>37¢</strong></td>
<td>56¢</td>
<td>Toss-up (Cook) / Lean R (Sabato) / Tilt R (IE)</td>
</tr>
<tr class="even">
<td>캔자스</td>
<td>31¢</td>
<td>20¢</td>
<td>Lean R (Cook·Sabato)</td>
</tr>
</tbody>
</table>
<p><strong>위스콘신에서 벌어진 일이 이 표의 전부다.</strong> 8/11 민주 경선에서 밀워키 카운티 행정관 <strong>David Crowley가 민주사회주의자 Francesca Hong을 1%p 미만 차(비공식 집계 약 0.4%p)로 꺾었다.</strong> 홍은 경선 직전 조사에서 크게 앞서 있었고, 크롤리는 7/8 선거운동을 접었다가 7/18 에버스 주지사의 지지를 업고 복귀한 후보다. AP는 홍의 승복 뒤 8/12 새벽 2시 34분에 콜했다(결과는 인증 전까지 비공식). 그 직후 예측시장의 위스콘신 민주 가격은 <strong>38¢에서 73¢로 35포인트</strong> 올랐고, 사바토는 8/13 Toss-up → <strong>Lean D</strong>로 옮겼다.</p>
<p>주 지형은 하루 사이에 바뀌지 않았다. 바뀐 것은 후보 한 명이다. 시장이 매기던 38¢는 상당 부분 <strong>“민주사회주의자 후보가 위스콘신 주 전체 선거에서 이길 수 있는가”</strong>에 대한 할인이었고, 그 할인이 사라지자 가격이 제자리를 찾은 것으로 읽힌다. 지난주 이 사이트가 아이오와에서 지적한 것과 같은 이야기다 — <strong>전국 환경이 같아도 후보에 따라 결과가 갈린다.</strong> 다만 이번에는 방향이 반대다. 아이오와에서는 강한 후보(Rob Sand)가 시장 가격을 끌어올렸고, 위스콘신에서는 약하다고 평가받던 후보가 탈락하면서 가격이 올랐다.</p>
<p>한 가지 실무적 함의가 있다. 이 사이트가 싣고 있던 <strong>위스콘신 본선 조사 3건(Marquette 동률·RMG +1·Wedgewood +3)은 전부 홍 기준 가상대결</strong>이라, 확정된 대진에는 적용할 수 없다. 크롤리 기준 본선 조사가 나올 때까지 이 주의 조사 칸은 비워 둔다 — 있는 숫자를 그대로 쓰는 쪽이 편하지만 그건 다른 대진의 숫자다. <a href="../governors.html#candidates">주지사 후보 카드</a>의 위스콘신 민주 칸도 크롤리로 교체했다(사진은 라이선스 확인 전까지 placeholder).</p>
<p>반대편에서 <strong>네바다는 민주 56¢ → 37¢로 19포인트 떨어졌다.</strong> 사바토는 7/23에 이미 Lean R로 옮겨 뒀고 인사이드일렉션스도 Tilt R이다. 현직 롬바르도(R)를 상대하는 애런 포드(D)는 공개 조사에서 동률~R+3 사이였는데, 시장은 그보다 훨씬 공화 쪽으로 갔다. (<a href="https://www.wpr.org/news/wisconsin-democratic-primary-governor-too-close-to-call-david-crowley-francesca-hong">WPR(크롤리 승리)</a> · <a href="https://www.pbs.org/newshour/politics/david-crowley-wins-democratic-primary-for-wisconsin-governor-over-francesca-hong">PBS</a>)</p>
</section>
</section>
<section id="part-2.-분석" class="level1">
<h1>PART 2. 분석</h1>
<section id="환경-종합-판단" class="level2">
<h2 class="anchored" data-anchor-id="환경-종합-판단">환경 종합 판단</h2>
<blockquote class="blockquote">
<p><strong>21주차(8/10~8/16) 거시 환경은 여당에 뚜렷이 불리한 방향을 유지·강화했다.</strong> 주 전반은 7월 CPI(3.4%)·PPI(0.0%)의 물가 2연속 안도로 여당에 제한적 호재였으나, 금요일(8/14) 소매판매 −0.6%(2025년 5월 이후 최대 낙폭)와 미시간대 소비심리 51.0(3개월 만 첫 하락, 1년 기대인플레 4.3%)이 서사를 ‘스태그플레이션 라이트’로 되돌렸다. 트럼프 순지지는 −20.4(2기 최저권)에서 5일째 고착됐고, 제너릭 밸럿은 D+6.7~8(LV 기준)로 안정적. 결정적으로 8/15 CNN 보도에서 <strong>백악관 참모진이 양원 상실 흐름을 내부적으로 인정</strong>하고 개인 PAC 3,000만 달러 방출·기반 동원 일변도로 전환했다. 호르무즈 교착으로 유가는 주간 +6%, 휘발유 $4.07 — 트럼프가 “선거 전 종전 무관”을 공언하며 ’10월 완화’ 시나리오를 스스로 봉쇄해 유가발 인플레 상방 리스크가 가을까지 살아 있다. 반증 재료(CPI·PPI 안도, 증시 사상 최고, 이민 순플러스, 공화 우위 재획정)는 남아 있으나 방향을 바꾸지 못했다. <strong>베이지안 판정: “민주 우호 환경” 가설 지지(중~강), 저점에서 한 단계 더 굳어짐.</strong> (인용: <code>national_weekly/2026-08-16</code> §6-4)</p>
</blockquote>
<p>여기에 한 가지를 덧붙인다. 이번 주 여당에 가장 뼈아픈 신호는 지표가 아니라 <strong>여당 자신의 발언</strong>이다. 백악관 참모가 CNN에 “당의 운명이 거의 전적으로 MAGA 저투표성향층 동원에 달렸다”고 말한 것은, 무당층 설득을 통한 만회를 사실상 포기했다는 뜻으로 읽힌다. −20의 지지율과 D+7의 환경을 <strong>차등 투표율만으로</strong> 뒤집겠다는 베팅인데, 역사적으로 중간선거가 그렇게 결정된 사례는 드물다. 이 사이트가 매주 추적하는 외부 판단(등급·모델·시장)과 여당의 내부 판단이 이번 주에 처음으로 같은 곳을 가리켰다.</p>
</section>
<section id="상원-산수-이번-주엔-숫자가-네-종류로-갈렸다" class="level2">
<h2 class="anchored" data-anchor-id="상원-산수-이번-주엔-숫자가-네-종류로-갈렸다">상원 산수 — 이번 주엔 숫자가 네 종류로 갈렸다</h2>
<p>현 구도 <strong>공화 53 vs 민주 47</strong>, 다수엔 <strong>순 +4</strong> 필요. 등급가중(Solid/Likely=확정, Lean=75%, Toss-up=50%)으로 계산하면 확장(탈환) 기대는 NC(0.75)+ME(0.50)+AK(0.50)+OH(0.50)+<strong>TX(~0.33, 에머슨 냉각 반영해 지난주 ~0.38에서 하향)</strong> ≈ <strong>+2.58석</strong>, 방어 손실 확률은 <strong>MI(~0.52, 폭스 조사 반영해 지난주 ~0.42에서 악화)</strong>+NH(<sub>0.28)+GA(</sub>0.06) ≈ <strong>−0.86석</strong> — <strong>순 기대의석 ≈ +1.72석</strong>으로 문턱 +4에 명확히 미달한다. 지난주(~+1.85)에서 조금 내려왔는데, 그 안을 뜯어보면 <strong>NC 재확인(+)을 미시간 악화와 텍사스 냉각(−)이 상쇄한</strong> 결과다.</p>
<p>지난주에 이 사이트는 “민주 상원 다수를 두고 유통되는 숫자는 서로 종류가 다르다”고 썼다. 이번 주에는 그 종류가 하나 더 늘었다.</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>종류</th>
<th>값</th>
<th>기준</th>
<th>읽는 법</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>등급가중 산수</strong> (자체)</td>
<td>순 기대의석 <strong>+1.72석</strong></td>
<td>8/16</td>
<td>Cook·Sabato의 <strong>서수적 등급</strong>을 확률로 환산. 전국 환경(D+6.7)이 들어갈 자리가 구조적으로 없다</td>
</tr>
<tr class="even">
<td><strong>예측시장</strong> (Kalshi)</td>
<td>민주 다수 <strong>48¢</strong> (전주 45¢)</td>
<td>8/16</td>
<td>거래액 $308만·미결제 $153만의 두꺼운 시장. 가격은 확률의 근사일 뿐</td>
</tr>
<tr class="odd">
<td><strong>구조 모델</strong></td>
<td>Race to the WH <strong>55.2%</strong> / Decision Desk HQ <strong>45.0%</strong></td>
<td>8/16 · 8/14</td>
<td>전국 환경을 주별 사전분포에 반영한 시뮬레이션. 두 모델이 10%p 갈린다</td>
</tr>
<tr class="even">
<td><strong>여론조사 기반 모델</strong> ★신규</td>
<td>G.E. Morris <strong>55%</strong> / Silver Bulletin FLIPR <strong>약 57%</strong></td>
<td>8/12 · 8/14</td>
<td><strong>이번 주 처음</strong> 민주 과반을 명목 favorite로 판정. FLIPR은 8/14 출범한 신규 모델</td>
</tr>
</tbody>
</table>
<p><strong>왜 +1.72석과 57%가 같은 주에 나오는가.</strong> 모순이 아니라 서로 다른 질문에 답하고 있어서다. 등급가중은 각 주를 <strong>독립</strong>으로 놓고 Toss-up을 일률적으로 50%로 계산한다. 그러면 토스업 4~5석(ME·MI·AK·OH·TX 경계)에서 민주가 필요한 만큼 이기는 조합의 확률이 자동으로 낮아진다. 반면 여론조사 모델은 <strong>전국 환경이 주별 결과를 함께 밀어 올린다</strong>고 가정한다 — D+6.7이 실제 투표에서 재현되면 토스업들이 하나씩 독립적으로 갈리는 게 아니라 <strong>같은 방향으로 함께 넘어간다</strong>는 것이다. 이 상관(correlation) 가정 하나가 확률을 14~22%대에서 55%대로 옮긴다.</p>
<p>어느 쪽이 맞는지는 11월에 판명되지만, 지금 독자가 할 수 있는 판단은 있다. <strong>“여러 모델의 평균”을 내지 말 것.</strong> 서로 다른 가정을 평균하면 어느 가정도 아닌 숫자가 나온다.</p>
<p>한 가지 정정을 두 주 연속으로 적어 둔다. 이 사이트가 종합하는 브리핑 원문에는 Race to the WH가 이번 주에도 <strong>“공화 87.5% / 민주 12.5%”</strong>로 기재돼 있는데, <strong>모델의 공표 시계열을 원천에서 직접 받으면 8/16 기준 민주 55.2%</strong>(예상 의석 D 50.9 – R 49.1)다. 지난주에도 같은 격차(원문 12.5% ↔︎ 원천 57.6%)를 확인했고, 이 사이트는 원천값을 싣는다. 이 정정이 이번 주에는 해석까지 바꾼다 — 브리핑 원문의 틀에서는 “여론조사 모델(55~57%) 대 구조 모델·시장(공화 87%)”의 거대한 괴리가 이번 주 최대 논점이지만, <strong>원천값으로 다시 보면 RtWH 55.2%·Morris 55%·Silver 57%가 오히려 한 무리로 모이고, 그 반대편에 Kalshi 48¢·DDHQ 45%가 선다.</strong> 괴리는 여전히 있지만 크기는 40포인트가 아니라 10포인트다. (<a href="https://www.racetothewh.com/senate/26">Race to the WH</a> · <a href="https://www.natesilver.net/p/nate-silver-2026-midterm-election-polls-model">Silver Bulletin FLIPR</a> · <a href="https://www.dailykos.com/stories/2026/8/12/800083030/elections/democrats-gain-momentum-in-flipping-the-senate/">Daily Kos(Morris 55%)</a>)</p>
<p>Silver Bulletin FLIPR에 대해서는 <strong>유보 조건</strong>을 함께 적는다. 의석 표가 유료 구간이고, 인용돼 도는 등급표(TX·ME·MI를 Lean D로 표기)가 <strong>모델 자체의 공개 평균과 충돌</strong>한다 — FLIPR의 미시간 평균은 로저스 우위인데 등급표는 “Lean D”로 적혀 있다. 이 사이트는 모델 페이지를 직접 확인하기 전까지 그 등급표를 미검증으로 취급한다.</p>
<p>정리하면 <strong>Base(모달)는 여전히 공화 방어</strong>다. 다만 이번 주에 <strong>상방과 하방의 꼬리가 동시에 두꺼워졌다.</strong> Bull(민주 50–50~51–49)의 조건은 지난주 “미시간 수성”이 추가된 데 이어 이번 주 <strong>“메인 지명자가 검증을 통과할 것”</strong>이 하나 더 붙었다. 반대로 Bear(54–46 이상)는 조지아 탈환이 필수인데 조지아가 또 반대 방향으로 갔다 — 딥 Bear의 상단은 오늘 증거 기준 53–47에 압축된다.</p>
</section>
<section id="미시간-조사는-r4-시장은-d-57" class="level2">
<h2 class="anchored" data-anchor-id="미시간-조사는-r4-시장은-d-57">미시간 — 조사는 R+4, 시장은 D 57¢</h2>
<p>이번 주 가장 읽을 만한 불일치는 미시간에 있다. 공개 조사는 <strong>엘사예드가 뒤지거나 동률인 것이 4연속</strong>이고, 그중 폭스뉴스/Beacon&amp;Shaw(8/6–10, RV 1,006)는 경선 이후 <strong>주요 언론사의 첫 본선 조사</strong>라 무게가 다르다. 그런데 Kalshi는 같은 날 엘사예드를 <strong>57¢</strong>로 매긴다. 조사대로면 45¢ 아래가 자연스러운 값이다.</p>
<p>시장이 무엇을 보고 있는지는 폭스 조사의 교차분석에 힌트가 있다. 같은 조사에서 <strong>54%가 “엘사예드의 정책이 너무 극단적”</strong>이라고 답했지만 <strong>51%는 “로저스가 트럼프와 너무 가깝다”</strong>고 답했고, 투표 열의는 민주 지지층이 앞섰다. 이슈별로도 엘사예드는 의료 중시층에서 +47, 인플레 중시층에서 +10 우위이고 로저스는 이민 중시층에서 +82로 압도한다 — <strong>어느 이슈가 11월의 지배 이슈가 되느냐</strong>에 따라 결과가 갈리는 구조다. 시장은 D+6.7의 전국 환경이 결국 이 구조를 민주 쪽으로 밀 것이라고 보고, 조사는 지금 이 시점의 톱라인을 보고 있다.</p>
<p>여기서 이 사이트의 원칙을 다시 적어 둔다. <strong>가격과 조사를 평균 내지 말 것.</strong> 둘은 같은 질문에 대한 두 개의 답이 아니라, 각각 “지금 누가 앞서는가”와 “11월에 누가 이길 것 같은가”에 대한 답이다. 미시간은 이 구분이 12포인트 차이로 벌어진 상태로 한 주를 마쳤다. 검증 시점도 정해져 있다 — 다음 독립 조사다. 상세는 <a href="../states/mi.html">미시간 State Focus</a>.</p>
<div class="kr-box kr-trade">
<p><strong>Korea Watch (8/10~8/16).</strong> 이번 주는 <strong>‘안보’ 유형이 처음으로 주간을 지배(13건 중 5건)</strong>한 동맹 태세 주간이었다. <strong>을지 자유의 방패(UFS)가 8/17~27 일정으로 공식 발표</strong>됐고(한국군 약 1만 8천 명 참가, 드론·GPS 교란·사이버 대응이 신규 편성), 유엔군사령부는 훈련 설계에 <strong>북러 전쟁의 실전 경험을 반영</strong>했다고 확인했다. 그런데 훈련 개시 직전 <strong>USS 조지워싱턴 항모가 중동으로 이동</strong>해 서태평양에 항모 공백이 생겼다 — 확장억제의 가장 가시적인 자산이 빠진 상태로 연합훈련이 시작되는 구도다. 북한은 <strong>8/12 원산에서 중거리급 추정 미사일을 약 700km 발사</strong>(2026년 11번째·6일 새 두 번째)하고 외무성 담화로 UFS를 “침략전쟁 리허설”로 규정하며 주 단위 도발 사이클을 재가동했다.</p>
<p>산업·동맹 축에서는 <strong>트럼프의 ‘해군·조선산업기반 재건’ 각서(8/13)</strong>가 가장 큰 사안이다. 외국 조선소에서 미 군함 2척을 조건부로 건조할 수 있게 열어 둔 조치로 <strong>한화오션 거제·필리조선소가 직접 수혜 대상</strong>이다. 다만 이 각서는 하원을 통과한 FY2027 NDAA의 <strong>해외 건조 금지 조항과 정면으로 충돌</strong>한다. 여기에 OMB의 FY27 정책성명(4척 해외 건조 승인 요구)과 한화디펜스USA의 오스탈USA 12억 달러 인수 제안이 겹치면서, <strong>9월 상하원 조정회의가 MASGA 실행의 유일한 관문</strong>으로 확정됐다. 한국의 SSN(원자력추진잠수함) 관련 법안도 미 의회 심사 관문을 통과해야 한다는 점이 확인됐다.</p>
<p><strong>미 선거와의 직접 연계는 8월 휴회 속에 이번 주에도 없었다</strong>(선거연계 0건). 대신 이 사이트가 추적하는 주지사 트랙에서 하나가 사라졌다 — <strong>위스콘신 민주 경선에서 탈락한 Francesca Hong은 한국 이민자 부모를 둔 한국계 미국인</strong>으로, 지명됐다면 경합 8주 주지사 후보 가운데 유일한 직접 연결이었다. 크롤리 확정으로 현재 경합주 주지사 후보 중 한국과의 직접 접점은 남아 있지 않다. <strong>8/25 이재명–트럼프 워싱턴 정상회담</strong>은 이번 주에도 독립 확인에 실패해 <strong>미확인으로 존치</strong>한다(4주 연속). ’전투기 오폭 후 훈련 중단이 UFS에 미치는 영향’도 같은 처리다. (상세는 <a href="../korea-watch.html">Korea Watch</a>)</p>
</div>
</section>
<section id="다음-관전-포인트" class="level2">
<h2 class="anchored" data-anchor-id="다음-관전-포인트">다음 관전 포인트</h2>
<ul>
<li><strong>8/18(화) — 알래스카 top-4 예비.</strong> 관전 포인트는 진출 여부(펠톨라·현역 확실)가 아니라 <strong>동명이인 “댄 J. 설리번”의 잠식 득표율</strong>이다. 11월 RCV 혼란 위험의 첫 실측치가 여기서 나온다. 같은 날 <strong>플로리다 예선</strong>(24-4 신지도의 첫 투표 — FL-25 토스업, 윤리위 조사 중인 FL-07 밀스의 생존 여부)과 CA-14 특별선거 결선.</li>
<li><strong>메인 — 스캔들 이후 첫 공개 조사.</strong> 지금 도는 3조사는 전부 8/12 보도 이전 필드다. 잭슨의 우위가 유지되는지가 탈환 축 전체의 향방을 가른다.</li>
<li><strong>미시간 — 추가 독립 조사.</strong> 폭스 +4가 재현되는지, 아니면 Kalshi의 57¢ 쪽이 맞는지. 이번 주 최대 불일치의 검증 시점이다.</li>
<li><strong>8/19(수) — 7월 FOMC 의사록.</strong> 소매판매·소비심리 쇼크 이후 9월 인하 신호를 어떻게 읽을지. 같은 주 초 <strong>쌍둥이 충격을 반영한 첫 지지율·밸럿 조사</strong>도 나온다.</li>
<li><strong>8/25(월) — 사우스캐롤라이나 결선.</strong> 달린 그레이엄 vs 랠프 노먼. 다수 산술엔 무영향이나 <strong>트럼프 지지 효과의 다음 직접 시험대</strong>다.</li>
<li><strong>Cook의 NC-11 추종 여부.</strong> 사바토·인사이드는 이미 Toss-up이고 볼컴 공천으로 대진도 확정됐다. Cook이 옮기면 토스업은 20석이 된다 — 다음 집계 변동 1순위.</li>
<li><strong>한국 함의.</strong> UFS(8/17~27) 개시에 대한 북한 반응, 9월 NDAA 조정회의(해외 건조 금지 조항 대 트럼프 각서), 8/25 정상회담 보도의 독립 확인 여부.</li>
</ul>
<hr>
<div class="as-of">
<p>출처: NIS 주간 브리핑 종합(전국·상원·하원·Korea Watch, 08/10~08/16). 환경 지표 — Silver Bulletin·RealClearPolling·USPollingData·Morning Consult·ActiVote. 경제 — BLS(7월 CPI·PPI·소매판매)·미시간대·AAA. 상원 실측 — 폭스뉴스/Beacon&amp;Shaw·에머슨/넥스타·Elon대·Carolina Forward/Change Research·Alaska Survey Research·UNH 파인트리·하트리서치(SMP 의뢰)·AARP(파브리지오 워드/임팩트 리서치). 상원 등급 — Cook(8/5)·Sabato(8/13)·Inside Elections(8/6), 이번 주 Cook·Sabato 하드 변동 0건. 하원 등급 — Cook 8/13 자동 취득(270towin 재게시분, 435개구 해독). 예측시장 — Kalshi 공개 API 원가격(8/16). 외부 모델 — Race to the WH(공표 시계열 직접 취득, 8/16)·Decision Desk HQ(모델 갱신 8/14)·G.E. Morris(8/12 인용)·Silver Bulletin FLIPR(8/14, 등급표는 미검증). 위스콘신 경선 결과 — WPR·PBS NewsHour(비공식 집계, 인증 전). 등급가중 순 기대의석은 자체 산출이며 모델·시장 확률과 같은 잣대로 비교하지 않는다. 일부 수치는 발표 시점 기준이며 확정 시 갱신.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "복사완료!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "복사완료!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/us-elections-2026\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>데이터 기준 시각은 각 표 상단에 표기됩니다. · 예측시장 가격은 확률의 근사일 뿐입니다.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>